<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import { appVersionPerms, type AppVersionVo } from '@qiwu/shared'
import { appVersionApi } from '@/api/platform/settings/app-version'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { openDialog } from '@/core/dialog'
import { Icon } from '@/core/icons'
import { usePerm } from '@/core/permission'
import { useDictStore } from '@/core/stores/dict'
import AppVersionForm from './form.vue'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'SettingsAppVersion' })

const { t } = useI18n()
const dict = useDictStore()
const {
  query,
  rows,
  total,
  loading,
  filtered,
  selection,
  search,
  reset,
  refresh,
  onSelectionChange,
  onSortChange,
  remove,
  batchRemove,
} = useCrudList({
  api: appVersionApi,
  filters: {
    platform: null as string | null,
    packageKind: null as string | null,
    version: '',
    isForced: null as string | null,
    enabled: null as string | null,
    createdAtRange: null as [string, string] | null,
  },
  sort: '-createdAt',
})
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `settings.appVersion`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  {
    prop: 'platform',
    label: 'field.settings.appVersion.platform',
    sortable: true,
    width: 120,
    showOverflowTooltip: true,
  },
  {
    prop: 'packageKind',
    label: 'field.settings.appVersion.packageKind',
    width: 120,
    showOverflowTooltip: true,
  },
  {
    prop: 'version',
    label: 'field.settings.appVersion.version',
    sortable: true,
    width: 200,
    showOverflowTooltip: true,
  },
  {
    prop: 'nativeMin',
    label: 'field.settings.appVersion.nativeMin',
    sortable: true,
    width: 200,
    showOverflowTooltip: true,
  },
  { prop: 'isForced', label: 'field.settings.appVersion.isForced', width: 100 },
  { prop: 'enabled', label: 'field.settings.appVersion.enabled', width: 100 },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
  { prop: 'url', label: 'field.settings.appVersion.url', minWidth: 120, showOverflowTooltip: true },
]
// computed: the perms reload when the server's permission version moves
const perm = usePerm()
const canModify = computed(() => perm.has(appVersionPerms.modify))
// the edit form loads GET /:id, which needs `view` too
const canEdit = computed(() => perm.all([appVersionPerms.modify, appVersionPerms.view]))

/** Add (no id) or edit in the form dialog; reload once saved. */
async function openForm(id?: number) {
  const name = () => t('settings.appVersion.entity')
  const saved = await openDialog(
    AppVersionForm,
    { id },
    { title: () => t(id ? 'crud.title.edit' : 'crud.title.create', { name: name() }) },
  )
  if (saved) await refresh()
}

async function setEnabled(row: AppVersionVo, enabled: boolean) {
  // failures are toasted by the request layer; the reload shows the stored state either way
  await appVersionApi.setEnabled(row.id, enabled).catch(() => undefined)
  await refresh()
}
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.settings.appVersion.platform')">
          <DictSelect v-model="query.platform" code="settings.app_platform" />
        </el-form-item>
        <el-form-item :label="t('field.settings.appVersion.packageKind')">
          <DictSelect v-model="query.packageKind" code="settings.app_package_kind" />
        </el-form-item>
        <el-form-item :label="t('field.settings.appVersion.version')">
          <el-input v-model="query.version" name="version" clearable />
        </el-form-item>
        <el-form-item :label="t('field.settings.appVersion.isForced')">
          <DictSelect v-model="query.isForced" code="core.yes_no" />
        </el-form-item>
        <el-form-item :label="t('field.settings.appVersion.enabled')">
          <DictSelect v-model="query.enabled" code="core.enabled" />
        </el-form-item>
        <el-form-item :label="t('field.common.createdAt')" class="qw-search-wide">
          <el-date-picker
            v-model="query.createdAtRange"
            type="daterange"
            value-format="YYYY-MM-DD"
            :start-placeholder="t('field.common.createdAtFrom')"
            :end-placeholder="t('field.common.createdAtTo')"
          />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="settings.appVersion"
        :columns="columns"
        @refresh="refresh"
      >
        <el-button v-perm="appVersionPerms.create" type="primary" @click="openForm()">
          <el-icon class="el-icon--left"><Icon icon="lucide:plus" /></el-icon>
          {{ t('crud.action.create') }}
        </el-button>
        <el-button
          v-if="selection.length"
          v-perm="appVersionPerms.remove"
          type="danger"
          plain
          @click="batchRemove"
        >
          {{ t('crud.action.batchDelete') }}
        </el-button>
      </TableToolbar>

      <QwTable
        table-id="settings.appVersion"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        selection
        @selection-change="onSelectionChange"
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <template #cell-platform="{ row }">
          <DictTag code="settings.app_platform" :value="row.platform" />
        </template>
        <template #cell-packageKind="{ row }">
          <DictTag code="settings.app_package_kind" :value="row.packageKind" />
        </template>
        <template #cell-isForced="{ row }">
          <DictTag code="core.yes_no" :value="row.isForced" />
        </template>
        <template #cell-enabled="{ row }">
          <el-switch
            v-if="canModify"
            size="small"
            :model-value="row.enabled"
            :aria-label="`${t('field.settings.appVersion.enabled')} ${dict.label('settings.app_platform', row.platform)} ${row.version}`"
            @change="setEnabled(row, $event as boolean)"
          />
          <DictTag v-else code="core.enabled" :value="row.enabled" />
        </template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #actions="{ row }">
          <el-button v-if="canEdit" link type="primary" @click="openForm(row.id)">
            {{ t('crud.action.edit') }}
          </el-button>
          <el-button v-perm="appVersionPerms.remove" link type="danger" @click="remove([row.id])">
            {{ t('crud.action.delete') }}
          </el-button>
        </template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>
  </div>
</template>
