// @generated by qw-codegen (crud)
import type { ParameterCreate, ParameterVo } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/settings/params'

/** /api/settings/params: the standard CRUD calls plus the module's own. */
export const paramApi = {
  ...crudApi<ParameterVo, ParameterCreate>(BASE),
  /** drops every param's cached value on the server */
  refreshCache: () => api.post(`${BASE}/refresh-cache`),
}
