<!-- @generated by qw-codegen (tree) -->
<script setup lang="ts">
import { computed, shallowRef, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import {
  MENU_GROUP_ROUTE_NAME,
  type MenuKind,
  menuCreate,
  menuParentAllows,
  menuUnusedFields,
} from '@qiwu/shared'
import { menuApi } from '@/api/platform/iam/menu'
import IconPicker from '@/core/components/IconPicker.vue'
import TreeParentSelect from '@/core/components/TreeParentSelect.vue'
import { useCrudForm } from '@/core/composables/use-crud'
import { useDict } from '@/core/composables/use-dict'
import { localized } from '@/core/i18n'
import { joinPath } from '@/core/router/build-routes'

/**
 * Add / edit form of the menu tree, opened with `openDialog(MenuForm, { id })` or, to add
 * below a row, `{ parentId, kind }`. The kind (fixed once added) and, for a page, the link type decide
 * the fields shown (`menuUnusedFields`: the server saves the hidden ones empty) and the parents offered
 * (`menuParentAllows`; the row itself and its subtree are left out, cleared = top level). A group's route
 * name is required in the generator's format, filled from the full route path (`/erp/sale` → `erp-sale`; a
 * relative path hangs below the parent's) until typed over, and read-only once saved in that format (the server refuses a change too).
 */
defineOptions({ name: 'IamMenuForm' })
const {
  id,
  parentId = 0,
  kind = 'group',
} = defineProps<{ id?: number; parentId?: number; kind?: MenuKind }>()
const emit = defineEmits<{ done: [saved: { id: number }]; cancel: [] }>()
const { t } = useI18n()
const { model, row, formRef, rules, loading, submitting, submit } = useCrudForm({
  api: menuApi,
  schema: menuCreate,
  emptyModel: () => ({
    parentId,
    kind,
    name: '',
    nameI18n: { 'zh-CN': '', 'en-US': '' },
    routePath: '',
    component: '',
    componentName: '',
    routeName: '',
    linkType: 'route' as const,
    linkUrl: '',
    perms: '',
    icon: '',
    sortNo: 0,
    visible: true,
    keepAlive: false,
    alwaysShow: false,
    enabled: true,
  }),
  id,
  emit,
})
// a row saved without per-locale names loads null: the two inputs need the object
watch(
  () => model.nameI18n,
  (v) => {
    if (!v) model.nameI18n = { 'zh-CN': '', 'en-US': '' }
  },
)
const { options: kindOptions } = useDict('iam.menu_kind')
const { options: linkTypeOptions } = useDict('iam.menu_link_type')
// the parent picker's rows (enabled ones): their kinds decide what this row may hold
const parents = menuApi.list({ enabled: true })
const kinds = shallowRef(new Map<number, MenuKind>())
/** each parent's full route path: its ancestors' (possibly relative) paths joined as the router does */
const fullPaths = shallowRef(new Map<number, string>())
void parents
  .then((forest) => {
    const map = new Map<number, MenuKind>()
    const paths = new Map<number, string>()
    const walk = (list: typeof forest, base: string) =>
      list.forEach((n) => {
        const path = joinPath(base, n.routePath)
        map.set(n.id, n.kind)
        paths.set(n.id, path)
        walk(n.children, path)
      })
    walk(forest, '')
    kinds.value = map
    fullPaths.value = paths
  })
  .catch(() => undefined) // the request layer showed it
const unused = computed(() =>
  menuUnusedFields(model.kind, model.linkType, kinds.value.get(model.parentId ?? 0)),
)
const shown = (field: keyof typeof model) => !(field in unused.value)

const group = computed(() => model.kind === 'group')
/** a saved group's route name (in the group format) is the natural key seeds find it by */
const routeNameFixed = computed(
  () => group.value && MENU_GROUP_ROUTE_NAME.test(row.value?.routeName ?? ''),
)
/** `/erp/sale` → `erp-sale`: the group route name a full path suggests */
const routeNameOf = (path: string) =>
  path
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^[^a-z]+|-+$/g, '')
/** the route name the path suggests, a relative one under the parent's full path (`sale` below `/erp`) */
const suggested = computed(() =>
  model.routePath
    ? routeNameOf(joinPath(fullPaths.value.get(model.parentId ?? 0) ?? '', model.routePath))
    : '',
)
// follows the path, the parent and the parents' arrival until typed over
watch(suggested, (name, before) => {
  if (!group.value || routeNameFixed.value) return
  if (!model.routeName || model.routeName === before) model.routeName = name
})
</script>

<template>
  <el-form ref="formRef" v-loading="loading" :model="model" :rules="rules" label-position="left">
    <el-form-item :label="t('field.iam.menu.kind')" prop="kind">
      <el-radio-group v-model="model.kind" :disabled="id != null">
        <el-radio v-for="o in kindOptions" :key="o.value" :value="o.value">{{ o.label }}</el-radio>
      </el-radio-group>
    </el-form-item>
    <el-form-item :label="t('field.iam.menu.parentId')" prop="parentId">
      <!-- the page's enabled rows (a disabled parent is refused) that hold this kind, without this one
           and its subtree -->
      <TreeParentSelect
        v-model="model.parentId"
        :load="() => parents"
        :label="(n) => localized(n.nameI18n, n.name)"
        :disabled="(n) => !menuParentAllows(n.kind, model.kind)"
        :exclude="id"
      />
    </el-form-item>
    <el-form-item :label="t('field.iam.menu.name')" prop="name">
      <el-input
        v-model="model.name"
        maxlength="128"
        :placeholder="t('iam.menu.placeholder.name')"
      />
    </el-form-item>
    <el-form-item :label="t('field.iam.menu.zh-CN')">
      <el-input v-model="model.nameI18n!['zh-CN']" maxlength="128" />
    </el-form-item>
    <el-form-item :label="t('field.iam.menu.en-US')">
      <el-input v-model="model.nameI18n!['en-US']" maxlength="128" />
    </el-form-item>
    <el-form-item v-if="shown('linkType')" :label="t('field.iam.menu.linkType')" prop="linkType">
      <el-radio-group v-model="model.linkType">
        <el-radio v-for="o in linkTypeOptions" :key="o.value" :value="o.value">{{
          o.label
        }}</el-radio>
      </el-radio-group>
    </el-form-item>
    <el-form-item v-if="shown('linkUrl')" :label="t('field.iam.menu.linkUrl')" prop="linkUrl">
      <el-input v-model="model.linkUrl" maxlength="512" placeholder="https://" />
    </el-form-item>
    <el-form-item v-if="shown('icon')" :label="t('field.iam.menu.icon')" prop="icon">
      <IconPicker v-model="model.icon" />
    </el-form-item>
    <el-form-item v-if="shown('routePath')" :label="t('field.iam.menu.routePath')" prop="routePath">
      <el-input
        v-model="model.routePath"
        maxlength="255"
        :placeholder="t('iam.menu.placeholder.routePath')"
      />
    </el-form-item>
    <el-form-item v-if="shown('component')" :label="t('field.iam.menu.component')" prop="component">
      <el-input
        v-model="model.component"
        maxlength="255"
        :placeholder="t('iam.menu.placeholder.component')"
      />
    </el-form-item>
    <el-form-item
      v-if="shown('componentName')"
      :label="t('field.iam.menu.componentName')"
      prop="componentName"
    >
      <el-input
        v-model="model.componentName"
        maxlength="128"
        :placeholder="t('iam.menu.placeholder.componentName')"
      />
    </el-form-item>
    <el-form-item
      v-if="shown('routeName')"
      :label="t('field.iam.menu.routeName')"
      prop="routeName"
      :required="group"
    >
      <el-input
        v-model="model.routeName"
        maxlength="128"
        :disabled="routeNameFixed"
        :title="routeNameFixed ? t('iam.menu.routeNameFixed') : undefined"
        :placeholder="
          t(group ? 'iam.menu.placeholder.groupRouteName' : 'iam.menu.placeholder.routeName')
        "
      />
    </el-form-item>
    <el-form-item v-if="shown('perms')" :label="t('field.iam.menu.perms')" prop="perms">
      <el-input
        v-model="model.perms"
        maxlength="128"
        :placeholder="t('iam.menu.placeholder.perms')"
      />
    </el-form-item>
    <el-form-item :label="t('field.iam.menu.sortNo')" prop="sortNo">
      <el-input-number v-model="model.sortNo" :min="0" :max="999999" controls-position="right" />
    </el-form-item>
    <el-form-item v-if="shown('visible')" :label="t('field.iam.menu.visible')" prop="visible">
      <el-switch v-model="model.visible" />
    </el-form-item>
    <el-form-item v-if="shown('keepAlive')" :label="t('field.iam.menu.keepAlive')" prop="keepAlive">
      <el-switch v-model="model.keepAlive" />
    </el-form-item>
    <el-form-item
      v-if="shown('alwaysShow')"
      :label="t('field.iam.menu.alwaysShow')"
      prop="alwaysShow"
    >
      <el-switch v-model="model.alwaysShow" />
    </el-form-item>
    <el-form-item :label="t('field.iam.menu.enabled')" prop="enabled">
      <el-switch v-model="model.enabled" />
    </el-form-item>
  </el-form>
  <div class="qw-dialog-footer">
    <el-button @click="emit('cancel')">{{ t('common.action.cancel') }}</el-button>
    <el-button type="primary" :loading="submitting" @click="submit">
      {{ t('crud.action.save') }}
    </el-button>
  </div>
</template>
