// @generated by qw-codegen (tree)
import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  ParseIntPipe,
  Post,
  Put,
  Query,
} from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import {
  type EnabledBody,
  enabledBody,
  type MenuCreate,
  menuCreate,
  menuPerms,
  type MenuQuery,
  menuQuery,
  menuRowNodeVo,
  type MenuSortBody,
  menuSortBody,
  type MenuUpdate,
  menuUpdate,
  menuVo,
} from '@qiwu/shared'
import { z } from 'zod'
import { ActionLog } from '../../../../core/audit/action-log.js'
import { RequirePerm } from '../../../../core/auth/decorators.js'
import { Idempotent } from '../../../../core/guard/idempotent.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import type { Menu } from './menu.entity.js'
import { MenuService } from './menu.service.js'

@ApiTags('iam')
@Controller('iam/menus')
export class MenuController {
  constructor(private readonly menus: MenuService) {}

  @Get()
  @RequirePerm(menuPerms.browse)
  @ApiOperation({ summary: 'Menus matching the filters as a forest (not paged)' })
  @ApiEnvelope(z.array(menuRowNodeVo))
  list(@Query({ schema: menuQuery }) query: MenuQuery) {
    return this.menus.list(query)
  }

  @Get(':id')
  @RequirePerm(menuPerms.view)
  @ApiOperation({ summary: 'One menu' })
  @ApiEnvelope(menuVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.menus.get(id)
  }

  @Post()
  @RequirePerm(menuPerms.create)
  @Idempotent()
  @ActionLog({
    domain: 'iam.menu',
    verb: 'create',
    bizId: (_req, row) => (row as Menu | undefined)?.id,
  })
  @ApiOperation({ summary: 'Add a menu under an enabled parent holding its kind (0 = top level)' })
  @ApiEnvelope(menuVo, 201)
  create(@Body({ schema: menuCreate }) dto: MenuCreate) {
    return this.menus.create(dto)
  }

  // static segment before `:id`
  @Put('sort')
  @RequirePerm(menuPerms.modify)
  @ActionLog({ domain: 'iam.menu', verb: 'modify' })
  @ApiOperation({ summary: 'New sort numbers of several menus at once (all or nothing)' })
  @ApiEnvelope()
  sort(@Body({ schema: menuSortBody }) dto: MenuSortBody) {
    return this.menus.sort(dto)
  }

  @Put(':id')
  @RequirePerm(menuPerms.modify)
  @ActionLog({ domain: 'iam.menu', verb: 'modify' })
  @ApiOperation({ summary: 'Change a menu, not its kind (a new parent moves its whole subtree)' })
  @ApiEnvelope()
  update(@Param('id', ParseIntPipe) id: number, @Body({ schema: menuUpdate }) dto: MenuUpdate) {
    return this.menus.update(id, dto)
  }

  @Put(':id/enabled')
  @RequirePerm(menuPerms.modify)
  @ActionLog({ domain: 'iam.menu', verb: 'modify' })
  @ApiOperation({ summary: 'Enable or disable a menu (a disabled menu hides its subtree)' })
  @ApiEnvelope()
  setEnabled(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: enabledBody }) dto: EnabledBody,
  ) {
    return this.menus.update(id, dto)
  }

  @Delete(':id')
  @RequirePerm(menuPerms.remove)
  @ActionLog({ domain: 'iam.menu', verb: 'remove' })
  @ApiOperation({ summary: 'Delete a menu without children' })
  @ApiEnvelope()
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.menus.remove([id])
  }
}
