// @generated by qw-codegen (crud)
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { ActionLogController } from './action-log.controller.js'
import { ActionLog } from './action-log.entity.js'
import { ActionLogService } from './action-log.service.js'

@Module({
  imports: [TypeOrmModule.forFeature([ActionLog])],
  controllers: [ActionLogController],
  providers: [ActionLogService],
})
export class ActionLogModule {}
