// @generated by qw-codegen (crud)
import { Column, CreateDateColumn, Entity } from 'typeorm'
import { IdEntity } from '../../../../core/db/base.entity.js'

/**
 * `aud_action_log`: 操作日志. Append-only (core/audit AuditWriter inserts it), so no audit columns but
 * `created_at` (not a BaseEntity); soft-deleted like every table (IdEntity).
 */
@Entity('aud_action_log')
export class ActionLog extends IdEntity {
  /** 追踪 ID */
  @Column({ name: 'trace_id', type: 'varchar', length: 64, nullable: true })
  traceId: string | null

  /** 业务域（如 iam.user） */
  @Column({ length: 64 })
  domain: string

  /** 动作（create/modify/remove/…） */
  @Column({ length: 32 })
  verb: string

  /** 业务 ID */
  @Column({ name: 'biz_id', type: 'varchar', length: 64, nullable: true })
  bizId: string | null

  /** 操作人 ID */
  @Column({ name: 'user_id', type: 'bigint', unsigned: true, nullable: true })
  userId: number | null

  /** User type at the time of the event. */
  @Column({ name: 'user_type', type: 'varchar', length: 16, default: 'admin' })
  userType: string

  /** 操作人登录名 */
  @Column({ type: 'varchar', length: 64, nullable: true })
  username: string | null

  /** 操作人部门（i18n 键或文本） */
  @Column({ name: 'dept_name', type: 'varchar', length: 64, nullable: true })
  deptName: string | null

  /** 请求方法 */
  @Column({ name: 'http_method', length: 10 })
  httpMethod: string

  /** 请求 URL */
  @Column({ length: 512 })
  url: string

  /** IP 地址 */
  @Column({ type: 'varchar', length: 64, nullable: true })
  ip: string | null

  /** 操作地点 */
  @Column({ type: 'varchar', length: 128, nullable: true })
  location: string | null

  /** User-Agent */
  @Column({ name: 'user_agent', type: 'varchar', length: 512, nullable: true })
  userAgent: string | null

  /** 请求参数（JSON，敏感键脱敏，≤4 KB） */
  @Column({ type: 'text', nullable: true })
  params: string | null

  /** 返回结果（JSON，敏感键脱敏，≤2 KB） */
  @Column({ type: 'text', nullable: true })
  result: string | null

  /** 是否成功 */
  @Column({ type: 'boolean' })
  ok: boolean

  /** 失败原因（错误消息 i18n 键） */
  @Column({ name: 'error_msg', type: 'varchar', length: 1000, nullable: true })
  errorMsg: string | null

  /** 耗时（毫秒） */
  @Column({ name: 'cost_ms', type: 'int', unsigned: true })
  costMs: number

  /** 发生时间（UTC） */
  @CreateDateColumn({ name: 'created_at', type: 'datetime', precision: 3 })
  createdAt: Date
}
