// @generated by qw-codegen (crud)
// Action log menus: the page under the `audit` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (audit.action-log.json), the actions' in menu.json (menu.action.*).
import { actionLogPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [actionLogPerms.browse, 'menu.action.browse'],
  [actionLogPerms.view, 'menu.action.view'],
  [actionLogPerms.export, 'menu.action.export'],
  [actionLogPerms.remove, 'menu.action.remove'],
]

export async function seedActionLog(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'audit' })
  if (parentId === undefined) throw new Error('seedActionLog: the audit menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'audit-action-log' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.audit.actionLog',
      route_path: '/audit/action-logs',
      component: 'platform/audit/action-log/index',
      component_name: 'AuditActionLog',
      keep_alive: 1,
      icon: 'lucide:scroll-text',
      sort_no: 10,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
