<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import { ElMessageBox } from 'element-plus'
import { clientPerms, type ClientVo } from '@qiwu/shared'
import { clientApi } from '@/api/platform/oauth/client'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { toastRest, useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { openDialog } from '@/core/dialog'
import { tx } from '@/core/i18n'
import { Icon } from '@/core/icons'
import { usePerm } from '@/core/permission'
import ClientForm from './form.vue'
import ClientSecret from './secret.vue'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'OauthClient' })

const { t } = useI18n()
const {
  query,
  rows,
  total,
  loading,
  filtered,
  selection,
  search,
  reset,
  refresh,
  onSelectionChange,
  onSortChange,
  remove,
  batchRemove,
} = useCrudList({
  api: clientApi,
  filters: {
    clientId: '',
    name: '',
    enabled: null as string | null,
  },
  sort: '-createdAt',
})
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `oauth.client`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  {
    prop: 'clientId',
    label: 'field.oauth.client.clientId',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'name',
    label: 'field.oauth.client.name',
    sortable: true,
    minWidth: 160,
    showOverflowTooltip: true,
  },
  { prop: 'grantTypes', label: 'field.oauth.client.grantTypes', width: 280 },
  { prop: 'isBuiltin', label: 'field.oauth.client.isBuiltin', width: 100 },
  { prop: 'enabled', label: 'field.oauth.client.enabled', width: 100 },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
]
// computed: the perms reload when the server's permission version moves
const perm = usePerm()
const canModify = computed(() => perm.has(clientPerms.modify))
// the edit form loads GET /:id, which needs `view` too
const canEdit = computed(() => perm.all([clientPerms.modify, clientPerms.view]))

/** Add (no id) or edit in the form dialog; reload once saved, then show an added client's secret. */
async function openForm(id?: number) {
  const name = () => t('oauth.client.entity')
  const saved = await openDialog<{ id: number; clientId: string; secret?: string }>(
    ClientForm,
    { id },
    // the form's fields in 2 columns
    {
      title: () => t(id ? 'crud.title.edit' : 'crud.title.create', { name: name() }),
      width: '880px',
    },
  )
  if (!saved) return
  await refresh()
  if (saved.secret) await showSecret(saved.clientId, saved.secret)
}

/** The secret is answered this once: ESC does not close it by accident. */
function showSecret(clientId: string, secret: string) {
  return openDialog(
    ClientSecret,
    { clientId, secret },
    { title: () => t('oauth.client.secretTitle'), closeOnPressEscape: false },
  )
}

/** A new secret after a confirm; the old one stops working at once (failures: the request layer). */
async function resetSecret(row: ClientVo) {
  const go = await ElMessageBox.confirm(
    t('oauth.client.resetConfirm', { id: row.clientId }),
    t('crud.confirm.title'),
    {
      type: 'warning',
      confirmButtonText: t('menu.action.resetSecret'),
      cancelButtonText: t('common.action.cancel'),
    },
  ).catch(() => false)
  if (!go) return
  try {
    const { secret } = await clientApi.resetSecret(row.id)
    await showSecret(row.clientId, secret)
  } catch (e) {
    toastRest(e)
  }
}

async function setEnabled(row: ClientVo, enabled: boolean) {
  // failures are toasted by the request layer; the reload shows the stored state either way
  await clientApi.setEnabled(row.id, enabled).catch(() => undefined)
  await refresh()
}
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.oauth.client.clientId')">
          <el-input v-model="query.clientId" name="clientId" clearable />
        </el-form-item>
        <el-form-item :label="t('field.oauth.client.name')">
          <el-input v-model="query.name" name="name" clearable />
        </el-form-item>
        <el-form-item :label="t('field.oauth.client.enabled')">
          <DictSelect v-model="query.enabled" code="core.enabled" />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="oauth.client"
        :columns="columns"
        @refresh="refresh"
      >
        <el-button v-perm="clientPerms.create" type="primary" @click="openForm()">
          <el-icon class="el-icon--left"><Icon icon="lucide:plus" /></el-icon>
          {{ t('crud.action.create') }}
        </el-button>
        <el-button
          v-if="selection.length"
          v-perm="clientPerms.remove"
          type="danger"
          plain
          @click="batchRemove"
        >
          {{ t('crud.action.batchDelete') }}
        </el-button>
      </TableToolbar>

      <QwTable
        table-id="oauth.client"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        selection
        :selectable="(row: ClientVo) => !row.isBuiltin"
        :actions-width="200"
        @selection-change="onSelectionChange"
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <!-- seeded names are i18n keys (seed.oauth.*) -->
        <template #cell-name="{ row }">{{ tx(row.name) }}</template>
        <template #cell-grantTypes="{ row }">
          <el-tag
            v-for="g in (row as ClientVo).grantTypes"
            :key="g"
            size="small"
            class="client-grant"
          >
            {{ t(`oauth.client.grant.${g}`) }}
          </el-tag>
        </template>
        <template #cell-isBuiltin="{ row }">
          <DictTag code="core.yes_no" :value="row.isBuiltin" />
        </template>
        <template #cell-enabled="{ row }">
          <el-switch
            v-if="canModify"
            size="small"
            :model-value="row.enabled"
            :disabled="row.isBuiltin"
            :aria-label="`${t('field.oauth.client.enabled')} ${tx(row.name)}`"
            @change="setEnabled(row, $event as boolean)"
          />
          <DictTag v-else code="core.enabled" :value="row.enabled" />
        </template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #actions="{ row }">
          <!-- built-in rows (console) are read-only: the server answers 422 anyway -->
          <el-button
            v-if="canEdit"
            link
            type="primary"
            :disabled="row.isBuiltin"
            @click="openForm(row.id)"
          >
            {{ t('crud.action.edit') }}
          </el-button>
          <el-button
            v-perm="clientPerms['reset-secret']"
            link
            type="primary"
            :disabled="row.isBuiltin"
            @click="resetSecret(row)"
          >
            {{ t('menu.action.resetSecret') }}
          </el-button>
          <el-button
            v-perm="clientPerms.remove"
            link
            type="danger"
            :disabled="row.isBuiltin"
            @click="remove([row.id])"
          >
            {{ t('crud.action.delete') }}
          </el-button>
        </template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>
  </div>
</template>

<style scoped>
.client-grant + .client-grant {
  margin-left: 4px;
}
</style>
