// @generated by qw-codegen (tree)
import { z } from 'zod'
import { type MenuLinkType, PERM_CODE } from '../../common/auth.js'
import { blankAsNull, i18nTextInput } from '../../common/crud.js'
import { WEB_STATIC_ROUTE_NAMES } from '../../common/reserved-names.js'
import { fieldDomains } from '../../validation/zod-i18n.js'

/**
 * Menus (`iam_menu`), `/api/iam/menus` (see docs/design-notes.md#api-envelope), a tree table (`parent_id`, 0 =
 * top level, + `tree_path`) listed whole as a forest (docs/codegen-golden.md "Tree"): the rows
 * `/api/auth/menus` and the roles' grants are made of. Field labels `field.iam.menu.<prop>`.
 * - `kind` (set when the row is added): `group` a section of the side menu (a route path its pages may
 *   extend); `page` a view (`linkType` `route`), an embedded page (`iframe`) or an external link opened in
 *   a new tab (`external`); `action` a permission point (`perms`) under a page.
 * - `name`: an i18n key (seeded menus, `menu.*`) or text; `nameI18n` per locale wins over it (see docs/design-notes.md#i18n).
 * - A change of `perms`, `enabled` or the parent, and a delete, reload every session (`PermVersion.bumpAll`);
 *   a menu with children or granted to a role is not deleted (409).
 */

export const menuPerms = {
  browse: 'iam.menu.browse',
  view: 'iam.menu.view',
  create: 'iam.menu.create',
  modify: 'iam.menu.modify',
  remove: 'iam.menu.remove',
} as const

/** menus a sort request may renumber at once */
const MENU_SORT_MAX = 500

export const MENU_KINDS = ['group', 'page', 'action'] as const
export type MenuKind = (typeof MENU_KINDS)[number]
export const MENU_LINK_TYPES = [
  'route',
  'iframe',
  'external',
] as const satisfies readonly MenuLinkType[]

/** The kinds a parent of each kind holds: pages hold hidden sub-pages and their actions. */
const CHILD_KINDS: Record<MenuKind | 'top', readonly MenuKind[]> = {
  top: ['group', 'page'],
  group: ['group', 'page'],
  page: ['page', 'action'],
  action: [],
}
/** May a menu of `kind` go under a parent of kind `parent` (null = top level)? Else 422 `iam.menu_parent_kind`. */
export const menuParentAllows = (parent: MenuKind | null, kind: MenuKind): boolean =>
  CHILD_KINDS[parent ?? 'top'].includes(kind)

/**
 * A group's route name: the generator's format (`CG_IDENT.routeName`), required, and fixed
 * once saved (422 `iam.menu_route_name_fixed`): the natural key seeds find the group by.
 */
export const MENU_GROUP_ROUTE_NAME = /^[a-z][a-z0-9-]{0,127}$/

/**
 * The built-in menu groups, exactly (`home` is a page): what the template's seeds create
 * (seed-idempotent checks it). The generator's parent-chain walk stops at the first of these: a project
 * group (db/seeds/project/menu-groups.seed.ts) is any other.
 */
export const BUILTIN_MENU_GROUPS: readonly string[] = [
  'workflow',
  'wf-admin',
  'biz',
  'system',
  'messaging',
  'audit',
  'storage',
  'monitor',
  'devtools',
  'demo',
]

/** any menu's route name (a group's: `MENU_GROUP_ROUTE_NAME`) */
const ROUTE_NAME = /^[A-Za-z][\w-]*$/
/** `/iam/users/:id/roles`, `reports` (relative: under the parent's path) */
const ROUTE_PATH = /^[\w\-./:]*$/
/** a view under src/views without extension: `platform/iam/menu/index` */
const COMPONENT = /^[\w-]+(\/[\w-]+)*$/
const ICON = /^lucide:[a-z0-9]+(-[a-z0-9]+)*$/
/** a path on this site (`/api/docs`): one leading slash, never `//host` or `/\host`, no spaces */
const SITE_PATH = /^\/(?![/\\])[^\s\\]*$/

const menuFields = z.object({
  parentId: z.number().int().min(0).optional(),
  kind: z.enum(MENU_KINDS),
  name: z.string().trim().min(1).max(128),
  /** per-locale names; blank ones are left out, none at all = null */
  nameI18n: i18nTextInput(128),
  /** unique among siblings (top-level menus too): 409 `duplicate` */
  routePath: z.string().trim().max(255).regex(ROUTE_PATH).optional(),
  component: blankAsNull(z.string().trim().max(255).regex(COMPONENT)),
  componentName: blankAsNull(
    z
      .string()
      .trim()
      .max(128)
      .regex(/^[A-Za-z]\w*$/),
  ),
  /** unique among menus (409 `duplicate`); never a static route's of the web (`profile`, `my-inbox`) */
  routeName: blankAsNull(
    z
      .string()
      .trim()
      .max(128)
      .regex(ROUTE_NAME)
      .refine((n) => !WEB_STATIC_ROUTE_NAMES.includes(n), {
        error: 'validation.route_name_reserved',
      }),
  ),
  /** reserved: the web router does not read it yet */
  routeQuery: blankAsNull(z.string().trim().max(255)),
  linkType: z.enum(MENU_LINK_TYPES).optional(),
  /** http(s), or a path on this site (the seeded API docs iframe: `/api/docs`) */
  linkUrl: blankAsNull(
    z
      .string()
      .trim()
      .max(512)
      .pipe(z.union([z.string().regex(SITE_PATH), z.url({ protocol: /^https?$/ })])),
  ),
  /** `<domain>.<resource>.<verb>` (see docs/design-notes.md#permissions) */
  perms: blankAsNull(z.string().trim().max(128).regex(PERM_CODE)),
  /** a Lucide icon (`lucide:house`, IconPicker) */
  icon: blankAsNull(z.string().trim().max(64).regex(ICON)),
  sortNo: z.number().int().min(0).max(999_999).optional(),
  visible: z.boolean().optional(),
  keepAlive: z.boolean().optional(),
  alwaysShow: z.boolean().optional(),
  enabled: z.boolean().optional(),
})
type MenuFields = z.infer<typeof menuFields>

/**
 * The fields a menu of `kind` (a page: of `linkType`, under a parent of `parentKind`) does not use, with the
 * values they are saved as: the form hides them, the server writes these values (external links
 * register no route, iframe pages show `linkUrl` in IframeView, keep-alive by `componentName`; a page under
 * a page is a hidden sub-page, the side menu shows pages as leaves; see docs/design-notes.md#layering).
 */
export function menuUnusedFields(
  kind: MenuKind,
  linkType: MenuLinkType = 'route',
  parentKind: MenuKind | null = null,
): Partial<MenuFields> {
  if (kind === 'page' && parentKind === 'page')
    return { ...menuUnusedFields(kind, linkType), visible: false }
  const view = { component: null, routeQuery: null, linkType: 'route', linkUrl: null } as const
  if (kind === 'action')
    return {
      ...view,
      routePath: '',
      routeName: null,
      componentName: null,
      icon: null,
      visible: true,
      keepAlive: false,
      alwaysShow: false,
    }
  if (kind === 'group') return { ...view, componentName: null, keepAlive: false, perms: null }
  const page = { perms: null, alwaysShow: false } as const
  if (linkType === 'route') return { ...page, linkUrl: null }
  if (linkType === 'iframe') return { ...page, component: null, routeQuery: null }
  return {
    ...page,
    routePath: '',
    component: null,
    componentName: null,
    routeQuery: null,
    keepAlive: false,
  }
}

/**
 * What each kind needs: a group its path and route name (`MENU_GROUP_ROUTE_NAME`; not judged when
 * `groupRouteName` is false), a page its path + view or link, an action its perms.
 */
function kindRules(m: MenuFields, ctx: z.RefinementCtx, groupRouteName = true) {
  const need = (path: 'routePath' | 'component' | 'linkUrl' | 'perms' | 'routeName') => {
    if (m[path] == null || m[path] === '')
      ctx.addIssue({ code: 'custom', path: [path], message: 'validation.required', input: m[path] })
  }
  const link = m.linkType ?? 'route'
  if (m.kind === 'action') return need('perms')
  const group = m.kind === 'group' && groupRouteName
  if (group) need('routeName')
  // (one the field's own format refuses is reported once, by the field)
  const name = m.routeName ?? ''
  if (group && ROUTE_NAME.test(name) && !MENU_GROUP_ROUTE_NAME.test(name))
    ctx.addIssue({
      code: 'custom',
      path: ['routeName'],
      message: 'validation.invalid_format.other',
      input: m.routeName,
    })
  if (m.kind === 'group' || link !== 'external') need('routePath')
  if (m.kind === 'page') need(link === 'route' ? 'component' : 'linkUrl')
}

/**
 * POST body; columns with a DB default may be left out, nullable ones may be null. `parentId`: 0 =
 * top level, else an enabled row (404 / 422 `tree.parent_disabled`) that holds this kind (422
 * `iam.menu_parent_kind`); changing it moves the row with its whole subtree, never below itself (422
 * `tree.parent_invalid`). A non-root caller writes only `perms` it holds itself (403
 * `iam.grant_exceeds_own`: the perm reaches every role granted the menu).
 */
export const menuCreate = menuFields.superRefine(kindRules).register(fieldDomains, {
  domain: 'iam.menu',
})
export type MenuCreate = z.infer<typeof menuCreate>

/**
 * The row a PUT leaves when it sends no `routeName` (the server's check): `menuCreate` without the group
 * route-name rule, so an older group (route name NULL, `Legacy_Group`) is still enabled, moved or renamed;
 * a `routeName` sent is judged in full (the menu page's form always sends it).
 */
export const menuKeptRouteName = menuFields
  .superRefine((m, ctx) => kindRules(m, ctx, false))
  .register(fieldDomains, { domain: 'iam.menu' })

/** PUT body: the fields sent are changed, the others kept; the kind stays. The row as saved must hold. */
export const menuUpdate = menuFields
  .omit({ kind: true })
  .partial()
  .register(fieldDomains, { domain: 'iam.menu' })
export type MenuUpdate = z.infer<typeof menuUpdate>

/**
 * PUT /sort (modify): new sort numbers of several menus at once (the list's sort mode), all or nothing (an
 * unknown id → 404). Parents stay; perms are untouched, so sessions need no reload.
 */
export const menuSortBody = z
  .object({
    items: z
      .array(
        z.object({
          id: z.number().int().positive(),
          sortNo: z.number().int().min(0).max(999_999),
        }),
      )
      .min(1)
      .max(MENU_SORT_MAX),
  })
  .register(fieldDomains, { domain: 'iam.menu' })
export type MenuSortBody = z.infer<typeof menuSortBody>

/**
 * GET query: the list filters (kind, enabled equal). A matching row whose parent does not match is a root
 * of the result. The page filters names on its own (the texts of seeded keys are the web's).
 */
export const menuQuery = z
  .object({
    kind: z.enum(MENU_KINDS).optional(),
    enabled: z.stringbool().optional(),
  })
  .register(fieldDomains, { domain: 'iam.menu' })
export type MenuQuery = z.output<typeof menuQuery>

export const menuVo = z.object({
  id: z.number().int(),
  parentId: z.number().int(),
  treePath: z.string(),
  kind: z.enum(MENU_KINDS),
  name: z.string(),
  nameI18n: z.object({ 'zh-CN': z.string(), 'en-US': z.string() }).partial().nullable(),
  routePath: z.string(),
  component: z.string().nullable(),
  componentName: z.string().nullable(),
  routeName: z.string().nullable(),
  routeQuery: z.string().nullable(),
  linkType: z.enum(MENU_LINK_TYPES),
  linkUrl: z.string().nullable(),
  perms: z.string().nullable(),
  icon: z.string().nullable(),
  sortNo: z.number().int(),
  visible: z.boolean(),
  keepAlive: z.boolean(),
  alwaysShow: z.boolean(),
  enabled: z.boolean(),
  createdBy: z.number().int().nullable(),
  createdAt: z.iso.datetime(),
  updatedBy: z.number().int().nullable(),
  updatedAt: z.iso.datetime(),
})
export type MenuVo = z.infer<typeof menuVo>

/** A row of the menu page's forest (not `MenuNode`: that is the `/api/auth/menus` tree). */
export interface MenuRowNode extends MenuVo {
  children: MenuRowNode[]
}

/** GET / (browse): the menus matching the filters as a forest, siblings by `sort_no, id`. */
export const menuRowNodeVo: z.ZodType<MenuRowNode> = menuVo.extend({
  get children() {
    return z.array(menuRowNodeVo)
  },
})
