// @generated by qw-codegen (crud)
import { z } from 'zod'
import { PAGE_SIZE_MAX, pageQuery } from '../../common/pagination.js'
import { fieldDomains } from '../../validation/zod-i18n.js'
import { menuVo } from './menu.schema.js'
import { userVo } from './user.schema.js'

/**
 * Roles (`iam_role`), `/api/iam/roles` (see docs/design-notes.md#api-envelope). Field labels
 * `field.iam.role.<prop>`. Not data-scoped (see docs/design-notes.md#data-scope): roles belong to no dept, `iam.role.*` perms and
 * GrantPolicy guard them. Builtin roles (`is_builtin`, set by seeds only) keep their code and are never
 * deleted; the root role (builtin, code `root`) is also never disabled and only a root caller edits it
 * (422 `iam.role_builtin`). A role held by users is not deleted (409 `iam.role_has_users`). A new role
 * starts with the data scope `own_dept` (the data-scope dialog changes it).
 */

export const rolePerms = {
  browse: 'iam.role.browse',
  view: 'iam.role.view',
  create: 'iam.role.create',
  modify: 'iam.role.modify',
  remove: 'iam.role.remove',
  export: 'iam.role.export',
  /** the menu grant and the data scope of a role (both what its holders may do) */
  grant: 'iam.role.grant',
  /** the members page: list, add and remove the users of a role */
  'assign-users': 'iam.role.assign-users',
} as const

/** Role data scope codes (see docs/design-notes.md#data-scope), the dict `iam.data_scope`. */
export const DATA_SCOPES = ['all', 'picked_depts', 'own_dept', 'own_dept_tree', 'own_rows'] as const
export type DataScopeCode = (typeof DATA_SCOPES)[number]

/** POST body; columns with a DB default may be left out, nullable ones may be null. */
export const roleCreate = z
  .object({
    name: z.string().trim().min(1).max(64),
    code: z.string().trim().min(1).max(64),
    sortNo: z.number().int().min(0).max(999_999).optional(),
    enabled: z.boolean().optional(),
    note: z.string().trim().max(500).nullish(),
  })
  .register(fieldDomains, { domain: 'iam.role' })
export type RoleCreate = z.infer<typeof roleCreate>

/** PUT body: the fields sent are changed, the others kept. */
export const roleUpdate = roleCreate.partial().register(fieldDomains, { domain: 'iam.role' })
export type RoleUpdate = z.infer<typeof roleUpdate>

/** GET query: paging, sort and the list filters (text contains, ranges from / to, the rest equals). */
export const roleQuery = pageQuery(['sortNo', 'name', 'code', 'dataScope', 'createdAt', 'id'])
  .extend({
    name: z.string().trim().max(64).optional(),
    code: z.string().trim().max(64).optional(),
    enabled: z.stringbool().optional(),
  })
  .register(fieldDomains, { domain: 'iam.role' })
export type RoleQuery = z.output<typeof roleQuery>

export const roleVo = z.object({
  id: z.number().int(),
  name: z.string(),
  code: z.string(),
  sortNo: z.number().int(),
  dataScope: z.string(),
  menuLink: z.boolean(),
  deptLink: z.boolean(),
  isBuiltin: z.boolean(),
  enabled: z.boolean(),
  note: z.string().nullable(),
  createdBy: z.number().int().nullable(),
  createdAt: z.iso.datetime(),
  updatedBy: z.number().int().nullable(),
  updatedAt: z.iso.datetime(),
})
export type RoleVo = z.infer<typeof roleVo>

/**
 * GET /options (any signed-in user): enabled roles by `sort_no, id`; `root` only for a root caller.
 * `name` is an i18n key (seeded roles, `seed.role.*`) or plain text: render with `tx()`.
 */
export const roleOptionVo = roleVo.pick({ id: true, code: true, name: true })
export type RoleOption = z.infer<typeof roleOptionVo>

/** ids one grant request may carry (menus and depts are hundreds at most) */
const GRANT_IDS_MAX = 5000
const grantIds = z.array(z.number().int().positive()).max(GRANT_IDS_MAX)

/**
 * PUT /:id/menus (`grant`; GET answers the same): the menus the role grants, replacing the stored ones,
 * and the grant tree's link switch (`menuLink`, kept for the next edit). The tree saves, with the link on
 * (a parent follows its children), the checked plus the half-checked menus, so a lone action brings its
 * page and group; it echoes only the leaves among them (el-tree derives the parents). With the link off it
 * saves and echoes exactly the checked ones. `/api/auth/menus` adds the ancestors of every granted menu
 * either way (see docs/design-notes.md#permissions). An unknown menu → 404; not for the root role (422 `iam.role_builtin`); the
 * holders get it at their next request.
 */
export const roleMenusBody = z
  .object({ menuLink: z.boolean(), menuIds: grantIds })
  .register(fieldDomains, { domain: 'iam.role' })
export type RoleMenusBody = z.infer<typeof roleMenusBody>

/**
 * PUT /:id/data-scope (`grant`; GET answers the same): the data scope (see docs/design-notes.md#data-scope), the depts of
 * `picked_depts` (stored only for it, saved and echoed like the menus by the dept tree's `deptLink`). An
 * unknown or deleted dept → 404; not for the root role (422); the holders get it at their next request.
 */
export const roleDataScopeBody = z
  .object({ dataScope: z.enum(DATA_SCOPES), deptLink: z.boolean(), deptIds: grantIds })
  .register(fieldDomains, { domain: 'iam.role' })
export type RoleDataScopeBody = z.infer<typeof roleDataScopeBody>

/** A node of the grant tree: every menu, disabled ones too, by `sort_no, id`. */
export interface RoleMenuNode extends Pick<
  z.infer<typeof menuVo>,
  'id' | 'parentId' | 'kind' | 'name' | 'nameI18n' | 'perms' | 'enabled'
> {
  children: RoleMenuNode[]
}

/** GET /menu-tree (`grant`): the whole menu table as a forest for the grant tree. */
export const roleMenuNodeVo: z.ZodType<RoleMenuNode> = menuVo
  .pick({
    id: true,
    parentId: true,
    kind: true,
    name: true,
    nameI18n: true,
    perms: true,
    enabled: true,
  })
  .extend({
    get children() {
      return z.array(roleMenuNodeVo)
    },
  })

/**
 * GET /:id/members (`assign-users`): a page of the users holding the role (`assigned`, the default) or not
 * (`assigned=false`), always through the caller's `iam_user` data scope (see docs/design-notes.md#data-scope): users outside it are
 * never listed. `keyword` = username or display name contains.
 */
export const roleMemberQuery = pageQuery(['username', 'displayName', 'createdAt', 'id'])
  .extend({
    assigned: z.stringbool().default(true),
    keyword: z.string().trim().max(64).optional(),
  })
  .register(fieldDomains, { domain: 'iam.role' })
export type RoleMemberQuery = z.output<typeof roleMemberQuery>

export const roleMemberVo = userVo.pick({
  id: true,
  username: true,
  displayName: true,
  deptId: true,
  deptName: true,
  enabled: true,
  createdAt: true,
})
export type RoleMemberVo = z.infer<typeof roleMemberVo>

/**
 * POST /:id/members (add) and /:id/members/revoke (remove), `assign-users`: users of the caller's data
 * scope (any other → 404, nothing changes); adding passes GrantPolicy for each user's dept (403), users
 * already in (or not in) the role are left as they are; nobody leaves the root role (422). The changed
 * users get it at their next request.
 */
export const roleMembersBody = z
  .object({ userIds: z.array(z.number().int().positive()).min(1).max(PAGE_SIZE_MAX) })
  .register(fieldDomains, { domain: 'iam.role' })
export type RoleMembersBody = z.infer<typeof roleMembersBody>
