// @generated by qw-codegen (crud)
import type { WfFormCreate, WfFormDetailVo, WfFormVo } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/wf/forms'

/** Process forms (/api/wf/forms; see docs/design-notes.md#workflow) behind `wfPerms.form`; the list leaves schemas out. */
export const wfFormApi = {
  ...crudApi<WfFormVo, WfFormCreate>(BASE),
  setEnabled: (id: number, enabled: boolean) => api.put(`${BASE}/${id}/enabled`, { enabled }),
  /** + the stored (sanitized) schema */
  detail: (id: number) => api.get<WfFormDetailVo>(`${BASE}/${id}`),
}
