// @generated by qw-codegen (crud)
// Param menus: the page under the `system` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (settings.param.json), the actions' in menu.json (menu.action.*).
import { paramPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [paramPerms.browse, 'menu.action.browse'],
  [paramPerms.view, 'menu.action.view'],
  [paramPerms.create, 'menu.action.create'],
  [paramPerms.modify, 'menu.action.modify'],
  [paramPerms.remove, 'menu.action.remove'],
  [paramPerms.export, 'menu.action.export'],
]

export async function seedParameter(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'system' })
  if (parentId === undefined) throw new Error('seedParameter: the system menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'settings-param' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.settings.param',
      route_path: '/settings/params',
      component: 'platform/settings/param/index',
      component_name: 'SettingsParameter',
      keep_alive: 1,
      icon: 'lucide:sliders-horizontal',
      sort_no: 70,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
