// @generated by qw-codegen (master_sub)
// Invoice menus: the page under the `demo` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (demo.invoice.json), the actions' in menu.json (menu.action.*).
import { invoicePerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findRow, upsert } from '../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [invoicePerms.browse, 'menu.action.browse'],
  [invoicePerms.view, 'menu.action.view'],
  [invoicePerms.create, 'menu.action.create'],
  [invoicePerms.modify, 'menu.action.modify'],
  [invoicePerms.remove, 'menu.action.remove'],
]

export async function seedInvoice(q: EntityManager): Promise<string[]> {
  // the group menu: one an administrator deleted skips these menus, a missing one is an error
  const parent = await findRow(q, 'iam_menu', { route_name: 'demo', kind: 'group' })
  if (!parent) throw new Error('seedInvoice: the demo menu group is missing')
  if (parent.deleted)
    return ['seed: the demo menu group was deleted: the invoice menus are skipped']
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'demo-invoice' },
    {
      kind: 'page',
      name: 'menu.demo.invoice',
      route_path: '/demo/invoices',
      component: 'demo/invoice/index',
      component_name: 'DemoInvoice',
      keep_alive: 1,
    },
    // written once: an administrator may move the page and change its icon and sort in the menu page
    { parent_id: parent.id, icon: 'lucide:receipt-text', sort_no: 30 },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
