// @generated by qw-codegen (master_sub)
import { Injectable, NotFoundException } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { InvoiceCreate, InvoiceLineInput, InvoiceQuery, InvoiceUpdate } from '@qiwu/shared'
import type { SelectQueryBuilder } from 'typeorm'
import { BaseCrudService } from '../../../core/db/base-crud.service.js'
import { contains } from '../../../core/db/page.js'
import { assertReferencesLive, softDeleteRows } from '../../../core/db/references.js'
import { InvoiceLine } from './invoice-line.entity.js'
import { Invoice } from './invoice.entity.js'

/**
 * Invoices over BaseCrudService, each saved as one document with its lines
 * (docs/codegen-golden.md "Master-sub"): create / update write the row and its sub rows in one
 * transaction, the base remove soft-deletes the row with its sub rows (the entity registers them as
 * cascaded). Uniqueness is the DB's (`unique(…, alive)`, errno 1062 → 409 `duplicate`).
 */
@Injectable()
export class InvoiceService extends BaseCrudService<Invoice> {
  constructor(txHost: TransactionHost<TransactionalAdapterTypeOrm>) {
    super(txHost, Invoice)
  }

  /** GET /:id: the row of the caller's scope (else 404) with its lines. */
  async detail(id: number): Promise<Invoice & { lines: InvoiceLine[] }> {
    const row = await this.get(id)
    return Object.assign(row, {
      lines: await this.txHost.tx.getRepository(InvoiceLine).find({
        where: { invoiceId: id },
        order: { id: 'ASC' },
      }),
    })
  }

  /** The row and its sub rows in one transaction; answers what GET /:id does. */
  override create({ lines, ...dto }: InvoiceCreate): Promise<Invoice & { lines: InvoiceLine[] }> {
    return this.txHost.withTransaction(async () => {
      const { id } = await super.create(dto)
      await this.saveLines(id, lines)
      return this.detail(id)
    })
  }

  /** The fields sent; a sub-row list sent is the whole new list (diffed), one left out is kept. */
  override update(id: number, { lines, ...dto }: InvoiceUpdate): Promise<void> {
    return this.txHost.withTransaction(async () => {
      // locks the row in the caller's scope first: the sub rows below are this document's
      await super.update(id, dto)
      if (lines) await this.saveLines(id, lines)
    })
  }

  /**
   * The lines of row `invoiceId` as sent, inside its write's transaction (the row locked or just
   * added): one with the id of a stored one is updated, one without an id added, stored ones not sent
   * deleted (soft, like every row); an id of any other row → 404 and the whole write is rolled back.
   * A reference a row holds (registered by the table it points at) must name a live row, else 404
   * (`assertReferencesLive`, as BaseCrudService does for the master); an update judges changed values only.
   */
  private async saveLines(invoiceId: number, rows: InvoiceLineInput[]): Promise<void> {
    const repo = this.txHost.tx.getRepository(InvoiceLine)
    const stored = new Map((await repo.find({ where: { invoiceId } })).map((r) => [r.id, r]))
    const sent = new Set(rows.flatMap((r) => (r.id === undefined ? [] : [r.id])))
    if ([...sent].some((id) => !stored.has(id))) throw new NotFoundException()
    const gone = [...stored.keys()].filter((id) => !sent.has(id))
    await softDeleteRows(this.txHost.tx, 'demo_invoice_line', gone)
    for (const { id, ...row } of rows)
      if (id === undefined) {
        const added = { ...row, invoiceId }
        await assertReferencesLive(this.txHost.tx, 'demo_invoice_line', added)
        await repo.insert(added)
      } else {
        await assertReferencesLive(this.txHost.tx, 'demo_invoice_line', row, async () =>
          stored.get(id)!,
        )
        await repo.update(id, row)
      }
  }

  protected override filter(
    qb: SelectQueryBuilder<Invoice>,
    { invoiceNo, buyer, issuedAtFrom, issuedAtTo, state, createdAtFrom, createdAtTo }: InvoiceQuery,
  ): SelectQueryBuilder<Invoice> {
    if (invoiceNo) qb.andWhere('t.invoice_no LIKE :invoiceNo', { invoiceNo: contains(invoiceNo) })
    if (buyer) qb.andWhere('t.buyer LIKE :buyer', { buyer: contains(buyer) })
    if (issuedAtFrom)
      qb.andWhere('t.issued_at >= :issuedAtFrom', { issuedAtFrom: new Date(issuedAtFrom) })
    if (issuedAtTo) qb.andWhere('t.issued_at <= :issuedAtTo', { issuedAtTo: new Date(issuedAtTo) })
    if (state) qb.andWhere('t.state = :state', { state })
    if (createdAtFrom)
      qb.andWhere('t.created_at >= :createdAtFrom', { createdAtFrom: new Date(createdAtFrom) })
    if (createdAtTo)
      qb.andWhere('t.created_at <= :createdAtTo', { createdAtTo: new Date(createdAtTo) })
    return qb
  }
}
