// @generated by qw-codegen (crud)
// Role menus: the page under the `system` group (found by route_name, never by id), one action
// row per permission and the hidden members page (`visible = 0`; see docs/design-notes.md#layering) holding the `assign-users`
// action, so granting that action also delivers its route. Upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (iam.role.json), the actions' in menu.json (menu.action.*).
import { rolePerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [rolePerms.browse, 'menu.action.browse'],
  [rolePerms.view, 'menu.action.view'],
  [rolePerms.create, 'menu.action.create'],
  [rolePerms.modify, 'menu.action.modify'],
  [rolePerms.remove, 'menu.action.remove'],
  [rolePerms.export, 'menu.action.export'],
  [rolePerms.grant, 'menu.action.grant'],
]

export async function seedRole(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'system' })
  if (parentId === undefined) throw new Error('seedRole: the system menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'iam-role' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.iam.role',
      route_path: '/iam/roles',
      component: 'platform/iam/role/index',
      component_name: 'IamRole',
      keep_alive: 1,
      icon: 'lucide:shield-user',
      sort_no: 20,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  const usersPageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'iam-role-users' },
    {
      parent_id: pageId,
      kind: 'page',
      name: 'menu.iam.roleUsers',
      route_path: '/iam/roles/:id/users',
      component: 'platform/iam/role/assign-users',
      component_name: 'IamRoleAssignUsers',
      visible: 0,
      keep_alive: 0,
      icon: 'lucide:users-round',
      sort_no: (ACTIONS.length + 1) * 10,
    },
  )
  await upsert(
    q,
    'iam_menu',
    { kind: 'action', perms: rolePerms['assign-users'] },
    { parent_id: usersPageId, name: 'menu.action.assignUsers', sort_no: 10 },
  )
  return []
}
