// @generated by qw-codegen (crud)
import { Column, Entity } from 'typeorm'
import { BaseEntity } from '../../../../core/db/base.entity.js'

/** `iam_role`: 角色 (soft-deleted) */
@Entity('iam_role')
export class Role extends BaseEntity {
  /** 角色名（种子为 seed.* 键） */
  @Column({ length: 64 })
  name: string

  /** 角色编码（root 为超级管理员） */
  @Column({ length: 64 })
  code: string

  /** 排序号 */
  @Column({ name: 'sort_no', type: 'int', default: 0 })
  sortNo: number

  /** 数据范围（字典 iam.data_scope） */
  @Column({ name: 'data_scope', length: 24 })
  dataScope: string

  /** 菜单授权树父子联动 */
  @Column({ name: 'menu_link', type: 'boolean', default: true })
  menuLink: boolean

  /** 部门授权树父子联动 */
  @Column({ name: 'dept_link', type: 'boolean', default: true })
  deptLink: boolean

  /** 是否内置 */
  @Column({ name: 'is_builtin', type: 'boolean', default: false })
  isBuiltin: boolean

  /** 是否启用 */
  @Column({ type: 'boolean', default: true })
  enabled: boolean

  /** 备注 */
  @Column({ type: 'varchar', length: 500, nullable: true })
  note: string | null
}
