// @generated by qw-codegen (crud)
// Mail template menus: the page under the `messaging` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (messaging.mail-template.json), the actions' in menu.json (menu.action.*).
import { mailTemplatePerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [mailTemplatePerms.browse, 'menu.action.browse'],
  [mailTemplatePerms.view, 'menu.action.view'],
  [mailTemplatePerms.create, 'menu.action.create'],
  [mailTemplatePerms.modify, 'menu.action.modify'],
  [mailTemplatePerms.remove, 'menu.action.remove'],
]

export async function seedMailTemplate(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'messaging' })
  if (parentId === undefined)
    throw new Error('seedMailTemplate: the messaging menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'messaging-mail-template' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.messaging.mailTemplate',
      route_path: '/messaging/mail-templates',
      component: 'platform/messaging/mail-template/index',
      component_name: 'MessagingMailTemplate',
      keep_alive: 1,
      icon: 'lucide:mail',
      sort_no: 50,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
