<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { mailAccountCreate } from '@qiwu/shared'
import { mailAccountApi } from '@/api/platform/messaging/mail-account'
import DictSelect from '@/core/components/DictSelect.vue'
import { useCrudForm } from '@/core/composables/use-crud'

/** Add / edit form of the mail account list, opened with `openDialog(MailAccountForm, { id })`. */
defineOptions({ name: 'MessagingMailAccountForm' })
const { id } = defineProps<{ id?: number }>()
const emit = defineEmits<{ done: [saved: { id: number }]; cancel: [] }>()
const { t } = useI18n()
const { model, formRef, rules, loading, submitting, submit } = useCrudForm({
  api: mailAccountApi,
  schema: mailAccountCreate,
  emptyModel: () => ({
    name: '',
    address: '',
    username: '',
    password: '',
    host: '',
    port: null,
    security: 'starttls' as const,
    enabled: true,
  }),
  id,
  emit,
})
</script>

<template>
  <el-form ref="formRef" v-loading="loading" :model="model" :rules="rules" label-position="left">
    <el-form-item :label="t('field.messaging.mailAccount.name')" prop="name">
      <el-input v-model="model.name" maxlength="64" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.mailAccount.address')" prop="address">
      <el-input v-model="model.address" maxlength="128" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.mailAccount.username')" prop="username">
      <el-input v-model="model.username" maxlength="128" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.mailAccount.password')" prop="password">
      <el-input
        v-model="model.password"
        type="password"
        show-password
        autocomplete="new-password"
        maxlength="117"
        :placeholder="id == null ? '' : t('crud.placeholder.secretKeep')"
      />
    </el-form-item>
    <el-form-item :label="t('field.messaging.mailAccount.host')" prop="host">
      <el-input v-model="model.host" maxlength="255" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.mailAccount.port')" prop="port">
      <el-input-number v-model="model.port" :min="1" :max="65535" controls-position="right" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.mailAccount.security')" prop="security">
      <DictSelect v-model="model.security" code="messaging.mail_security" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.mailAccount.enabled')" prop="enabled">
      <el-switch v-model="model.enabled" />
    </el-form-item>
  </el-form>
  <div class="qw-dialog-footer">
    <el-button @click="emit('cancel')">{{ t('common.action.cancel') }}</el-button>
    <el-button type="primary" :loading="submitting" @click="submit">
      {{ t('crud.action.save') }}
    </el-button>
  </div>
</template>
