<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import { ElMessage } from 'element-plus'
import { mailAccountPerms, type MailAccountVo } from '@qiwu/shared'
import { mailAccountApi } from '@/api/platform/messaging/mail-account'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { toastRest, useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { openDialog } from '@/core/dialog'
import { Icon } from '@/core/icons'
import { usePerm } from '@/core/permission'
import MailAccountForm from './form.vue'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'MessagingMailAccount' })

const { t } = useI18n()
const {
  query,
  rows,
  total,
  loading,
  filtered,
  selection,
  search,
  reset,
  refresh,
  onSelectionChange,
  onSortChange,
  remove,
  batchRemove,
} = useCrudList({
  api: mailAccountApi,
  filters: {
    name: '',
    address: '',
    security: null as string | null,
    enabled: null as string | null,
  },
  sort: '-createdAt',
})
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `messaging.mailAccount`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  {
    prop: 'name',
    label: 'field.messaging.mailAccount.name',
    sortable: true,
    minWidth: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'address',
    label: 'field.messaging.mailAccount.address',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'username',
    label: 'field.messaging.mailAccount.username',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'host',
    label: 'field.messaging.mailAccount.host',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'port',
    label: 'field.messaging.mailAccount.port',
    sortable: true,
    width: 120,
    align: 'right',
  },
  {
    prop: 'security',
    label: 'field.messaging.mailAccount.security',
    sortable: true,
    width: 180,
    showOverflowTooltip: true,
  },
  { prop: 'enabled', label: 'field.messaging.mailAccount.enabled', width: 100 },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
]
// computed: the perms reload when the server's permission version moves
const perm = usePerm()
const canModify = computed(() => perm.has(mailAccountPerms.modify))
// the edit form loads GET /:id, which needs `view` too
const canEdit = computed(() => perm.all([mailAccountPerms.modify, mailAccountPerms.view]))

/** Add (no id) or edit in the form dialog; reload once saved. */
async function openForm(id?: number) {
  const name = () => t('messaging.mailAccount.entity')
  const saved = await openDialog(
    MailAccountForm,
    { id },
    { title: () => t(id ? 'crud.title.edit' : 'crud.title.create', { name: name() }) },
  )
  if (saved) await refresh()
}

async function setEnabled(row: MailAccountVo, enabled: boolean) {
  // failures are toasted by the request layer; the reload shows the stored state either way
  await mailAccountApi.setEnabled(row.id, enabled).catch(() => undefined)
  await refresh()
}

const testing = reactive(new Set<number>())
async function testConnection(id: number) {
  testing.add(id)
  try {
    const result = await mailAccountApi.test(id)
    ElMessage[result.ok ? 'success' : 'error'](
      t(result.ok ? 'messaging.mailAccount.testOk' : 'messaging.mailAccount.testFailed'),
    )
  } catch (e) {
    toastRest(e)
  } finally {
    testing.delete(id)
  }
}
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.messaging.mailAccount.name')">
          <el-input v-model="query.name" name="name" clearable />
        </el-form-item>
        <el-form-item :label="t('field.messaging.mailAccount.address')">
          <el-input v-model="query.address" name="address" clearable />
        </el-form-item>
        <el-form-item :label="t('field.messaging.mailAccount.security')">
          <DictSelect v-model="query.security" code="messaging.mail_security" />
        </el-form-item>
        <el-form-item :label="t('field.messaging.mailAccount.enabled')">
          <DictSelect v-model="query.enabled" code="core.enabled" />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="messaging.mailAccount"
        :columns="columns"
        @refresh="refresh"
      >
        <el-button v-perm="mailAccountPerms.create" type="primary" @click="openForm()">
          <el-icon class="el-icon--left"><Icon icon="lucide:plus" /></el-icon>
          {{ t('crud.action.create') }}
        </el-button>
        <el-button
          v-if="selection.length"
          v-perm="mailAccountPerms.remove"
          type="danger"
          plain
          @click="batchRemove"
        >
          {{ t('crud.action.batchDelete') }}
        </el-button>
      </TableToolbar>

      <QwTable
        table-id="messaging.mailAccount"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        selection
        @selection-change="onSelectionChange"
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <template #cell-security="{ row }">
          <DictTag code="messaging.mail_security" :value="row.security" />
        </template>
        <template #cell-enabled="{ row }">
          <el-switch
            v-if="canModify"
            size="small"
            :model-value="row.enabled"
            :aria-label="`${t('field.messaging.mailAccount.enabled')} ${row.name}`"
            @change="setEnabled(row, $event as boolean)"
          />
          <DictTag v-else code="core.enabled" :value="row.enabled" />
        </template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #actions="{ row }">
          <el-button
            v-if="canModify"
            link
            type="primary"
            :loading="testing.has(row.id)"
            :disabled="testing.has(row.id)"
            @click="testConnection(row.id)"
          >
            <el-icon class="el-icon--left"><Icon icon="lucide:plug-zap" /></el-icon>
            {{ t('messaging.mailAccount.testConnection') }}
          </el-button>
          <el-button v-if="canEdit" link type="primary" @click="openForm(row.id)">
            {{ t('crud.action.edit') }}
          </el-button>
          <el-button v-perm="mailAccountPerms.remove" link type="danger" @click="remove([row.id])">
            {{ t('crud.action.delete') }}
          </el-button>
        </template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>
  </div>
</template>
