// @generated by qw-codegen (crud)
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  ParseIntPipe,
  Post,
  Put,
  Query,
} from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import {
  type EnabledBody,
  enabledBody,
  type IdsBody,
  idsBody,
  pageVo,
  type WfFormCreate,
  wfFormCreate,
  wfFormDetailVo,
  type WfFormQuery,
  wfFormQuery,
  type WfFormUpdate,
  wfFormUpdate,
  wfFormVo,
  wfPerms,
} from '@qiwu/shared'
import { ActionLog } from '../../../core/audit/action-log.js'
import { RequirePerm } from '../../../core/auth/decorators.js'
import { Idempotent } from '../../../core/guard/idempotent.js'
import { ApiEnvelope } from '../../../core/http/api-envelope.decorator.js'
import type { WfForm } from './wf-form.entity.js'
import { WfFormService } from './wf-form.service.js'

const perms = wfPerms.form

/**
 * Process forms (see docs/design-notes.md#workflow): form-create schemas that dynamic models bind. `wfPerms.form`, seeded to
 * root only; a schema is code, so create / modify are admin-level and the body is sanitized on save.
 */
@ApiTags('wf')
@Controller('wf/forms')
export class WfFormController {
  constructor(private readonly forms: WfFormService) {}

  @Get()
  @RequirePerm(perms.browse)
  @ApiOperation({ summary: 'Page of forms (without schemas)' })
  @ApiEnvelope(pageVo(wfFormVo))
  page(@Query({ schema: wfFormQuery }) query: WfFormQuery) {
    return this.forms.list(query)
  }

  @Get(':id')
  @RequirePerm(perms.view)
  @ApiOperation({ summary: 'One form with its schema' })
  @ApiEnvelope(wfFormDetailVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.forms.get(id)
  }

  @Post()
  @RequirePerm(perms.create)
  @Idempotent()
  @ActionLog({
    domain: 'wf.form',
    verb: 'create',
    bizId: (_req, row) => (row as WfForm | undefined)?.id,
  })
  @ApiOperation({ summary: 'Add a form (its schema sanitized: code or unknown components → 400)' })
  @ApiEnvelope(wfFormDetailVo, 201)
  create(@Body({ schema: wfFormCreate }) dto: WfFormCreate) {
    return this.forms.create(dto)
  }

  @Put(':id')
  @RequirePerm(perms.modify)
  @ActionLog({ domain: 'wf.form', verb: 'modify' })
  @ApiOperation({ summary: 'Change a form (a schema sent is sanitized like on create)' })
  @ApiEnvelope()
  update(@Param('id', ParseIntPipe) id: number, @Body({ schema: wfFormUpdate }) dto: WfFormUpdate) {
    return this.forms.update(id, dto)
  }

  @Put(':id/enabled')
  @RequirePerm(perms.modify)
  @ActionLog({ domain: 'wf.form', verb: 'modify' })
  @ApiOperation({ summary: 'Enable or disable a form' })
  @ApiEnvelope()
  setEnabled(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: enabledBody }) dto: EnabledBody,
  ) {
    return this.forms.update(id, dto)
  }

  @Delete(':id')
  @RequirePerm(perms.remove)
  @ActionLog({ domain: 'wf.form', verb: 'remove' })
  @ApiOperation({ summary: 'Delete a form no model binds' })
  @ApiEnvelope()
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.forms.remove([id])
  }

  @Post('batch-delete')
  @HttpCode(200)
  @RequirePerm(perms.remove)
  @ActionLog({ domain: 'wf.form', verb: 'remove' })
  @ApiOperation({ summary: 'Delete forms: all or none' })
  @ApiEnvelope()
  batchRemove(@Body({ schema: idsBody }) { ids }: IdsBody) {
    return this.forms.remove(ids)
  }
}
