// @generated by qw-codegen (crud)
import type { FormSchema } from '@qiwu/shared'
import { Column, Entity } from 'typeorm'
import { BaseEntity } from '../../../core/db/base.entity.js'
import { referencedBy } from '../../../core/db/references.js'

// other tables' rows holding these ids, checked on delete (no foreign keys: core/db/references.ts)
// process model
referencedBy('wf_form', { table: 'wf_model', column: 'form_id' })

/** `wf_form`: 流程表单 */
@Entity('wf_form')
export class WfForm extends BaseEntity {
  /** 表单名称（种子为 seed.wf.* 键） */
  @Column({ length: 128 })
  name: string

  /** 表单结构（form-create rule + option，保存时已过滤） */
  @Column({ name: 'schema_json', type: 'json' })
  schemaJson: FormSchema

  /** 是否启用 */
  @Column({ type: 'boolean', default: true })
  enabled: boolean

  /** 备注 */
  @Column({ type: 'varchar', length: 500, nullable: true })
  note: string | null
}
