// @generated by qw-codegen (crud)
import { Injectable } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { Page, WfFormQuery } from '@qiwu/shared'
import type { SelectQueryBuilder } from 'typeorm'
import { BaseCrudService } from '../../../core/db/base-crud.service.js'
import { contains, paginate } from '../../../core/db/page.js'
import { seedKeysLike } from '../../../core/i18n/seed-names.js'
import { WfForm } from './wf-form.entity.js'

/**
 * Forms over BaseCrudService (not data-scoped: `wfPerms` guard the admin pages). Uniqueness is the DB's
 * (`unique(name, alive)`, errno 1062 → 409 `duplicate`); remove is the base soft delete, which checks
 * the references the entity registers (a model's `form_id`: 409 `in_use`). The schema reaches
 * create/update already sanitized (the body schema's `wfFormSchemaJson`).
 */
@Injectable()
export class WfFormService extends BaseCrudService<WfForm> {
  constructor(txHost: TransactionHost<TransactionalAdapterTypeOrm>) {
    super(txHost, WfForm)
  }

  protected override filter(
    qb: SelectQueryBuilder<WfForm>,
    { name, enabled, createdAtFrom, createdAtTo }: WfFormQuery,
  ): SelectQueryBuilder<WfForm> {
    if (name) {
      // seeded names are keys (seed.wf.*): also match the text users see, in any language
      const seeded = seedKeysLike('seed.wf.', name)
      qb.andWhere(
        seeded.length ? '(t.name LIKE :name OR t.name IN (:...seeded))' : 't.name LIKE :name',
        { name: contains(name), seeded },
      )
    }
    if (enabled !== undefined) qb.andWhere('t.enabled = :enabled', { enabled })
    if (createdAtFrom)
      qb.andWhere('t.created_at >= :createdAtFrom', { createdAtFrom: new Date(createdAtFrom) })
    if (createdAtTo)
      qb.andWhere('t.created_at <= :createdAtTo', { createdAtTo: new Date(createdAtTo) })
    return qb
  }

  /** A page of forms without their schemas (those come with the detail only). */
  list(query: WfFormQuery): Promise<Page<WfForm>> {
    const columns = this.repo.metadata.columns
      .filter((c) => c.propertyName !== 'schemaJson')
      .map((c) => `t.${c.propertyName}`)
    return paginate(this.filter(this.scopedQb('t').select(columns), query), query)
  }
}
