// @generated by qw-codegen (crud)
import type { I18nText } from '@qiwu/shared'
import { Column, Entity } from 'typeorm'
import { BaseEntity } from '../../../../core/db/base.entity.js'

/** `cfg_dict_entry`: 字典项 */
@Entity('cfg_dict_entry')
export class DictEntry extends BaseEntity {
  /** 字典编码 */
  @Column({ name: 'dict_code', length: 100 })
  dictCode: string

  /** 字典值 */
  @Column({ length: 100 })
  value: string

  /** 标签（无对应语言时显示） */
  @Column({ length: 100 })
  label: string

  /** 多语言标签 */
  @Column({ name: 'label_i18n', type: 'json', nullable: true })
  labelI18n: I18nText | null

  /** 排序号 */
  @Column({ name: 'sort_no', type: 'int', default: 0 })
  sortNo: number

  /** 标签样式（primary/success/info/warning/danger） */
  @Column({ name: 'tag_type', type: 'varchar', length: 12, nullable: true })
  tagType: string | null

  /** 样式类名 */
  @Column({ name: 'css_class', type: 'varchar', length: 100, nullable: true })
  cssClass: string | null

  /** 是否默认值 */
  @Column({ name: 'is_default', type: 'boolean', default: false })
  isDefault: boolean

  /** 是否启用 */
  @Column({ type: 'boolean', default: true })
  enabled: boolean

  /** 备注 */
  @Column({ type: 'varchar', length: 500, nullable: true })
  note: string | null
}
