// @generated by qw-codegen (crud)
// Dict entry menus: a hidden page (`visible = 0`; see docs/design-notes.md#layering) under the dict page (found by
// route_name, never by id; the dict list opens it for one dict, `/settings/dicts/:code/entries`) and one
// action row per permission below it, so granting an entry action also delivers the route. Upserted by
// route_name / perms. Names are i18n keys: the page's in the module's web locale fragment
// (settings.dict-entry.json), the actions' in menu.json (menu.action.*).
import { dictEntryPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [dictEntryPerms.browse, 'menu.action.browse'],
  [dictEntryPerms.view, 'menu.action.view'],
  [dictEntryPerms.create, 'menu.action.create'],
  [dictEntryPerms.modify, 'menu.action.modify'],
  [dictEntryPerms.remove, 'menu.action.remove'],
  [dictEntryPerms.export, 'menu.action.export'],
]

export async function seedDictEntry(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'settings-dict' })
  if (parentId === undefined) throw new Error('seedDictEntry: the dict page menu is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'settings-dict-entry' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.settings.dictEntry',
      route_path: '/settings/dicts/:code/entries',
      component: 'platform/settings/dict-entry/index',
      component_name: 'SettingsDictEntry',
      visible: 0,
      keep_alive: 0,
      icon: 'lucide:list',
      // after the dict page's actions
      sort_no: 100,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
