// @generated by qw-codegen (crud)
import { Injectable, NotFoundException } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { DictEntryQuery } from '@qiwu/shared'
import { type DeepPartial, In, type QueryDeepPartialEntity, type SelectQueryBuilder } from 'typeorm'
import { BaseCrudService } from '../../../../core/db/base-crud.service.js'
import type { ExcelColumn } from '../../../../core/excel/excel.service.js'
import { DictService as DictCache } from '../../../../core/settings/dict.service.js'
import { DictEntry } from './dict-entry.entity.js'

/** Excel columns in list order (headers: the field labels; dict columns as their labels). */
export const dictEntryColumns: ExcelColumn[] = [
  { prop: 'value', label: 'field.settings.dictEntry.value' },
  { prop: 'label', label: 'field.settings.dictEntry.label' },
  { prop: 'sortNo', label: 'field.settings.dictEntry.sortNo', type: 'number' },
  { prop: 'tagType', label: 'field.settings.dictEntry.tagType', dict: 'settings.tag_type' },
  {
    prop: 'isDefault',
    label: 'field.settings.dictEntry.isDefault',
    type: 'boolean',
    dict: 'core.yes_no',
  },
  {
    prop: 'enabled',
    label: 'field.settings.dictEntry.enabled',
    type: 'boolean',
    dict: 'core.enabled',
  },
  { prop: 'note', label: 'field.settings.dictEntry.note', width: 40 },
]

/**
 * Dict entries over BaseCrudService. A value is unique within its dict (DB index, errno 1062 → 409
 * `duplicate`). Hand-written on top: a new entry's dict must exist (404), read FOR SHARE so a delete
 * of that dict waits and then sees the entry (409 `in_use`, DictService); the dict stays (the update
 * schema lacks it); after every write commits, the dicts it touched drop their cached entries and move
 * their versions (core/settings DictService, the read side every page uses).
 */
@Injectable()
export class DictEntryService extends BaseCrudService<DictEntry> {
  constructor(
    txHost: TransactionHost<TransactionalAdapterTypeOrm>,
    private readonly cache: DictCache,
  ) {
    super(txHost, DictEntry)
  }

  protected override filter(
    qb: SelectQueryBuilder<DictEntry>,
    { dictCode, enabled }: DictEntryQuery,
  ): SelectQueryBuilder<DictEntry> {
    if (dictCode) qb.andWhere('t.dict_code = :dictCode', { dictCode })
    if (enabled !== undefined) qb.andWhere('t.enabled = :enabled', { enabled })
    return qb
  }

  override async create(dto: DeepPartial<DictEntry>): Promise<DictEntry> {
    const row = await this.txHost.withTransaction(async () => {
      const [dict] = await this.txHost.tx.query<unknown[]>(
        'SELECT id FROM cfg_dict WHERE code = ? AND deleted_at IS NULL FOR SHARE',
        [dto.dictCode],
      )
      if (!dict) throw new NotFoundException()
      return super.create(dto)
    })
    await this.cache.invalidate(row.dictCode)
    return row
  }

  /** PUT /:id and /:id/enabled. */
  override async update(id: number, dto: QueryDeepPartialEntity<DictEntry>): Promise<void> {
    const code = await this.txHost.withTransaction(async () => {
      await super.update(id, dto)
      return (await this.repo.findOneByOrFail({ id })).dictCode
    })
    await this.cache.invalidate(code)
  }

  override async remove(ids: readonly number[]): Promise<void> {
    const codes = await this.txHost.withTransaction(async () => {
      await this.lockScopedIds(ids)
      const codes = (await this.repo.findBy({ id: In([...ids]) })).map((e) => e.dictCode)
      await super.remove(ids)
      return codes
    })
    await this.cache.invalidate(...codes)
  }
}
