// @generated by qw-codegen (crud)
import { Column, CreateDateColumn, Entity } from 'typeorm'
import { IdEntity } from '../../../../core/db/base.entity.js'

/**
 * `aud_signin_log`: 登录日志. Append-only (core/audit AuditWriter inserts it), so no audit columns but
 * `created_at` (not a BaseEntity); soft-deleted like every table (IdEntity).
 */
@Entity('aud_signin_log')
export class SigninLog extends IdEntity {
  /** 追踪 ID */
  @Column({ name: 'trace_id', type: 'varchar', length: 64, nullable: true })
  traceId: string | null

  /** 类型（password/sms/signout/kicked/refresh_reuse/locked） */
  @Column({ length: 16 })
  kind: string

  /** 用户 ID（用户名不存在时为空） */
  @Column({ name: 'user_id', type: 'bigint', unsigned: true, nullable: true })
  userId: number | null

  /** User type at the time of the event. */
  @Column({ name: 'user_type', type: 'varchar', length: 16, default: 'admin' })
  userType: string

  /** 登录名（按输入记录） */
  @Column({ length: 64 })
  username: string

  /** 客户端 ID */
  @Column({ name: 'client_id', length: 64 })
  clientId: string

  /** IP 地址 */
  @Column({ type: 'varchar', length: 64, nullable: true })
  ip: string | null

  /** 登录地点 */
  @Column({ type: 'varchar', length: 128, nullable: true })
  location: string | null

  /** 浏览器 */
  @Column({ type: 'varchar', length: 64, nullable: true })
  browser: string | null

  /** 操作系统 */
  @Column({ type: 'varchar', length: 64, nullable: true })
  os: string | null

  /** 是否成功 */
  @Column({ type: 'boolean' })
  ok: boolean

  /** 提示消息 i18n 键 */
  @Column({ name: 'msg_key', type: 'varchar', length: 128, nullable: true })
  msgKey: string | null

  /** 提示消息参数 */
  @Column({ name: 'msg_params', type: 'json', nullable: true })
  msgParams: unknown

  /** 发生时间（UTC） */
  @CreateDateColumn({ name: 'created_at', type: 'datetime', precision: 3 })
  createdAt: Date
}
