// @generated by qw-codegen (crud)
import { Injectable } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { Page, SigninLogQuery } from '@qiwu/shared'
import { I18nService } from 'nestjs-i18n'
import type { SelectQueryBuilder } from 'typeorm'
import { demoNetwork } from '../../../../core/audit/demo-network.js'
import { demoMode } from '../../../../core/config/demo-mode.js'
import { BaseCrudService } from '../../../../core/db/base-crud.service.js'
import { contains, type PageParams } from '../../../../core/db/page.js'
import type { ExcelColumn } from '../../../../core/excel/excel.service.js'
import { currentLocale } from '../../../../core/i18n/locale.js'
import { SigninLog } from './signin-log.entity.js'

/** A row with its message in the reader's language (stored as key + params; see docs/design-notes.md#i18n). */
export type SigninLogRow = SigninLog & { msg: string | null }

/** Excel columns in list order (headers: the field labels; dict columns as their labels). */
export const signinLogColumns: ExcelColumn[] = [
  { prop: 'kind', label: 'field.audit.signinLog.kind', dict: 'audit.signin_kind' },
  { prop: 'username', label: 'field.audit.signinLog.username' },
  { prop: 'userType', label: 'field.audit.signinLog.userType', dict: 'audit.user_type' },
  { prop: 'ip', label: 'field.audit.signinLog.ip' },
  { prop: 'browser', label: 'field.audit.signinLog.browser' },
  { prop: 'os', label: 'field.audit.signinLog.os' },
  { prop: 'ok', label: 'field.audit.signinLog.ok', type: 'boolean', dict: 'core.yes_no' },
  { prop: 'msg', label: 'field.audit.signinLog.msg' },
  { prop: 'createdAt', label: 'field.common.createdAt', type: 'datetime', only: 'export' },
]

/**
 * Sign-in logs over BaseCrudService: read (each row's message translated), export and delete (the base
 * `remove`, or `clean` everything). Rows are only ever inserted by core/auth (AuditWriter).
 */
@Injectable()
export class SigninLogService extends BaseCrudService<SigninLog> {
  constructor(
    txHost: TransactionHost<TransactionalAdapterTypeOrm>,
    private readonly i18n: I18nService,
  ) {
    super(txHost, SigninLog)
  }

  override async page<F extends string>(
    query: PageParams<F>,
    columns?: Partial<Record<F, string>>,
  ): Promise<Page<SigninLogRow>> {
    const { items, total } = await super.page(query, columns)
    return { items: items.map((r) => this.withMsg(r)), total }
  }

  override async get(id: number): Promise<SigninLogRow> {
    return this.withMsg(await super.get(id))
  }

  override async *exportRows<F extends string>(
    query: Pick<PageParams<F>, 'sort'>,
    columns?: Partial<Record<F, string>>,
  ): AsyncGenerator<SigninLogRow[]> {
    for await (const rows of super.exportRows(query, columns))
      yield rows.map((r) => this.withMsg(r))
  }

  /** Soft-deletes every live row (`audit.purge` drops them for good past `audit.retention_days`). */
  async clean(): Promise<void> {
    await this.repo.createQueryBuilder().softDelete().execute()
  }

  private withMsg(row: SigninLog): SigninLogRow {
    const args = (row.msgParams ?? undefined) as Record<string, unknown> | undefined
    const msg = row.msgKey && this.i18n.translate(row.msgKey, { lang: currentLocale(), args })
    return demoNetwork(Object.assign(row, { msg: msg ? String(msg) : null }))
  }

  protected override filter(
    qb: SelectQueryBuilder<SigninLog>,
    { kind, username, ip, ok, createdAtFrom, createdAtTo }: SigninLogQuery,
  ): SelectQueryBuilder<SigninLog> {
    if (kind) qb.andWhere('t.kind = :kind', { kind })
    if (username) qb.andWhere('t.username LIKE :username', { username: contains(username) })
    if (ip && !demoMode()) qb.andWhere('t.ip LIKE :ip', { ip: contains(ip) })
    if (ok !== undefined) qb.andWhere('t.ok = :ok', { ok })
    if (createdAtFrom)
      qb.andWhere('t.created_at >= :createdAtFrom', { createdAtFrom: new Date(createdAtFrom) })
    if (createdAtTo)
      qb.andWhere('t.created_at <= :createdAtTo', { createdAtTo: new Date(createdAtTo) })
    return qb
  }
}
