// @generated by qw-codegen (crud)
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { SigninLogController } from './signin-log.controller.js'
import { SigninLog } from './signin-log.entity.js'
import { SigninLogService } from './signin-log.service.js'

@Module({
  imports: [TypeOrmModule.forFeature([SigninLog])],
  controllers: [SigninLogController],
  providers: [SigninLogService],
})
export class SigninLogModule {}
