// @generated by qw-codegen (crud)
// Signin log menus: the page under the `audit` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (audit.signin-log.json), the actions' in menu.json (menu.action.*).
import { signinLogPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [signinLogPerms.browse, 'menu.action.browse'],
  [signinLogPerms.view, 'menu.action.view'],
  [signinLogPerms.export, 'menu.action.export'],
  [signinLogPerms.remove, 'menu.action.remove'],
  [signinLogPerms.unlock, 'menu.action.unlock'],
]

export async function seedSigninLog(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'audit' })
  if (parentId === undefined) throw new Error('seedSigninLog: the audit menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'audit-signin-log' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.audit.signinLog',
      route_path: '/audit/signin-logs',
      component: 'platform/audit/signin-log/index',
      component_name: 'AuditSigninLog',
      keep_alive: 1,
      icon: 'lucide:log-in',
      sort_no: 20,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
