// @generated by qw-codegen (crud)
import type { BulletinCreate, BulletinReceiptVo, BulletinVo, Page } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/messaging/bulletins'

/** /api/messaging/bulletins: the standard CRUD calls plus publishing and the read receipts. */
export const bulletinApi = {
  ...crudApi<BulletinVo, BulletinCreate>(BASE),
  publish: (id: number, published: boolean) => api.put(`${BASE}/${id}/published`, { published }),
  receipts: (id: number, params: object) =>
    api.get<Page<BulletinReceiptVo>>(`${BASE}/${id}/receipts`, { params }),
}
