// @generated by qw-codegen (crud)
import type { InboxVo } from '@qiwu/shared'
import { crudApi } from '@/core/request/http'

const BASE = '/messaging/inboxes'

/** /api/messaging/inboxes: the standard CRUD calls. */
export const inboxApi = {
  // read-only: the list, one row and the export
  ...crudApi<InboxVo>(BASE),
}
