// @generated by qw-codegen (crud)
import { Injectable } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { HttpTraceQuery, Page } from '@qiwu/shared'
import { I18nService } from 'nestjs-i18n'
import type { SelectQueryBuilder } from 'typeorm'
import { demoNetwork } from '../../../../core/audit/demo-network.js'
import { demoMode } from '../../../../core/config/demo-mode.js'
import { BaseCrudService } from '../../../../core/db/base-crud.service.js'
import { contains, type PageParams } from '../../../../core/db/page.js'
import type { ExcelColumn } from '../../../../core/excel/excel.service.js'
import { currentLocale } from '../../../../core/i18n/locale.js'
import { HttpTrace } from './http-trace.entity.js'

/** Excel columns in list order (headers: the field labels; dict columns as their labels). */
export const httpTraceColumns: ExcelColumn[] = [
  { prop: 'username', label: 'field.audit.httpTrace.username' },
  { prop: 'method', label: 'field.audit.httpTrace.method' },
  { prop: 'statusCode', label: 'field.audit.httpTrace.statusCode', type: 'number' },
  { prop: 'bizCode', label: 'field.audit.httpTrace.bizCode' },
  { prop: 'ip', label: 'field.audit.httpTrace.ip' },
  { prop: 'startedAt', label: 'field.audit.httpTrace.startedAt', type: 'datetime' },
  { prop: 'costMs', label: 'field.audit.httpTrace.costMs', type: 'number' },
  { prop: 'url', label: 'field.audit.httpTrace.url', width: 40 },
]

/**
 * Http traces over BaseCrudService. Read only here: rows are soft-deleted like every
 * table and dropped for good by `audit.purge` past `audit.retention_days`.
 */
@Injectable()
export class HttpTraceService extends BaseCrudService<HttpTrace> {
  constructor(
    txHost: TransactionHost<TransactionalAdapterTypeOrm>,
    private readonly i18n: I18nService,
  ) {
    super(txHost, HttpTrace)
  }

  override async page<F extends string>(
    query: PageParams<F>,
    columns?: Partial<Record<F, string>>,
  ): Promise<Page<HttpTrace>> {
    const { items, total } = await super.page(query, columns)
    return { items: items.map((r) => this.translated(r)), total }
  }

  override async get(id: number): Promise<HttpTrace> {
    return this.translated(await super.get(id))
  }

  override async *exportRows<F extends string>(
    query: Pick<PageParams<F>, 'sort'>,
    columns?: Partial<Record<F, string>>,
  ): AsyncGenerator<HttpTrace[]> {
    for await (const rows of super.exportRows(query, columns)) yield rows.map(demoNetwork)
  }

  /**
   * The stored error message is the error envelope's i18n key (core/audit): read in the reader's language
   * (see docs/design-notes.md#i18n). The error's params are not stored, so a placeholder (`{max}`) stays unfilled;
   * store them like the sign-in log's `msg_params` if one matters.
   */
  private translated(row: HttpTrace): HttpTrace {
    const key = row.msg
    if (key) row.msg = String(this.i18n.translate(key, { lang: currentLocale() }))
    return demoNetwork(row)
  }

  protected override filter(
    qb: SelectQueryBuilder<HttpTrace>,
    {
      url,
      traceId,
      username,
      method,
      statusCode,
      bizCode,
      ip,
      startedAtFrom,
      startedAtTo,
    }: HttpTraceQuery,
  ): SelectQueryBuilder<HttpTrace> {
    if (url) qb.andWhere('t.url LIKE :url', { url: contains(url) })
    if (traceId) qb.andWhere('t.trace_id = :traceId', { traceId })
    if (username) qb.andWhere('t.username LIKE :username', { username: contains(username) })
    if (method) qb.andWhere('t.method = :method', { method })
    if (statusCode !== undefined) qb.andWhere('t.status_code = :statusCode', { statusCode })
    if (bizCode) qb.andWhere('t.biz_code = :bizCode', { bizCode })
    if (ip && !demoMode()) qb.andWhere('t.ip LIKE :ip', { ip: contains(ip) })
    if (startedAtFrom)
      qb.andWhere('t.started_at >= :startedAtFrom', { startedAtFrom: new Date(startedAtFrom) })
    if (startedAtTo)
      qb.andWhere('t.started_at <= :startedAtTo', { startedAtTo: new Date(startedAtTo) })
    return qb
  }
}
