// @generated by qw-codegen (crud)
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { HttpTraceController } from './http-trace.controller.js'
import { HttpTrace } from './http-trace.entity.js'
import { HttpTraceService } from './http-trace.service.js'

@Module({
  imports: [TypeOrmModule.forFeature([HttpTrace])],
  controllers: [HttpTraceController],
  providers: [HttpTraceService],
})
export class HttpTraceModule {}
