<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { inboxTemplateCreate, type InboxTemplateVo } from '@qiwu/shared'
import { inboxTemplateApi } from '@/api/platform/messaging/inbox-template'
import DictSelect from '@/core/components/DictSelect.vue'
import { useCrudForm } from '@/core/composables/use-crud'
import { tx } from '@/core/i18n'

/** Add / edit form of the inbox template list, opened with `openDialog(InboxTemplateForm, { id })`. */
defineOptions({ name: 'MessagingInboxTemplateForm' })
const { id, source } = defineProps<{ id?: number; source?: InboxTemplateVo }>()
const emit = defineEmits<{ done: [saved: { id: number }]; cancel: [] }>()
const { t } = useI18n()
const { model, formRef, rules, loading, submitting, submit } = useCrudForm({
  api: inboxTemplateApi,
  schema: inboxTemplateCreate,
  emptyModel: () => ({
    code: source?.code ?? '',
    locale: (source?.locale === 'zh-CN' ? 'en-US' : 'zh-CN') as 'zh-CN' | 'en-US',
    name: source ? tx(source.name) : '',
    title: source?.title ?? '',
    body: source?.body ?? '',
    category: (source?.category === 'business' ? 'business' : 'system') as 'business' | 'system',
    senderLabel: source?.senderLabel ?? '',
    enabled: source?.enabled ?? true,
  }),
  id,
  emit,
})
</script>

<template>
  <el-form ref="formRef" v-loading="loading" :model="model" :rules="rules" label-position="left">
    <el-form-item :label="t('field.messaging.inboxTemplate.code')" prop="code">
      <el-input v-model="model.code" maxlength="100" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.inboxTemplate.locale')" prop="locale">
      <DictSelect v-model="model.locale" code="core.locale" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.inboxTemplate.name')" prop="name">
      <el-input v-model="model.name" maxlength="100" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.inboxTemplate.title')" prop="title">
      <el-input v-model="model.title" maxlength="200" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.inboxTemplate.body')" prop="body">
      <el-input v-model="model.body" type="textarea" :rows="3" maxlength="16383" show-word-limit />
    </el-form-item>
    <el-form-item :label="t('field.messaging.inboxTemplate.category')" prop="category">
      <DictSelect v-model="model.category" code="messaging.inbox_category" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.inboxTemplate.senderLabel')" prop="senderLabel">
      <el-input v-model="model.senderLabel" maxlength="64" />
    </el-form-item>
    <el-form-item :label="t('field.messaging.inboxTemplate.enabled')" prop="enabled">
      <el-switch v-model="model.enabled" />
    </el-form-item>
  </el-form>
  <div class="qw-dialog-footer">
    <el-button @click="emit('cancel')">{{ t('common.action.cancel') }}</el-button>
    <el-button type="primary" :loading="submitting" @click="submit">
      {{ t('crud.action.save') }}
    </el-button>
  </div>
</template>
