<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import { inboxTemplatePerms, type InboxTemplateVo } from '@qiwu/shared'
import { inboxTemplateApi } from '@/api/platform/messaging/inbox-template'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { openDialog } from '@/core/dialog'
import { tx } from '@/core/i18n'
import { Icon } from '@/core/icons'
import { usePerm } from '@/core/permission'
import InboxTemplateForm from './form.vue'
import InboxTemplateTest from './test.vue'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'MessagingInboxTemplate' })

const { t } = useI18n()
const {
  query,
  rows,
  total,
  loading,
  filtered,
  selection,
  search,
  reset,
  refresh,
  onSelectionChange,
  onSortChange,
  remove,
  batchRemove,
} = useCrudList({
  api: inboxTemplateApi,
  filters: {
    code: '',
    locale: null as string | null,
    name: '',
    category: null as string | null,
    enabled: null as string | null,
  },
  sort: 'code,locale',
})
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `messaging.inboxTemplate`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  {
    prop: 'code',
    label: 'field.messaging.inboxTemplate.code',
    sortable: true,
    width: 140,
    showOverflowTooltip: true,
  },
  {
    prop: 'locale',
    label: 'field.messaging.inboxTemplate.locale',
    sortable: true,
    width: 120,
    showOverflowTooltip: true,
  },
  {
    prop: 'name',
    label: 'field.messaging.inboxTemplate.name',
    sortable: true,
    minWidth: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'title',
    label: 'field.messaging.inboxTemplate.title',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'category',
    label: 'field.messaging.inboxTemplate.category',
    sortable: true,
    width: 120,
    showOverflowTooltip: true,
  },
  { prop: 'enabled', label: 'field.messaging.inboxTemplate.enabled', width: 100 },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
]
// computed: the perms reload when the server's permission version moves
const perm = usePerm()
const canModify = computed(() => perm.has(inboxTemplatePerms.modify))
const canCreate = computed(() => perm.has(inboxTemplatePerms.create))
// the edit form loads GET /:id, which needs `view` too
const canEdit = computed(() => perm.all([inboxTemplatePerms.modify, inboxTemplatePerms.view]))

/** Add (no id) or edit in the form dialog; reload once saved. */
async function openForm(id?: number, source?: InboxTemplateVo) {
  const name = () => t('messaging.inboxTemplate.entity')
  const saved = await openDialog(
    InboxTemplateForm,
    { id, source },
    { title: () => t(id ? 'crud.title.edit' : 'crud.title.create', { name: name() }) },
  )
  if (saved) await refresh()
}

function testSend(row: InboxTemplateVo) {
  return openDialog(
    InboxTemplateTest,
    { row },
    { title: () => t('messaging.inboxTemplate.testSend') },
  )
}

async function setEnabled(row: InboxTemplateVo, enabled: boolean) {
  // failures are toasted by the request layer; the reload shows the stored state either way
  await inboxTemplateApi.setEnabled(row.id, enabled).catch(() => undefined)
  await refresh()
}
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.messaging.inboxTemplate.code')">
          <el-input v-model="query.code" name="code" clearable />
        </el-form-item>
        <el-form-item :label="t('field.messaging.inboxTemplate.locale')">
          <DictSelect v-model="query.locale" code="core.locale" />
        </el-form-item>
        <el-form-item :label="t('field.messaging.inboxTemplate.name')">
          <el-input v-model="query.name" name="name" clearable />
        </el-form-item>
        <el-form-item :label="t('field.messaging.inboxTemplate.category')">
          <DictSelect v-model="query.category" code="messaging.inbox_category" />
        </el-form-item>
        <el-form-item :label="t('field.messaging.inboxTemplate.enabled')">
          <DictSelect v-model="query.enabled" code="core.enabled" />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="messaging.inboxTemplate"
        :columns="columns"
        @refresh="refresh"
      >
        <el-button v-perm="inboxTemplatePerms.create" type="primary" @click="openForm()">
          <el-icon class="el-icon--left"><Icon icon="lucide:plus" /></el-icon>
          {{ t('crud.action.create') }}
        </el-button>
        <el-button
          v-if="selection.length"
          v-perm="inboxTemplatePerms.remove"
          type="danger"
          plain
          @click="batchRemove"
        >
          {{ t('crud.action.batchDelete') }}
        </el-button>
      </TableToolbar>

      <QwTable
        table-id="messaging.inboxTemplate"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        selection
        @selection-change="onSelectionChange"
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <template #cell-locale="{ row }">
          <DictTag code="core.locale" :value="row.locale" />
        </template>
        <!-- seeded names are i18n keys (seed.inboxTemplate.*) -->
        <template #cell-name="{ row }">{{ tx(row.name) }}</template>
        <template #cell-category="{ row }">
          <DictTag code="messaging.inbox_category" :value="row.category" />
        </template>
        <template #cell-enabled="{ row }">
          <el-switch
            v-if="canModify"
            size="small"
            :model-value="row.enabled"
            :aria-label="`${t('field.messaging.inboxTemplate.enabled')} ${tx(row.name)}`"
            @change="setEnabled(row, $event as boolean)"
          />
          <DictTag v-else code="core.enabled" :value="row.enabled" />
        </template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #actions="{ row }">
          <el-button v-if="canEdit" link type="primary" @click="openForm(row.id)">
            {{ t('crud.action.edit') }}
          </el-button>
          <el-button
            v-perm="inboxTemplatePerms.remove"
            link
            type="danger"
            @click="remove([row.id])"
          >
            {{ t('crud.action.delete') }}
          </el-button>
          <el-dropdown
            v-if="canCreate || canModify"
            trigger="click"
            @command="(c: string) => (c === 'translate' ? openForm(undefined, row) : testSend(row))"
          >
            <el-button link type="primary">
              {{ t('crud.action.more') }}
              <el-icon class="el-icon--right"><Icon icon="lucide:chevron-down" /></el-icon>
            </el-button>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item v-if="canCreate" command="translate">
                  <el-icon><Icon icon="lucide:languages" /></el-icon>
                  {{ t('messaging.inboxTemplate.addTranslation') }}
                </el-dropdown-item>
                <el-dropdown-item v-if="canModify" command="test">
                  <el-icon><Icon icon="lucide:send" /></el-icon>
                  {{ t('messaging.inboxTemplate.testSend') }}
                </el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>
  </div>
</template>
