// @generated by qw-codegen (crud)
import { z } from 'zod'
import { pageQuery } from '../../common/pagination.js'
import { fieldDomains } from '../../validation/zod-i18n.js'

/**
 * Http traces (`aud_http_trace`), `/api/audit/http-traces` (see docs/design-notes.md#api-envelope). Field labels
 * `field.audit.httpTrace.<prop>`. `msg` stores the error envelope's message key; the server translates
 * it into the reader's language on read (see docs/design-notes.md#i18n).
 */

export const httpTracePerms = {
  browse: 'audit.httpTrace.browse',
  view: 'audit.httpTrace.view',
  export: 'audit.httpTrace.export',
} as const

/** GET query: paging, sort and the list filters (text contains, ranges from / to, the rest equals). */
export const httpTraceQuery = pageQuery(['statusCode', 'startedAt', 'costMs', 'id'])
  .extend({
    url: z.string().trim().max(512).optional(),
    traceId: z.string().trim().max(64).optional(),
    username: z.string().trim().max(64).optional(),
    method: z.string().trim().max(10).optional(),
    statusCode: z.coerce.number().int().optional(),
    bizCode: z.string().trim().max(16).optional(),
    ip: z.string().trim().max(64).optional(),
    startedAtFrom: z.iso.datetime({ offset: true }).optional(),
    startedAtTo: z.iso.datetime({ offset: true }).optional(),
  })
  .register(fieldDomains, { domain: 'audit.httpTrace' })
export type HttpTraceQuery = z.output<typeof httpTraceQuery>

export const httpTraceVo = z.object({
  id: z.number().int(),
  url: z.string(),
  traceId: z.string().nullable(),
  userId: z.number().int().nullable(),
  username: z.string().nullable(),
  userType: z.string().nullable(),
  clientId: z.string().nullable(),
  method: z.string(),
  query: z.string().nullable(),
  body: z.string().nullable(),
  statusCode: z.number().int(),
  bizCode: z.string(),
  msg: z.string().nullable(),
  ip: z.string().nullable(),
  userAgent: z.string().nullable(),
  startedAt: z.iso.datetime(),
  costMs: z.number().int(),
})
export type HttpTraceVo = z.infer<typeof httpTraceVo>
