<!-- @generated by qw-codegen (master_sub) -->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import { invoicePerms } from '@qiwu/shared'
import { invoiceApi } from '@/api/demo/invoice'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { useDateRangeShortcuts } from '@/core/date-shortcuts'
import { openDialog } from '@/core/dialog'
import { Icon } from '@/core/icons'
import { usePerm } from '@/core/permission'
import InvoiceForm from './form.vue'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'DemoInvoice' })

const { t } = useI18n()
const dateRangeShortcuts = useDateRangeShortcuts()
const {
  query,
  rows,
  total,
  loading,
  filtered,
  selection,
  search,
  reset,
  refresh,
  onSelectionChange,
  onSortChange,
  remove,
  batchRemove,
} = useCrudList({
  api: invoiceApi,
  filters: {
    invoiceNo: '',
    buyer: '',
    issuedAtRange: null as [string, string] | null,
    state: null as string | null,
    createdAtRange: null as [string, string] | null,
  },
  sort: '-createdAt',
})
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `demo.invoice`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  {
    prop: 'invoiceNo',
    label: 'field.demo.invoice.invoiceNo',
    sortable: true,
    minWidth: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'buyer',
    label: 'field.demo.invoice.buyer',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  { prop: 'total', label: 'field.demo.invoice.total', sortable: true, width: 120, align: 'right' },
  { prop: 'issuedAt', label: 'field.demo.invoice.issuedAt', sortable: true, width: 160 },
  {
    prop: 'state',
    label: 'field.demo.invoice.state',
    sortable: true,
    width: 120,
    showOverflowTooltip: true,
  },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
]
// computed: the perms reload when the server's permission version moves
const perm = usePerm()
// the edit form loads GET /:id, which needs `view` too
const canEdit = computed(() => perm.all([invoicePerms.modify, invoicePerms.view]))

/** Add (no id) or edit in the form dialog; reload once saved. */
async function openForm(id?: number) {
  const name = () => t('demo.invoice.entity')
  const saved = await openDialog(
    InvoiceForm,
    { id },
    // wide: the form edits its lines in a table
    {
      title: () => t(id ? 'crud.title.edit' : 'crud.title.create', { name: name() }),
      width: '880px',
    },
  )
  if (saved) await refresh()
}
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.demo.invoice.invoiceNo')">
          <el-input v-model="query.invoiceNo" name="invoiceNo" clearable />
        </el-form-item>
        <el-form-item :label="t('field.demo.invoice.buyer')">
          <el-input v-model="query.buyer" name="buyer" clearable />
        </el-form-item>
        <el-form-item :label="t('field.demo.invoice.issuedAt')" class="qw-search-wide">
          <el-date-picker
            v-model="query.issuedAtRange"
            type="daterange"
            :shortcuts="dateRangeShortcuts"
            value-format="YYYY-MM-DD"
            :start-placeholder="t('field.demo.invoice.issuedAtFrom')"
            :end-placeholder="t('field.demo.invoice.issuedAtTo')"
          />
        </el-form-item>
        <el-form-item :label="t('field.demo.invoice.state')">
          <DictSelect v-model="query.state" code="demo.invoice_state" />
        </el-form-item>
        <el-form-item :label="t('field.common.createdAt')" class="qw-search-wide">
          <el-date-picker
            v-model="query.createdAtRange"
            type="daterange"
            :shortcuts="dateRangeShortcuts"
            value-format="YYYY-MM-DD"
            :start-placeholder="t('field.common.createdAtFrom')"
            :end-placeholder="t('field.common.createdAtTo')"
          />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="demo.invoice"
        :columns="columns"
        @refresh="refresh"
      >
        <el-button v-perm="invoicePerms.create" type="primary" @click="openForm()">
          <el-icon class="el-icon--left"><Icon icon="lucide:plus" /></el-icon>
          {{ t('crud.action.create') }}
        </el-button>
        <el-button
          v-if="selection.length"
          v-perm="invoicePerms.remove"
          type="danger"
          plain
          @click="batchRemove"
        >
          {{ t('crud.action.batchDelete') }}
        </el-button>
      </TableToolbar>

      <QwTable
        table-id="demo.invoice"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        selection
        @selection-change="onSelectionChange"
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <template #cell-total="{ row }">{{ row.total.toFixed(2) }}</template>
        <template #cell-issuedAt="{ row }">{{
          row.issuedAt ? dayjs(row.issuedAt).format('YYYY-MM-DD HH:mm') : ''
        }}</template>
        <template #cell-state="{ row }">
          <DictTag code="demo.invoice_state" :value="row.state" />
        </template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #actions="{ row }">
          <el-button v-if="canEdit" link type="primary" @click="openForm(row.id)">
            {{ t('crud.action.edit') }}
          </el-button>
          <el-button v-perm="invoicePerms.remove" link type="danger" @click="remove([row.id])">
            {{ t('crud.action.delete') }}
          </el-button>
        </template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>
  </div>
</template>
