// @generated by qw-codegen (tree)
import { Injectable } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { TopicQuery } from '@qiwu/shared'
import type { SelectQueryBuilder } from 'typeorm'
import { BaseTreeService } from '../../../core/db/base-tree.service.js'
import { contains } from '../../../core/db/page.js'
import { Topic } from './topic.entity.js'

/**
 * Topics, a tree over BaseTreeService (docs/codegen-golden.md "Tree"): the forest list, the
 * paths, moves with the whole subtree and the enable / delete rules are the base's. Uniqueness is the
 * DB's (`unique(…, alive)`, errno 1062 → 409 `duplicate`); deletes are soft and check the references the
 * entity registers (409 `in_use`).
 */
@Injectable()
export class TopicService extends BaseTreeService<Topic> {
  constructor(txHost: TransactionHost<TransactionalAdapterTypeOrm>) {
    super(txHost, Topic)
  }

  protected override filter(
    qb: SelectQueryBuilder<Topic>,
    { title, enabled }: TopicQuery,
  ): SelectQueryBuilder<Topic> {
    if (title) qb.andWhere('t.title LIKE :title', { title: contains(title) })
    if (enabled !== undefined) qb.andWhere('t.enabled = :enabled', { enabled })
    return qb
  }
}
