<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import type { MailTemplateVo } from '@qiwu/shared'
import { mailTemplateApi } from '@/api/platform/messaging/mail-template'
import DictTag from '@/core/components/DictTag.vue'
import HtmlFrame from '@/core/components/HtmlFrame.vue'
import { refName, tx } from '@/core/i18n'

/** One mail template in the list's detail drawer (GET /:id). */
defineOptions({ name: 'MessagingMailTemplateDetail' })
const { id } = defineProps<{ id: number }>()
const { t } = useI18n()

const row = shallowRef<MailTemplateVo>()
const loading = ref(true)
// failures are toasted by the request layer (404 out of scope included)
mailTemplateApi
  .get(id)
  .then((r) => (row.value = r))
  .catch(() => undefined)
  .finally(() => (loading.value = false))
const time = (iso: string | null) => (iso ? dayjs(iso).format('YYYY-MM-DD HH:mm') : '')
</script>

<template>
  <div v-loading="loading" class="qw-detail">
    <el-descriptions v-if="row" :column="1" border>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.code')">
        {{ row.code }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.locale')">
        <DictTag code="core.locale" :value="row.locale" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.name')">
        {{ tx(row.name) }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.accountId')">
        {{
          row.accountId === null
            ? t('messaging.mailTemplate.defaultAccount')
            : refName(row.accountId, row.accountName)
        }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.senderLabel')">
        {{ row.senderLabel }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.subject')">
        {{ row.subject }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.body')">
        <HtmlFrame :html="row.body" :title="t('field.messaging.mailTemplate.body')" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.messaging.mailTemplate.enabled')">
        <DictTag code="core.enabled" :value="row.enabled" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.common.createdAt')">
        {{ time(row.createdAt) }}
      </el-descriptions-item>
    </el-descriptions>
  </div>
</template>
