<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { bookCreate } from '@qiwu/shared'
import { bookApi } from '@/api/demo/book'
import DeptTreeSelect from '@/core/components/DeptTreeSelect.vue'
import DictSelect from '@/core/components/DictSelect.vue'
import ImageUpload from '@/core/components/ImageUpload.vue'
import { useCrudForm } from '@/core/composables/use-crud'
import { uploadField } from '@/core/composables/use-upload'

/** Add / edit form of the book list, opened with `openDialog(BookForm, { id })`. */
defineOptions({ name: 'DemoBookForm' })
const { id } = defineProps<{ id?: number }>()
const emit = defineEmits<{ done: [saved: { id: number }]; cancel: [] }>()
const { t } = useI18n()
const { model, formRef, rules, loading, submitting, submit } = useCrudForm({
  api: bookApi,
  schema: bookCreate,
  emptyModel: () => ({
    isbn: '',
    title: '',
    author: '',
    coverUrl: '',
    publishedOn: null,
    price: 0,
    genre: '',
    deptId: null,
    enabled: true,
  }),
  id,
  emit,
})
// the column keeps one upload: an image's public URL (a public tag), a file's `<id>/<name>`
const coverUrlFiles = uploadField(model, 'coverUrl', 'image')
</script>

<template>
  <el-form ref="formRef" v-loading="loading" :model="model" :rules="rules" label-position="left">
    <el-form-item :label="t('field.demo.book.isbn')" prop="isbn">
      <el-input v-model="model.isbn" maxlength="20" />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.title')" prop="title">
      <el-input v-model="model.title" maxlength="200" />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.author')" prop="author">
      <el-input v-model="model.author" maxlength="100" />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.coverUrl')" prop="coverUrl">
      <ImageUpload v-model="coverUrlFiles" biz-tag="cover" />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.publishedOn')" prop="publishedOn">
      <el-date-picker v-model="model.publishedOn" type="date" value-format="YYYY-MM-DD" />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.price')" prop="price">
      <el-input-number
        v-model="model.price"
        :min="-99999999.99"
        :max="99999999.99"
        :precision="2"
        :step="0.01"
        controls-position="right"
      />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.genre')" prop="genre">
      <DictSelect v-model="model.genre" code="demo.genre" />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.deptId')" prop="deptId">
      <DeptTreeSelect v-model="model.deptId" />
    </el-form-item>
    <el-form-item :label="t('field.demo.book.enabled')" prop="enabled">
      <el-switch v-model="model.enabled" />
    </el-form-item>
  </el-form>
  <div class="qw-dialog-footer">
    <el-button @click="emit('cancel')">{{ t('common.action.cancel') }}</el-button>
    <el-button type="primary" :loading="submitting" @click="submit">
      {{ t('crud.action.save') }}
    </el-button>
  </div>
</template>
