// @generated by qw-codegen (crud)
// App version menus: the page under the `system` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (settings.app-version.json), the actions' in menu.json (menu.action.*).
import { appVersionPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findRow, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [appVersionPerms.browse, 'menu.action.browse'],
  [appVersionPerms.view, 'menu.action.view'],
  [appVersionPerms.create, 'menu.action.create'],
  [appVersionPerms.modify, 'menu.action.modify'],
  [appVersionPerms.remove, 'menu.action.remove'],
]

export async function seedAppVersion(q: EntityManager): Promise<string[]> {
  // the group menu: one an administrator deleted skips these menus, a missing one is an error
  const parent = await findRow(q, 'iam_menu', { route_name: 'system', kind: 'group' })
  if (!parent) throw new Error('seedAppVersion: the system menu group is missing')
  if (parent.deleted)
    return ['seed: the system menu group was deleted: the app version menus are skipped']
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'settings-app-version' },
    {
      parent_id: parent.id,
      kind: 'page',
      name: 'menu.settings.appVersion',
      route_path: '/settings/app-versions',
      component: 'platform/settings/app-version/index',
      component_name: 'SettingsAppVersion',
      keep_alive: 1,
      icon: 'lucide:smartphone',
      sort_no: 75,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
