// @generated by qw-codegen (crud)
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  ParseIntPipe,
  Post,
  Put,
  Query,
} from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import {
  type AppUpdateQuery,
  appUpdateQuery,
  appUpdateVo,
  type AppVersionCreate,
  appVersionCreate,
  appVersionPerms,
  type AppVersionQuery,
  appVersionQuery,
  type AppVersionUpdate,
  appVersionUpdate,
  appVersionVo,
  type EnabledBody,
  enabledBody,
  type IdsBody,
  idsBody,
  pageVo,
} from '@qiwu/shared'
import { ActionLog } from '../../../../core/audit/action-log.js'
import { Public, RequirePerm } from '../../../../core/auth/decorators.js'
import { Idempotent } from '../../../../core/guard/idempotent.js'
import { RateLimit } from '../../../../core/guard/rate-limit.decorator.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import type { AppVersion } from './app-version.entity.js'
import { AppVersionService } from './app-version.service.js'

@ApiTags('settings')
@Controller('settings/app-versions')
export class AppVersionController {
  constructor(private readonly appVersions: AppVersionService) {}

  @Get()
  @RequirePerm(appVersionPerms.browse)
  @ApiOperation({ summary: 'Page of app versions' })
  @ApiEnvelope(pageVo(appVersionVo))
  page(@Query({ schema: appVersionQuery }) query: AppVersionQuery) {
    return this.appVersions.page(query)
  }

  /** Before `:id` (else its ParseIntPipe answers `latest` with 400); public: a broken session still updates. */
  @Get('latest')
  @Public()
  @RateLimit(60, 60_000)
  @ApiOperation({ summary: 'The update an App should offer (null: none, or the check is off)' })
  @ApiEnvelope(appUpdateVo.nullable())
  latest(@Query({ schema: appUpdateQuery }) query: AppUpdateQuery) {
    return this.appVersions.latest(query)
  }

  @Get(':id')
  @RequirePerm(appVersionPerms.view)
  @ApiOperation({ summary: 'One app version' })
  @ApiEnvelope(appVersionVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.appVersions.get(id)
  }

  @Post()
  @RequirePerm(appVersionPerms.create)
  @Idempotent()
  @ActionLog({
    domain: 'settings.appVersion',
    verb: 'create',
    bizId: (_req, row) => (row as AppVersion | undefined)?.id,
  })
  @ApiOperation({ summary: 'Add an app version' })
  @ApiEnvelope(appVersionVo, 201)
  create(@Body({ schema: appVersionCreate }) dto: AppVersionCreate) {
    return this.appVersions.create(dto)
  }

  @Put(':id')
  @RequirePerm(appVersionPerms.modify)
  @ActionLog({ domain: 'settings.appVersion', verb: 'modify' })
  @ApiOperation({ summary: 'Change an app version' })
  @ApiEnvelope()
  update(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: appVersionUpdate }) dto: AppVersionUpdate,
  ) {
    return this.appVersions.update(id, dto)
  }

  @Put(':id/enabled')
  @RequirePerm(appVersionPerms.modify)
  @ActionLog({ domain: 'settings.appVersion', verb: 'modify' })
  @ApiOperation({ summary: 'Enable or disable an app version' })
  @ApiEnvelope()
  setEnabled(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: enabledBody }) dto: EnabledBody,
  ) {
    return this.appVersions.update(id, dto)
  }

  @Delete(':id')
  @RequirePerm(appVersionPerms.remove)
  @ActionLog({ domain: 'settings.appVersion', verb: 'remove' })
  @ApiOperation({ summary: 'Delete an app version' })
  @ApiEnvelope()
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.appVersions.remove([id])
  }

  @Post('batch-delete')
  @HttpCode(200)
  @RequirePerm(appVersionPerms.remove)
  @ActionLog({ domain: 'settings.appVersion', verb: 'remove' })
  @ApiOperation({ summary: 'Delete app versions: all or none' })
  @ApiEnvelope()
  batchRemove(@Body({ schema: idsBody }) { ids }: IdsBody) {
    return this.appVersions.remove(ids)
  }
}
