// @generated by qw-codegen (crud)
import { Column, Entity } from 'typeorm'
import { BaseEntity } from '../../../../core/db/base.entity.js'

/** `cfg_app_version`: App 版本 */
@Entity('cfg_app_version')
export class AppVersion extends BaseEntity {
  /** 平台（android/ios） */
  @Column({ length: 16 })
  platform: string

  /** 包类型（wgt：资源热更新包，full：整包） */
  @Column({ name: 'package_kind', length: 8 })
  packageKind: string

  /** 版本号（如 1.2.0） */
  @Column({ length: 24 })
  version: string

  /** 热更新包要求的最低原生版本（空为不限） */
  @Column({ name: 'native_min', type: 'varchar', length: 24, nullable: true })
  nativeMin: string | null

  /** 下载地址（https；整包为应用商店或安装包链接） */
  @Column({ length: 1024 })
  url: string

  /** 强制更新 */
  @Column({ name: 'is_forced', type: 'boolean', default: false })
  isForced: boolean

  /** 更新说明 */
  @Column({ type: 'text', nullable: true })
  notes: string | null

  /** 发布状态 */
  @Column({ type: 'boolean', default: true })
  enabled: boolean
}
