// @generated by qw-codegen (crud)
import { Controller, Get, Param, ParseIntPipe, Query } from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import {
  mailRecordPerms,
  type MailRecordQuery,
  mailRecordQuery,
  mailRecordVo,
  pageVo,
} from '@qiwu/shared'
import { RequirePerm } from '../../../../core/auth/decorators.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import { MailRecordService } from './mail-record.service.js'

@ApiTags('messaging')
@Controller('messaging/mail-records')
export class MailRecordController {
  constructor(private readonly mailRecords: MailRecordService) {}

  @Get()
  @RequirePerm(mailRecordPerms.browse)
  @ApiOperation({ summary: 'Page of mail records' })
  @ApiEnvelope(pageVo(mailRecordVo))
  page(@Query({ schema: mailRecordQuery }) query: MailRecordQuery) {
    return this.mailRecords.page(query)
  }

  @Get(':id')
  @RequirePerm(mailRecordPerms.view)
  @ApiOperation({ summary: 'One mail record' })
  @ApiEnvelope(mailRecordVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.mailRecords.get(id)
  }
}
