// @generated by qw-codegen (crud)
import type { ClientCreate, ClientSecretVo, ClientVo } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/oauth/clients'

/** /api/oauth/clients: the standard CRUD calls plus the module's own. */
export const clientApi = {
  ...crudApi<ClientVo, ClientCreate>(BASE),
  setEnabled: (id: number, enabled: boolean) => api.put(`${BASE}/${id}/enabled`, { enabled }),
  /** a new secret, answered this once; the old one stops working at once */
  resetSecret: (id: number) => api.post<ClientSecretVo>(`${BASE}/${id}/secret`),
}
