<!-- @generated by qw-codegen (crud) -->
<template>
  <z-paging
    ref="paging"
    v-model="rows"
    :default-page-size="PAGE_SIZE_DEFAULT"
    :empty-view-center="false"
    :default-theme-style="pagingTheme.style"
    :loading-more-title-custom-style="pagingTheme.title"
    :loading-more-no-more-line-custom-style="pagingTheme.line"
    @query="query"
  >
    <view class="qw-detail qw-stack">
      <wd-search
        v-model="keyword"
        hide-cancel
        placeholder-left
        :placeholder="t('field.demo.book.title')"
        @search="reload"
        @clear="reload"
      />
      <QwPerm :perm="bookPerms.create">
        <wd-button custom-class="qw-btn qw-btn--primary" type="primary" block @click="create">
          {{ t('crud.action.create') }}
        </wd-button>
      </QwPerm>
      <view
        v-for="row in rows"
        :key="row.id"
        class="qw-card qw-row"
        :role="canView ? 'link' : undefined"
        @click="open(row.id)"
      >
        <view class="qw-row__main">
          <view class="qw-row__line">
            <text class="qw-row__title">{{ row.title }}</text>
            <text :class="`qw-tag qw-tag--${dictTag('core.enabled', row.enabled).type}`">{{
              dictTag('core.enabled', row.enabled).label
            }}</text>
            <text class="qw-row__time">{{ formatShort(row.createdAt) }}</text>
          </view>
          <text class="qw-row__sub">{{ metaLine(row.isbn, row.author) }}</text>
        </view>
      </view>
    </view>
    <template #empty="{ isLoadFailed }">
      <QwEmpty :title="isLoadFailed ? error || t('common.error.network') : t('crud.empty')" />
    </template>
  </z-paging>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLoad, onShow } from '@dcloudio/uni-app'
import { bookPerms, type BookVo, PAGE_SIZE_DEFAULT, PAGE_SIZE_MAX } from '@qiwu/shared'
import { bookApi } from '@/api/demo/book'
import QwEmpty from '@/core/components/QwEmpty.vue'
import QwPerm from '@/core/components/QwPerm.vue'
import { metaLine, useDicts } from '@/core/crud'
import { formatShort } from '@/core/format'
import { t } from '@/core/i18n'
import { errorText } from '@/core/request'
import { hasPerm } from '@/core/stores/auth'
import { pagingTheme } from '@/core/theme'

/**
 * The books (mobile, generated): sorted by `-createdAt`, paged by z-paging (pull to
 * refresh, load on scroll), searched by `title`; a row opens its detail.
 */
const paging = ref<ZPagingRef<BookVo>>()
const rows = ref<BookVo[]>([])
const error = ref('')
const keyword = ref('')
const { dictTag } = useDicts(['core.enabled'])

const canView = computed(() => hasPerm(bookPerms.view))
const open = (id: number) =>
  canView.value && uni.navigateTo({ url: `/pages-biz/demo/book/detail?id=${id}` })
const create = () => uni.navigateTo({ url: '/pages-biz/demo/book/form' })

// only the latest request's answer shows: a search sent meanwhile drops the earlier one's
let seq = 0
function query(page: number, pageSize: number) {
  const mine = ++seq
  bookApi
    .page({
      page,
      pageSize,
      sort: '-createdAt',
      ...(keyword.value ? { title: keyword.value } : {}),
    })
    .then(
      (res) => {
        if (mine !== seq) return
        error.value = ''
        void paging.value?.completeByTotal(res.items, res.total)
      },
      (e) => {
        if (mine !== seq) return
        error.value = errorText(e)
        void paging.value?.complete(false)
      },
    )
}
const reload = () => void paging.value?.reload()

onLoad(() => uni.setNavigationBarTitle({ title: t('menu.demo.book') }))
// z-paging loads the first page itself; showing again (back from a form or detail) reloads the loaded pages
// in one request, within the API's page size limit
let shown = false
onShow(() => {
  if (shown && paging.value)
    void (rows.value.length >= PAGE_SIZE_MAX ? paging.value.reload() : paging.value.refresh())
  shown = true
})
</script>
