// @generated by qw-codegen (crud)
import { z } from 'zod'
import { pageQuery } from '../common/pagination.js'
import { fieldDomains } from '../validation/zod-i18n.js'

/**
 * Books (`demo_book`), `/api/demo/books` (see docs/design-notes.md#api-envelope). Field labels
 * `field.demo.book.<prop>`.
 */

export const bookPerms = {
  browse: 'demo.book.browse',
  view: 'demo.book.view',
  create: 'demo.book.create',
  modify: 'demo.book.modify',
  remove: 'demo.book.remove',
  export: 'demo.book.export',
  import: 'demo.book.import',
} as const

/** POST body; columns with a DB default may be left out, nullable ones may be null. */
export const bookCreate = z
  .object({
    isbn: z.string().trim().min(1).max(20),
    title: z.string().trim().min(1).max(200),
    author: z.string().trim().max(100).nullish(),
    coverUrl: z.string().trim().max(512).nullish(),
    publishedOn: z.iso.date().meta({ example: '2024-05-01' }).nullish(),
    price: z
      .number()
      .min(-99_999_999.99)
      .max(99_999_999.99)
      .multipleOf(0.01)
      .meta({ example: 42.5 })
      .optional(),
    genre: z.string().trim().min(1).max(16).meta({ example: 'fiction' }),
    deptId: z.number().int().min(0).nullish(),
    enabled: z.boolean().optional(),
  })
  .register(fieldDomains, { domain: 'demo.book' })
export type BookCreate = z.infer<typeof bookCreate>

/** PUT body: the fields sent are changed, the others kept. */
export const bookUpdate = bookCreate.partial().register(fieldDomains, { domain: 'demo.book' })
export type BookUpdate = z.infer<typeof bookUpdate>

/** GET query: paging, sort and the list filters (text contains, ranges from / to, the rest equals). */
export const bookQuery = pageQuery([
  'isbn',
  'title',
  'author',
  'publishedOn',
  'price',
  'genre',
  'createdAt',
  'id',
])
  .extend({
    isbn: z.string().trim().max(20).optional(),
    title: z.string().trim().max(200).optional(),
    publishedOnFrom: z.iso.date().optional(),
    publishedOnTo: z.iso.date().optional(),
    genre: z.string().trim().max(16).optional(),
    deptId: z.coerce.number().int().optional(),
    enabled: z.stringbool().optional(),
    createdAtFrom: z.iso.datetime({ offset: true }).optional(),
    createdAtTo: z.iso.datetime({ offset: true }).optional(),
  })
  .register(fieldDomains, { domain: 'demo.book' })
export type BookQuery = z.output<typeof bookQuery>

export const bookVo = z.object({
  id: z.number().int(),
  isbn: z.string(),
  title: z.string(),
  author: z.string().nullable(),
  coverUrl: z.string().nullable(),
  publishedOn: z.iso.date().nullable(),
  price: z.number(),
  genre: z.string(),
  deptId: z.number().int().nullable(),
  enabled: z.boolean(),
  createdBy: z.number().int().nullable(),
  createdAt: z.iso.datetime(),
  updatedBy: z.number().int().nullable(),
  updatedAt: z.iso.datetime(),
})
export type BookVo = z.infer<typeof bookVo>
