// @generated by qw-codegen (tree)
import { z } from 'zod'
import { fieldDomains } from '../validation/zod-i18n.js'

/**
 * Topics (`demo_topic`), `/api/demo/topics` (see docs/design-notes.md#api-envelope), a tree table (`parent_id`, 0 =
 * top level, + `tree_path`) listed whole as a forest (docs/codegen-golden.md "Tree"). Field labels
 * `field.demo.topic.<prop>`.
 */

export const topicPerms = {
  browse: 'demo.topic.browse',
  view: 'demo.topic.view',
  create: 'demo.topic.create',
  modify: 'demo.topic.modify',
  remove: 'demo.topic.remove',
} as const

/**
 * POST body; columns with a DB default may be left out, nullable ones may be null. `parentId`: 0 =
 * top level, else an enabled row (404 / 422 `tree.parent_disabled`); changing it moves the row with its
 * whole subtree, never below itself (422 `tree.parent_invalid`).
 */
export const topicCreate = z
  .object({
    parentId: z.number().int().min(0).optional(),
    title: z.string().trim().min(1).max(100),
    sortNo: z.number().int().min(0).max(999_999).optional(),
    enabled: z.boolean().optional(),
  })
  .register(fieldDomains, { domain: 'demo.topic' })
export type TopicCreate = z.infer<typeof topicCreate>

/** PUT body: the fields sent are changed, the others kept. */
export const topicUpdate = topicCreate.partial().register(fieldDomains, { domain: 'demo.topic' })
export type TopicUpdate = z.infer<typeof topicUpdate>

/**
 * GET query: the list filters (text contains, ranges from / to, the rest equals). A matching row whose
 * parent does not match is a root of the result.
 */
export const topicQuery = z
  .object({
    title: z.string().trim().max(100).optional(),
    enabled: z.stringbool().optional(),
  })
  .register(fieldDomains, { domain: 'demo.topic' })
export type TopicQuery = z.output<typeof topicQuery>

export const topicVo = z.object({
  id: z.number().int(),
  parentId: z.number().int(),
  treePath: z.string(),
  title: z.string(),
  sortNo: z.number().int(),
  enabled: z.boolean(),
  createdBy: z.number().int().nullable(),
  createdAt: z.iso.datetime(),
  updatedBy: z.number().int().nullable(),
  updatedAt: z.iso.datetime(),
})
export type TopicVo = z.infer<typeof topicVo>

export interface TopicNode extends TopicVo {
  children: TopicNode[]
}

/** GET / (browse): the caller's topics matching the filters as a forest, siblings by `sort_no, id`. */
export const topicNodeVo: z.ZodType<TopicNode> = topicVo.extend({
  get children() {
    return z.array(topicNodeVo)
  },
})
