<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import { positionPerms, type PositionVo } from '@qiwu/shared'
import { positionApi } from '@/api/platform/iam/position'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { openDialog } from '@/core/dialog'
import { tx } from '@/core/i18n'
import { Icon } from '@/core/icons'
import { usePerm } from '@/core/permission'
import PositionForm from './form.vue'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'IamPosition' })

const { t } = useI18n()
const {
  query,
  rows,
  total,
  loading,
  filtered,
  selection,
  search,
  reset,
  refresh,
  onSelectionChange,
  onSortChange,
  remove,
  batchRemove,
  exporting,
  exportXlsx,
} = useCrudList({
  api: positionApi,
  filters: { code: '', name: '', enabled: null as string | null },
  sort: 'sortNo',
})
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `iam.position`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  {
    prop: 'code',
    label: 'field.iam.position.code',
    sortable: true,
    width: 140,
    showOverflowTooltip: true,
  },
  {
    prop: 'name',
    label: 'field.iam.position.name',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'sortNo',
    label: 'field.iam.position.sortNo',
    sortable: true,
    width: 120,
    align: 'right',
  },
  { prop: 'enabled', label: 'field.iam.position.enabled', width: 100 },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
  { prop: 'note', label: 'field.iam.position.note', minWidth: 120, showOverflowTooltip: true },
]
// computed: the perms reload when the server's permission version moves
const perm = usePerm()
const canModify = computed(() => perm.has(positionPerms.modify))
// the edit form loads GET /:id, which needs `view` too
const canEdit = computed(() => perm.all([positionPerms.modify, positionPerms.view]))

/** Add (no id) or edit in the form dialog; reload once saved. */
async function openForm(id?: number) {
  const name = () => t('iam.position.entity')
  const saved = await openDialog(
    PositionForm,
    { id },
    { title: () => t(id ? 'crud.title.edit' : 'crud.title.create', { name: name() }) },
  )
  if (saved) await refresh()
}

async function setEnabled(row: PositionVo, enabled: boolean) {
  // failures are toasted by the request layer; the reload shows the stored state either way
  await positionApi.setEnabled(row.id, enabled).catch(() => undefined)
  await refresh()
}
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.iam.position.code')">
          <el-input v-model="query.code" name="code" clearable />
        </el-form-item>
        <el-form-item :label="t('field.iam.position.name')">
          <el-input v-model="query.name" name="name" clearable />
        </el-form-item>
        <el-form-item :label="t('field.iam.position.enabled')">
          <DictSelect v-model="query.enabled" code="core.enabled" />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="iam.position"
        :columns="columns"
        @refresh="refresh"
      >
        <el-button v-perm="positionPerms.create" type="primary" @click="openForm()">
          <el-icon class="el-icon--left"><Icon icon="lucide:plus" /></el-icon>
          {{ t('crud.action.create') }}
        </el-button>
        <el-button
          v-perm="positionPerms.export"
          :loading="exporting"
          @click="exportXlsx(`${t('menu.iam.position')}.xlsx`)"
        >
          <el-icon class="el-icon--left"><Icon icon="lucide:download" /></el-icon>
          {{ t('crud.action.export') }}
        </el-button>
        <el-button
          v-if="selection.length"
          v-perm="positionPerms.remove"
          type="danger"
          plain
          @click="batchRemove"
        >
          {{ t('crud.action.batchDelete') }}
        </el-button>
      </TableToolbar>

      <QwTable
        table-id="iam.position"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        selection
        @selection-change="onSelectionChange"
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <!-- seeded names are i18n keys (seed.position.*) -->
        <template #cell-name="{ row }">{{ tx(row.name) }}</template>
        <template #cell-enabled="{ row }">
          <el-switch
            v-if="canModify"
            size="small"
            :model-value="row.enabled"
            :aria-label="`${t('field.iam.position.enabled')} ${tx(row.name)}`"
            @change="setEnabled(row, $event as boolean)"
          />
          <DictTag v-else code="core.enabled" :value="row.enabled" />
        </template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #actions="{ row }">
          <el-button v-if="canEdit" link type="primary" @click="openForm(row.id)">
            {{ t('crud.action.edit') }}
          </el-button>
          <el-button v-perm="positionPerms.remove" link type="danger" @click="remove([row.id])">
            {{ t('crud.action.delete') }}
          </el-button>
        </template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>
  </div>
</template>
