// @generated by qw-codegen (crud)
import { Injectable } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { SmsRecordQuery } from '@qiwu/shared'
import type { SelectQueryBuilder } from 'typeorm'
import { BaseCrudService } from '../../../../core/db/base-crud.service.js'
import { contains } from '../../../../core/db/page.js'
import { SmsRecord } from './sms-record.entity.js'

/**
 * Sms records over BaseCrudService. Read only here: rows are soft-deleted like every
 * table and dropped for good by `audit.purge` past `audit.retention_days`.
 */
@Injectable()
export class SmsRecordService extends BaseCrudService<SmsRecord> {
  constructor(txHost: TransactionHost<TransactionalAdapterTypeOrm>) {
    super(txHost, SmsRecord)
  }

  protected override filter(
    qb: SelectQueryBuilder<SmsRecord>,
    { templateCode, mobile, status, receiptStatus, createdAtFrom, createdAtTo }: SmsRecordQuery,
  ): SelectQueryBuilder<SmsRecord> {
    if (templateCode)
      qb.andWhere('t.template_code LIKE :templateCode', { templateCode: contains(templateCode) })
    if (mobile) qb.andWhere('t.mobile = :mobile', { mobile })
    if (status) qb.andWhere('t.status = :status', { status })
    if (receiptStatus) qb.andWhere('t.receipt_status = :receiptStatus', { receiptStatus })
    if (createdAtFrom)
      qb.andWhere('t.created_at >= :createdAtFrom', { createdAtFrom: new Date(createdAtFrom) })
    if (createdAtTo)
      qb.andWhere('t.created_at <= :createdAtTo', { createdAtTo: new Date(createdAtTo) })
    return qb
  }
}
