// @generated by qw-codegen (crud)
// Sms record menus: the page under the `messaging` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (messaging.sms-record.json), the actions' in menu.json (menu.action.*).
import { smsRecordPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [smsRecordPerms.browse, 'menu.action.browse'],
  [smsRecordPerms.view, 'menu.action.view'],
]

export async function seedSmsRecord(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'messaging' })
  if (parentId === undefined) throw new Error('seedSmsRecord: the messaging menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'messaging-sms-record' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.messaging.smsRecord',
      route_path: '/messaging/sms-records',
      component: 'platform/messaging/sms-record/index',
      component_name: 'MessagingSmsRecord',
      keep_alive: 1,
      icon: 'lucide:message-square-more',
      sort_no: 90,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
