// @generated by qw-codegen (crud)
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  ParseIntPipe,
  Post,
  Put,
  Query,
} from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import {
  configPerms,
  configQuery,
  configVo,
  type EnabledBody,
  enabledBody,
  type IdsBody,
  idsBody,
  pageVo,
  type StorageConfigCreate,
  storageConfigCreate,
  type StorageConfigQuery,
  type StorageConfigUpdate,
  storageConfigUpdate,
  storageConfigVo,
  storageTestVo,
} from '@qiwu/shared'
import { ActionLog } from '../../../../core/audit/action-log.js'
import { RequirePerm } from '../../../../core/auth/decorators.js'
import { Idempotent } from '../../../../core/guard/idempotent.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import { StorageConfigService } from './config.service.js'

@ApiTags('storage')
@Controller('storage/configs')
export class StorageConfigController {
  constructor(private readonly configs: StorageConfigService) {}

  @Get()
  @RequirePerm(configPerms.browse)
  @ApiOperation({ summary: 'Page of configs (no driver settings)' })
  @ApiEnvelope(pageVo(configVo))
  page(@Query({ schema: configQuery }) query: StorageConfigQuery) {
    return this.configs.list(query)
  }

  @Get(':id')
  @RequirePerm(configPerms.view)
  @ApiOperation({ summary: 'One config with its driver settings (secretKey masked)' })
  @ApiEnvelope(storageConfigVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.configs.detail(id)
  }

  @Post()
  @RequirePerm(configPerms.create)
  @Idempotent()
  @ActionLog({
    domain: 'storage.config',
    verb: 'create',
    bizId: (_req, row) => (row as { id?: number } | undefined)?.id,
  })
  @ApiOperation({ summary: 'Add a config (local or s3; never primary)' })
  @ApiEnvelope(storageConfigVo, 201)
  create(@Body({ schema: storageConfigCreate }) dto: StorageConfigCreate) {
    return this.configs.add(dto)
  }

  @Put(':id')
  @RequirePerm(configPerms.modify)
  @ActionLog({ domain: 'storage.config', verb: 'modify' })
  @ApiOperation({ summary: 'Change a config: the whole form; secretKey left out or masked = kept' })
  @ApiEnvelope()
  update(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: storageConfigUpdate }) dto: StorageConfigUpdate,
  ) {
    return this.configs.edit(id, dto)
  }

  @Put(':id/enabled')
  @RequirePerm(configPerms.modify)
  @ActionLog({ domain: 'storage.config', verb: 'modify' })
  @ApiOperation({ summary: 'Enable or disable a config (never the primary one)' })
  @ApiEnvelope()
  setEnabled(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: enabledBody }) { enabled }: EnabledBody,
  ) {
    return this.configs.setEnabled(id, enabled)
  }

  @Put(':id/primary')
  @RequirePerm(configPerms.modify)
  @ActionLog({ domain: 'storage.config', verb: 'modify' })
  @ApiOperation({ summary: 'Make an enabled config the primary one (new uploads go there)' })
  @ApiEnvelope()
  setPrimary(@Param('id', ParseIntPipe) id: number) {
    return this.configs.setPrimary(id)
  }

  @Post(':id/test')
  @HttpCode(200)
  @RequirePerm(configPerms.modify)
  @ActionLog({ domain: 'storage.config', verb: 'test' })
  @ApiOperation({ summary: 'Test the stored config: {ok} only, never why it failed' })
  @ApiEnvelope(storageTestVo)
  test(@Param('id', ParseIntPipe) id: number) {
    return this.configs.test(id)
  }

  @Delete(':id')
  @RequirePerm(configPerms.remove)
  @ActionLog({ domain: 'storage.config', verb: 'remove' })
  @ApiOperation({ summary: 'Delete a config (not the primary one, not one holding files)' })
  @ApiEnvelope()
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.configs.remove([id])
  }

  @Post('batch-delete')
  @HttpCode(200)
  @RequirePerm(configPerms.remove)
  @ActionLog({ domain: 'storage.config', verb: 'remove' })
  @ApiOperation({ summary: 'Delete configs: all or none' })
  @ApiEnvelope()
  batchRemove(@Body({ schema: idsBody }) { ids }: IdsBody) {
    return this.configs.remove(ids)
  }
}
