// @generated by qw-codegen (crud)
import { constants } from 'node:fs'
import { access, mkdir } from 'node:fs/promises'
import { Injectable } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import {
  Err,
  type Page,
  STORAGE_SECRET_MASK,
  type StorageConfigCreate,
  type StorageConfigQuery,
  type StorageConfigRowVo,
  type StorageConfigUpdate,
  type StorageConfigVo,
  type StorageTestVo,
} from '@qiwu/shared'
import {
  type EntityManager,
  In,
  type QueryDeepPartialEntity,
  type SelectQueryBuilder,
} from 'typeorm'
import { AppConfigService } from '../../../../core/config/config.module.js'
import { SecretBox } from '../../../../core/crypto/secret-box.js'
import { BaseCrudService } from '../../../../core/db/base-crud.service.js'
import { contains } from '../../../../core/db/page.js'
import { BizError } from '../../../../core/http/biz-error.js'
import { seedKeysLike } from '../../../../core/i18n/seed-names.js'
import { isRefusedLiteral, outboundRule } from '../../../../core/net/net-guard.js'
import { uploadRoot } from '../../../../core/paths.js'
import { type S3Config, S3Storage } from '../s3-storage.js'
import { StorageConfig } from './config.entity.js'

const iso = (d: Date) => d.toISOString()

/** A list row: the driver config (endpoint, keys) stays out. */
const rowVo = (r: StorageConfig): StorageConfigRowVo => ({
  id: r.id,
  name: r.name,
  driver: r.driver,
  isPrimary: r.isPrimary,
  enabled: r.enabled,
  note: r.note,
  createdBy: r.createdBy,
  createdAt: iso(r.createdAt),
  updatedBy: r.updatedBy,
  updatedAt: iso(r.updatedAt),
})

/**
 * A deleted storage's S3 `secretKey` goes once no object row (live or deleted) is left on it: the
 * retention purge needs it until then to delete the deleted objects' bodies. Run by the storage delete
 * and after every purge (`StorageService.purgeDeleted`).
 */
export async function dropUnusedSecrets(q: EntityManager): Promise<void> {
  await q.query(
    `UPDATE fs_storage s SET s.config = JSON_REMOVE(s.config, '$.secretKey')
      WHERE s.deleted_at IS NOT NULL AND JSON_CONTAINS_PATH(s.config, 'one', '$.secretKey')
        AND NOT EXISTS (SELECT 1 FROM fs_object o WHERE o.storage_id = s.id)`, // qw:include-deleted objects waiting for the purge count too
  )
}

/**
 * Storage configs (see docs/design-notes.md#storage) over BaseCrudService; generated list, hand-written driver forms (G).
 * `config` JSON: local `{publicPrefix}` (the root is `STORAGE_LOCAL_ROOT` only), s3 the connection
 * with `secretKey` boxed by SecretBox and never answered (masked). An S3 endpoint on an inner IP literal,
 * `localhost` or an unregistered port is refused on save (422); names are checked by the core/net agents
 * whenever the storage connects (test connection answers `{ok}` only). Exactly one storage is primary:
 * set through `setPrimary`, never disabled or deleted while primary.
 */
@Injectable()
export class StorageConfigService extends BaseCrudService<StorageConfig> {
  constructor(
    txHost: TransactionHost<TransactionalAdapterTypeOrm>,
    private readonly box: SecretBox,
    private readonly cfg: AppConfigService,
  ) {
    super(txHost, StorageConfig)
  }

  protected override filter(
    qb: SelectQueryBuilder<StorageConfig>,
    { name, driver, enabled }: StorageConfigQuery,
  ): SelectQueryBuilder<StorageConfig> {
    if (name) {
      // seeded names are keys (seed.storage.*): also match the text users see, in any language
      const seeded = seedKeysLike('seed.storage.', name)
      qb.andWhere(
        seeded.length ? '(t.name LIKE :name OR t.name IN (:...seeded))' : 't.name LIKE :name',
        { name: contains(name), seeded },
      )
    }
    if (driver) qb.andWhere('t.driver = :driver', { driver })
    if (enabled !== undefined) qb.andWhere('t.enabled = :enabled', { enabled })
    return qb
  }

  async list(query: StorageConfigQuery): Promise<Page<StorageConfigRowVo>> {
    const page = await this.page(query)
    return { ...page, items: page.items.map(rowVo) }
  }

  /** The form's detail: the driver fields, `secretKey` masked. */
  async detail(id: number): Promise<StorageConfigVo> {
    const r = await this.get(id)
    const common = {
      id: r.id,
      name: r.name,
      isPrimary: r.isPrimary,
      enabled: r.enabled,
      note: r.note,
      createdAt: iso(r.createdAt),
      updatedAt: iso(r.updatedAt),
    }
    const c = r.config ?? {}
    const text = (v: unknown) => (typeof v === 'string' && v ? v : null)
    if (r.driver === 'local')
      return { ...common, driver: 'local', publicPrefix: text(c.publicPrefix) }
    return {
      ...common,
      driver: 's3',
      endpoint: String(c.endpoint ?? ''),
      region: String(c.region ?? ''),
      bucket: String(c.bucket ?? ''),
      accessKey: String(c.accessKey ?? ''),
      secretKey: STORAGE_SECRET_MASK,
      forcePathStyle: c.forcePathStyle === true,
      publicDomain: text(c.publicDomain),
    }
  }

  /** A new storage, never primary (`setPrimary` makes it so). */
  async add(body: StorageConfigCreate): Promise<StorageConfigVo> {
    const { name, driver, enabled, note } = body
    const row = await this.create({
      name,
      driver,
      enabled,
      note,
      isPrimary: false,
      config: this.configOf(body, null),
    })
    return this.detail(row.id)
  }

  /** The whole form; the driver stays; keeping a secret requires an unchanged connection target. */
  edit(id: number, body: StorageConfigUpdate): Promise<void> {
    return this.txHost.withTransaction(async () => {
      const stored = await this.locked(id)
      if (stored.driver !== body.driver) throw new BizError(Err.STORAGE_DRIVER_FIXED)
      if (stored.isPrimary && body.enabled === false) throw new BizError(Err.STORAGE_PRIMARY_LOCKED)
      const set = { name: body.name, enabled: body.enabled, note: body.note }
      await this.repo.update(id, {
        ...Object.fromEntries(Object.entries(set).filter(([, v]) => v !== undefined)),
        config: this.configOf(body, stored.config),
      } as QueryDeepPartialEntity<StorageConfig>)
    })
  }

  setEnabled(id: number, enabled: boolean): Promise<void> {
    return this.txHost.withTransaction(async () => {
      const stored = await this.locked(id)
      if (stored.isPrimary && !enabled) throw new BizError(Err.STORAGE_PRIMARY_LOCKED)
      await this.repo.update(id, { enabled })
    })
  }

  /**
   * Live objects on a storage keep it (the reference registry → 409 `in_use`; deleted objects waiting
   * for the purge do not, the purge reads the deleted storage's config, its secret dropped after the
   * last one: `dropUnusedSecrets`); the primary one stays.
   */
  override remove(ids: readonly number[]): Promise<void> {
    return this.txHost.withTransaction(async () => {
      await this.lockScopedIds(ids)
      if (await this.repo.existsBy({ id: In([...ids]), isPrimary: true }))
        throw new BizError(Err.STORAGE_PRIMARY_LOCKED)
      await super.remove(ids)
      await dropUnusedSecrets(this.txHost.tx)
    })
  }

  /** Makes an enabled storage the primary one (new uploads go there); the previous one stays enabled. */
  setPrimary(id: number): Promise<void> {
    return this.txHost.withTransaction(async () => {
      const target = await this.locked(id)
      if (!target.enabled) throw new BizError(Err.STORAGE_PRIMARY_LOCKED)
      if (target.isPrimary) return
      // the old one first (unique primary index); a racing switch waits on its row lock, or ends 409
      await this.repo.update({ isPrimary: true }, { isPrimary: false })
      await this.repo.update(id, { isPrimary: true })
    })
  }

  /**
   * Test connection with the stored config: local = the upload root is writable; s3 = the bucket
   * answers these credentials through the SSRF guard within 5 s. Only `{ok}`: why it failed (refused
   * address, timeout, credentials, bucket) is never told apart and nothing remote is echoed.
   */
  async test(id: number): Promise<StorageTestVo> {
    const r = await this.get(id)
    if (r.driver === 'local') {
      const ok = await mkdir(uploadRoot(), { recursive: true })
        .then(() => access(uploadRoot(), constants.W_OK))
        .then(
          () => true,
          () => false,
        )
      return { ok }
    }
    let s3: S3Storage
    try {
      const c = r.config as unknown as S3Config
      s3 = new S3Storage(
        { ...c, secretKey: this.box.decrypt(c.secretKey) },
        outboundRule(this.cfg, 's3'),
      )
    } catch {
      return { ok: false }
    }
    try {
      return { ok: await s3.test() }
    } finally {
      s3.destroy()
    }
  }

  private async locked(id: number): Promise<StorageConfig> {
    await this.lockScopedIds([id])
    return this.repo.findOneByOrFail({ id })
  }

  /** The `config` JSON of a body (`stored` = the row's current one when editing). */
  private configOf(
    body: StorageConfigCreate | StorageConfigUpdate,
    stored: Record<string, unknown> | null,
  ): Record<string, unknown> {
    if (body.driver === 'local') return { publicPrefix: body.publicPrefix ?? null }
    const url = new URL(body.endpoint)
    const port = Number(url.port || (url.protocol === 'https:' ? 443 : 80))
    if (isRefusedLiteral(url.hostname, port, outboundRule(this.cfg, 's3')))
      throw new BizError(Err.STORAGE_ENDPOINT_REFUSED)
    // editing: left out, blank or the mask keeps the secret only for the same connection target
    const secret = body.secretKey?.trim()
    const keep = stored != null && (!secret || secret === STORAGE_SECRET_MASK)
    if (
      stored?.secretKey &&
      keep &&
      (['endpoint', 'bucket', 'accessKey'] as const).some((key) => body[key] !== stored[key])
    )
      throw new BizError(Err.STORAGE_SECRET_REQUIRED)
    return {
      endpoint: body.endpoint,
      region: body.region,
      bucket: body.bucket,
      accessKey: body.accessKey,
      // the stored s3 row (driver fixed) always has one; a create always sends one (schema)
      secretKey: keep ? stored?.secretKey : this.box.encrypt(body.secretKey!),
      forcePathStyle: body.forcePathStyle,
      publicDomain: body.publicDomain ?? null,
    }
  }
}
