// @generated by qw-codegen (crud)
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { DictController } from './dict.controller.js'
import { Dict } from './dict.entity.js'
import { DictService } from './dict.service.js'

@Module({
  imports: [TypeOrmModule.forFeature([Dict])],
  controllers: [DictController],
  providers: [DictService],
})
export class DictModule {}
