// @generated by qw-codegen (crud)
// Dict menus: the page under the `system` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (settings.dict.json), the actions' in menu.json (menu.action.*).
import { dictPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [dictPerms.browse, 'menu.action.browse'],
  [dictPerms.view, 'menu.action.view'],
  [dictPerms.create, 'menu.action.create'],
  [dictPerms.modify, 'menu.action.modify'],
  [dictPerms.remove, 'menu.action.remove'],
  [dictPerms.export, 'menu.action.export'],
]

export async function seedDict(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'system' })
  if (parentId === undefined) throw new Error('seedDict: the system menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'settings-dict' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.settings.dict',
      route_path: '/settings/dicts',
      component: 'platform/settings/dict/index',
      component_name: 'SettingsDict',
      keep_alive: 1,
      icon: 'lucide:book-a',
      sort_no: 60,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
