// @generated by qw-codegen (crud)
import type { I18nText } from '@qiwu/shared'
import { Column, Entity } from 'typeorm'
import { BaseEntity } from '../../../../core/db/base.entity.js'

/** `cfg_dict`: 字典 */
@Entity('cfg_dict')
export class Dict extends BaseEntity {
  /** 字典编码（点分，如 iam.gender） */
  @Column({ length: 100 })
  code: string

  /** 字典名称（无对应语言时显示） */
  @Column({ length: 100 })
  name: string

  /** 多语言名称 */
  @Column({ name: 'name_i18n', type: 'json', nullable: true })
  nameI18n: I18nText | null

  /** 是否启用 */
  @Column({ type: 'boolean', default: true })
  enabled: boolean

  /** 备注 */
  @Column({ type: 'varchar', length: 500, nullable: true })
  note: string | null
}
