<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import { smsRecordPerms, type SmsRecordVo } from '@qiwu/shared'
import { smsRecordApi } from '@/api/platform/messaging/sms-record'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { Icon } from '@/core/icons'
import { usePerm } from '@/core/permission'
import SmsRecordDetail from './detail.vue'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'MessagingSmsRecord' })

const { t } = useI18n()
const { query, rows, total, loading, filtered, search, reset, refresh, onSortChange } = useCrudList(
  {
    api: smsRecordApi,
    filters: {
      templateCode: '',
      mobile: '',
      status: null as string | null,
      receiptStatus: null as string | null,
      createdAtRange: null as [string, string] | null,
    },
    sort: '-createdAt',
  },
)
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `messaging.smsRecord`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  {
    prop: 'templateCode',
    label: 'field.messaging.smsRecord.templateCode',
    sortable: true,
    width: 160,
    showOverflowTooltip: true,
  },
  {
    prop: 'mobile',
    label: 'field.messaging.smsRecord.mobile',
    sortable: true,
    width: 260,
    showOverflowTooltip: true,
  },
  {
    prop: 'status',
    label: 'field.messaging.smsRecord.status',
    width: 120,
    showOverflowTooltip: true,
  },
  {
    prop: 'receiptStatus',
    label: 'field.messaging.smsRecord.receiptStatus',
    width: 130,
    showOverflowTooltip: true,
  },
  { prop: 'receiptAt', label: 'field.messaging.smsRecord.receiptAt', sortable: true, width: 160 },
  {
    prop: 'attempts',
    label: 'field.messaging.smsRecord.attempts',
    sortable: true,
    width: 130,
    align: 'right',
  },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
  {
    prop: 'error',
    label: 'field.messaging.smsRecord.error',
    width: 160,
    showOverflowTooltip: true,
  },
]
// computed: the perms reload when the server's permission version moves
const perm = usePerm()
// the detail drawer loads GET /:id, which needs `view`
const canView = computed(() => perm.has(smsRecordPerms.view))

const detailId = ref<number>()
const detailOpen = ref(false)
function openDetail(row: SmsRecordVo) {
  detailId.value = row.id
  detailOpen.value = true
}
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.messaging.smsRecord.templateCode')">
          <el-input v-model="query.templateCode" name="templateCode" clearable />
        </el-form-item>
        <el-form-item :label="t('field.messaging.smsRecord.mobile')">
          <el-input v-model="query.mobile" name="mobile" clearable />
        </el-form-item>
        <el-form-item :label="t('field.messaging.smsRecord.status')">
          <DictSelect v-model="query.status" code="messaging.sms_record_status" />
        </el-form-item>
        <el-form-item :label="t('field.messaging.smsRecord.receiptStatus')">
          <DictSelect v-model="query.receiptStatus" code="messaging.sms_receipt_status" />
        </el-form-item>
        <el-form-item :label="t('field.common.createdAt')" class="qw-search-wide">
          <el-date-picker
            v-model="query.createdAtRange"
            type="daterange"
            value-format="YYYY-MM-DD"
            :start-placeholder="t('field.common.createdAtFrom')"
            :end-placeholder="t('field.common.createdAtTo')"
          />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="messaging.smsRecord"
        :columns="columns"
        @refresh="refresh"
      >
      </TableToolbar>

      <QwTable
        table-id="messaging.smsRecord"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <template #cell-templateCode="{ row }">
          <el-button
            v-if="canView"
            link
            type="primary"
            class="qw-cell-link"
            @click="openDetail(row)"
          >
            {{ row.templateCode }}
          </el-button>
          <template v-else>{{ row.templateCode }}</template>
        </template>
        <template #cell-status="{ row }">
          <DictTag code="messaging.sms_record_status" :value="row.status" />
        </template>
        <template #cell-receiptStatus="{ row }">
          <DictTag code="messaging.sms_receipt_status" :value="row.receiptStatus" />
        </template>
        <template #cell-receiptAt="{ row }">{{
          row.receiptAt ? dayjs(row.receiptAt).format('YYYY-MM-DD HH:mm') : ''
        }}</template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>

    <!-- destroy-on-close: each opening loads the row anew (it may have been edited meanwhile) -->
    <el-drawer
      v-model="detailOpen"
      :title="t('crud.title.detail', { name: t('messaging.smsRecord.entity') })"
      size="480px"
      destroy-on-close
    >
      <SmsRecordDetail v-if="detailId" :id="detailId" />
    </el-drawer>
  </div>
</template>
