// @generated by qw-codegen (crud)
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  ParseIntPipe,
  Post,
  Put,
  Query,
} from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import {
  type EnabledBody,
  enabledBody,
  type IdsBody,
  idsBody,
  type InboxTemplateCreate,
  inboxTemplateCreate,
  inboxTemplatePerms,
  type InboxTemplateQuery,
  inboxTemplateQuery,
  type InboxTemplateUpdate,
  inboxTemplateUpdate,
  inboxTemplateVo,
  type InboxTemplateTestBody,
  inboxTemplateTestBody,
  templateTestVo,
  pageVo,
} from '@qiwu/shared'
import { ActionLog } from '../../../../core/audit/action-log.js'
import { RequirePerm } from '../../../../core/auth/decorators.js'
import { Idempotent } from '../../../../core/guard/idempotent.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import { clsGet } from '../../../../core/context/cls.js'
import { InboxChannel } from '../inbox/inbox.channel.js'
import type { InboxTemplate } from './inbox-template.entity.js'
import { InboxTemplateService } from './inbox-template.service.js'

@ApiTags('messaging')
@Controller('messaging/inbox-templates')
export class InboxTemplateController {
  constructor(
    private readonly inboxTemplates: InboxTemplateService,
    private readonly inboxChannel: InboxChannel,
  ) {}

  @Get()
  @RequirePerm(inboxTemplatePerms.browse)
  @ApiOperation({ summary: 'Page of inbox templates' })
  @ApiEnvelope(pageVo(inboxTemplateVo))
  page(@Query({ schema: inboxTemplateQuery }) query: InboxTemplateQuery) {
    return this.inboxTemplates.page({
      ...query,
      sort: query.sort ?? [
        { field: 'code', order: 'ASC' },
        { field: 'locale', order: 'ASC' },
      ],
    })
  }

  @Get(':id')
  @RequirePerm(inboxTemplatePerms.view)
  @ApiOperation({ summary: 'One inbox template' })
  @ApiEnvelope(inboxTemplateVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.inboxTemplates.get(id)
  }

  @Post(':id/test')
  @HttpCode(200)
  @RequirePerm(inboxTemplatePerms.modify)
  @ActionLog({ domain: 'messaging.inboxTemplate', verb: 'test' })
  @ApiOperation({ summary: 'Send this stored template to the caller only' })
  @ApiEnvelope(templateTestVo)
  async test(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: inboxTemplateTestBody }) { params }: InboxTemplateTestBody,
  ) {
    const row = await this.inboxTemplates.get(id)
    return this.inboxChannel.testSend(row, clsGet('principal')!.userId, params)
  }

  @Post()
  @RequirePerm(inboxTemplatePerms.create)
  @Idempotent()
  @ActionLog({
    domain: 'messaging.inboxTemplate',
    verb: 'create',
    bizId: (_req, row) => (row as InboxTemplate | undefined)?.id,
  })
  @ApiOperation({ summary: 'Add an inbox template' })
  @ApiEnvelope(inboxTemplateVo, 201)
  create(@Body({ schema: inboxTemplateCreate }) dto: InboxTemplateCreate) {
    return this.inboxTemplates.create(dto)
  }

  @Put(':id')
  @RequirePerm(inboxTemplatePerms.modify)
  @ActionLog({ domain: 'messaging.inboxTemplate', verb: 'modify' })
  @ApiOperation({ summary: 'Change an inbox template' })
  @ApiEnvelope()
  update(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: inboxTemplateUpdate }) dto: InboxTemplateUpdate,
  ) {
    return this.inboxTemplates.update(id, dto)
  }

  @Put(':id/enabled')
  @RequirePerm(inboxTemplatePerms.modify)
  @ActionLog({ domain: 'messaging.inboxTemplate', verb: 'modify' })
  @ApiOperation({ summary: 'Enable or disable an inbox template' })
  @ApiEnvelope()
  setEnabled(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: enabledBody }) dto: EnabledBody,
  ) {
    return this.inboxTemplates.update(id, dto)
  }

  @Delete(':id')
  @RequirePerm(inboxTemplatePerms.remove)
  @ActionLog({ domain: 'messaging.inboxTemplate', verb: 'remove' })
  @ApiOperation({ summary: 'Delete an inbox template' })
  @ApiEnvelope()
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.inboxTemplates.remove([id])
  }

  @Post('batch-delete')
  @HttpCode(200)
  @RequirePerm(inboxTemplatePerms.remove)
  @ActionLog({ domain: 'messaging.inboxTemplate', verb: 'remove' })
  @ApiOperation({ summary: 'Delete inbox templates: all or none' })
  @ApiEnvelope()
  batchRemove(@Body({ schema: idsBody }) { ids }: IdsBody) {
    return this.inboxTemplates.remove(ids)
  }
}
