// @generated by qw-codegen (crud)
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  ParseIntPipe,
  Post,
  Put,
  Query,
} from '@nestjs/common'
import { ApiOperation, ApiProduces, ApiTags } from '@nestjs/swagger'
import {
  type EnabledBody,
  enabledBody,
  type IdsBody,
  idsBody,
  pageVo,
  type PositionCreate,
  positionCreate,
  positionOptionVo,
  positionPerms,
  type PositionQuery,
  positionQuery,
  type PositionUpdate,
  positionUpdate,
  positionVo,
} from '@qiwu/shared'
import { z } from 'zod'
import { ActionLog } from '../../../../core/audit/action-log.js'
import { RequirePerm } from '../../../../core/auth/decorators.js'
import { ExcelService, XLSX_TYPE } from '../../../../core/excel/excel.service.js'
import { Idempotent } from '../../../../core/guard/idempotent.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import type { Position } from './position.entity.js'
import { positionColumns, PositionService } from './position.service.js'

@ApiTags('iam')
@Controller('iam/positions')
export class PositionController {
  constructor(
    private readonly positions: PositionService,
    private readonly excel: ExcelService,
  ) {}

  @Get()
  @RequirePerm(positionPerms.browse)
  @ApiOperation({ summary: 'Page of positions' })
  @ApiEnvelope(pageVo(positionVo))
  page(@Query({ schema: positionQuery }) query: PositionQuery) {
    return this.positions.page(query)
  }

  /** The list's rows (same filters and sort, no paging) as .xlsx. */
  @Get('export')
  @RequirePerm(positionPerms.export)
  @ActionLog({ domain: 'iam.position', verb: 'export' })
  @ApiOperation({ summary: 'Export the filtered positions (.xlsx)' })
  @ApiProduces(XLSX_TYPE)
  export(@Query({ schema: positionQuery }) query: PositionQuery) {
    return this.excel.export('positions', positionColumns, this.positions.exportRows(query))
  }

  /** Any signed-in user: pickers in other modules list id + name only. */
  @Get('options')
  @ApiOperation({ summary: 'Enabled positions for pickers' })
  @ApiEnvelope(z.array(positionOptionVo))
  options() {
    return this.positions.options()
  }

  @Get(':id')
  @RequirePerm(positionPerms.view)
  @ApiOperation({ summary: 'One position' })
  @ApiEnvelope(positionVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.positions.get(id)
  }

  @Post()
  @RequirePerm(positionPerms.create)
  @Idempotent()
  @ActionLog({
    domain: 'iam.position',
    verb: 'create',
    bizId: (_req, row) => (row as Position | undefined)?.id,
  })
  @ApiOperation({ summary: 'Add a position' })
  @ApiEnvelope(positionVo, 201)
  create(@Body({ schema: positionCreate }) dto: PositionCreate) {
    return this.positions.create(dto)
  }

  @Put(':id')
  @RequirePerm(positionPerms.modify)
  @ActionLog({ domain: 'iam.position', verb: 'modify' })
  @ApiOperation({ summary: 'Change a position' })
  @ApiEnvelope()
  update(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: positionUpdate }) dto: PositionUpdate,
  ) {
    return this.positions.update(id, dto)
  }

  @Put(':id/enabled')
  @RequirePerm(positionPerms.modify)
  @ActionLog({ domain: 'iam.position', verb: 'modify' })
  @ApiOperation({ summary: 'Enable or disable a position' })
  @ApiEnvelope()
  setEnabled(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: enabledBody }) dto: EnabledBody,
  ) {
    return this.positions.update(id, dto)
  }

  @Delete(':id')
  @RequirePerm(positionPerms.remove)
  @ActionLog({ domain: 'iam.position', verb: 'remove' })
  @ApiOperation({ summary: 'Delete a position' })
  @ApiEnvelope()
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.positions.remove([id])
  }

  @Post('batch-delete')
  @HttpCode(200)
  @RequirePerm(positionPerms.remove)
  @ActionLog({ domain: 'iam.position', verb: 'remove' })
  @ApiOperation({ summary: 'Delete positions: all or none' })
  @ApiEnvelope()
  batchRemove(@Body({ schema: idsBody }) { ids }: IdsBody) {
    return this.positions.remove(ids)
  }
}
