// @generated by qw-codegen (crud)
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { PositionController } from './position.controller.js'
import { Position } from './position.entity.js'
import { PositionService } from './position.service.js'

@Module({
  imports: [TypeOrmModule.forFeature([Position])],
  controllers: [PositionController],
  providers: [PositionService],
})
export class PositionModule {}
