// @generated by qw-codegen (crud)
import { Column, Entity } from 'typeorm'
import { BaseEntity } from '../../../../core/db/base.entity.js'
import { referencedBy } from '../../../../core/db/references.js'

// other tables' rows holding these ids, checked on delete (no foreign keys: core/db/references.ts)
// 用户岗位
referencedBy('iam_position', { table: 'iam_user_positions', column: 'position_id' })

/** `iam_position`: 岗位 */
@Entity('iam_position')
export class Position extends BaseEntity {
  /** 岗位编码 */
  @Column({ length: 64 })
  code: string

  /** 岗位名称（种子为 seed.* 键） */
  @Column({ length: 64 })
  name: string

  /** 排序号 */
  @Column({ name: 'sort_no', type: 'int', default: 0 })
  sortNo: number

  /** 是否启用 */
  @Column({ type: 'boolean', default: true })
  enabled: boolean

  /** 备注 */
  @Column({ type: 'varchar', length: 500, nullable: true })
  note: string | null
}
