<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import type { SigninLogVo } from '@qiwu/shared'
import { signinLogApi } from '@/api/platform/audit/signin-log'
import DictTag from '@/core/components/DictTag.vue'
import { clientName } from '@/core/i18n'

/** One signin log in the list's detail drawer (GET /:id). */
defineOptions({ name: 'AuditSigninLogDetail' })
const { id } = defineProps<{ id: number }>()
const { t } = useI18n()

const row = shallowRef<SigninLogVo>()
const loading = ref(true)
// failures are toasted by the request layer (404 out of scope included)
signinLogApi
  .get(id)
  .then((r) => (row.value = r))
  .catch(() => undefined)
  .finally(() => (loading.value = false))
const time = (iso: string | null) => (iso ? dayjs(iso).format('YYYY-MM-DD HH:mm') : '')
</script>

<template>
  <div v-loading="loading" class="qw-detail">
    <el-descriptions v-if="row" :column="1" border>
      <el-descriptions-item :label="t('field.audit.signinLog.traceId')">
        {{ row.traceId }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.kind')">
        <DictTag code="audit.signin_kind" :value="row.kind" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.userId')">
        {{ row.userId }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.userType')">
        <DictTag code="audit.user_type" :value="row.userType" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.username')">
        {{ row.username }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.clientId')">
        {{ clientName(row.clientId) }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.ip')">
        {{ row.ip }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.location')">
        {{ row.location }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.browser')">
        {{ row.browser }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.os')">
        {{ row.os }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.ok')">
        <DictTag code="core.yes_no" :value="row.ok" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.signinLog.msg')">
        {{ row.msg }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.common.createdAt')">
        {{ time(row.createdAt) }}
      </el-descriptions-item>
    </el-descriptions>
  </div>
</template>
