<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import type { RunVo } from '@qiwu/shared'
import { runApi } from '@/api/platform/scheduler/run'
import DictTag from '@/core/components/DictTag.vue'
import { tx } from '@/core/i18n'

/** One run in the list's detail drawer (GET /:id). */
defineOptions({ name: 'SchedulerRunDetail' })
const { id } = defineProps<{ id: number }>()
const { t } = useI18n()

const row = shallowRef<RunVo>()
const loading = ref(true)
// failures are toasted by the request layer (404 out of scope included)
runApi
  .get(id)
  .then((r) => (row.value = r))
  .catch(() => undefined)
  .finally(() => (loading.value = false))
const time = (iso: string | null) => (iso ? dayjs(iso).format('YYYY-MM-DD HH:mm') : '')
</script>

<template>
  <div v-loading="loading" class="qw-detail">
    <el-descriptions v-if="row" :column="1" border>
      <el-descriptions-item :label="t('field.scheduler.run.taskId')">
        {{ row.taskId }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.taskName')">
        {{ tx(row.taskName) }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.handler')">
        {{ row.handler }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.attempt')">
        {{ row.attempt }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.outcome')">
        <DictTag code="scheduler.run_outcome" :value="row.outcome" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.output')">
        <span class="qw-detail__text">{{ row.output }}</span>
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.error')">
        <span class="qw-detail__text">{{ row.error }}</span>
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.startedAt')">
        {{ time(row.startedAt) }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.endedAt')">
        {{ time(row.endedAt) }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.scheduler.run.costMs')">
        {{ row.costMs }}
      </el-descriptions-item>
    </el-descriptions>
  </div>
</template>
