// @generated by qw-codegen (crud)
// audit.httpTrace (generated CRUD; see docs/design-notes.md#codegen, #api-envelope), read-only: list filters/sort/paging, get, export,
// no write routes; 403 per permission, 400, 404 unknown ids, @ActionLog export rows, Swagger. Rows go straight into the
// table. Only the standard cases: module-specific ones go into a hand-written
// audit-http-trace-extra.e2e-spec.ts.
import type { NestExpressApplication } from '@nestjs/platform-express'
import { Test } from '@nestjs/testing'
import { getDataSourceToken } from '@nestjs/typeorm'
import { Err, httpTracePerms } from '@qiwu/shared'
import ExcelJS from 'exceljs'
import { I18nService } from 'nestjs-i18n'
import request from 'supertest'
import type { DataSource } from 'typeorm'
import { AppModule } from '../../src/app.module.js'
import { setupApp } from '../../src/app.setup.js'
import { REDIS, type Redis } from '../../src/core/redis/redis.module.js'
import { findId, insertRow } from '../../src/db/seeds/upsert.js'
import { HttpTrace } from '../../src/modules/platform/audit/http-trace/http-trace.entity.js'
import { logOf } from '../setup/audit.js'
import { bearer, signIn } from '../setup/auth.js'
import { cleanRedis } from '../setup/redis.js'

const PREFIX = 'e2e-http-trace-'
const URL = '/api/audit/http-traces'
const MISSING = 999_999
/** export column labels, in order */
const HEADERS = [
  'field.audit.httpTrace.username',
  'field.audit.httpTrace.method',
  'field.audit.httpTrace.statusCode',
  'field.audit.httpTrace.bizCode',
  'field.audit.httpTrace.ip',
  'field.audit.httpTrace.startedAt',
  'field.audit.httpTrace.costMs',
  'field.audit.httpTrace.url',
]

let app: NestExpressApplication
let ds: DataSource
let redis: Redis
let i18n: I18nService
const tokens: Record<'admin' | 'reader' | 'plain', string> = { admin: '', reader: '', plain: '' }
const userIds: number[] = []
let roleId: number
/** the table's last id before this spec: every row above it is this spec's (cleanup) */
let lastId = 0

const call = (
  who: keyof typeof tokens,
  method: 'get' | 'post' | 'put' | 'delete',
  path = '',
  body?: object,
) => {
  const req = request(app.getHttpServer())[method](`${URL}${path}`).set(bearer(tokens[who]))
  return body ? req.send(body) : req
}
/** A row added straight to the table (the module takes no writes), as GET answers it. */
async function add(body: object) {
  const repo = ds.getRepository(HttpTrace)
  const { id } = await repo.save(repo.create(body))
  return (await call('admin', 'get', `/${id}`).expect(200)).body.data
}
let seq = 0
const unique = () => `${PREFIX}${++seq}`
/** A valid POST body made of `tag` (required and unique fields, the configured examples). */
const body = (tag: string, over: object = {}) => ({
  url: tag,
  method: tag.slice(-10),
  statusCode: 1,
  bizCode: tag.slice(-16),
  costMs: 1,
  ...over,
})
/** A translated message (the app's own translations). */
const t = (lang: string, key: string, args?: object) => i18n.t(key, { lang, args }) as string
/** Live rows of the table (a list's total without filters). */
const count = async () =>
  Number((await ds.query('SELECT COUNT(*) AS n FROM aud_http_trace WHERE deleted_at IS NULL'))[0].n)
const idsOf = (res: request.Response) => res.body.data.items.map((r: { id: number }) => r.id)

async function user(name: string, roles: number[]) {
  const id = await insertRow(ds.manager, 'iam_user', {
    username: PREFIX + name,
    display_name: name,
    password_hash: 'not-used-by-this-spec',
    password_changed_at: new Date(),
  })
  for (const r of roles)
    await ds.query('INSERT INTO iam_user_roles (user_id, role_id) VALUES (?, ?)', [id, r])
  userIds.push(id)
  return (await signIn(app, PREFIX + name)).accessToken
}

beforeAll(async () => {
  const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile()
  app = setupApp(moduleRef.createNestApplication<NestExpressApplication>({ logger: false }))
  await app.listen(0, '127.0.0.1')
  ds = app.get<DataSource>(getDataSourceToken())
  redis = app.get(REDIS)
  i18n = app.get(I18nService)
  await cleanRedis(redis)
  lastId = Number((await ds.query('SELECT COALESCE(MAX(id), 0) AS n FROM aud_http_trace'))[0].n)
  roleId = await insertRow(ds.manager, 'iam_role', {
    code: `${PREFIX}reader`,
    name: `${PREFIX}reader`,
    data_scope: 'all',
  })
  const browse = await findId(ds.manager, 'iam_menu', { perms: httpTracePerms.browse })
  await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [roleId, browse])
  tokens.admin = (await signIn(app)).accessToken
  tokens.reader = await user('reader', [roleId])
  tokens.plain = await user('plain', [])
})

afterAll(async () => {
  if (ds) {
    await ds.query('DELETE FROM aud_http_trace WHERE id > ?', [lastId])
    if (userIds.length) {
      await ds.query('DELETE FROM iam_user_roles WHERE user_id IN (?)', [userIds])
      await ds.query('DELETE FROM iam_user WHERE id IN (?)', [userIds])
    }
    await ds.query('DELETE FROM iam_role_menus WHERE role_id = ?', [roleId])
    await ds.query('DELETE FROM iam_role WHERE id = ?', [roleId])
  }
  if (redis) await cleanRedis(redis)
  await app?.close()
})

describe('CRUD', () => {
  it('get: a row by id, as the list shows it', async () => {
    const row = await add(body(unique()))
    const res = await call('admin', 'get').query({ sort: '-id', pageSize: 1 }).expect(200)
    expect(res.body.data.items).toEqual([row])
  })

  it('list: newest first by the sort whitelist, all live rows counted, paging', async () => {
    const ids: number[] = []
    for (let i = 0; i < 3; i++) ids.push((await add(body(unique()))).id)
    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const res = await list({ sort: '-id', pageSize: 3 })
    expect(idsOf(res)).toEqual([...ids].reverse())
    expect(res.body.data.total).toBe(await count())
    expect(idsOf(await list({ sort: '-id', page: 2, pageSize: 2 }))[0]).toBe(ids[0])
  })

  it('list: text filters contain (LIKE wildcards literal)', async () => {
    const tag = unique()
    for (const suffix of ['a', 'b', 'c']) await add(body(`${tag}-${suffix}`))
    await add(body(`${tag}_x`))

    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const keys = (res: request.Response) => res.body.data.items.map((r: { url: string }) => r.url)
    const res = await list({ url: `${tag}-`, sort: '-id' })
    expect(keys(res)).toEqual([`${tag}-c`, `${tag}-b`, `${tag}-a`])
    expect(res.body.data.total).toBe(3)
    // `%` and `_` in the filter are plain characters
    expect(keys(await list({ url: `${tag}_` }))).toEqual([`${tag}_x`])
    const page2 = await list({ url: `${tag}-`, sort: 'id', page: 2, pageSize: 2 })
    expect(keys(page2)).toEqual([`${tag}-c`])
    expect(page2.body.data.total).toBe(3)
  })
})

describe('errors', () => {
  it('403 per permission: browse-only may list, not view; no perm → no list', async () => {
    const { id } = await add(body(unique()))
    await call('reader', 'get').expect(200)
    const forbidden = [call('reader', 'get', `/${id}`), call('plain', 'get')]
    for (const res of await Promise.all(forbidden)) {
      expect(res.status).toBe(403)
      expect(res.body.code).toBe(Err.FORBIDDEN.code)
    }
  })

  it('400: invalid query / id', async () => {
    await call('admin', 'get').query({ sort: 'url' }).expect(400)
    await call('admin', 'get', '/abc').expect(400)
  })

  it('404: an unknown id; no write routes (POST / PUT / DELETE → 404, nothing written)', async () => {
    const row = await add(body(unique()))
    for (const res of [
      await call('admin', 'get', `/${MISSING}`),
      await call('admin', 'post', '', body(unique())),
      await call('admin', 'put', `/${row.id}`, {}),
      await call('admin', 'delete', `/${row.id}`),
      await call('admin', 'post', '/batch-delete', { ids: [row.id] }),
    ])
      expect(res.status).toBe(404)
    expect((await call('admin', 'get', `/${row.id}`).expect(200)).body.data).toEqual(row)
  })
})

/** A binary (xlsx) response body as a Buffer. */
const binary = (r: request.Response, cb: (err: Error | null, body: Buffer) => void) => {
  const chunks: Buffer[] = []
  r.on('data', (c: Buffer) => chunks.push(c))
  r.on('end', () => cb(null, Buffer.concat(chunks)))
}
/** The first sheet of an xlsx body (or none). */
async function sheet(body: unknown) {
  const wb = new ExcelJS.Workbook()
  await wb.xlsx.load(body as Parameters<typeof wb.xlsx.load>[0])
  return wb.worksheets[0]
}
const cells = (ws: ExcelJS.Worksheet, row: number, length: number) =>
  Array.from({ length }, (_, i) => ws.getRow(row).getCell(i + 1).value ?? null)

describe('export', () => {
  /** GET /export as the parsed first sheet, with the response. */
  async function exported(who: keyof typeof tokens, query: object, headers: object = {}) {
    const res = await call(who, 'get', '/export')
      .query(query)
      .set(headers as Record<string, string>)
      .buffer(true)
      .parse(binary)
    return { res, ws: res.status === 200 ? await sheet(res.body) : undefined }
  }
  const row = (ws: ExcelJS.Worksheet, n: number) => cells(ws, n, HEADERS.length)

  it('export: every row (no paging) in list order as .xlsx, headers translated', async () => {
    const tag = unique()
    await add(body(`${tag}-a`))
    await add(body(`${tag}-b`))
    // counted before: an export of the action log adds its own row right after
    const rows = await count()
    const { res, ws } = await exported('admin', { sort: '-id', pageSize: 1 })
    expect(res.status).toBe(200)
    expect(res.headers['content-type']).toContain('spreadsheetml.sheet')
    expect(res.headers['content-disposition']).toBe('attachment; filename="httpTraces.xlsx"')
    expect(row(ws!, 1)).toEqual(HEADERS.map((k) => t('zh-CN', k)))
    // all live rows, newest first
    expect(ws!.actualRowCount).toBe(rows + 1)
    expect(row(ws!, 2)[7]).toBe(`${tag}-b`)
    expect(row(ws!, 3)[7]).toBe(`${tag}-a`)
  })

  it('export: English headers for an en-US request', async () => {
    await add(body(unique()))
    const { ws } = await exported('admin', { sort: '-id' }, { 'Accept-Language': 'en-US' })
    expect(row(ws!, 1)).toEqual(HEADERS.map((k) => t('en-US', k)))
  })

  it('export: 403 without audit.httpTrace.export, 400 for a bad query, action-logged', async () => {
    expect((await exported('reader', {})).res.status).toBe(403)
    expect((await exported('admin', { sort: 'url' })).res.status).toBe(400)
    const traceId = `${PREFIX}${process.pid}-export`
    await exported('admin', { url: unique() }, { 'X-Request-Id': traceId })
    expect(await logOf(ds, traceId)).toMatchObject({
      domain: 'audit.httpTrace',
      verb: 'export',
      ok: 1,
    })
  })
})

it('Swagger documents every route', async () => {
  const doc = (await request(app.getHttpServer()).get('/api/docs-json').expect(200)).body
  expect(
    Object.keys(doc.paths)
      .filter((p) => p.startsWith(URL))
      .sort(),
  ).toEqual([URL, `${URL}/export`, `${URL}/{id}`])
  expect(
    doc.paths[URL].get.responses['200'].content['application/json'].schema.properties.data,
  ).toMatchObject({ properties: { items: { type: 'array' }, total: { type: 'integer' } } })
})
