// @generated by qw-codegen (tree)
// iam.menu (generated tree, docs/codegen-golden.md "Tree"; see docs/design-notes.md#codegen, #api-envelope): the list as a filtered
// forest, create under an enabled parent (tree_path = the parent's + own id), a move rewriting the whole
// subtree's paths (never below itself), enable with the ancestors / no disable over an enabled child,
// no delete with children; 403 per permission, 400 translated, 404 unknown ids, @Idempotent, @ActionLog
// rows, Swagger. Hand-written on top (menus are a G module): `form` — the fields and parents each kind
// takes, link types, name_i18n, formats, perms a non-root editor may write; `rules` —
// unique sibling paths and route names, no delete with children or grants, PUT /sort, sessions reloaded
// (bumpAll) by every menu write, so a disabled menu's holders get 403 at their next request and signed-in
// browsers reload their routes.
import type { NestExpressApplication } from '@nestjs/platform-express'
import { Test } from '@nestjs/testing'
import { getDataSourceToken } from '@nestjs/typeorm'
import { Err, type MenuRowNode as MenuNode, menuPerms } from '@qiwu/shared'
import { I18nService } from 'nestjs-i18n'
import request from 'supertest'
import type { DataSource } from 'typeorm'
import { AppModule } from '../../src/app.module.js'
import { setupApp } from '../../src/app.setup.js'
import { redisKey } from '../../src/core/redis/cache-namespaces.js'
import { REDIS, type Redis } from '../../src/core/redis/redis.module.js'
import { findId, insertRow } from '../../src/db/seeds/upsert.js'
import { logOf } from '../setup/audit.js'
import { bearer, signIn } from '../setup/auth.js'
import { cleanRedis } from '../setup/redis.js'

const PREFIX = 'e2e-menu-'
const URL = '/api/iam/menus'
const MISSING = 999_999
/** the form's fields, as the edit form sends them back */
const FORM = [
  'parentId',
  'kind',
  'name',
  'routePath',
  'component',
  'componentName',
  'routeName',
  'routeQuery',
  'linkType',
  'linkUrl',
  'perms',
  'icon',
  'sortNo',
  'visible',
  'keepAlive',
  'alwaysShow',
  'enabled',
]

let app: NestExpressApplication
let ds: DataSource
let redis: Redis
let i18n: I18nService
const tokens: Record<'admin' | 'reader' | 'plain' | 'editor', string> = {
  admin: '',
  reader: '',
  plain: '',
  editor: '',
}
const userIds: number[] = []
let roleId: number
let editorRoleId: number
/** the table's last id before this spec: every row above it is this spec's (cleanup) */
let lastId = 0

const call = (
  who: keyof typeof tokens,
  method: 'get' | 'post' | 'put' | 'delete',
  path = '',
  body?: object,
) => {
  const req = request(app.getHttpServer())[method](`${URL}${path}`).set(bearer(tokens[who]))
  return body ? req.send(body) : req
}
const create = (body: object) => call('admin', 'post', '', body)
let seq = 0
const unique = () => `${PREFIX}${++seq}`
/** A valid POST body made of `tag`: a group (its path and a unique route name), top level. */
const body = (tag: string, over: object = {}) => ({
  kind: 'group',
  name: `${tag} name`,
  routePath: `/${tag}`,
  routeName: tag,
  ...over,
})
/** A row added through the API under `parent` (0 = top level), as POST answers it. */
const add = async (parent: number, over: object = {}, tag = unique()) =>
  (await create(body(tag, { parentId: parent, ...over })).expect(201)).body.data
/** The forest GET / answers for `query`. */
const list = async (query: object = {}): Promise<MenuNode[]> =>
  (await call('admin', 'get').query(query).expect(200)).body.data
/** The node `id` anywhere in `nodes`. */
const find = (nodes: MenuNode[], id: number): MenuNode | undefined => {
  for (const n of nodes) {
    const hit = n.id === id ? n : find(n.children, id)
    if (hit) return hit
  }
}
/** Id tree of nodes: `id` or `[id, children]`. */
type Shape = number | [number, Shape[]]
const shape = (nodes: MenuNode[]): Shape[] =>
  nodes.map((n) => (n.children.length ? [n.id, shape(n.children)] : n.id))
const pathOf = async (id: number): Promise<string> =>
  (await ds.query('SELECT tree_path AS p FROM iam_menu WHERE id = ?', [id]))[0].p
/** Synthetic ASCII ancestor ids, ending in the real id, for exact column-length fixtures. */
const setPathLength = async (id: number, length: number): Promise<string> => {
  const prefix = `/${MISSING}/`
  const padding = length - prefix.length - `${id}/`.length
  const odd = padding % 2
  const path = `${prefix}${'1/'.repeat((padding - odd * 3) / 2)}${odd ? '11/' : ''}${id}/`
  expect(path).toHaveLength(length)
  await ds.query('UPDATE iam_menu SET tree_path = ? WHERE id = ?', [path, id])
  return path
}
/** A translated message (the app's own translations). */
const t = (lang: string, key: string, args?: object) => i18n.t(key, { lang, args }) as string
const label = (lang: string, field: string) => t(lang, `field.iam.menu.${field}`)
const expectErr = (res: request.Response, status: number, code: string) => {
  expect(res.status).toBe(status)
  expect(res.body.code).toBe(code)
}
/** The fields a 400 names. */
const paths = (res: request.Response) => res.body.errors.map((e: { path: string }) => e.path)
/** A permission code no seeded menu holds. */
const perm = () => `e2e.menu-${++seq}.run`
/** A page (a view route) body under `parent`. */
const page = (parent: number, over: object = {}) =>
  body(unique(), { kind: 'page', component: 'home/index', parentId: parent, ...over })
/** An action body under `parent`. */
const action = (parent: number, over: object = {}) => ({
  kind: 'action',
  name: `${unique()} action`,
  perms: perm(),
  parentId: parent,
  ...over,
})

async function user(name: string, roles: number[]) {
  const id = await insertRow(ds.manager, 'iam_user', {
    username: PREFIX + name,
    display_name: name,
    password_hash: 'not-used-by-this-spec',
    password_changed_at: new Date(),
  })
  for (const r of roles)
    await ds.query('INSERT INTO iam_user_roles (user_id, role_id) VALUES (?, ?)', [id, r])
  userIds.push(id)
  return (await signIn(app, PREFIX + name)).accessToken
}

beforeAll(async () => {
  const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile()
  app = setupApp(moduleRef.createNestApplication<NestExpressApplication>({ logger: false }))
  await app.listen(0, '127.0.0.1')
  ds = app.get<DataSource>(getDataSourceToken())
  redis = app.get(REDIS)
  i18n = app.get(I18nService)
  await cleanRedis(redis)
  lastId = Number((await ds.query('SELECT COALESCE(MAX(id), 0) AS n FROM iam_menu'))[0].n)
  roleId = await insertRow(ds.manager, 'iam_role', {
    code: `${PREFIX}reader`,
    name: `${PREFIX}reader`,
    data_scope: 'all',
  })
  const browse = await findId(ds.manager, 'iam_menu', { perms: menuPerms.browse })
  await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [roleId, browse])
  // a non-root menu editor: every menu perm but remove
  editorRoleId = await insertRow(ds.manager, 'iam_role', {
    code: `${PREFIX}editor`,
    name: `${PREFIX}editor`,
    data_scope: 'all',
  })
  for (const perms of [menuPerms.browse, menuPerms.view, menuPerms.create, menuPerms.modify])
    await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [
      editorRoleId,
      await findId(ds.manager, 'iam_menu', { perms }),
    ])
  tokens.admin = (await signIn(app)).accessToken
  tokens.reader = await user('reader', [roleId])
  tokens.plain = await user('plain', [])
  tokens.editor = await user('editor', [editorRoleId])
})

afterAll(async () => {
  if (ds) {
    await ds.query('DELETE FROM iam_menu WHERE id > ?', [lastId])
    if (userIds.length) {
      await ds.query('DELETE FROM iam_user_roles WHERE user_id IN (?)', [userIds])
      await ds.query('DELETE FROM iam_user WHERE id IN (?)', [userIds])
    }
    await ds.query('DELETE FROM iam_role_menus WHERE role_id IN (?)', [[roleId, editorRoleId]])
    await ds.query('DELETE FROM iam_role WHERE id IN (?)', [[roleId, editorRoleId]])
  }
  if (redis) await cleanRedis(redis)
  await app?.close()
})

describe('tree', () => {
  it.each([false, true])(
    'path length: create and a move overflowing only a descendant (deleted=%s) return 422 without writes',
    async (deleted) => {
      const a = await add(0)
      const b = await add(a.id)
      const x = await add(0)
      if (deleted) await call('admin', 'delete', `/${b.id}`).expect(200)
      await setPathLength(x.id, 512)
      const tag = unique()
      const created = await create(body(tag, { parentId: x.id })).set('Accept-Language', 'en-US')
      expectErr(created, 422, Err.TREE_PATH_TOO_LONG.code)
      expect(created.body.msg).toBe(t('en-US', Err.TREE_PATH_TOO_LONG.key))
      expect(await ds.query('SELECT id FROM iam_menu WHERE parent_id = ?', [x.id])).toEqual([])
      await ds.query('UPDATE iam_menu SET updated_by = NULL WHERE id IN (?)', [[a.id, b.id]])
      const rows = () =>
        ds.query(
          'SELECT parent_id, tree_path, updated_by, updated_at, deleted_at FROM iam_menu WHERE id IN (?) ORDER BY id',
          [[a.id, b.id]],
        )
      const before = await rows()
      const suffix = `${a.id}/${b.id}/`
      const tooDeep = await setPathLength(x.id, 513 - suffix.length)
      expect(`${tooDeep}${a.id}/`.length).toBeLessThan(512)
      const moved = await call('admin', 'put', `/${a.id}`, { parentId: x.id })
      expectErr(moved, 422, Err.TREE_PATH_TOO_LONG.code)
      expect(moved.body.msg).toBe(t('zh-CN', Err.TREE_PATH_TOO_LONG.key))
      expect(await rows()).toEqual(before)
      const boundary = await setPathLength(x.id, 512 - suffix.length)
      await call('admin', 'put', `/${a.id}`, { parentId: x.id }).expect(200)
      expect(await pathOf(a.id)).toBe(`${boundary}${a.id}/`)
      expect(await pathOf(b.id)).toBe(`${boundary}${suffix}`)
      expect(await pathOf(b.id)).toHaveLength(512)
      expect((await rows())[1].deleted_at !== null).toBe(deleted)
    },
  )

  it('create → 201 with the row: tree_path = own id at the top level, the parent path + own id below; get returns it; a PUT of the loaded row changes nothing', async () => {
    const tag = unique()
    const top = (await create(body(tag)).expect(201)).body.data
    expect(top).toMatchObject({
      id: expect.any(Number),
      ...body(tag),
      parentId: 0,
      treePath: `/${top.id}/`,
      nameI18n: null,
      component: null,
      componentName: null,
      routeQuery: null,
      linkType: 'route',
      linkUrl: null,
      perms: null,
      icon: null,
      sortNo: 0,
      visible: true,
      keepAlive: false,
      alwaysShow: false,
      enabled: true,
      createdBy: expect.any(Number),
    })
    expect(new Date(top.createdAt).toISOString()).toBe(top.createdAt)
    expect((await call('admin', 'get', `/${top.id}`).expect(200)).body.data).toEqual(top)
    const child = await add(top.id)
    expect(child).toMatchObject({ parentId: top.id, treePath: `${top.treePath}${child.id}/` })
    const loaded = Object.fromEntries(FORM.map((f) => [f, child[f]]))
    await call('admin', 'put', `/${child.id}`, loaded).expect(200)
    expect((await call('admin', 'get', `/${child.id}`).expect(200)).body.data).toMatchObject({
      ...loaded,
      treePath: child.treePath,
    })
  })

  it('list: the whole forest, children under their parent by sortNo, id; top-level rows are the roots', async () => {
    const a = await add(0)
    const b = await add(a.id, { sortNo: 2 })
    const c = await add(a.id, { sortNo: 1 })
    const d = await add(b.id)
    expect(shape([find(await list(), a.id)!])).toEqual([[a.id, [c.id, [b.id, [d.id]]]]])
    const all = await list()
    expect(all.map((n) => n.id)).toContain(a.id)
    expect(all.every((n) => n.parentId === 0)).toBe(true)
  })

  it('list filters: enabled equals; a match whose parent does not match is a root', async () => {
    const on = await add(0)
    const off = await add(on.id, { enabled: false })
    const disabled = await list({ enabled: false })
    expect(disabled.map((n) => n.id)).toContain(off.id)
    expect(disabled.every((n) => !n.enabled && !n.children.length)).toBe(true)
    expect(find(await list({ enabled: true }), off.id)).toBeUndefined()
  })

  it('parent: a disabled one → 422, an unknown one → 404 (create and move), nothing written', async () => {
    const off = await add(0, { enabled: false })
    expectErr(
      await create(body(unique(), { parentId: off.id })),
      422,
      Err.TREE_PARENT_DISABLED.code,
    )
    expectErr(await create(body(unique(), { parentId: MISSING })), 404, Err.NOT_FOUND.code)
    const a = await add(0)
    expectErr(
      await call('admin', 'put', `/${a.id}`, { parentId: MISSING }),
      404,
      Err.NOT_FOUND.code,
    )
    expectErr(
      await call('admin', 'put', `/${a.id}`, { parentId: off.id }),
      422,
      Err.TREE_PARENT_DISABLED.code,
    )
    expect(await pathOf(a.id)).toBe(`/${a.id}/`)
  })

  it('move: one statement rewrites the paths of the whole subtree; never below itself (422); to the top level and back', async () => {
    const a = await add(0)
    const b = await add(a.id)
    const c = await add(b.id)
    const x = await add(0)
    await call('admin', 'put', `/${a.id}`, { parentId: x.id }).expect(200)
    expect((await call('admin', 'get', `/${a.id}`).expect(200)).body.data).toMatchObject({
      parentId: x.id,
      treePath: `${x.treePath}${a.id}/`,
    })
    expect(await pathOf(b.id)).toBe(`${x.treePath}${a.id}/${b.id}/`)
    expect(await pathOf(c.id)).toBe(`${x.treePath}${a.id}/${b.id}/${c.id}/`)
    expect(shape([find(await list(), x.id)!])).toEqual([[x.id, [[a.id, [[b.id, [c.id]]]]]]])
    for (const parent of [a.id, b.id, c.id]) {
      const res = await call('admin', 'put', `/${a.id}`, { parentId: parent })
      expectErr(res, 422, Err.TREE_PARENT_INVALID.code)
      expect(res.body.msg).toBe(t('zh-CN', Err.TREE_PARENT_INVALID.key))
    }
    expect(await pathOf(c.id)).toBe(`${x.treePath}${a.id}/${b.id}/${c.id}/`)
    await call('admin', 'put', `/${b.id}`, { parentId: 0 }).expect(200)
    expect(await pathOf(c.id)).toBe(`/${b.id}/${c.id}/`)
    await call('admin', 'put', `/${b.id}`, { parentId: a.id }).expect(200)
    expect(await pathOf(c.id)).toBe(`${x.treePath}${a.id}/${b.id}/${c.id}/`)
  })

  it('enabled: each row on its own (a disabled menu hides its subtree): disabling a parent keeps its children, enabling a child leaves its ancestors', async () => {
    const a = await add(0)
    const b = await add(a.id)
    const c = await add(b.id)
    await call('admin', 'put', `/${a.id}/enabled`, { enabled: false }).expect(200)
    await call('admin', 'put', `/${c.id}/enabled`, { enabled: false }).expect(200)
    await call('admin', 'put', `/${c.id}`, { enabled: true }).expect(200)
    const enabled = async (id: number) =>
      (await call('admin', 'get', `/${id}`).expect(200)).body.data.enabled
    expect([await enabled(a.id), await enabled(b.id), await enabled(c.id)]).toEqual([
      false,
      true,
      true,
    ])
  })

  it('delete: a row with children → 409 has_children; a leaf, then its parent (soft: the rows stay, marked deleted)', async () => {
    const a = await add(0)
    const b = await add(a.id)
    const res = await call('admin', 'delete', `/${a.id}`)
    expectErr(res, 409, Err.TREE_HAS_CHILDREN.code)
    expect(res.body.msg).toBe(t('zh-CN', Err.TREE_HAS_CHILDREN.key))
    await call('admin', 'delete', `/${b.id}`).expect(200)
    await call('admin', 'delete', `/${a.id}`).expect(200)
    await call('admin', 'get', `/${a.id}`).expect(404)
    expect(
      await ds.query('SELECT id FROM iam_menu WHERE id IN (?) AND deleted_at IS NULL', [
        [a.id, b.id],
      ]),
    ).toEqual([])
    expect(await ds.query('SELECT id FROM iam_menu WHERE id IN (?)', [[a.id, b.id]])).toHaveLength(
      2,
    )
  })
})

describe('form', () => {
  it('form: each kind keeps only its fields, the others are saved empty (group: path, icon; page: route, view; action: perms)', async () => {
    const other = {
      icon: 'lucide:folder',
      alwaysShow: true,
      keepAlive: true,
      perms: perm(),
      component: 'home/index',
      componentName: 'HomeView',
      linkUrl: 'https://example.com',
    }
    const g = (await create(body(unique(), other)).expect(201)).body.data
    expect(g).toMatchObject({
      kind: 'group',
      icon: 'lucide:folder',
      alwaysShow: true,
      perms: null,
      component: null,
      componentName: null,
      linkType: 'route',
      linkUrl: null,
      keepAlive: false,
    })
    const p = (await create(page(g.id, { ...other, routePath: 'reports' })).expect(201)).body.data
    expect(p).toMatchObject({
      kind: 'page',
      linkType: 'route',
      routePath: 'reports',
      component: 'home/index',
      componentName: 'HomeView',
      icon: 'lucide:folder',
      keepAlive: true,
      alwaysShow: false,
      perms: null,
      linkUrl: null,
    })
    const a = (
      await create(action(p.id, { ...other, routePath: '/x', routeName: 'x' })).expect(201)
    ).body.data
    expect(a).toMatchObject({
      kind: 'action',
      perms: other.perms,
      routePath: '',
      routeName: null,
      component: null,
      componentName: null,
      icon: null,
      keepAlive: false,
      alwaysShow: false,
      linkUrl: null,
    })
    expect(find(await list({ kind: 'action' }), a.id)).toMatchObject({ id: a.id, children: [] })
    expect(find(await list({ kind: 'group' }), a.id)).toBeUndefined()
  })

  it('form: required by kind → 400 on that field (group path; page path + view, or its link; action perms)', async () => {
    const g = await add(0)
    const p = await add(g.id, { kind: 'page', component: 'home/index' })
    for (const [b, field] of [
      [body(unique(), { routePath: '' }), 'routePath'],
      [page(g.id, { component: '' }), 'component'],
      [page(g.id, { routePath: '' }), 'routePath'],
      [page(g.id, { linkType: 'iframe' }), 'linkUrl'],
      [page(g.id, { linkType: 'external' }), 'linkUrl'],
      [action(p.id, { perms: '' }), 'perms'],
    ] as const) {
      const res = await create(b).expect(400)
      expect(paths(res)).toEqual([field])
      expect(res.body.errors[0].msg).toBe(
        t('zh-CN', 'validation.required', { field: label('zh-CN', field) }),
      )
    }
  })

  it('form: link types — an iframe page (path + http(s) or site link, keep-alive name), an external link (the link alone); other links → 400', async () => {
    const g = await add(0)
    const iframe = (
      await create(
        page(g.id, {
          linkType: 'iframe',
          linkUrl: 'https://example.com/docs',
          componentName: 'DocsFrame',
          keepAlive: true,
        }),
      ).expect(201)
    ).body.data
    expect(iframe).toMatchObject({
      linkType: 'iframe',
      linkUrl: 'https://example.com/docs',
      component: null,
      componentName: 'DocsFrame',
      keepAlive: true,
    })
    const ext = (
      await create(
        page(g.id, { linkType: 'external', linkUrl: 'http://example.com', keepAlive: true }),
      ).expect(201)
    ).body.data
    expect(ext).toMatchObject({
      linkType: 'external',
      linkUrl: 'http://example.com',
      routePath: '',
      component: null,
      componentName: null,
      keepAlive: false,
    })
    // a path on this site, like the seeded API docs page (/api/docs)
    const local = (
      await create(page(g.id, { linkType: 'iframe', linkUrl: '/api/docs' })).expect(201)
    ).body.data
    expect(local).toMatchObject({ linkType: 'iframe', linkUrl: '/api/docs' })
    for (const linkUrl of [
      'javascript:alert(1)',
      'ftp://example.com/a',
      'example.com',
      '//example.com/x',
      '/\\example.com',
      '/a b',
    ]) {
      const res = await create(page(g.id, { linkType: 'external', linkUrl })).expect(400)
      expect(paths(res)).toEqual(['linkUrl'])
    }
    expect(paths(await create(page(g.id, { linkType: 'popup' })).expect(400))).toEqual(['linkType'])
  })

  it('form: formats — perms <domain>.<resource>.<verb>, Lucide icons, view paths, route names → 400', async () => {
    const g = await add(0)
    const p = await add(g.id, { kind: 'page', component: 'home/index' })
    for (const [b, field] of [
      [action(p.id, { perms: 'iam:user:browse' }), 'perms'],
      [action(p.id, { perms: '*' }), 'perms'],
      [body(unique(), { icon: 'mdi:home' }), 'icon'],
      [page(g.id, { component: '../secret' }), 'component'],
      [body(unique(), { routeName: 'has space' }), 'routeName'],
      [body(unique(), { kind: 'link' }), 'kind'],
    ] as const)
      expect(paths(await create(b).expect(400))).toEqual([field])
  })

  it('form: name_i18n per locale — blanks left out, none at all → null, other locales → 400; /api/auth/menus hands it over', async () => {
    const a = (
      await create(body(unique(), { nameI18n: { 'zh-CN': ' 报表 ', 'en-US': 'Reports' } })).expect(
        201,
      )
    ).body.data
    expect(a.nameI18n).toEqual({ 'zh-CN': '报表', 'en-US': 'Reports' })
    const b = (
      await create(body(unique(), { nameI18n: { 'zh-CN': '', 'en-US': 'Only English' } })).expect(
        201,
      )
    ).body.data
    expect(b.nameI18n).toEqual({ 'en-US': 'Only English' })
    await call('admin', 'put', `/${b.id}`, { nameI18n: { 'zh-CN': ' ', 'en-US': '' } }).expect(200)
    expect((await call('admin', 'get', `/${b.id}`).expect(200)).body.data.nameI18n).toBeNull()
    expect(
      paths(await create(body(unique(), { nameI18n: { fr: 'Rapports' } })).expect(400)),
    ).toEqual(['nameI18n'])
    const tree = (
      await request(app.getHttpServer())
        .get('/api/auth/menus')
        .set(bearer(tokens.admin))
        .expect(200)
    ).body.data
    expect(tree.find((n: { id: number }) => n.id === a.id)).toMatchObject({
      name: a.name,
      nameI18n: { 'zh-CN': '报表', 'en-US': 'Reports' },
    })
  })

  it('form: the kind stays on edit; the row as a PUT leaves it must hold (a page switched to iframe without a link → 400)', async () => {
    const g = await add(0)
    const p = await add(g.id, { kind: 'page', component: 'home/index' })
    await call('admin', 'put', `/${p.id}`, { kind: 'action', perms: perm() }).expect(200)
    expect((await call('admin', 'get', `/${p.id}`).expect(200)).body.data).toMatchObject({
      kind: 'page',
      perms: null,
    })
    expect(
      paths(await call('admin', 'put', `/${p.id}`, { linkType: 'iframe' }).expect(400)),
    ).toEqual(['linkUrl'])
    await call('admin', 'put', `/${p.id}`, {
      linkType: 'iframe',
      linkUrl: 'https://example.com',
    }).expect(200)
    expect((await call('admin', 'get', `/${p.id}`).expect(200)).body.data).toMatchObject({
      linkType: 'iframe',
      linkUrl: 'https://example.com',
      component: null,
    })
  })

  it('form: parents by kind — actions only under pages, nothing under an action, no group under a page → 422 on create and move; sub-pages stay hidden', async () => {
    const g = await add(0)
    const p = await add(g.id, { kind: 'page', component: 'home/index' })
    const a = (await create(action(p.id)).expect(201)).body.data
    const g2 = await add(0)
    for (const res of [
      await create(action(g.id)),
      await create(action(0)),
      await create(page(a.id)),
      await create(body(unique(), { parentId: p.id })),
      await call('admin', 'put', `/${a.id}`, { parentId: g.id }),
      await call('admin', 'put', `/${g2.id}`, { parentId: p.id }),
    ]) {
      expectErr(res, 422, Err.IAM_MENU_PARENT_KIND.code)
      expect(res.body.msg).toBe(t('zh-CN', Err.IAM_MENU_PARENT_KIND.key))
    }
    expect(await pathOf(a.id)).toBe(`${p.treePath}${a.id}/`)
    expect(await pathOf(g2.id)).toBe(`/${g2.id}/`)
    // a page under a page is a hidden sub-page (the side menu shows pages as leaves); an action moves under it
    const sub = await add(p.id, { kind: 'page', component: 'home/index', visible: true })
    expect(sub.visible).toBe(false)
    await call('admin', 'put', `/${sub.id}`, { visible: true }).expect(200)
    expect((await call('admin', 'get', `/${sub.id}`).expect(200)).body.data.visible).toBe(false)
    await call('admin', 'put', `/${a.id}`, { parentId: sub.id }).expect(200)
    expect(await pathOf(a.id)).toBe(`${sub.treePath}${a.id}/`)
  })

  it('form: a non-root editor writes only perms it holds (403 grant_exceeds_own); perms sent back unchanged pass', async () => {
    const g = await add(0)
    const p = await add(g.id, { kind: 'page', component: 'home/index' })
    const post = (b: object) => call('editor', 'post', '', b)
    const denied = await post(action(p.id, { perms: 'iam.user.remove' }))
    expectErr(denied, 403, Err.IAM_GRANT_EXCEEDS_OWN.code)
    const held = (await post(action(p.id, { perms: menuPerms.view })).expect(201)).body.data
    const other = (await create(action(p.id, { perms: 'iam.user.remove' })).expect(201)).body.data
    await call('editor', 'put', `/${other.id}`, {
      name: 'renamed',
      perms: 'iam.user.remove',
    }).expect(200)
    expectErr(
      await call('editor', 'put', `/${held.id}`, { perms: 'iam.user.remove' }),
      403,
      Err.IAM_GRANT_EXCEEDS_OWN.code,
    )
    expect((await call('admin', 'get', `/${held.id}`).expect(200)).body.data.perms).toBe(
      menuPerms.view,
    )
  })
})

describe('rules', () => {
  const permVerAll = async () => Number((await redis.get(redisKey('authPermVer', 'all'))) ?? 0)

  it('rules: route paths are unique among siblings and at the top level (409); another parent or an empty path is fine', async () => {
    const path = `/${unique()}`
    const g = await add(0, { routePath: path })
    expectErr(await create(body(unique(), { routePath: path })), 409, Err.DUPLICATE.code)
    const p = (await create(page(g.id, { routePath: 'list' })).expect(201)).body.data
    expectErr(await create(page(g.id, { routePath: 'list' })), 409, Err.DUPLICATE.code)
    const other = await add(0)
    const q = (await create(page(other.id, { routePath: 'list' })).expect(201)).body.data
    // actions and external links have no path: never a clash
    for (let i = 0; i < 2; i++) {
      await create(action(p.id)).expect(201)
      await create(
        page(g.id, { linkType: 'external', linkUrl: `https://example.com/${i}` }),
      ).expect(201)
    }
    // moving onto a sibling's path is refused too, nothing moves
    expectErr(await call('admin', 'put', `/${q.id}`, { parentId: g.id }), 409, Err.DUPLICATE.code)
    expect(await pathOf(q.id)).toBe(`${other.treePath}${q.id}/`)
  })

  it('rules: route names are unique (409)', async () => {
    const tag = unique()
    await create(body(tag)).expect(201)
    expectErr(await create(body(unique(), { routeName: tag })), 409, Err.DUPLICATE.code)
  })

  it('rules: a group needs a route name in the generator format (400); a page keeps the wider one', async () => {
    for (const routeName of [undefined, null, '', 'Upper', 'under_score', '9lives'])
      expect(paths(await create(body(unique(), { routeName })).expect(400))).toEqual(['routeName'])
    const g = await add(0)
    await create(page(g.id, { routeName: `Page_${seq}` })).expect(201)
  })

  it('rules: a static route name of the web is no menu route name (400): a menu route would replace the page', async () => {
    for (const routeName of ['password-change', 'my-inbox', 'profile', 'not-found']) {
      const res = await create(body(unique(), { routeName })).expect(400)
      expect(paths(res)).toEqual(['routeName'])
      expect(res.body.errors[0].msg).toBe(
        t('zh-CN', 'validation.route_name_reserved', { field: label('zh-CN', 'routeName') }),
      )
    }
    const g = await add(0)
    expect(paths(await create(page(g.id, { routeName: 'lock' })).expect(400))).toEqual([
      'routeName',
    ])
    const p = (await create(page(g.id)).expect(201)).body.data
    expect(
      paths(await call('admin', 'put', `/${p.id}`, { routeName: 'password-reset' }).expect(400)),
    ).toEqual(['routeName'])
  })

  it('rules: a group saved before the route-name rule (none, `Legacy_Group`) is still enabled and moved; a route name sent is judged (400)', async () => {
    const target = await add(0)
    for (const legacy of [null, `Legacy_Group${seq}`]) {
      const tag = unique()
      const id = await insertRow(ds.manager, 'iam_menu', {
        kind: 'group',
        name: tag,
        route_path: `/${tag}`,
        route_name: legacy,
      })
      await call('admin', 'put', `/${id}/enabled`, { enabled: false }).expect(200)
      await call('admin', 'put', `/${id}`, { parentId: target.id }).expect(200)
      expect(await pathOf(id)).toBe(`${target.treePath}${id}/`)
      expect(
        paths(await call('admin', 'put', `/${id}`, { routeName: 'Bad_Name' }).expect(400)),
      ).toEqual(['routeName'])
    }
  })

  it('rules: a group route name is fixed once saved (422); the same value, a page, a legacy group may change it', async () => {
    const g = await add(0)
    const res = await call('admin', 'put', `/${g.id}`, { routeName: unique() })
    expectErr(res, 422, Err.IAM_MENU_ROUTE_NAME_FIXED.code)
    expectErr(
      await call('admin', 'put', `/${g.id}`, { routeName: null }),
      422,
      Err.IAM_MENU_ROUTE_NAME_FIXED.code,
    )
    await call('admin', 'put', `/${g.id}`, { routeName: g.routeName, name: 'renamed' }).expect(200)
    expect((await call('admin', 'get', `/${g.id}`).expect(200)).body.data).toMatchObject({
      routeName: g.routeName,
      name: 'renamed',
    })
    // a page's route name is no seed key of a group
    const p = (await create(page(g.id)).expect(201)).body.data
    await call('admin', 'put', `/${p.id}`, { routeName: unique() }).expect(200)
    // a group saved before the rule (none, or outside the format) gets one once, then keeps it
    for (const legacy of [null, 'Legacy_Group']) {
      const tag = unique()
      const id = await insertRow(ds.manager, 'iam_menu', {
        kind: 'group',
        name: tag,
        route_path: `/${tag}`,
        route_name: legacy === null ? null : `${legacy}${seq}`,
      })
      await call('admin', 'put', `/${id}`, { routeName: tag }).expect(200)
      expectErr(
        await call('admin', 'put', `/${id}`, { routeName: unique() }),
        422,
        Err.IAM_MENU_ROUTE_NAME_FIXED.code,
      )
    }
  })

  it('rules: delete — not with children (409 has_children), not while granted to a role (409 menu_granted)', async () => {
    const g = await add(0)
    const p = (await create(page(g.id)).expect(201)).body.data
    const a = (await create(action(p.id)).expect(201)).body.data
    expectErr(await call('admin', 'delete', `/${p.id}`), 409, Err.TREE_HAS_CHILDREN.code)
    await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [roleId, a.id])
    const res = await call('admin', 'delete', `/${a.id}`)
    expectErr(res, 409, Err.IAM_MENU_GRANTED.code)
    expect(res.body.msg).toBe(t('zh-CN', Err.IAM_MENU_GRANTED.key))
    await ds.query('DELETE FROM iam_role_menus WHERE role_id = ? AND menu_id = ?', [roleId, a.id])
    for (const id of [a.id, p.id, g.id]) await call('admin', 'delete', `/${id}`).expect(200)
  })

  it('rules: PUT /sort renumbers several menus at once; an unknown id → 404 and nothing changes; 403 / 400', async () => {
    const g = await add(0)
    const [x, y] = [await add(g.id), await add(g.id)]
    const before = await permVerAll()
    await call('admin', 'put', '/sort', {
      items: [
        { id: x.id, sortNo: 20 },
        { id: y.id, sortNo: 10 },
      ],
    }).expect(200)
    expect(shape([find(await list(), g.id)!])).toEqual([[g.id, [y.id, x.id]]])
    expect(await permVerAll()).toBe(before + 1) // the menus' order: browsers reload them
    expectErr(
      await call('admin', 'put', '/sort', {
        items: [
          { id: x.id, sortNo: 1 },
          { id: MISSING, sortNo: 2 },
        ],
      }),
      404,
      Err.NOT_FOUND.code,
    )
    expect((await call('admin', 'get', `/${x.id}`).expect(200)).body.data.sortNo).toBe(20)
    expectErr(
      await call('reader', 'put', '/sort', { items: [{ id: x.id, sortNo: 1 }] }),
      403,
      Err.FORBIDDEN.code,
    )
    for (const items of [[], [{ id: x.id, sortNo: -1 }], [{ id: 'x', sortNo: 1 }]])
      await call('admin', 'put', '/sort', { items }).expect(400)
  })

  it('rules: every menu write reloads every session (bumpAll): create, any edit, enable, delete, sort; a refused write does not', async () => {
    const g = await add(0)
    const p = (await create(page(g.id)).expect(201)).body.data
    const a = (await create(action(p.id)).expect(201)).body.data
    const bumps = async (write: () => Promise<unknown>) => {
      const before = await permVerAll()
      await write()
      return (await permVerAll()) - before
    }
    expect(await bumps(() => create(action(p.id)).expect(201))).toBe(1)
    // what /api/auth/menus returns (routes, names, icons, order) changes the browsers' routes too
    for (const dto of [
      { name: 'renamed' },
      { perms: perm() },
      { enabled: false },
      { parentId: p.id },
    ])
      expect(await bumps(() => call('admin', 'put', `/${a.id}`, dto).expect(200))).toBe(1)
    for (const dto of [{ routePath: `/${unique()}` }, { visible: false }, { icon: 'lucide:house' }])
      expect(await bumps(() => call('admin', 'put', `/${p.id}`, dto).expect(200))).toBe(1)
    expect(
      await bumps(() => call('admin', 'put', `/${a.id}/enabled`, { enabled: true }).expect(200)),
    ).toBe(1)
    expect(
      await bumps(() =>
        call('admin', 'put', '/sort', { items: [{ id: p.id, sortNo: 5 }] }).expect(200),
      ),
    ).toBe(1)
    expect(await bumps(() => call('admin', 'delete', `/${a.id}`).expect(200))).toBe(1)
    // a refused write reloads nothing
    expect(
      await bumps(() => call('admin', 'put', `/${p.id}`, { parentId: MISSING }).expect(404)),
    ).toBe(0)
  })

  it('rules: a signed-in session sees a new X-Perm-Ver after a menu create, a path change and a visibility change', async () => {
    const version = async () =>
      (await request(app.getHttpServer()).get('/api/auth/me').set(bearer(tokens.plain)).expect(200))
        .headers['x-perm-ver'] as string
    const g = await add(0)
    const seen = [await version()]
    const p = (await create(page(g.id)).expect(201)).body.data
    seen.push(await version())
    await call('admin', 'put', `/${p.id}`, { routePath: `/${unique()}` }).expect(200)
    seen.push(await version())
    await call('admin', 'put', `/${p.id}`, { visible: false }).expect(200)
    seen.push(await version())
    expect(new Set(seen).size).toBe(4)
  })

  it('rules: disabling a menu (or an ancestor) → its holders get 403 at their next request, no new sign-in; enabling restores; changed perms move with it', async () => {
    const g = await add(0)
    const p = (await create(page(g.id)).expect(201)).body.data
    const a = (await create(action(p.id, { perms: menuPerms.browse })).expect(201)).body.data
    const holderRole = await insertRow(ds.manager, 'iam_role', {
      code: `${PREFIX}holder`,
      name: `${PREFIX}holder`,
      data_scope: 'all',
    })
    try {
      await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [
        holderRole,
        a.id,
      ])
      const holder = await user('holder', [holderRole])
      const browse = () =>
        request(app.getHttpServer()).get(URL).set(bearer(holder)).query({ kind: 'group' })
      await browse().expect(200)
      await call('admin', 'put', `/${a.id}/enabled`, { enabled: false }).expect(200)
      expectErr(await browse(), 403, Err.FORBIDDEN.code)
      await call('admin', 'put', `/${a.id}/enabled`, { enabled: true }).expect(200)
      await browse().expect(200)
      // a disabled ancestor hides the whole subtree
      await call('admin', 'put', `/${g.id}`, { enabled: false }).expect(200)
      expectErr(await browse(), 403, Err.FORBIDDEN.code)
      await call('admin', 'put', `/${g.id}`, { enabled: true }).expect(200)
      await browse().expect(200)
      // the grant follows the menu's perms
      await call('admin', 'put', `/${a.id}`, { perms: menuPerms.view }).expect(200)
      expectErr(await browse(), 403, Err.FORBIDDEN.code)
      await request(app.getHttpServer()).get(`${URL}/${a.id}`).set(bearer(holder)).expect(200)
    } finally {
      await ds.query('DELETE FROM iam_role_menus WHERE role_id = ?', [holderRole])
      await ds.query('DELETE FROM iam_user_roles WHERE role_id = ?', [holderRole])
      await ds.query('DELETE FROM iam_role WHERE id = ?', [holderRole])
    }
  })
})

describe('errors', () => {
  it('403 per permission: browse-only may list, not view/create/modify/delete; no perm → no list', async () => {
    const { id } = await add(0)
    await call('reader', 'get').expect(200)
    for (const res of await Promise.all([
      call('reader', 'get', `/${id}`),
      call('reader', 'post', '', body(unique())),
      call('reader', 'put', `/${id}`, {}),
      call('reader', 'put', `/${id}/enabled`, { enabled: false }),
      call('reader', 'put', '/sort', { items: [{ id, sortNo: 1 }] }),
      call('reader', 'delete', `/${id}`),
      call('plain', 'get'),
    ]))
      expectErr(res, 403, Err.FORBIDDEN.code)
  })

  it('400: invalid body / query / id, with translated field messages', async () => {
    const required = (lang: string, field: string) =>
      t(lang, 'validation.required', { field: label(lang, field) })
    expect(label('zh-CN', 'kind')).not.toMatch(/^field\./)
    expect(label('en-US', 'kind')).not.toMatch(/^field\./)
    const { kind: _left, ...left } = body(unique())
    const invalid = { ...left, parentId: -1 }
    const zh = await create(invalid).expect(400)
    expect(zh.body.code).toBe(Err.VALIDATION_FAILED.code)
    expect(zh.body.errors.map((e: { path: string }) => e.path)).toEqual(
      FORM.filter((f) => f === 'parentId' || f === 'kind'),
    )
    expect(zh.body.errors).toContainEqual({ path: 'kind', msg: required('zh-CN', 'kind') })
    const en = await create(invalid).set('Accept-Language', 'en-US').expect(400)
    expect(en.body.errors).toContainEqual({ path: 'kind', msg: required('en-US', 'kind') })
    const { id } = await add(0)
    await call('admin', 'get').query({ enabled: 'maybe' }).expect(400)
    await call('admin', 'put', `/${id}/enabled`, { enabled: 'no' }).expect(400)
    await call('admin', 'get', '/abc').expect(400)
  })

  it('404: unknown ids for get, update, enabled, delete', async () => {
    for (const res of [
      await call('admin', 'get', `/${MISSING}`),
      await call('admin', 'put', `/${MISSING}`, {}),
      await call('admin', 'put', `/${MISSING}/enabled`, { enabled: true }),
      await call('admin', 'delete', `/${MISSING}`),
    ])
      expectErr(res, 404, Err.NOT_FOUND.code)
  })

  it('the same create submitted twice within 3 s → 429 (@Idempotent)', async () => {
    const tag = unique()
    await create(body(tag)).expect(201)
    expectErr(await create(body(tag)), 429, Err.TOO_MANY_REQUESTS.code)
  })
})

it('@ActionLog: every write leaves a row with domain iam.menu, its verb and the id', async () => {
  const trace = `${PREFIX}${process.pid}-`
  const created = await create(body(unique())).set('X-Request-Id', `${trace}c`).expect(201)
  const { id } = created.body.data
  await call('admin', 'put', `/${id}`, {}).set('X-Request-Id', `${trace}u`)
  await call('admin', 'put', `/${id}/enabled`, { enabled: false }).set('X-Request-Id', `${trace}e`)
  await call('admin', 'delete', `/${id}`).set('X-Request-Id', `${trace}d`)
  await call('admin', 'delete', `/${MISSING}`).set('X-Request-Id', `${trace}m`)
  const expected: [string, object][] = [
    ['c', { verb: 'create', biz_id: String(id), ok: 1 }],
    ['u', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['e', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['d', { verb: 'remove', biz_id: String(id), ok: 1 }],
    ['m', { verb: 'remove', biz_id: String(MISSING), ok: 0, error_msg: Err.NOT_FOUND.key }],
  ]
  for (const [suffix, row] of expected)
    expect(await logOf(ds, `${trace}${suffix}`)).toMatchObject({
      domain: 'iam.menu',
      username: 'admin',
      ...row,
    })
})

it('Swagger documents every route', async () => {
  const doc = (await request(app.getHttpServer()).get('/api/docs-json').expect(200)).body
  expect(
    Object.keys(doc.paths)
      .filter((p) => p.startsWith(URL))
      .sort(),
  ).toEqual([URL, `${URL}/sort`, `${URL}/{id}`, `${URL}/{id}/enabled`])
  expect(
    doc.paths[URL].get.responses['200'].content['application/json'].schema.properties.data,
  ).toMatchObject({ type: 'array' })
})
