// @generated by qw-codegen (crud)
// messaging.smsTemplate (generated CRUD; see docs/design-notes.md#codegen, #api-envelope): list filters/sort/paging, get, create, update, delete,
// batch delete, enabled toggle;
// 403 per permission, 400 translated, 404 unknown ids, @Idempotent, @ActionLog rows,
// Swagger. Only the standard cases: module-specific ones go into a hand-written
// messaging-sms-template-extra.e2e-spec.ts.
import type { NestExpressApplication } from '@nestjs/platform-express'
import { Test } from '@nestjs/testing'
import { getDataSourceToken } from '@nestjs/typeorm'
import { Err, smsChannelPerms, smsTemplatePerms } from '@qiwu/shared'
import { I18nService } from 'nestjs-i18n'
import request from 'supertest'
import type { DataSource } from 'typeorm'
import { AppModule } from '../../src/app.module.js'
import { setupApp } from '../../src/app.setup.js'
import { TransactionHost } from '@nestjs-cls/transactional'
import { NotifyChannels } from '../../src/core/notify/notify.js'
import { REDIS, type Redis } from '../../src/core/redis/redis.module.js'
import type { SmsNotifyChannel } from '../../src/modules/platform/messaging/sms-template/sms-notify-channel.js'
import { SmsTemplate } from '../../src/modules/platform/messaging/sms-template/sms-template.entity.js'
import { findId, insertRow } from '../../src/db/seeds/upsert.js'
import { logOf } from '../setup/audit.js'
import { bearer, signIn } from '../setup/auth.js'
import { cleanRedis } from '../setup/redis.js'

const PREFIX = 'e2e-sms-template-'
const URL = '/api/messaging/sms-templates'
const MISSING = 999_999
/** the form's fields, as the edit form sends them back */
const FORM = [
  'code',
  'locale',
  'channelId',
  'name',
  'purpose',
  'body',
  'providerTemplateId',
  'enabled',
]

let app: NestExpressApplication
let ds: DataSource
let redis: Redis
let i18n: I18nService
const tokens: Record<'admin' | 'reader' | 'plain' | 'writer', string> = {
  admin: '',
  reader: '',
  plain: '',
  writer: '',
}
const userIds: number[] = []
const channelIds: number[] = []
let roleId: number
let writerRoleId: number
/** the table's last id before this spec: every row above it is this spec's (cleanup) */
let lastId = 0

const call = (
  who: keyof typeof tokens,
  method: 'get' | 'post' | 'put' | 'delete',
  path = '',
  body?: object,
) => {
  const req = request(app.getHttpServer())[method](`${URL}${path}`).set(bearer(tokens[who]))
  return body ? req.send(body) : req
}
const create = (body: object) => call('admin', 'post', '', body)
/** A row added through the API, as POST answers it. */
const add = async (body: object) => (await create(body).expect(201)).body.data
let seq = 0
const unique = () => `${PREFIX}${++seq}`
/** A valid POST body made of `tag` (required and unique fields, the configured examples). */
const body = (tag: string, over: object = {}) => ({
  code: tag,
  locale: 'zh-CN',
  name: `${tag} name`,
  purpose: 'notice',
  body: `${tag} body`,
  ...over,
})
/** A translated message (the app's own translations). */
const t = (lang: string, key: string, args?: object) => i18n.t(key, { lang, args }) as string
const label = (lang: string, field: string) => t(lang, `field.messaging.smsTemplate.${field}`)
/** Live rows of the table (a list's total without filters). */
const count = async () =>
  Number(
    (await ds.query('SELECT COUNT(*) AS n FROM msg_sms_template WHERE deleted_at IS NULL'))[0].n,
  )
const idsOf = (res: request.Response) => res.body.data.items.map((r: { id: number }) => r.id)

async function user(name: string, roles: number[]) {
  const id = await insertRow(ds.manager, 'iam_user', {
    username: PREFIX + name,
    display_name: name,
    password_hash: 'not-used-by-this-spec',
    password_changed_at: new Date(),
  })
  for (const r of roles)
    await ds.query('INSERT INTO iam_user_roles (user_id, role_id) VALUES (?, ?)', [id, r])
  userIds.push(id)
  return (await signIn(app, PREFIX + name)).accessToken
}

beforeAll(async () => {
  const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile()
  app = setupApp(moduleRef.createNestApplication<NestExpressApplication>({ logger: false }))
  await app.listen(0, '127.0.0.1')
  ds = app.get<DataSource>(getDataSourceToken())
  redis = app.get(REDIS)
  i18n = app.get(I18nService)
  await cleanRedis(redis)
  lastId = Number((await ds.query('SELECT COALESCE(MAX(id), 0) AS n FROM msg_sms_template'))[0].n)
  roleId = await insertRow(ds.manager, 'iam_role', {
    code: `${PREFIX}reader`,
    name: `${PREFIX}reader`,
    data_scope: 'all',
  })
  const browse = await findId(ds.manager, 'iam_menu', { perms: smsTemplatePerms.browse })
  await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [roleId, browse])
  writerRoleId = await insertRow(ds.manager, 'iam_role', {
    code: `${PREFIX}writer`,
    name: `${PREFIX}writer`,
    data_scope: 'all',
  })
  for (const perm of [...Object.values(smsTemplatePerms), ...Object.values(smsChannelPerms)]) {
    const menuId = await findId(ds.manager, 'iam_menu', { perms: perm })
    await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [
      writerRoleId,
      menuId,
    ])
  }
  tokens.admin = (await signIn(app)).accessToken
  tokens.reader = await user('reader', [roleId])
  tokens.plain = await user('plain', [])
  tokens.writer = await user('writer', [writerRoleId])
})

afterAll(async () => {
  if (ds) {
    await ds.query('DELETE FROM msg_sms_template WHERE id > ?', [lastId])
    if (channelIds.length)
      await ds.query('DELETE FROM msg_sms_channel WHERE id IN (?)', [channelIds])
    if (userIds.length) {
      await ds.query('DELETE FROM iam_user_roles WHERE user_id IN (?)', [userIds])
      await ds.query('DELETE FROM iam_user WHERE id IN (?)', [userIds])
    }
    await ds.query('DELETE FROM iam_role_menus WHERE role_id IN (?, ?)', [roleId, writerRoleId])
    await ds.query('DELETE FROM iam_role WHERE id IN (?, ?)', [roleId, writerRoleId])
  }
  if (redis) await cleanRedis(redis)
  await app?.close()
})

it('auth.* templates reject non-root writes even with every SMS permission; root can manage them', async () => {
  const [seed] = await ds.query<
    Array<{
      id: number
      code: string
      body: string
      channel_id: number | null
      provider_template_id: string | null
      enabled: number
    }>
  >(
    "SELECT id, code, body, channel_id, provider_template_id, enabled FROM msg_sms_template WHERE code = 'auth.sms_code' AND locale = 'en-US'",
  )
  const channelId = await insertRow(ds.manager, 'msg_sms_channel', {
    driver: 'debug',
    name: unique(),
  })
  channelIds.push(channelId)
  const ordinary = await add(body(unique()))
  const forbidden = async (res: request.Response) => {
    expect(res.status).toBe(403)
    expect(res.body.code).toBe(Err.IAM_GRANT_EXCEEDS_OWN.code)
  }
  const snapshot = async () =>
    (
      await ds.query(
        'SELECT code, body, channel_id, provider_template_id, enabled FROM msg_sms_template WHERE id = ?',
        [seed!.id],
      )
    )[0]
  const initial = await snapshot()
  try {
    for (const change of [
      { body: 'intercept {code}' },
      { channelId },
      { providerTemplateId: 'ATTACK' },
      { code: unique() },
    ]) {
      await forbidden(await call('writer', 'put', `/${seed!.id}`, change))
      expect(await snapshot()).toEqual(initial)
    }
    await forbidden(await call('writer', 'put', `/${seed!.id}/enabled`, { enabled: false }))
    await forbidden(await call('writer', 'delete', `/${seed!.id}`))
    await forbidden(await call('writer', 'post', '/batch-delete', { ids: [ordinary.id, seed!.id] }))
    await forbidden(await call('writer', 'post', '', body('auth.other')))
    await forbidden(await call('writer', 'put', `/${ordinary.id}`, { code: 'auth.other' }))
    expect(await snapshot()).toEqual(initial)
    expect((await call('admin', 'get', `/${ordinary.id}`)).body.data.code).toBe(ordinary.code)

    await call('writer', 'put', `/${ordinary.id}`, { body: 'ordinary edit' }).expect(200)
    await call('admin', 'put', `/${seed!.id}`, {
      body: 'root {code}',
      channelId,
      providerTemplateId: 'ROOT',
    }).expect(200)
    await call('admin', 'put', `/${seed!.id}`, { code: 'auth.root_test' }).expect(200)
    await call('admin', 'put', `/${seed!.id}`, { code: seed!.code }).expect(200)
    await call('admin', 'put', `/${seed!.id}/enabled`, { enabled: false }).expect(200)
    const rootOnly = await add(body('auth.other'))
    await call('admin', 'delete', `/${rootOnly.id}`).expect(200)
    const rootBatch = await add(body('auth.batch'))
    await call('admin', 'post', '/batch-delete', { ids: [rootBatch.id] }).expect(200)
  } finally {
    await ds.query(
      'UPDATE msg_sms_template SET code = ?, body = ?, channel_id = ?, provider_template_id = ?, enabled = ? WHERE id = ?',
      [
        seed!.code,
        seed!.body,
        seed!.channel_id,
        seed!.provider_template_id,
        seed!.enabled,
        seed!.id,
      ],
    )
  }
})

it('mixed-case auth.* templates reject non-root create, recode, update, toggle, and delete', async () => {
  const forbidden = async (res: request.Response) => {
    expect(res.status).toBe(403)
    expect(res.body.code).toBe(Err.IAM_GRANT_EXCEEDS_OWN.code)
  }
  const ordinary = await add(body(unique()))
  const id = await insertRow(ds.manager, 'msg_sms_template', {
    ...body('AUTH.x'),
    locale: 'en-US',
  })
  try {
    await forbidden(await call('writer', 'post', '', body('AUTH.sms_code')))
    await forbidden(await call('writer', 'put', `/${ordinary.id}`, { code: 'Auth.other' }))
    for (const change of [{ body: 'intercept {code}' }, { code: unique() }])
      await forbidden(await call('writer', 'put', `/${id}`, change))
    await forbidden(await call('writer', 'put', `/${id}/enabled`, { enabled: false }))
    await forbidden(await call('writer', 'delete', `/${id}`))
    expect((await call('admin', 'get', `/${id}`).expect(200)).body.data).toMatchObject({
      code: 'AUTH.x',
      enabled: true,
    })
    await call('admin', 'put', `/${id}`, { body: 'root edit' }).expect(200)
    await call('admin', 'put', `/${id}/enabled`, { enabled: false }).expect(200)
    await call('admin', 'delete', `/${id}`).expect(200)
    const created = await add(body('AUTH.root_case'))
    await call('admin', 'delete', `/${created.id}`).expect(200)
  } finally {
    await ds.query('DELETE FROM msg_sms_template WHERE id = ?', [id])
  }
})

it('test-send requires root for every auth.* template before writing a record', async () => {
  const mobile = '13881112233'
  const [auth] = await ds.query<Array<{ id: number; channel_id: number | null }>>(
    "SELECT id, channel_id FROM msg_sms_template WHERE code = 'auth.sms_code' AND locale = 'en-US'",
  )
  const channelId = await insertRow(ds.manager, 'msg_sms_channel', {
    driver: 'debug',
    name: unique(),
  })
  const otherChannelId = await insertRow(ds.manager, 'msg_sms_channel', {
    driver: 'debug',
    name: unique(),
  })
  channelIds.push(channelId, otherChannelId)
  const ordinary = await add(body(unique(), { channelId: otherChannelId, body: 'Code {code}' }))
  const variantId = await insertRow(ds.manager, 'msg_sms_template', {
    code: 'AUTH.Sms_Code_Test',
    locale: 'en-US',
    channel_id: channelId,
    name: unique(),
    purpose: 'notice',
    body: 'Code {code}',
  })
  const payload = { mobile, params: { code: '123456' } }
  const send = (who: 'admin' | 'writer', id: number) => call(who, 'post', `/${id}/test`, payload)
  await ds.query('UPDATE msg_sms_template SET channel_id = ? WHERE id = ?', [channelId, auth!.id])
  try {
    const attempts = []
    for (const id of [auth!.id, variantId]) attempts.push(await send('writer', id))
    expect(attempts.map((res) => res.status)).toEqual([403, 403])
    expect(attempts.map((res) => res.body.code)).toEqual([
      Err.IAM_GRANT_EXCEEDS_OWN.code,
      Err.IAM_GRANT_EXCEEDS_OWN.code,
    ])
    expect(
      Number(
        (await ds.query('SELECT COUNT(*) AS n FROM msg_sms_record WHERE mobile = ?', [mobile]))[0]
          .n,
      ),
    ).toBe(0)
    await send('writer', ordinary.id).expect(200)
    await send('admin', auth!.id).expect(200)
  } finally {
    await ds.query('DELETE FROM msg_sms_record WHERE mobile = ?', [mobile])
    await ds.query('UPDATE msg_sms_template SET channel_id = ? WHERE id = ?', [
      auth!.channel_id,
      auth!.id,
    ])
    await ds.query('DELETE FROM msg_sms_template WHERE id = ?', [variantId])
  }
})

it('non-root writes and test-sends stay off the auth.* route: its channel, its provider template id on any channel', async () => {
  const mobile = '13881112244'
  const forbidden = (res: request.Response) => {
    expect(res.status).toBe(403)
    expect(res.body.code).toBe(Err.IAM_GRANT_EXCEEDS_OWN.code)
  }
  const [auth] = await ds.query<
    Array<{ id: number; channel_id: number | null; provider_template_id: string | null }>
  >(
    "SELECT id, channel_id, provider_template_id FROM msg_sms_template WHERE code = 'auth.sms_code' AND locale = 'en-US'",
  )
  const authChannel = await insertRow(ds.manager, 'msg_sms_channel', {
    driver: 'debug',
    name: unique(),
  })
  const otherChannel = await insertRow(ds.manager, 'msg_sms_channel', {
    driver: 'debug',
    name: unique(),
  })
  const thirdChannel = await insertRow(ds.manager, 'msg_sms_channel', {
    driver: 'debug',
    name: unique(),
  })
  channelIds.push(authChannel, otherChannel, thirdChannel)
  const ordinary = await add(body(unique(), { channelId: otherChannel, body: 'Code {code}' }))
  const cloneOnAuth = await insertRow(ds.manager, 'msg_sms_template', {
    ...body(unique()),
    channel_id: authChannel,
    body: 'Code {code}',
  })
  const records = async () =>
    Number(
      (await ds.query('SELECT COUNT(*) AS n FROM msg_sms_record WHERE mobile = ?', [mobile]))[0].n,
    )
  const send = (who: 'admin' | 'writer', id: number) =>
    call(who, 'post', `/${id}/test`, { mobile, params: { code: '654321' } })
  const stored = async (id: number) =>
    (
      await ds.query(
        'SELECT channel_id, provider_template_id, enabled FROM msg_sms_template WHERE id = ?',
        [id],
      )
    )[0]
  await ds.query('UPDATE msg_sms_template SET channel_id = ? WHERE id = ?', [authChannel, auth!.id])
  try {
    // a clone onto the auth channel
    const clone = unique()
    forbidden(
      await call(
        'writer',
        'post',
        '',
        body(clone, { channelId: authChannel, body: 'Code {code}' }),
      ),
    )
    expect(
      Number(
        (await ds.query('SELECT COUNT(*) AS n FROM msg_sms_template WHERE code = ?', [clone]))[0].n,
      ),
    ).toBe(0)
    // re-pointing onto it, and any write or test-send of a template already there
    const before = await stored(ordinary.id)
    forbidden(await call('writer', 'put', `/${ordinary.id}`, { channelId: authChannel }))
    expect(await stored(ordinary.id)).toEqual(before)
    const there = await stored(cloneOnAuth)
    for (const change of [{ body: 'edit {code}' }, { channelId: otherChannel }])
      forbidden(await call('writer', 'put', `/${cloneOnAuth}`, change))
    forbidden(await call('writer', 'put', `/${cloneOnAuth}/enabled`, { enabled: false }))
    expect(await stored(cloneOnAuth)).toEqual(there)
    forbidden(await send('writer', cloneOnAuth))
    expect(await records()).toBe(0)

    // the auth.* template's provider template id (it sits on its own channel) on ANY other channel:
    // one provider account may sit behind several channels
    await ds.query('UPDATE msg_sms_template SET provider_template_id = ? WHERE id = ?', [
      'AUTH-TPL-e2e',
      auth!.id,
    ])
    const code = unique()
    forbidden(
      await call(
        'writer',
        'post',
        '',
        body(code, { channelId: otherChannel, providerTemplateId: ' auth-tpl-E2E ' }),
      ),
    )
    expect(
      Number(
        (await ds.query('SELECT COUNT(*) AS n FROM msg_sms_template WHERE code = ?', [code]))[0].n,
      ),
    ).toBe(0)
    const plain = await stored(ordinary.id)
    forbidden(
      await call('writer', 'put', `/${ordinary.id}`, { providerTemplateId: ' auth-tpl-E2E ' }),
    )
    expect(await stored(ordinary.id)).toEqual(plain)
    // a (root-made) template already on that id: no edit, re-point, enable or test-send
    const reuse = await insertRow(ds.manager, 'msg_sms_template', {
      ...body(unique()),
      channel_id: otherChannel,
      provider_template_id: 'auth-tpl-e2e',
      enabled: false,
      body: 'Code {code}',
    })
    const reused = await stored(reuse)
    for (const change of [
      { body: 'edit {code}' },
      { channelId: thirdChannel },
      { providerTemplateId: 'OTHER' },
    ])
      forbidden(await call('writer', 'put', `/${reuse}`, change))
    forbidden(await call('writer', 'put', `/${reuse}/enabled`, { enabled: true }))
    expect(await stored(reuse)).toEqual(reused)
    await ds.query('UPDATE msg_sms_template SET enabled = 1 WHERE id = ?', [reuse])
    forbidden(await send('writer', reuse))
    expect(await records()).toBe(0)
    // another id on another channel is not the auth route
    await call(
      'writer',
      'post',
      '',
      body(unique(), { channelId: otherChannel, providerTemplateId: 'OTHER' }),
    ).expect(201)

    // off the route a non-root works as before; root may do everything
    await send('writer', ordinary.id).expect(200)
    await call('admin', 'put', `/${cloneOnAuth}`, { body: 'root {code}' }).expect(200)
    await send('admin', cloneOnAuth).expect(200)
    await send('admin', reuse).expect(200)
    await call(
      'admin',
      'post',
      '',
      body(unique(), { channelId: otherChannel, providerTemplateId: 'AUTH-TPL-e2e' }),
    ).expect(201)
    expect(await records()).toBe(3)
  } finally {
    await ds.query('DELETE FROM msg_sms_record WHERE mobile = ?', [mobile])
    await ds.query(
      'UPDATE msg_sms_template SET channel_id = ?, provider_template_id = ? WHERE id = ?',
      [auth!.channel_id, auth!.provider_template_id, auth!.id],
    )
  }
})

it('a template without a channel never falls back onto an auth.* channel, whichever channels a non-root disables or deletes', async () => {
  const mobile = '13881112255'
  const [auth] = await ds.query<Array<{ id: number; channel_id: number | null }>>(
    "SELECT id, channel_id FROM msg_sms_template WHERE code = 'auth.sms_code' AND locale = 'en-US'",
  )
  const enabledBefore = (
    await ds.query<Array<{ id: number }>>('SELECT id FROM msg_sms_channel WHERE enabled = 1')
  ).map((row) => row.id)
  // only this test's channels are enabled: the default F, then the auth channel A, then G
  const channel = () =>
    insertRow(ds.manager, 'msg_sms_channel', { driver: 'debug', name: unique() })
  const f = await channel()
  const a = await channel()
  const g = await channel()
  channelIds.push(f, a, g)
  const notify = app.get(NotifyChannels).get('sms') as SmsNotifyChannel
  const channelOf = async (recordId: number) =>
    (await ds.query('SELECT channel_id FROM msg_sms_record WHERE id = ?', [recordId]))[0]
      .channel_id as number | null
  /** a notification rendered from the template (the dispatcher's write) */
  const write = async (id: number) => {
    const template = await ds.getRepository(SmsTemplate).findOneByOrFail({ id })
    return app.get(TransactionHost).withTransaction(() =>
      notify.write({
        template,
        recipient: { userId: null, email: null, mobile, locale: 'zh-CN', timezone: 'UTC' },
        params: {},
        values: { code: '222222' },
      }),
    )
  }
  let sends = 0
  // a new code each time: the same body again within 3 s is an @Idempotent duplicate
  const send = async (id: number) =>
    (
      await call('writer', 'post', `/${id}/test`, {
        mobile,
        params: { code: String(222222 + ++sends) },
      }).expect(200)
    ).body.data as { ok: boolean; recordId: number }
  const channels = (method: 'put' | 'delete', path: string, payload?: object) => {
    const req = request(app.getHttpServer())
      [method](`/api/messaging/sms-channels/${path}`)
      .set(bearer(tokens.writer))
    return payload ? req.send(payload) : req
  }
  if (enabledBefore.length)
    await ds.query('UPDATE msg_sms_channel SET enabled = 0 WHERE id IN (?)', [enabledBefore])
  await ds.query('UPDATE msg_sms_template SET channel_id = ? WHERE id = ?', [a, auth!.id])
  try {
    const t = await add(body(unique(), { body: 'Code {code}' }))
    const own = (
      await call('writer', 'post', '', body(unique(), { body: 'Code {code}' })).expect(201)
    ).body.data
    expect([t.channelId, own.channelId]).toEqual([null, null])
    expect(await channelOf(await write(own.id))).toBe(f)
    // the default is disabled: the next enabled channel is the auth one, and it is skipped
    await channels('put', `${f}/enabled`, { enabled: false }).expect(200)
    expect(await channelOf(await write(own.id))).toBe(g)
    const sent = await send(own.id)
    expect(sent.ok).toBe(true)
    expect(await channelOf(sent.recordId)).toBe(g)
    // the last other one is deleted: no channel rather than the auth one
    await channels('delete', `${g}`).expect(200)
    for (const id of [own.id, t.id]) {
      expect(await channelOf(await write(id))).toBeNull()
      const failed = await send(id)
      expect(failed.ok).toBe(false)
      expect(await channelOf(failed.recordId)).toBeNull()
    }
    expect(
      Number(
        (await ds.query('SELECT COUNT(*) AS n FROM msg_sms_record WHERE channel_id = ?', [a]))[0].n,
      ),
    ).toBe(0)
  } finally {
    await ds.query('DELETE FROM msg_sms_record WHERE mobile = ?', [mobile])
    await ds.query('UPDATE msg_sms_template SET channel_id = ? WHERE id = ?', [
      auth!.channel_id,
      auth!.id,
    ])
    if (enabledBefore.length)
      await ds.query('UPDATE msg_sms_channel SET enabled = 1 WHERE id IN (?)', [enabledBefore])
  }
})

it('a mixed-case AUTH.* template alone makes its channel and provider template id root-only, and never a fallback', async () => {
  const mobile = '13881112266'
  const forbidden = (res: request.Response) => {
    expect(res.status).toBe(403)
    expect(res.body.code).toBe(Err.IAM_GRANT_EXCEEDS_OWN.code)
  }
  const enabledBefore = (
    await ds.query<Array<{ id: number }>>('SELECT id FROM msg_sms_channel WHERE enabled = 1')
  ).map((row) => row.id)
  // only this test's channels are enabled: x (named by the variant only), then o
  const channel = () =>
    insertRow(ds.manager, 'msg_sms_channel', { driver: 'debug', name: unique() })
  const x = await channel()
  const o = await channel()
  channelIds.push(x, o)
  const variant = await add(
    body('AUTH.Probe_Variant', { channelId: x, providerTemplateId: 'Probe-TPL-e2e' }),
  )
  const onX = await add(body(unique(), { channelId: x, body: 'Code {code}' }))
  const reuse = await add(
    body(unique(), { channelId: o, providerTemplateId: 'PROBE-tpl-E2E', body: 'Code {code}' }),
  )
  const ordinary = await add(body(unique(), { channelId: o, body: 'Code {code}' }))
  const loose = await add(body(unique(), { body: 'Code {code}' }))
  const rows = async (code: string) =>
    Number(
      (await ds.query('SELECT COUNT(*) AS n FROM msg_sms_template WHERE code = ?', [code]))[0].n,
    )
  const records = async () =>
    (
      await ds.query<Array<{ channel_id: number | null }>>(
        'SELECT channel_id FROM msg_sms_record WHERE mobile = ?',
        [mobile],
      )
    ).map((row) => row.channel_id)
  const stored = async (id: number) =>
    (
      await ds.query('SELECT channel_id, provider_template_id FROM msg_sms_template WHERE id = ?', [
        id,
      ])
    )[0]
  let sends = 0
  const send = (id: number) =>
    call('writer', 'post', `/${id}/test`, { mobile, params: { code: String(333333 + ++sends) } })
  if (enabledBefore.length)
    await ds.query('UPDATE msg_sms_channel SET enabled = 0 WHERE id IN (?)', [enabledBefore])
  try {
    for (const over of [
      { channelId: x },
      { channelId: o, providerTemplateId: '  probe-TPL-e2e ' },
      { providerTemplateId: 'PROBE-TPL-E2E' },
    ]) {
      const code = unique()
      forbidden(await call('writer', 'post', '', body(code, over)))
      expect(await rows(code)).toBe(0)
    }
    const before = await stored(ordinary.id)
    for (const change of [{ channelId: x }, { providerTemplateId: 'probe-tpl-e2e' }])
      forbidden(await call('writer', 'put', `/${ordinary.id}`, change))
    expect(await stored(ordinary.id)).toEqual(before)
    for (const id of [onX.id, reuse.id]) forbidden(await send(id))
    expect(await records()).toEqual([])
    // the fallback skips x (named only by the variant) for o
    const sent = (await send(loose.id).expect(200)).body.data as { ok: boolean }
    expect(sent.ok).toBe(true)
    expect(await records()).toEqual([o])
  } finally {
    await ds.query('DELETE FROM msg_sms_record WHERE mobile = ?', [mobile])
    await ds.query('DELETE FROM msg_sms_template WHERE id = ?', [variant.id])
    if (enabledBefore.length)
      await ds.query('UPDATE msg_sms_channel SET enabled = 1 WHERE id IN (?)', [enabledBefore])
  }
})

describe('CRUD', () => {
  it('create → 201 with the row (defaults filled, audit columns set); get returns it', async () => {
    const tag = unique()
    const res = await create(body(tag)).expect(201)
    const row = res.body.data
    expect(row).toMatchObject({
      id: expect.any(Number),
      ...body(tag),
      channelId: null,
      providerTemplateId: null,
      enabled: true,
      createdBy: expect.any(Number),
    })
    expect(new Date(row.createdAt).toISOString()).toBe(row.createdAt)
    const got = await call('admin', 'get', `/${row.id}`).expect(200)
    expect(got.body.data).toEqual({ ...row, channelName: null })
  })

  it('list and get show a disabled channel name, and null for the default channel', async () => {
    const name = unique()
    const channelId = await insertRow(ds.manager, 'msg_sms_channel', {
      driver: 'debug',
      name,
      enabled: false,
    })
    channelIds.push(channelId)
    const bound = await add(body(unique(), { channelId }))
    const unbound = await add(body(unique()))
    const list = await call('admin', 'get').query({ code: PREFIX, sort: '-id' }).expect(200)
    const byId = new Map(list.body.data.items.map((row: { id: number }) => [row.id, row]))
    expect(byId.get(bound.id)).toMatchObject({ channelId, channelName: name })
    expect(byId.get(unbound.id)).toMatchObject({ channelId: null, channelName: null })
    expect((await call('admin', 'get', `/${bound.id}`).expect(200)).body.data).toMatchObject({
      channelId,
      channelName: name,
    })
    expect((await call('admin', 'get', `/${unbound.id}`).expect(200)).body.data).toMatchObject({
      channelId: null,
      channelName: null,
    })
  })

  it('list: newest first by the sort whitelist, all live rows counted, paging, enabled equals', async () => {
    const ids: number[] = []
    for (let i = 0; i < 3; i++) ids.push((await add(body(unique()))).id)
    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const res = await list({ sort: '-id', pageSize: 3 })
    expect(idsOf(res)).toEqual([...ids].reverse())
    expect(res.body.data.total).toBe(await count())
    expect(idsOf(await list({ sort: '-id', page: 2, pageSize: 2 }))[0]).toBe(ids[0])
    const off = (await add(body(unique(), { enabled: false }))).id
    expect(idsOf(await list({ enabled: 'false', sort: '-id', pageSize: 1 }))).toEqual([off])
    expect(idsOf(await list({ enabled: 'true', sort: '-id', pageSize: 1 }))).toEqual([ids[2]])
  })

  it('list: text filters contain (LIKE wildcards literal) and combine with enabled', async () => {
    const tag = unique()
    for (const suffix of ['a', 'b', 'c']) await add(body(`${tag}-${suffix}`))
    await add(body(`${tag}-off`, { enabled: false }))
    await add(body(`${tag}_x`))

    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const keys = (res: request.Response) => res.body.data.items.map((r: { code: string }) => r.code)
    const res = await list({ code: `${tag}-`, enabled: 'true', sort: '-id' })
    expect(keys(res)).toEqual([`${tag}-c`, `${tag}-b`, `${tag}-a`])
    expect(res.body.data.total).toBe(3)
    expect(keys(await list({ code: tag, enabled: 'false' }))).toEqual([`${tag}-off`])
    // `%` and `_` in the filter are plain characters
    expect(keys(await list({ code: `${tag}_` }))).toEqual([`${tag}_x`])
    expect(keys(await list({ name: `${tag}-b name` }))).toEqual([`${tag}-b`])
    const page2 = await list({ code: `${tag}-`, sort: 'id', page: 2, pageSize: 2 })
    expect(keys(page2)).toEqual([`${tag}-c`, `${tag}-off`])
    expect(page2.body.data.total).toBe(4)
  })

  it('update changes the fields sent and keeps the others; enabled toggles', async () => {
    const tag = unique()
    const { id } = await add(body(tag))
    await call('admin', 'put', `/${id}`, { name: `${tag} renamed` }).expect(200)
    await call('admin', 'put', `/${id}/enabled`, { enabled: false }).expect(200)
    expect((await call('admin', 'get', `/${id}`)).body.data).toMatchObject({
      ...body(tag),
      name: `${tag} renamed`,
      enabled: false,
    })
  })

  it('a row PUT back as loaded (nulls included, as the edit form sends it) → 200, unchanged', async () => {
    const row = await add(body(unique()))
    const loaded = Object.fromEntries(FORM.map((f) => [f, row[f]]))
    await call('admin', 'put', `/${row.id}`, loaded).expect(200)
    expect((await call('admin', 'get', `/${row.id}`)).body.data).toMatchObject(loaded)
  })

  it('delete and batch delete (soft: the rows stay, marked deleted)', async () => {
    const ids: number[] = []
    for (let i = 0; i < 3; i++) ids.push((await add(body(unique()))).id)
    await call('admin', 'delete', `/${ids[0]}`).expect(200)
    await call('admin', 'post', '/batch-delete', { ids: ids.slice(1) }).expect(200)
    expect(
      await ds.query('SELECT id FROM msg_sms_template WHERE id IN (?) AND deleted_at IS NULL', [
        ids,
      ]),
    ).toEqual([])
    expect(await ds.query('SELECT id FROM msg_sms_template WHERE id IN (?)', [ids])).toHaveLength(3)
    await call('admin', 'get', `/${ids[0]}`).expect(404)
  })

  it('channel references (no foreign key): a live template keeps its channel (409 in_use); an unknown or deleted channel → 404, nothing saved', async () => {
    const used = await insertRow(ds.manager, 'msg_sms_channel', { driver: 'debug', name: unique() })
    channelIds.push(used)
    const removeChannel = () =>
      request(app.getHttpServer())
        .delete(`/api/messaging/sms-channels/${used}`)
        .set(bearer(tokens.admin))
    const row = await add(body(unique(), { channelId: used }))
    expect((await removeChannel().expect(409)).body.code).toBe(Err.IN_USE.code)
    // a deleted template does not count
    await call('admin', 'delete', `/${row.id}`).expect(200)
    await removeChannel().expect(200)
    const before = await count()
    for (const channelId of [used, MISSING]) await create(body(unique(), { channelId })).expect(404)
    expect(await count()).toBe(before)
    const other = await add(body(unique()))
    await call('admin', 'put', `/${other.id}`, { channelId: used }).expect(404)
    expect((await call('admin', 'get', `/${other.id}`).expect(200)).body.data.channelId).toBeNull()
  })
})

describe('errors', () => {
  it('403 per permission: browse-only may list, not view/create/modify/delete; no perm → no list', async () => {
    const { id } = await add(body(unique()))
    await call('reader', 'get').expect(200)
    const forbidden = [
      call('reader', 'get', `/${id}`),
      call('reader', 'post', '', body(unique())),
      call('reader', 'put', `/${id}`, {}),
      call('reader', 'put', `/${id}/enabled`, { enabled: false }),
      call('reader', 'delete', `/${id}`),
      call('reader', 'post', '/batch-delete', { ids: [id] }),
      call('plain', 'get'),
    ]
    for (const res of await Promise.all(forbidden)) {
      expect(res.status).toBe(403)
      expect(res.body.code).toBe(Err.FORBIDDEN.code)
    }
  })

  it('400: invalid body / query / id, with translated field messages', async () => {
    const { id } = await add(body(unique()))
    const required = (lang: string, field: string) =>
      t(lang, 'validation.required', { field: label(lang, field) })
    expect(label('zh-CN', 'code')).not.toMatch(/^field\./)
    expect(label('en-US', 'code')).not.toMatch(/^field\./)
    const zh = await create({ ...body(unique()), code: '', name: 'x'.repeat(101) }).expect(400)
    expect(zh.body).toMatchObject({
      code: Err.VALIDATION_FAILED.code,
      msg: required('zh-CN', 'code'),
    })
    expect(zh.body.errors).toEqual([
      { path: 'code', msg: required('zh-CN', 'code') },
      {
        path: 'name',
        msg: t('zh-CN', 'validation.too_big.string', {
          field: label('zh-CN', 'name'),
          maximum: 100,
        }),
      },
    ])
    const { code: _, ...keyless } = body(unique())
    const en = await create(keyless).set('Accept-Language', 'en-US').expect(400)
    expect(en.body.errors).toEqual([{ path: 'code', msg: required('en-US', 'code') }])
    await call('admin', 'get').query({ sort: 'body' }).expect(400)
    await call('admin', 'put', `/${id}/enabled`, { enabled: 'no' }).expect(400)
    await call('admin', 'post', '/batch-delete', { ids: [] }).expect(400)
    await call('admin', 'get', '/abc').expect(400)
  })

  it('404: unknown ids for get, update, enabled, delete; a batch with one unknown id deletes nothing', async () => {
    const { id } = await add(body(unique()))
    for (const res of [
      await call('admin', 'get', `/${MISSING}`),
      await call('admin', 'put', `/${MISSING}`, {}),
      await call('admin', 'put', `/${MISSING}/enabled`, { enabled: true }),
      await call('admin', 'delete', `/${MISSING}`),
      await call('admin', 'post', '/batch-delete', { ids: [id, MISSING] }),
    ]) {
      expect(res.status).toBe(404)
      expect(res.body.code).toBe(Err.NOT_FOUND.code)
    }
    await call('admin', 'get', `/${id}`).expect(200)
  })

  it('the same create submitted twice within 3 s → 429 (@Idempotent)', async () => {
    const tag = unique()
    await create(body(tag)).expect(201)
    const again = await create(body(tag)).expect(429)
    expect(again.body.code).toBe(Err.TOO_MANY_REQUESTS.code)
  })
})

it('@ActionLog: every write leaves a row with domain messaging.smsTemplate, its verb and the id', async () => {
  const trace = `${PREFIX}${process.pid}-`
  const created = await create(body(unique())).set('X-Request-Id', `${trace}c`).expect(201)
  const { id } = created.body.data
  await call('admin', 'put', `/${id}`, {}).set('X-Request-Id', `${trace}u`)
  await call('admin', 'put', `/${id}/enabled`, { enabled: false }).set('X-Request-Id', `${trace}e`)
  await call('admin', 'delete', `/${id}`).set('X-Request-Id', `${trace}d`)
  await call('admin', 'post', '/batch-delete', { ids: [MISSING] }).set('X-Request-Id', `${trace}b`)
  const expected: [string, object][] = [
    ['c', { verb: 'create', biz_id: String(id), ok: 1 }],
    ['u', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['e', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['d', { verb: 'remove', biz_id: String(id), ok: 1 }],
    ['b', { verb: 'remove', biz_id: null, ok: 0, error_msg: Err.NOT_FOUND.key }],
  ]
  for (const [suffix, row] of expected)
    expect(await logOf(ds, `${trace}${suffix}`)).toMatchObject({
      domain: 'messaging.smsTemplate',
      username: 'admin',
      ...row,
    })
})

it('Swagger documents every route', async () => {
  const doc = (await request(app.getHttpServer()).get('/api/docs-json').expect(200)).body
  expect(
    Object.keys(doc.paths)
      .filter((p) => p.startsWith(URL))
      .sort(),
  ).toEqual([URL, `${URL}/batch-delete`, `${URL}/{id}`, `${URL}/{id}/enabled`, `${URL}/{id}/test`])
  expect(
    doc.paths[URL].get.responses['200'].content['application/json'].schema.properties.data,
  ).toMatchObject({ properties: { items: { type: 'array' }, total: { type: 'integer' } } })
  // the configured examples
  expect(
    doc.paths[URL].post.requestBody.content['application/json'].schema.properties,
  ).toMatchObject({
    locale: { example: 'zh-CN' },
    purpose: { example: 'notice' },
  })
})
