// @generated by qw-codegen (crud)
// oauth.client (generated CRUD; see docs/design-notes.md#codegen, #api-envelope, #auth-sessions): list filters/sort/paging, get, create,
// update, delete, batch delete, enabled toggle; 403 per permission, 400 translated, 409 duplicate, 404
// unknown ids, @Idempotent, @ActionLog rows, Swagger. Hand-written (G module): the secret answered once
// (create, reset), redirect URI and logo rules, grant rules on the body and on the row a PUT leaves,
// reserved and immutable client ids, the read-only built-in console row (422 B4010), and the client's
// sessions ending when it is deleted or disabled (a deleted id registered again inherits none).
import type { NestExpressApplication } from '@nestjs/platform-express'
import { Test } from '@nestjs/testing'
import { getDataSourceToken } from '@nestjs/typeorm'
import { clientPerms, Err } from '@qiwu/shared'
import { I18nService } from 'nestjs-i18n'
import request from 'supertest'
import type { DataSource } from 'typeorm'
import { AppModule } from '../../src/app.module.js'
import { setupApp } from '../../src/app.setup.js'
import { TokenService } from '../../src/core/auth/token.service.js'
import { REDIS, type Redis } from '../../src/core/redis/redis.module.js'
import { findId, insertRow } from '../../src/db/seeds/upsert.js'
import {
  OAuthProvider,
  secretDigest,
} from '../../src/modules/platform/oauth/provider/provider.service.js'
import { logOf } from '../setup/audit.js'
import { bearer, signIn } from '../setup/auth.js'
import { cleanRedis } from '../setup/redis.js'

const PREFIX = 'e2e-client-'
const URL = '/api/oauth/clients'
const MISSING = 999_999
/** the form's fields, as the edit form sends them back */
const FORM = [
  'clientId',
  'name',
  'logoUrl',
  'grantTypes',
  'redirectUris',
  'scopes',
  'autoApproveScopes',
  'accessTtlSec',
  'refreshTtlSec',
  'enabled',
]
const SECRET = /^[\w-]{43}$/

let app: NestExpressApplication
let ds: DataSource
let redis: Redis
let i18n: I18nService
let tokenService: TokenService
const tokens: Record<'admin' | 'reader' | 'plain', string> = { admin: '', reader: '', plain: '' }
const userIds: number[] = []
let roleId: number
/** the table's last id before this spec: every row above it is this spec's (cleanup) */
let lastId = 0
/** the seeded built-in `console` row */
let consoleId = 0

const call = (
  who: keyof typeof tokens,
  method: 'get' | 'post' | 'put' | 'delete',
  path = '',
  body?: object,
) => {
  const req = request(app.getHttpServer())[method](`${URL}${path}`).set(bearer(tokens[who]))
  return body ? req.send(body) : req
}
const create = (body: object) => call('admin', 'post', '', body)
/** A row added through the API, as POST answers it (with its secret). */
const add = async (body: object) => (await create(body).expect(201)).body.data
let seq = 0
const unique = () => `${PREFIX}${++seq}`
/** A valid POST body made of `tag` (an authorization code client). */
const body = (tag: string, over: object = {}) => ({
  clientId: tag,
  name: `${tag} name`,
  grantTypes: ['authorization_code', 'refresh_token'],
  redirectUris: ['https://app.example.com/cb'],
  scopes: ['user.read'],
  autoApproveScopes: [],
  ...over,
})
/** A translated message (the app's own translations). */
const t = (lang: string, key: string, args?: object) => i18n.t(key, { lang, args }) as string
const label = (lang: string, field: string) => t(lang, `field.oauth.client.${field}`)
const msg = (lang: string, key: string, field: string) =>
  t(lang, key, { field: label(lang, field) })
/** Live rows of the table (a list's total without filters). */
const count = async () =>
  Number((await ds.query('SELECT COUNT(*) AS n FROM oauth_client WHERE deleted_at IS NULL'))[0].n)
const idsOf = (res: request.Response) => res.body.data.items.map((r: { id: number }) => r.id)
/** The stored row, the hash included. */
const stored = async (id: number) =>
  (await ds.query('SELECT * FROM oauth_client WHERE id = ?', [id]))[0]
/** A session of a user (or, `machine`, client_credentials) under OAuth2 client `clientId`. */
async function session(clientId: string, machine = false) {
  const opts = { clientId, scopes: ['user.read'] }
  const issued = machine
    ? await tokenService.issue(
        {
          userId: null,
          userType: 'client',
          deptId: null,
          deptTreePath: null,
          roles: [],
          perms: [],
          locale: null,
          permVer: '0',
        },
        { keepSignedIn: false, ip: '127.0.0.1', ua: 'vitest', ...opts },
      )
    : await signIn(app, 'admin', opts)
  return issued.accessToken
}
/** Whether an access token still names a live session. */
const live = async (accessToken: string) => (await tokenService.authenticate(accessToken)) !== null

async function user(name: string, roles: number[]) {
  const id = await insertRow(ds.manager, 'iam_user', {
    username: PREFIX + name,
    display_name: name,
    password_hash: 'not-used-by-this-spec',
    password_changed_at: new Date(),
  })
  for (const r of roles)
    await ds.query('INSERT INTO iam_user_roles (user_id, role_id) VALUES (?, ?)', [id, r])
  userIds.push(id)
  return (await signIn(app, PREFIX + name)).accessToken
}

beforeAll(async () => {
  const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile()
  app = setupApp(moduleRef.createNestApplication<NestExpressApplication>({ logger: false }))
  await app.listen(0, '127.0.0.1')
  ds = app.get<DataSource>(getDataSourceToken())
  redis = app.get(REDIS)
  i18n = app.get(I18nService)
  tokenService = app.get(TokenService)
  await cleanRedis(redis)
  lastId = Number((await ds.query('SELECT COALESCE(MAX(id), 0) AS n FROM oauth_client'))[0].n)
  consoleId = (await findId(ds.manager, 'oauth_client', { client_id: 'console' }))!
  roleId = await insertRow(ds.manager, 'iam_role', {
    code: `${PREFIX}reader`,
    name: `${PREFIX}reader`,
    data_scope: 'all',
  })
  const browse = await findId(ds.manager, 'iam_menu', { perms: clientPerms.browse })
  await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [roleId, browse])
  tokens.admin = (await signIn(app)).accessToken
  tokens.reader = await user('reader', [roleId])
  tokens.plain = await user('plain', [])
})

afterAll(async () => {
  if (ds) {
    await ds.query('DELETE FROM oauth_client WHERE id > ?', [lastId])
    if (userIds.length) {
      await ds.query('DELETE FROM iam_user_roles WHERE user_id IN (?)', [userIds])
      await ds.query('DELETE FROM iam_user WHERE id IN (?)', [userIds])
    }
    await ds.query('DELETE FROM iam_role_menus WHERE role_id = ?', [roleId])
    await ds.query('DELETE FROM iam_role WHERE id = ?', [roleId])
  }
  if (redis) await cleanRedis(redis)
  await app?.close()
})

describe('CRUD', () => {
  it('create → 201 with the row (defaults filled, audit columns set) and its secret; get returns the row', async () => {
    const tag = unique()
    const res = await create(body(tag)).expect(201)
    const { secret, ...row } = res.body.data
    expect(secret).toMatch(SECRET)
    expect(row).toMatchObject({
      id: expect.any(Number),
      ...body(tag),
      logoUrl: null,
      accessTtlSec: 1800,
      refreshTtlSec: 604_800,
      isBuiltin: false,
      enabled: true,
      createdBy: expect.any(Number),
    })
    expect(row).not.toHaveProperty('secretHash')
    expect(new Date(row.createdAt).toISOString()).toBe(row.createdAt)
    const got = await call('admin', 'get', `/${row.id}`).expect(200)
    expect(got.body.data).toEqual(row)
  })

  it('list: newest first by the sort whitelist, all live rows counted, paging, enabled equals', async () => {
    const ids: number[] = []
    for (let i = 0; i < 3; i++) ids.push((await add(body(unique()))).id)
    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const res = await list({ sort: '-id', pageSize: 3 })
    expect(idsOf(res)).toEqual([...ids].reverse())
    expect(res.body.data.total).toBe(await count())
    expect(idsOf(await list({ sort: '-id', page: 2, pageSize: 2 }))[0]).toBe(ids[0])
    const off = (await add(body(unique(), { enabled: false }))).id
    expect(idsOf(await list({ enabled: 'false', sort: '-id', pageSize: 1 }))).toEqual([off])
    expect(idsOf(await list({ enabled: 'true', sort: '-id', pageSize: 1 }))).toEqual([ids[2]])
  })

  it('list: text filters contain (LIKE wildcards literal) and combine with enabled', async () => {
    const tag = unique()
    for (const suffix of ['a', 'b', 'c']) await add(body(`${tag}-${suffix}`))
    await add(body(`${tag}-off`, { enabled: false }))
    await add(body(`${tag}_x`))

    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const keys = (res: request.Response) =>
      res.body.data.items.map((r: { clientId: string }) => r.clientId)
    const res = await list({ clientId: `${tag}-`, enabled: 'true', sort: '-id' })
    expect(keys(res)).toEqual([`${tag}-c`, `${tag}-b`, `${tag}-a`])
    expect(res.body.data.total).toBe(3)
    expect(keys(await list({ clientId: tag, enabled: 'false' }))).toEqual([`${tag}-off`])
    // `%` and `_` in the filter are plain characters
    expect(keys(await list({ clientId: `${tag}_` }))).toEqual([`${tag}_x`])
    expect(keys(await list({ name: `${tag}-b name` }))).toEqual([`${tag}-b`])
    const page2 = await list({ clientId: `${tag}-`, sort: 'id', page: 2, pageSize: 2 })
    expect(keys(page2)).toEqual([`${tag}-c`, `${tag}-off`])
    expect(page2.body.data.total).toBe(4)
  })

  it('list: the seeded console name matches its text in any language; no row shows a secret', async () => {
    const res = await call('admin', 'get').query({ name: t('en-US', 'seed.oauth.console') })
    expect(res.status).toBe(200)
    expect(idsOf(res)).toContain(consoleId)
    const all = await call('admin', 'get').query({ pageSize: 100 }).expect(200)
    for (const row of all.body.data.items) {
      expect(row).not.toHaveProperty('secret')
      expect(row).not.toHaveProperty('secretHash')
    }
  })

  it('update changes the fields sent and keeps the others; enabled toggles', async () => {
    const tag = unique()
    const { id } = await add(body(tag))
    await call('admin', 'put', `/${id}`, { name: `${tag} renamed` }).expect(200)
    await call('admin', 'put', `/${id}/enabled`, { enabled: false }).expect(200)
    expect((await call('admin', 'get', `/${id}`)).body.data).toMatchObject({
      ...body(tag),
      name: `${tag} renamed`,
      enabled: false,
    })
  })

  it('a row PUT back as loaded (nulls included, as the edit form sends it) → 200, unchanged', async () => {
    const row = await add(body(unique()))
    const loaded = Object.fromEntries(FORM.map((f) => [f, row[f]]))
    await call('admin', 'put', `/${row.id}`, loaded).expect(200)
    expect((await call('admin', 'get', `/${row.id}`)).body.data).toMatchObject(loaded)
  })

  it('delete and batch delete (soft: the rows stay, marked deleted); the clients sessions end', async () => {
    const rows: { id: number; clientId: string }[] = []
    for (let i = 0; i < 3; i++) rows.push(await add(body(unique())))
    const ids = rows.map((r) => r.id)
    const sessions = await Promise.all(rows.map((r) => session(r.clientId)))
    const other = await session('e2e-other-client')
    await call('admin', 'delete', `/${ids[0]}`).expect(200)
    expect(await live(sessions[0]!)).toBe(false)
    expect(await live(sessions[1]!)).toBe(true)
    await call('admin', 'post', '/batch-delete', { ids: ids.slice(1) }).expect(200)
    for (const s of sessions) expect(await live(s)).toBe(false)
    expect(await live(other)).toBe(true)
    expect(
      await ds.query('SELECT id FROM oauth_client WHERE id IN (?) AND deleted_at IS NULL', [ids]),
    ).toEqual([])
    expect(await ds.query('SELECT id FROM oauth_client WHERE id IN (?)', [ids])).toHaveLength(3)
    await call('admin', 'get', `/${ids[0]}`).expect(404)
  })

  it('a deleted client id can be registered again; the new row inherits none of the old sessions', async () => {
    const old = await add(body(unique()))
    const user = await session(old.clientId)
    const machine = await session(old.clientId, true)
    await call('admin', 'delete', `/${old.id}`).expect(200)
    const again = await add({ ...body(unique()), clientId: old.clientId })
    expect(again.id).not.toBe(old.id)
    expect(await live(user)).toBe(false)
    expect(await live(machine)).toBe(false)
  })
})

describe('sessions', () => {
  it('disabling (PUT /:id/enabled or PUT /:id) ends every session of the client, the others stay', async () => {
    const a = await add(body(unique()))
    const b = await add(body(unique()))
    const [aUser, aMachine, bUser] = [
      await session(a.clientId),
      await session(a.clientId, true),
      await session(b.clientId),
    ]
    await call('admin', 'put', `/${a.id}/enabled`, { enabled: false }).expect(200)
    expect(await live(aUser)).toBe(false)
    expect(await live(aMachine)).toBe(false)
    expect(await live(bUser)).toBe(true)
    await call('admin', 'put', `/${b.id}`, { name: 'still on' }).expect(200)
    expect(await live(bUser)).toBe(true)
    await call('admin', 'put', `/${b.id}`, { enabled: false }).expect(200)
    expect(await live(bUser)).toBe(false)
  })

  it('a refused change (400, 422) ends no session', async () => {
    const a = await add(body(unique()))
    const s = await session(a.clientId)
    await call('admin', 'put', `/${a.id}`, { enabled: false, redirectUris: [] }).expect(400)
    expect(await live(s)).toBe(true)
  })
})

describe('secret', () => {
  it('created and reset secrets are answered once, stored as digests the provider accepts; a reset keeps sessions', async () => {
    const { id, clientId, secret } = await add(body(unique()))
    const hash = (await stored(id)).secret_hash as string
    expect(hash).toBe(secretDigest(secret))
    expect(await app.get(OAuthProvider).authenticate(clientId, secret)).toMatchObject({ id })
    const s = await session(clientId)

    const res = await call('admin', 'post', `/${id}/secret`).expect(200)
    expect(Object.keys(res.body.data)).toEqual(['secret'])
    const fresh = res.body.data.secret
    expect(fresh).toMatch(SECRET)
    expect(fresh).not.toBe(secret)
    const rehash = (await stored(id)).secret_hash as string
    expect(rehash).toBe(secretDigest(fresh))
    expect(await app.get(OAuthProvider).authenticate(clientId, secret)).toBeNull()
    expect(await live(s)).toBe(true)
    const got = (await call('admin', 'get', `/${id}`).expect(200)).body.data
    expect(got).not.toHaveProperty('secret')
    expect(got).not.toHaveProperty('secretHash')
  })

  it('a POST cannot forge a built-in row or its own secret', async () => {
    const row = await add(body(unique(), { isBuiltin: true, secret: 'mine', secretHash: 'mine' }))
    expect(row.isBuiltin).toBe(false)
    expect(row.secret).not.toBe('mine')
    const db = await stored(row.id)
    expect(db.is_builtin).toBe(0)
    expect(db.secret_hash).toBe(secretDigest(row.secret))
  })

  it('the same reset twice within 3 s → 429 (@Idempotent): the secret shown first stays valid', async () => {
    const { id } = await add(body(unique()))
    const first = (await call('admin', 'post', `/${id}/secret`).expect(200)).body.data.secret
    const again = await call('admin', 'post', `/${id}/secret`).expect(429)
    expect(again.body.code).toBe(Err.TOO_MANY_REQUESTS.code)
    expect((await stored(id)).secret_hash).toBe(secretDigest(first))
  })
})

describe('rules', () => {
  const BAD_URIS = [
    'http://evil.com/cb',
    'https://a.com/cb#x',
    'https://a.com/cb#',
    'https://*.a.com/cb',
    'https://user@a.com/cb',
    'https://a.com:pw@b.com/cb',
    'ftp://a.com/cb',
    '/cb',
    'https:/a.com/cb',
    'com.example.app:/cb',
    'http://localhost.evil.com/cb',
    'http://[::1]/cb',
    'https://a.com/c b',
    'HTTPS://a.com/cb',
    'https://a.com/c\\b',
    'https://:pw@a.com/cb',
    'https://a.com/c\x01b',
    'https://a.com/c\x7fb',
  ]

  it('redirect URIs: https, http only for localhost / 127.0.0.1, no fragment, *, userinfo or spaces (POST and PUT)', async () => {
    const { id } = await add(body(unique()))
    for (const uri of BAD_URIS) {
      const redirectUris = ['https://ok.example.com/cb', uri]
      for (const res of [
        await create(body(unique(), { redirectUris })),
        await call('admin', 'put', `/${id}`, { redirectUris }),
      ]) {
        // the URI on both sides: a failure names it
        expect({ uri, status: res.status, errors: res.body.errors }).toEqual({
          uri,
          status: 400,
          errors: [
            {
              path: 'redirectUris.1',
              msg: msg('zh-CN', 'validation.oauth.redirect_uri', 'redirectUris'),
            },
          ],
        })
      }
    }
    const en = await create(body(unique(), { redirectUris: [BAD_URIS[0]] }))
      .set('Accept-Language', 'en-US')
      .expect(400)
    expect(en.body.msg).toBe(msg('en-US', 'validation.oauth.redirect_uri', 'redirectUris'))
    expect((await call('admin', 'get', `/${id}`)).body.data.redirectUris).toEqual(
      body('').redirectUris,
    )
    const good = ['https://a.com/cb?x=1', 'http://localhost:8080/cb', 'http://127.0.0.1/cb']
    expect((await add(body(unique(), { redirectUris: good }))).redirectUris).toEqual(good)
  })

  it('logo: an https address or a path on this site; blank is none', async () => {
    for (const logoUrl of [
      'http://a.com/x.png',
      '//evil.com/x.png',
      '/\\evil.com/x.png',
      'javascript:alert(1)',
      'data:image/png;base64,AAAA',
      'https://a.com/x y.png',
    ]) {
      const res = await create(body(unique(), { logoUrl }))
      expect({ logoUrl, status: res.status, errors: res.body.errors }).toEqual({
        logoUrl,
        status: 400,
        errors: [{ path: 'logoUrl', msg: msg('zh-CN', 'validation.oauth.logo_url', 'logoUrl') }],
      })
    }
    for (const logoUrl of ['https://cdn.example.com/x.png', '/files/public/x.png'])
      expect((await add(body(unique(), { logoUrl }))).logoUrl).toBe(logoUrl)
    expect((await add(body(unique(), { logoUrl: ' ' }))).logoUrl).toBeNull()
  })

  it('grants: at least one known grant; refresh needs code; code needs redirect URIs and scopes; auto-approved ⊆ scopes; no duplicates', async () => {
    const cases: [object, string, string][] = [
      [{ grantTypes: [] }, 'grantTypes', 'validation.too_small.array'],
      [{ grantTypes: ['password'] }, 'grantTypes.0', 'validation.invalid_value'],
      [{ grantTypes: ['implicit'] }, 'grantTypes.0', 'validation.invalid_value'],
      [{ grantTypes: ['refresh_token'] }, 'grantTypes', 'validation.oauth.refresh_needs_code'],
      [{ redirectUris: [] }, 'redirectUris', 'validation.required'],
      [
        { redirectUris: Array.from({ length: 11 }, (_, i) => `https://a.com/cb${i}`) },
        'redirectUris',
        'validation.too_big.array',
      ],
      [{ scopes: [] }, 'scopes', 'validation.required'],
      [{ scopes: ['user.write'] }, 'scopes.0', 'validation.invalid_value'],
      [
        { grantTypes: ['client_credentials'], scopes: [], autoApproveScopes: ['user.read'] },
        'autoApproveScopes',
        'validation.oauth.auto_approve_subset',
      ],
      [
        { redirectUris: ['https://a.com/cb', 'https://a.com/cb'] },
        'redirectUris',
        'validation.oauth.duplicate',
      ],
      [
        { grantTypes: ['authorization_code', 'authorization_code'] },
        'grantTypes',
        'validation.oauth.duplicate',
      ],
    ]
    for (const [over, path, key] of cases) {
      const res = await create(body(unique(), over))
      expect({ over, status: res.status, error: res.body.errors?.[0] }).toMatchObject({
        over,
        status: 400,
        error: { path },
      })
      if (!key.endsWith('invalid_value') && !key.startsWith('validation.too_'))
        expect(res.body.errors[0].msg).toBe(msg('zh-CN', key, path.split('.')[0]!))
    }
    const machine = await add(
      body(unique(), { grantTypes: ['client_credentials'], redirectUris: [], scopes: [] }),
    )
    expect(machine.grantTypes).toEqual(['client_credentials'])
  })

  it('a PUT is judged on the row it leaves: dropping the redirect URIs of a code client → 400, unchanged', async () => {
    const { id } = await add(body(unique()))
    const res = await call('admin', 'put', `/${id}`, { redirectUris: [] }).expect(400)
    expect(res.body.errors).toEqual([
      { path: 'redirectUris', msg: msg('zh-CN', 'validation.required', 'redirectUris') },
    ])
    await call('admin', 'put', `/${id}`, { grantTypes: ['refresh_token'] }).expect(400)
    expect(await stored(id)).toMatchObject({
      redirect_uris: body('').redirectUris,
      grant_types: body('').grantTypes,
    })
    // a client_credentials client needs none
    await call('admin', 'put', `/${id}`, {
      grantTypes: ['client_credentials'],
      redirectUris: [],
    }).expect(200)
  })

  it('client id: lowercase [a-z0-9._-], 3–64; console and mobile are reserved; never changed by a PUT', async () => {
    for (const clientId of ['console', 'mobile']) {
      const res = await create(body(unique(), { clientId })).expect(400)
      expect(res.body.errors).toEqual([
        {
          path: 'clientId',
          msg: msg('zh-CN', 'validation.oauth.client_id_reserved', 'clientId'),
        },
      ])
    }
    for (const clientId of ['Bad_ID', 'ab', '-abc', 'a'.repeat(65), 'a b c'])
      await create(body(unique(), { clientId })).expect(400)
    const row = await add(body(unique()))
    await call('admin', 'put', `/${row.id}`, { clientId: 'renamed-client' }).expect(200)
    expect((await stored(row.id)).client_id).toBe(row.clientId)
  })
})

describe('built-in console client', () => {
  it('is read-only: change, enable/disable, reset secret, delete, batch delete → 422 B4010; nothing changes', async () => {
    const before = await stored(consoleId)
    const other = await add(body(unique()))
    for (const res of [
      await call('admin', 'put', `/${consoleId}`, { name: 'mine' }),
      await call('admin', 'put', `/${consoleId}`, {
        grantTypes: ['client_credentials'],
        redirectUris: [],
        scopes: [],
      }),
      await call('admin', 'put', `/${consoleId}/enabled`, { enabled: false }),
      await call('admin', 'post', `/${consoleId}/secret`),
      await call('admin', 'delete', `/${consoleId}`),
      await call('admin', 'post', '/batch-delete', { ids: [consoleId, other.id] }),
    ]) {
      expect(res.status).toBe(422)
      expect(res.body).toMatchObject({
        code: Err.OAUTH_CLIENT_BUILTIN.code,
        msg: t('zh-CN', Err.OAUTH_CLIENT_BUILTIN.key),
      })
    }
    expect(Err.OAUTH_CLIENT_BUILTIN.code).toBe('B4010')
    expect(await stored(consoleId)).toEqual(before)
    await call('admin', 'get', `/${other.id}`).expect(200)
    // the admin's own console session is untouched
    await call('admin', 'get', `/${consoleId}`).expect(200)
  })
})

describe('errors', () => {
  it('403 per permission: browse-only may list, not view/create/modify/reset/delete; no perm → no list', async () => {
    const { id } = await add(body(unique()))
    await call('reader', 'get').expect(200)
    const forbidden = [
      call('reader', 'get', `/${id}`),
      call('reader', 'post', '', body(unique())),
      call('reader', 'put', `/${id}`, {}),
      call('reader', 'put', `/${id}/enabled`, { enabled: false }),
      call('reader', 'post', `/${id}/secret`),
      call('reader', 'delete', `/${id}`),
      call('reader', 'post', '/batch-delete', { ids: [id] }),
      call('plain', 'get'),
    ]
    for (const res of await Promise.all(forbidden)) {
      expect(res.status).toBe(403)
      expect(res.body.code).toBe(Err.FORBIDDEN.code)
    }
  })

  it('400: invalid body / query / id, with translated field messages', async () => {
    const { id } = await add(body(unique()))
    expect(label('zh-CN', 'clientId')).not.toMatch(/^field\./)
    expect(label('en-US', 'clientId')).not.toMatch(/^field\./)
    const zh = await create({ ...body(unique()), clientId: 'Bad_ID', name: 'x'.repeat(65) }).expect(
      400,
    )
    expect(zh.body).toMatchObject({
      code: Err.VALIDATION_FAILED.code,
      msg: msg('zh-CN', 'validation.invalid_format.other', 'clientId'),
    })
    expect(zh.body.errors).toEqual([
      { path: 'clientId', msg: msg('zh-CN', 'validation.invalid_format.other', 'clientId') },
      {
        path: 'name',
        msg: t('zh-CN', 'validation.too_big.string', {
          field: label('zh-CN', 'name'),
          maximum: 64,
        }),
      },
    ])
    const { clientId: _, ...keyless } = body(unique())
    const en = await create(keyless).set('Accept-Language', 'en-US').expect(400)
    expect(en.body.errors).toEqual([
      { path: 'clientId', msg: msg('en-US', 'validation.required', 'clientId') },
    ])
    await call('admin', 'get').query({ sort: 'logoUrl' }).expect(400)
    await call('admin', 'put', `/${id}/enabled`, { enabled: 'no' }).expect(400)
    await call('admin', 'post', '/batch-delete', { ids: [] }).expect(400)
    await call('admin', 'get', '/abc').expect(400)
    await call('admin', 'post', '/abc/secret').expect(400)
  })

  it('409 duplicate: a live client id already taken (exact, case-sensitive ids)', async () => {
    const taken = await add(body(unique()))
    const res = await create({ ...body(unique()), clientId: taken.clientId })
    expect(res.status).toBe(409)
    expect(res.body).toMatchObject({
      code: Err.DUPLICATE.code,
      msg: t('zh-CN', Err.DUPLICATE.key),
    })
  })

  it('404: unknown ids for get, update, enabled, reset, delete; a batch with one unknown id deletes nothing', async () => {
    const { id } = await add(body(unique()))
    for (const res of [
      await call('admin', 'get', `/${MISSING}`),
      await call('admin', 'put', `/${MISSING}`, {}),
      await call('admin', 'put', `/${MISSING}/enabled`, { enabled: true }),
      await call('admin', 'post', `/${MISSING}/secret`),
      await call('admin', 'delete', `/${MISSING}`),
      await call('admin', 'post', '/batch-delete', { ids: [id, MISSING] }),
    ]) {
      expect(res.status).toBe(404)
      expect(res.body.code).toBe(Err.NOT_FOUND.code)
    }
    await call('admin', 'get', `/${id}`).expect(200)
  })

  it('the same create submitted twice within 3 s → 429 (@Idempotent)', async () => {
    const tag = unique()
    await create(body(tag)).expect(201)
    const again = await create(body(tag)).expect(429)
    expect(again.body.code).toBe(Err.TOO_MANY_REQUESTS.code)
  })
})

it('@ActionLog: every write leaves a row with domain oauth.client, its verb and the id; no secret in it', async () => {
  const trace = `${PREFIX}${process.pid}-`
  const created = await create(body(unique())).set('X-Request-Id', `${trace}c`).expect(201)
  const { id, secret } = created.body.data
  await call('admin', 'put', `/${id}`, {}).set('X-Request-Id', `${trace}u`)
  await call('admin', 'put', `/${id}/enabled`, { enabled: false }).set('X-Request-Id', `${trace}e`)
  const reset = await call('admin', 'post', `/${id}/secret`).set('X-Request-Id', `${trace}s`)
  await call('admin', 'delete', `/${id}`).set('X-Request-Id', `${trace}d`)
  await call('admin', 'post', '/batch-delete', { ids: [MISSING] }).set('X-Request-Id', `${trace}b`)
  const expected: [string, object][] = [
    ['c', { verb: 'create', biz_id: String(id), ok: 1 }],
    ['u', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['e', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['s', { verb: 'reset-secret', biz_id: String(id), ok: 1 }],
    ['d', { verb: 'remove', biz_id: String(id), ok: 1 }],
    ['b', { verb: 'remove', biz_id: null, ok: 0, error_msg: Err.NOT_FOUND.key }],
  ]
  for (const [suffix, row] of expected) {
    const log = await logOf(ds, `${trace}${suffix}`)
    expect(log).toMatchObject({ domain: 'oauth.client', username: 'admin', ...row })
    for (const plain of [secret, reset.body.data.secret])
      expect(JSON.stringify(log)).not.toContain(plain)
  }
})

it('Swagger documents every route', async () => {
  const doc = (await request(app.getHttpServer()).get('/api/docs-json').expect(200)).body
  expect(
    Object.keys(doc.paths)
      .filter((p) => p.startsWith(URL))
      .sort(),
  ).toEqual([
    URL,
    `${URL}/batch-delete`,
    `${URL}/{id}`,
    `${URL}/{id}/enabled`,
    `${URL}/{id}/secret`,
  ])
  expect(
    doc.paths[URL].get.responses['200'].content['application/json'].schema.properties.data,
  ).toMatchObject({ properties: { items: { type: 'array' }, total: { type: 'integer' } } })
  const created = doc.paths[URL].post.responses['201'].content['application/json'].schema
  expect(JSON.stringify(created)).toContain('secret')
})
