// @generated by qw-codegen (crud)
// wf.form (generated CRUD; see docs/design-notes.md#codegen, #api-envelope): list filters/sort/paging, get, create, update, delete,
// batch delete, enabled toggle;
// 403 per permission, 400 translated, 409 duplicate, 404 unknown ids, @Idempotent, @ActionLog rows,
// Swagger. Hand-written: the schema is sanitized on create and update (code,
// behaviour keys and unknown components → 400, unlisted keys dropped; see docs/design-notes.md#workflow), the list leaves schemas out, a
// form a model binds cannot be deleted (409 in_use).
// A dynamic model bound to a form publishes it; starting binds the form's `qw-upload`
// files (the initiator's own unbound `wf.attachment` uploads, else 400 and nothing started) to the
// instance, whose approvers and cc recipients may then download them (`wf.attachment` checker), others 403.
// The calc components' results (days, detail totals) are recomputed by the server on
// start, approve and resubmit over what the client sent, and the forks branch on them.
// start-info hands out the published form; the detail drops a step's `hide` fields (rule and value)
// for whoever holds or held a task on it, and marks the pending step's `edit` fields.
// Start, approve and resubmit check each value as its component holds it (options, ranges,
// required); a file downloads only for whoever may read the field naming it (a manual cc as the step that
// sent it); approve and resubmit bind the files they add.
import type { NestExpressApplication } from '@nestjs/platform-express'
import { Test } from '@nestjs/testing'
import { getDataSourceToken } from '@nestjs/typeorm'
import { Err, wfPerms } from '@qiwu/shared'
import { I18nService } from 'nestjs-i18n'
import request from 'supertest'
import type { DataSource } from 'typeorm'
import { AppModule } from '../../src/app.module.js'
import { setupApp } from '../../src/app.setup.js'
import { REDIS, type Redis } from '../../src/core/redis/redis.module.js'
import { findId, insertRow } from '../../src/db/seeds/upsert.js'
import { logOf } from '../setup/audit.js'
import { bearer, signIn } from '../setup/auth.js'
import { cleanRedis } from '../setup/redis.js'

const PREFIX = 'e2e-form-'
const URL = '/api/wf/forms'
const MISSING = 999_999
/** the form's fields, as the edit form sends them back */
const FORM = ['name', 'schemaJson', 'enabled', 'note']
/** a schema as sanitizeFormSchema returns it (nothing to strip) */
const SCHEMA = {
  rule: [
    { type: 'input', field: 'reason', title: 'Reason', props: { placeholder: 'why' } },
    { type: 'inputNumber', field: 'days', title: 'Days', $required: true, props: { min: 0 } },
  ],
  option: { form: { labelPosition: 'top' } },
}

let app: NestExpressApplication
let ds: DataSource
let redis: Redis
let i18n: I18nService
const tokens: Record<'admin' | 'reader' | 'plain', string> = { admin: '', reader: '', plain: '' }
const userIds: number[] = []
/** user ids by name (`user()`) */
const named: Record<string, number> = {}
let roleId: number
/** the table's last id before this spec: every row above it is this spec's (cleanup) */
let lastId = 0

const call = (
  who: keyof typeof tokens,
  method: 'get' | 'post' | 'put' | 'delete',
  path = '',
  body?: object,
) => {
  const req = request(app.getHttpServer())[method](`${URL}${path}`).set(bearer(tokens[who]))
  return body ? req.send(body) : req
}
const create = (body: object) => call('admin', 'post', '', body)
/** A row added through the API, as POST answers it. */
const add = async (body: object) => (await create(body).expect(201)).body.data
let seq = 0
const unique = () => `${PREFIX}${++seq}`
/** A valid POST body made of `tag` (required and unique fields, the configured examples). */
const body = (tag: string, over: object = {}) => ({
  name: tag,
  schemaJson: SCHEMA,
  ...over,
})
/** A translated message (the app's own translations). */
const t = (lang: string, key: string, args?: object) => i18n.t(key, { lang, args }) as string
const label = (lang: string, field: string) => t(lang, `field.wf.form.${field}`)
/** Live rows of the table (a list's total without filters). */
const count = async () =>
  Number((await ds.query('SELECT COUNT(*) AS n FROM wf_form WHERE deleted_at IS NULL'))[0].n)
const idsOf = (res: request.Response) => res.body.data.items.map((r: { id: number }) => r.id)

async function user(name: string, roles: number[]) {
  const id = await insertRow(ds.manager, 'iam_user', {
    username: PREFIX + name,
    display_name: name,
    password_hash: 'not-used-by-this-spec',
    password_changed_at: new Date(),
  })
  for (const r of roles)
    await ds.query('INSERT INTO iam_user_roles (user_id, role_id) VALUES (?, ?)', [id, r])
  userIds.push(id)
  named[name] = id
  return (await signIn(app, PREFIX + name)).accessToken
}

beforeAll(async () => {
  const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile()
  app = setupApp(moduleRef.createNestApplication<NestExpressApplication>({ logger: false }))
  await app.listen(0, '127.0.0.1')
  ds = app.get<DataSource>(getDataSourceToken())
  redis = app.get(REDIS)
  i18n = app.get(I18nService)
  await cleanRedis(redis)
  lastId = Number((await ds.query('SELECT COALESCE(MAX(id), 0) AS n FROM wf_form'))[0].n)
  roleId = await insertRow(ds.manager, 'iam_role', {
    code: `${PREFIX}reader`,
    name: `${PREFIX}reader`,
    data_scope: 'all',
  })
  const browse = await findId(ds.manager, 'iam_menu', { perms: wfPerms.form.browse })
  await ds.query('INSERT INTO iam_role_menus (role_id, menu_id) VALUES (?, ?)', [roleId, browse])
  tokens.admin = (await signIn(app)).accessToken
  tokens.reader = await user('reader', [roleId])
  tokens.plain = await user('plain', [])
})

afterAll(async () => {
  if (ds) {
    await ds.query('DELETE FROM wf_form WHERE id > ?', [lastId])
    const sub = `SELECT id FROM wf_instance WHERE model_key LIKE '${PREFIX}%'`
    for (const t of ['wf_task', 'wf_cc', 'wf_event'])
      await ds.query(`DELETE FROM ${t} WHERE instance_id IN (${sub})`)
    for (const t of ['wf_instance', 'wf_version', 'wf_model'])
      await ds.query(`DELETE FROM ${t} WHERE model_key LIKE ?`, [`${PREFIX}%`])
    if (userIds.length) {
      await ds.query('DELETE FROM fs_object WHERE uploader_id IN (?)', [userIds])
      await ds.query('DELETE FROM iam_user_roles WHERE user_id IN (?)', [userIds])
      await ds.query('DELETE FROM iam_user WHERE id IN (?)', [userIds])
    }
    await ds.query('DELETE FROM iam_role_menus WHERE role_id = ?', [roleId])
    await ds.query('DELETE FROM iam_role WHERE id = ?', [roleId])
  }
  if (redis) await cleanRedis(redis)
  await app?.close()
})

describe('CRUD', () => {
  it('create → 201 with the row (defaults filled, audit columns set); get returns it', async () => {
    const tag = unique()
    const res = await create(body(tag)).expect(201)
    const row = res.body.data
    expect(row).toMatchObject({
      id: expect.any(Number),
      ...body(tag),
      enabled: true,
      note: null,
      createdBy: expect.any(Number),
    })
    expect(new Date(row.createdAt).toISOString()).toBe(row.createdAt)
    const got = await call('admin', 'get', `/${row.id}`).expect(200)
    expect(got.body.data).toEqual(row)
  })

  it('list: newest first by the sort whitelist, all live rows counted, paging, enabled equals, created_at range', async () => {
    const ids: number[] = []
    for (let i = 0; i < 3; i++) ids.push((await add(body(unique()))).id)
    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const res = await list({ sort: '-id', pageSize: 3 })
    expect(idsOf(res)).toEqual([...ids].reverse())
    // schemas come with the detail only
    expect(res.body.data.items[0]).not.toHaveProperty('schemaJson')
    expect(res.body.data.total).toBe(await count())
    expect(idsOf(await list({ sort: '-id', page: 2, pageSize: 2 }))[0]).toBe(ids[0])
    const off = (await add(body(unique(), { enabled: false }))).id
    expect(idsOf(await list({ enabled: 'false', sort: '-id', pageSize: 1 }))).toEqual([off])
    expect(idsOf(await list({ enabled: 'true', sort: '-id', pageSize: 1 }))).toEqual([ids[2]])
    // created_at from / to: instants (ISO-8601 with an offset)
    const [{ at }] = await ds.query('SELECT created_at AS at FROM wf_form WHERE id = ?', [ids[0]])
    const around = (ms: number) => new Date(at.getTime() + ms).toISOString()
    expect(
      idsOf(await list({ createdAtFrom: around(-1000), createdAtTo: around(1000), sort: '-id' })),
    ).toContain(ids[0])
    expect(idsOf(await list({ createdAtTo: around(-1000), sort: '-id' }))).not.toContain(ids[0])
  })

  it('list: text filters contain (LIKE wildcards literal) and combine with enabled', async () => {
    const tag = unique()
    for (const suffix of ['a', 'b', 'c']) await add(body(`${tag}-${suffix}`))
    await add(body(`${tag}-off`, { enabled: false }))
    await add(body(`${tag}_x`))

    const list = (query: object) => call('admin', 'get').query(query).expect(200)
    const keys = (res: request.Response) => res.body.data.items.map((r: { name: string }) => r.name)
    const res = await list({ name: `${tag}-`, enabled: 'true', sort: '-id' })
    expect(keys(res)).toEqual([`${tag}-c`, `${tag}-b`, `${tag}-a`])
    expect(res.body.data.total).toBe(3)
    expect(keys(await list({ name: tag, enabled: 'false' }))).toEqual([`${tag}-off`])
    // `%` and `_` in the filter are plain characters
    expect(keys(await list({ name: `${tag}_` }))).toEqual([`${tag}_x`])
    const page2 = await list({ name: `${tag}-`, sort: 'id', page: 2, pageSize: 2 })
    expect(keys(page2)).toEqual([`${tag}-c`, `${tag}-off`])
    expect(page2.body.data.total).toBe(4)
  })

  it('update changes the fields sent and keeps the others; enabled toggles', async () => {
    const tag = unique()
    const { id } = await add(body(tag))
    await call('admin', 'put', `/${id}`, { note: `${tag} renamed` }).expect(200)
    await call('admin', 'put', `/${id}/enabled`, { enabled: false }).expect(200)
    expect((await call('admin', 'get', `/${id}`)).body.data).toMatchObject({
      ...body(tag),
      note: `${tag} renamed`,
      enabled: false,
    })
  })

  it('a row PUT back as loaded (nulls included, as the edit form sends it) → 200, unchanged', async () => {
    const row = await add(body(unique()))
    const loaded = Object.fromEntries(FORM.map((f) => [f, row[f]]))
    await call('admin', 'put', `/${row.id}`, loaded).expect(200)
    expect((await call('admin', 'get', `/${row.id}`)).body.data).toMatchObject(loaded)
  })

  it('delete and batch delete (soft: the rows stay, marked deleted)', async () => {
    const ids: number[] = []
    for (let i = 0; i < 3; i++) ids.push((await add(body(unique()))).id)
    await call('admin', 'delete', `/${ids[0]}`).expect(200)
    await call('admin', 'post', '/batch-delete', { ids: ids.slice(1) }).expect(200)
    expect(
      await ds.query('SELECT id FROM wf_form WHERE id IN (?) AND deleted_at IS NULL', [ids]),
    ).toEqual([])
    expect(await ds.query('SELECT id FROM wf_form WHERE id IN (?)', [ids])).toHaveLength(3)
    await call('admin', 'get', `/${ids[0]}`).expect(404)
    // unique among live rows only: a deleted row's name can be used again
    const { name } = (await ds.query('SELECT name AS name FROM wf_form WHERE id = ?', [ids[0]]))[0]
    // (another note: the same body as the deleted row's create would be a duplicate submit, 429)
    await create({ ...body(unique()), name, note: 'reused' }).expect(201)
  })
})

describe('schema (a form-create schema is code, sanitized on save; see docs/design-notes.md#workflow)', () => {
  const one = (over: object) => ({ rule: [{ type: 'input', field: 'f', ...over }] })

  it('create and update store what sanitizeFormSchema returns: keys outside the whitelist dropped', async () => {
    const dirty = {
      rule: [
        {
          type: 'input',
          field: 'f',
          title: 'F',
          props: { placeholder: 'p', autofocus: true },
          x: 1,
        },
      ],
      option: { form: { labelPosition: 'top' }, global: { input: { props: { x: 1 } } } },
    }
    const clean = {
      rule: [{ type: 'input', field: 'f', title: 'F', props: { placeholder: 'p' } }],
      option: { form: { labelPosition: 'top' } },
    }
    const { id, schemaJson } = await add(body(unique(), { schemaJson: dirty }))
    expect(schemaJson).toEqual(clean)
    const stored = async () =>
      (await ds.query('SELECT schema_json AS s FROM wf_form WHERE id = ?', [id]))[0].s
    expect(await stored()).toEqual(clean)
    const renamed = (field: string, of: typeof dirty | typeof clean) => ({
      ...of,
      rule: [{ ...of.rule[0], field }],
    })
    await call('admin', 'put', `/${id}`, { schemaJson: renamed('g', dirty) }).expect(200)
    expect(await stored()).toEqual(renamed('g', clean))
    expect((await call('admin', 'get', `/${id}`)).body.data.schemaJson).toEqual(renamed('g', clean))
  })

  it('400 for code, behaviour keys, unknown components or a bad shape anywhere; nothing stored', async () => {
    const { id } = await add(body(unique()))
    const before = await count()
    const cases: [schema: unknown, path: string, key: string, params: object][] = [
      [one({ value: '$FN:alert(1)' }), 'rule.0.value', 'code', { path: 'rule.0.value' }],
      [
        one({ props: { placeholder: ' \u0028) => fetch(1)' } }),
        'rule.0.props.placeholder',
        'code',
        { path: 'rule.0.props.placeholder' },
      ],
      [
        one({ title: '[[FORM-CREATE-PREFIX-function(){}-FORM-CREATE-SUFFIX]]' }),
        'rule.0.title',
        'code',
        { path: 'rule.0.title' },
      ],
      [one({ on: { change: 'x' } }), 'rule.0.on', 'forbidden_key', { key: 'on' }],
      [
        { rule: [], option: { form: { effect: { fetch: { action: '/api/x' } } } } },
        'option.form.effect',
        'forbidden_key',
        { key: 'effect' },
      ],
      [{ rule: [{ type: 'html', field: 'f' }] }, 'rule.0.type', 'unknown_type', { type: 'html' }],
      [
        { rule: [one({}).rule[0], one({}).rule[0]] },
        'rule.1.field',
        'duplicate_field',
        { name: 'f' },
      ],
    ]
    for (const [schemaJson, path, key, params] of cases)
      for (const res of [
        await create(body(unique(), { schemaJson })),
        await call('admin', 'put', `/${id}`, { schemaJson }),
      ]) {
        const msg = t('zh-CN', `validation.form.${key}`, params)
        expect({ path, status: res.status, body: res.body }).toMatchObject({
          path,
          status: 400,
          body: {
            code: Err.VALIDATION_FAILED.code,
            msg,
            errors: [{ path: `schemaJson.${path}`, msg }],
          },
        })
      }
    // the whitelist's shape errors: zod's messages under the schema's label
    const shape = await create(body(unique(), { schemaJson: 'not a schema' })).expect(400)
    expect(shape.body.errors).toEqual([
      { path: 'schemaJson', msg: expect.not.stringMatching(/^validation\./) },
    ])
    const { schemaJson: _, ...schemaless } = body(unique())
    const missing = await create(schemaless).expect(400)
    expect(missing.body.errors).toEqual([{ path: 'schemaJson', msg: expect.any(String) }])
    expect(await count()).toBe(before)
    expect((await call('admin', 'get', `/${id}`)).body.data.schemaJson).toEqual(SCHEMA)
  })

  it('a form a live model binds cannot be deleted (409 in_use); unbound, it can', async () => {
    const { id } = await add(body(unique()))
    const { insertId } = await ds.query(
      "INSERT INTO wf_model (model_key, name, form_kind, form_id) VALUES (?, 'x', 'dynamic', ?)",
      [`${PREFIX}${id}`, id],
    )
    const res = await call('admin', 'delete', `/${id}`).expect(409)
    expect(res.body.code).toBe(Err.IN_USE.code)
    await ds.query('UPDATE wf_model SET deleted_at = NOW(3) WHERE id = ?', [insertId])
    await call('admin', 'delete', `/${id}`).expect(200)
  })
})

describe('attachment: a dynamic model starts with its form uploads bound to the instance', () => {
  const people = ['starter', 'approver', 'ccer', 'outsider'] as const
  const tk: Record<string, string> = {}
  let modelKey: string
  const http = () => request(app.getHttpServer())
  let files = 0
  /** A PDF uploaded by `who` (a different body each time: a repeat within 3 s is a duplicate submit). */
  const upload = async (who: string, bizTag = 'wf.attachment') => {
    const name = `f${++files}.pdf`
    const pdf = Buffer.from(`%PDF-1.4\n% ${name}\ntrailer\n<<>>\n%%EOF\n`)
    const res = await http()
      .post('/api/storage/objects')
      .set(bearer(tk[who]!))
      .field('bizTag', bizTag)
      .attach('file', pdf, name)
      .expect(201)
    return `${res.body.data.id}/${name}`
  }
  const idOf = (ref: string) => Number(ref.split('/')[0])
  const refOf = async (ref: string) =>
    (await ds.query('SELECT biz_ref AS r FROM fs_object WHERE id = ?', [idOf(ref)]))[0].r
  const download = (who: string, ref: string) =>
    http()
      .get(`/api/storage/objects/${idOf(ref)}/download`)
      .set(bearer(who === 'admin' ? tokens.admin : tk[who]!))
  let amount = 0
  /** POST /wf/instances as the starter (`amount` differs each time: no duplicate submit). */
  const start = (files: unknown) =>
    http()
      .post('/api/wf/instances')
      .set(bearer(tk.starter!))
      .send({ modelKey, formValues: { files, amount: ++amount } })
  const instances = async () =>
    Number(
      (await ds.query('SELECT COUNT(*) AS n FROM wf_instance WHERE model_key = ?', [modelKey]))[0]
        .n,
    )

  beforeAll(async () => {
    for (const who of people) tk[who] = await user(who, [])
    const schemaJson = {
      rule: [
        { type: 'qw-upload', field: 'files', title: 'Files', props: { limit: 2 } },
        { type: 'inputNumber', field: 'amount', title: 'Amount' },
      ],
    }
    const form = await add(body(unique(), { schemaJson }))
    const admin = (method: 'post' | 'put', path: string, payload: object) =>
      http()[method](`/api/wf/models${path}`).set(bearer(tokens.admin)).send(payload)
    modelKey = unique()
    const model = (
      await admin('post', '', {
        modelKey,
        name: 'Att',
        formKind: 'dynamic',
        formId: form.id,
      }).expect(201)
    ).body.data
    const tree = {
      id: 'begin',
      type: 'begin',
      name: 'Begin',
      next: {
        id: 'cc',
        type: 'notify',
        name: 'Copy',
        assignee: { kind: 'users', ids: [named.ccer] },
        next: {
          id: 'ok',
          type: 'review',
          name: 'Review',
          assignee: { kind: 'users', ids: [named.approver] },
          sign: 'any',
          whenNobody: 'autoPass',
          whenInitiatorIsReviewer: 'self',
          onReject: 'finish',
        },
      },
    }
    // the version snapshots the form (wf-model.e2e): its qw-upload field is what start binds
    await admin('post', `/${model.id}/versions`, { tree }).expect(201)
  })

  it('start binds the files to the instance: initiator, approver, cc and root download, an unrelated user 403', async () => {
    const [a, b] = [await upload('starter'), await upload('starter')]
    // unbound: the uploader's only
    await download('approver', a!).expect(403)
    const res = await start(`${a}\n${b}`).expect(201)
    const ref = `wf:${res.body.data.id}`
    expect([await refOf(a!), await refOf(b!)]).toEqual([ref, ref])
    for (const who of ['starter', 'approver', 'ccer', 'admin']) await download(who, a!).expect(200)
    const denied = await download('outsider', b!).expect(403)
    expect(denied.body.code).toBe(Err.FORBIDDEN.code)
    // no files: nothing to bind
    await start('').expect(201)
  })

  it("anything but the initiator's own unbound wf.attachment uploads → 400, nothing started or bound", async () => {
    const own = await upload('starter')
    const bound = await upload('starter')
    await start(bound).expect(201)
    const before = await instances()
    const refused = [
      await upload('outsider'), // someone else's
      await upload('starter', 'attachment'), // another tag
      bound, // bound already
      '999999/none.pdf', // unknown
    ]
    for (const other of refused) {
      const res = await start(`${own}\n${other}`).expect(400)
      expect(res.body.code).toBe(Err.STORAGE_REF_INVALID.code)
    }
    // not `<id>/<name>` lines, more than the field's limit (2), not a string
    for (const files of ['nope', `${own}\n\n${own}`, `${own}\n${own}\n${own}`, [idOf(own)]]) {
      const res = await start(files).expect(400)
      expect(res.body.errors).toEqual([{ path: 'formValues.files', msg: expect.any(String) }])
    }
    expect(await refOf(own)).toBeNull()
    expect(await instances()).toBe(before)
  })
})

describe('calc: days and totals are recomputed by the server, and branches use them', () => {
  const tk: Record<string, string> = {}
  let modelKey: string
  const http = () => request(app.getHttpServer())
  const options = [
    { label: 'AM', value: 'am' },
    { label: 'PM', value: 'pm' },
  ]
  const step = (id: string, access?: object) => ({
    id,
    type: 'review',
    name: id,
    assignee: { kind: 'users', ids: [named[id]] },
    sign: 'any',
    whenNobody: 'autoPass',
    whenInitiatorIsReviewer: 'self',
    onReject: 'finish',
    ...(access ? { access } : {}),
  })
  /** detail rows `{ item, amount }` as the table sends them (JSON text) */
  const items = (...amounts: number[]) =>
    JSON.stringify(amounts.map((amount, i) => ({ item: `i${i}`, amount })))
  const start = (formValues: object) =>
    http().post('/api/wf/instances').set(bearer(tk.leaver!)).send({ modelKey, formValues })
  const act = (who: string, task: number, action: string, payload: object = {}) =>
    http().post(`/api/wf/tasks/${task}/${action}`).set(bearer(tk[who]!)).send(payload)
  const valuesOf = async (id: number) =>
    (await ds.query('SELECT form_values AS v FROM wf_instance WHERE id = ?', [id]))[0].v
  /** the pending task of instance `id`: its step and the holder's name */
  const pendingOf = async (id: number) => {
    const rows: { id: number; node: string; who: number }[] = await ds.query(
      "SELECT id, node_id AS node, assignee_id AS who FROM wf_task WHERE instance_id = ? AND state = 'pending'",
      [id],
    )
    return rows.map((r) => ({ ...r, who: Object.keys(named).find((n) => named[n] === r.who) }))
  }
  /** starts, expecting the stored values and the step it waits on */
  const started = async (sent: object, stored: object, node: 'lead' | 'boss') => {
    const id: number = (await start(sent).expect(201)).body.data.id
    expect(await valuesOf(id)).toEqual(stored)
    expect(await pendingOf(id)).toEqual([expect.objectContaining({ node, who: node })])
    return id
  }

  beforeAll(async () => {
    for (const who of ['leaver', 'lead', 'boss']) tk[who] = await user(who, [])
    const schemaJson = {
      rule: [
        { type: 'datePicker', field: 'start', title: 'Start' },
        { type: 'radio', field: 'startHalf', title: 'From', options },
        { type: 'datePicker', field: 'end', title: 'End' },
        { type: 'radio', field: 'endHalf', title: 'To', options },
        {
          type: 'qw-date-range-days',
          field: 'days',
          title: 'Days',
          props: {
            startField: 'start',
            endField: 'end',
            startHalfField: 'startHalf',
            endHalfField: 'endHalf',
          },
        },
        {
          type: 'qw-detail-table',
          field: 'items',
          title: 'Items',
          props: {
            columns: [
              { prop: 'item', label: 'Item' },
              { prop: 'amount', label: 'Amount', sum: 'total' },
            ],
          },
        },
      ],
    }
    const form = await add(body(unique(), { schemaJson }))
    const admin = (path: string, payload: object) =>
      http().post(`/api/wf/models${path}`).set(bearer(tokens.admin)).send(payload)
    modelKey = unique()
    const model = (
      await admin('', { modelKey, name: 'Calc', formKind: 'dynamic', formId: form.id }).expect(201)
    ).body.data
    // the initiator may edit every field on resubmit, the results too: they are recomputed anyway
    const edit = ['start', 'startHalf', 'end', 'endHalf', 'days', 'items', 'total']
    const tree = {
      id: 'begin',
      type: 'begin',
      name: 'Begin',
      access: Object.fromEntries(edit.map((f) => [f, 'edit'])),
      next: {
        id: 'route',
        type: 'fork',
        name: 'Route',
        paths: [
          {
            id: 'long',
            name: 'Long',
            when: [
              [{ field: 'days', op: 'gte', value: 3 }],
              [{ field: 'total', op: 'gt', value: 1000 }],
            ],
            child: step('boss'),
          },
          {
            id: 'short',
            name: 'Short',
            fallback: true,
            when: [],
            child: step('lead', { end: 'edit', days: 'edit', total: 'edit' }),
          },
        ],
      },
    }
    await admin(`/${model.id}/versions`, { tree }).expect(201)
  })

  it('publish: the days and the column total are number fields, the rows a string', async () => {
    const [v] = await ds.query('SELECT form_snapshot AS f FROM wf_version WHERE model_key = ?', [
      modelKey,
    ])
    expect(v.f.fields).toEqual({
      start: 'date',
      startHalf: 'string',
      end: 'date',
      endHalf: 'string',
      days: 'number',
      items: 'string',
      total: 'number',
    })
  })

  it('start: forged days and totals are overwritten, the fork branches on the recomputed values', async () => {
    const day = { start: '2026-10-01', end: '2026-10-01' }
    // 1 day and 100 in all, sent as 9 days and 5000: the short path
    await started(
      { ...day, days: 9, items: items(100), total: 5000 },
      { ...day, days: 1, items: items(100), total: 100 },
      'lead',
    )
    // 3 days (an afternoon end counts whole), sent as 0: the long path
    const three = { start: '2026-10-01', startHalf: 'am', end: '2026-10-03', endHalf: 'pm' }
    await started(
      { ...three, days: 0, items: items(1), total: 0 },
      { ...three, days: 3, items: items(1), total: 1 },
      'boss',
    )
    // half days off both ends: 2 days; rows over 1000 in all, sent as 0: the long path
    const halves = { ...three, startHalf: 'pm', endHalf: 'am' }
    await started(
      { ...halves, days: 5, items: items(600, 400.5), total: 0 },
      { ...halves, days: 2, items: items(600, 400.5), total: 1000.5 },
      'boss',
    )
    // end before start, rows not JSON: no days, nothing in all (the fallback)
    const back = { start: '2026-10-03', end: '2026-10-01' }
    await started(
      { ...back, days: 3, items: 'not json', total: 2000 },
      { ...back, days: null, items: null, total: 0 },
      'lead',
    )
  })

  it('resubmit and approve recompute from the edited inputs; the resubmit branches on the new values', async () => {
    const day = { start: '2026-10-05', end: '2026-10-05' }
    const id = await started(
      { ...day, items: items(10) },
      { ...day, days: 1, items: items(10), total: 10 },
      'lead',
    )
    const [lead] = await pendingOf(id)
    await act('lead', lead!.id, 'send-back', { to: 'begin' }).expect(200)
    const [begin] = await pendingOf(id)
    expect(begin).toMatchObject({ node: 'begin', who: 'leaver' })
    // 4 days and 30 in all, sent as 1 and 0: restarted from the fork, now the long path
    const longer = { end: '2026-10-08', items: items(10, 20) }
    await act('leaver', begin!.id, 'resubmit', {
      formValues: { ...longer, days: 1, total: 0 },
    }).expect(200)
    expect(await valuesOf(id)).toEqual({ ...day, ...longer, days: 4, total: 30 })
    expect(await pendingOf(id)).toEqual([expect.objectContaining({ node: 'boss', who: 'boss' })])

    // the lead edits the end (an `edit` field) and sends 99 days: stored as the 2 the dates give
    const other = await started(
      { ...day, items: items(11) },
      { ...day, days: 1, items: items(11), total: 11 },
      'lead',
    )
    const [task] = await pendingOf(other)
    await act('lead', task!.id, 'approve', {
      formValues: { end: '2026-10-06', days: 99, total: 99 },
    }).expect(200)
    expect(await valuesOf(other)).toEqual({
      ...day,
      end: '2026-10-06',
      days: 2,
      items: items(11),
      total: 11,
    })
  })
})

describe('access (字段权限; see docs/design-notes.md#workflow): start-info hands out the form, the detail hides what a step hides', () => {
  const tk: Record<string, string> = {}
  let modelKey: string
  const http = () => request(app.getHttpServer())
  const as = (who: string) => (who === 'admin' ? tokens.admin : tk[who]!)
  const detail = async (who: string, id: number) =>
    (
      await http()
        .get(`/api/wf/instances/${id}`)
        .set(bearer(as(who)))
        .expect(200)
    ).body.data
  const fieldsOf = (d: { schema: { rule: { field: string }[] } }) =>
    d.schema.rule.map((r) => r.field)
  const ALL = ['reason', 'secret', 'lead', 'amount']

  beforeAll(async () => {
    for (const who of ['asker', 'chief', 'ccee']) tk[who] = await user(who, [])
    const schemaJson = {
      rule: [
        { type: 'input', field: 'reason', title: 'Reason' },
        { type: 'input', field: 'secret', title: 'Secret' },
        { type: 'qw-user-select', field: 'lead', title: 'Lead' },
        { type: 'inputNumber', field: 'amount', title: 'Amount' },
      ],
    }
    const form = await add(body(unique(), { schemaJson }))
    modelKey = unique()
    const admin = (path: string, payload: object) =>
      http().post(`/api/wf/models${path}`).set(bearer(tokens.admin)).send(payload).expect(201)
    const model = (await admin('', { modelKey, name: 'Acc', formKind: 'dynamic', formId: form.id }))
      .body.data
    const tree = {
      id: 'begin',
      type: 'begin',
      name: 'Begin',
      next: {
        id: 'copy',
        type: 'notify',
        name: 'Copy',
        assignee: { kind: 'users', ids: [named.ccee] },
        next: {
          id: 'review',
          type: 'review',
          name: 'Review',
          // the user the form's `lead` field names (formFieldUser)
          assignee: { kind: 'formFieldUser', field: 'lead' },
          access: { secret: 'hide', amount: 'edit' },
          sign: 'any',
          whenNobody: 'autoPass',
          whenInitiatorIsReviewer: 'self',
          onReject: 'finish',
        },
      },
    }
    await admin(`/${model.id}/versions`, { tree })
  })

  it('start-info: the published schema; the field-picked user holds the task and never reads a hide field', async () => {
    const info = await http()
      .get(`/api/wf/models/${modelKey}/start-info`)
      .set(bearer(tk.asker!))
      .expect(200)
    expect(fieldsOf(info.body.data)).toEqual(ALL)
    expect(info.body.data.picks).toEqual([])

    const values = { reason: 'trip', secret: 's3', lead: named.chief, amount: 5 }
    const res = await http()
      .post('/api/wf/instances')
      .set(bearer(tk.asker!))
      .send({ modelKey, formValues: values })
      .expect(201)
    const id = res.body.data.id

    // the approver: the hide field neither as a rule nor as a value; amount editable
    let lead = await detail('chief', id)
    expect(lead.myTasks).toHaveLength(1)
    expect(lead.access).toEqual({ secret: 'hide', amount: 'edit' })
    expect(fieldsOf(lead)).toEqual(['reason', 'lead', 'amount'])
    expect(lead.formValues).toEqual({ reason: 'trip', lead: named.chief, amount: 5 })
    // the initiator, the cc recipient and root (wf.instance.view) read everything
    for (const who of ['asker', 'ccee', 'admin']) {
      const d = await detail(who, id)
      expect(d.access).toEqual({})
      expect(fieldsOf(d)).toEqual(ALL)
      expect(d.formValues).toEqual(values)
    }

    // approved (only the edit field taken): still hidden from them once the task is done
    await http()
      .post(`/api/wf/tasks/${lead.myTasks[0].id}/approve`)
      .set(bearer(tk.chief!))
      .send({ formValues: { amount: 7, secret: 'forged' } })
      .expect(200)
    lead = await detail('chief', id)
    expect(lead.myTasks).toEqual([])
    expect(lead.access).toEqual({ secret: 'hide' })
    expect(lead.formValues).toEqual({ reason: 'trip', lead: named.chief, amount: 7 })
    expect((await detail('asker', id)).formValues).toEqual({ ...values, amount: 7 })
  })
})

describe('values: start, approve and resubmit check each field as its component holds it', () => {
  const tk: Record<string, string> = {}
  let modelKey: string
  const http = () => request(app.getHttpServer())
  const opts = (...values: unknown[]) => values.map((value) => ({ label: String(value), value }))
  const items = JSON.stringify([{ item: 'taxi', cost: 30 }])
  // every component a form may use (FORM_COMPONENT_TYPES), as the browser fills it in
  const RULES = [
    { type: 'input', field: 'note', title: 'Note', props: { maxlength: 20 } },
    { type: 'input', field: 'title', title: 'Title', $required: true },
    { type: 'textarea', field: 'story', title: 'Story' },
    {
      type: 'inputNumber',
      field: 'amount',
      title: 'Amount',
      validate: [{ required: true, message: 'm' }],
      props: { min: 0, max: 1000 },
    },
    { type: 'select', field: 'kind', title: 'Kind', options: opts('a', 'b') },
    {
      type: 'select',
      field: 'kinds',
      title: 'Kinds',
      props: { multiple: true },
      options: opts('a', 'b', 'c'),
    },
    { type: 'radio', field: 'level', title: 'Level', options: opts(1, 2) },
    { type: 'checkbox', field: 'checks', title: 'Checks', options: opts('x', 'y') },
    { type: 'switch', field: 'urgent', title: 'Urgent' },
    { type: 'datePicker', field: 'day', title: 'Day' },
    { type: 'datePicker', field: 'at', title: 'At', props: { type: 'datetime' } },
    {
      type: 'datePicker',
      field: 'month',
      title: 'Month',
      props: { type: 'month', valueFormat: 'YYYY-MM' },
    },
    { type: 'datePicker', field: 'span', title: 'Span', props: { type: 'daterange' } },
    { type: 'timePicker', field: 'times', title: 'Times', props: { isRange: true } },
    { type: 'rate', field: 'stars', title: 'Stars' },
    { type: 'slider', field: 'pct', title: 'Pct' },
    {
      type: 'cascader',
      field: 'path',
      title: 'Path',
      options: [{ label: 'Z', value: 'zj', children: [{ label: 'H', value: 'hz' }] }],
    },
    { type: 'upload', field: 'pics', title: 'Pics' },
    { type: 'qw-user-select', field: 'boss', title: 'Boss' },
    { type: 'qw-dept-select', field: 'dept', title: 'Dept' },
    { type: 'qw-dict-select', field: 'gender', title: 'Gender', props: { code: 'iam.gender' } },
    { type: 'qw-upload', field: 'files', title: 'Files' },
    { type: 'qw-area-select', field: 'area', title: 'Area' },
    {
      type: 'qw-date-range-days',
      field: 'days',
      title: 'Days',
      props: { startField: 'day', endField: 'at' },
    },
    {
      type: 'qw-detail-table',
      field: 'items',
      title: 'Items',
      $required: true,
      props: {
        columns: [
          { prop: 'item', label: 'Item' },
          { prop: 'cost', label: 'Cost', sum: 'total' },
        ],
      },
    },
  ]
  const VALID = {
    title: 'Trip',
    story: 'long',
    amount: 120,
    kind: 'a',
    kinds: ['a', 'c'],
    level: 2,
    checks: ['x', 'y'],
    urgent: true,
    day: '2026-10-01',
    at: '2026-10-02T09:00:00+08:00',
    month: '2026-10',
    span: ['2026-10-01', '2026-10-03'],
    times: ['09:00:00', '18:00:00'],
    stars: 4,
    pct: 30,
    path: ['zj', 'hz'],
    pics: [],
    boss: 1,
    dept: 1,
    gender: 'female',
    files: '',
    area: ['330000', '330100', '330106'],
    items,
  }
  let n = 0
  /** POST /wf/instances as the filler (`note` differs each time: no duplicate submit) */
  const start = (formValues: Record<string, unknown>) =>
    http()
      .post('/api/wf/instances')
      .set(bearer(tk.filler!))
      .send({ modelKey, formValues: { note: `n${++n}`, ...formValues } })
  const act = (who: string, task: number, action: string, payload: object = {}) =>
    http().post(`/api/wf/tasks/${task}/${action}`).set(bearer(tk[who]!)).send(payload)
  const pathsOf = (res: request.Response) =>
    res.body.errors.map((e: { path: string }) => e.path).sort()
  const instances = async () =>
    Number(
      (await ds.query('SELECT COUNT(*) AS n FROM wf_instance WHERE model_key = ?', [modelKey]))[0]
        .n,
    )
  const pendingOf = async (id: number) =>
    (await ds.query("SELECT id FROM wf_task WHERE instance_id = ? AND state = 'pending'", [id]))[0]
      .id as number
  const valuesOf = async (id: number) =>
    (await ds.query('SELECT form_values AS v FROM wf_instance WHERE id = ?', [id]))[0].v

  beforeAll(async () => {
    for (const who of ['filler', 'checker']) tk[who] = await user(who, [])
    const form = await add(body(unique(), { schemaJson: { rule: RULES } }))
    modelKey = unique()
    const admin = (path: string, payload: object) =>
      http().post(`/api/wf/models${path}`).set(bearer(tokens.admin)).send(payload).expect(201)
    const model = (await admin('', { modelKey, name: 'Val', formKind: 'dynamic', formId: form.id }))
      .body.data
    const tree = {
      id: 'begin',
      type: 'begin',
      name: 'Begin',
      access: { amount: 'edit', note: 'edit' },
      next: {
        id: 'check',
        type: 'review',
        name: 'Check',
        assignee: { kind: 'users', ids: [named.checker] },
        access: { amount: 'edit', kind: 'edit', title: 'edit', gender: 'edit' },
        sign: 'any',
        whenNobody: 'autoPass',
        whenInitiatorIsReviewer: 'self',
        onReject: 'finish',
      },
    }
    await admin(`/${model.id}/versions`, { tree })
  })

  it('every component starts (201), its value stored as sent; month and the lists are string fields', async () => {
    const [v] = await ds.query('SELECT form_snapshot AS f FROM wf_version WHERE model_key = ?', [
      modelKey,
    ])
    expect(v.f.fields).toMatchObject({ day: 'date', at: 'date', month: 'string', stars: 'number' })
    // the one-day pickers' values as ISO (DATE_VALUE_FORMAT, forced on save)
    expect(v.f.schema.rule.find((r: { field: string }) => r.field === 'at').props).toEqual({
      type: 'datetime',
      valueFormat: 'YYYY-MM-DD[T]HH:mm:ssZ',
    })
    const res = await start(VALID).expect(201)
    expect(await valuesOf(res.body.data.id)).toEqual({
      ...VALID,
      note: `n${n}`,
      days: 2,
      total: 30,
    })
    // nothing but the required ones
    await start({ title: 'T', amount: 0, items }).expect(201)
  })

  it('missing required, outside the options, out of range → 400 at formValues.<field>, nothing started', async () => {
    const before = await instances()
    const { title: _t, ...untitled } = VALID
    const missing = await start({ ...untitled, amount: null, items: '[]' }).expect(400)
    expect(pathsOf(missing)).toEqual(['formValues.amount', 'formValues.items', 'formValues.title'])
    const options = await start({
      ...VALID,
      kind: 'z',
      kinds: ['a', 'q'],
      level: '2',
      gender: 'robot',
    })
    expect(options.status).toBe(400)
    expect(pathsOf(options)).toEqual([
      'formValues.gender',
      'formValues.kind',
      'formValues.kinds.1',
      'formValues.level',
    ])
    const ranges = await start({ ...VALID, note: 'x'.repeat(21), amount: 1001, stars: 6, pct: -1 })
    expect(ranges.status).toBe(400)
    expect(pathsOf(ranges)).toEqual([
      'formValues.amount',
      'formValues.note',
      'formValues.pct',
      'formValues.stars',
    ])
    const shapes = await start({ ...VALID, urgent: 'yes', checks: 'x', at: '2026-10-02 09:00:00' })
    expect(shapes.status).toBe(400)
    expect(pathsOf(shapes)).toEqual(['formValues.at', 'formValues.checks', 'formValues.urgent'])
    expect(await instances()).toBe(before)
  })

  it('approve and resubmit check the edit fields they change the same way (400 at the field)', async () => {
    const id: number = (await start(VALID).expect(201)).body.data.id
    const task = await pendingOf(id)
    for (const [formValues, path] of [
      [{ amount: 2000 }, 'formValues.amount'],
      [{ title: '  ' }, 'formValues.title'],
      [{ kind: 'z' }, 'formValues.kind'],
      [{ gender: 'robot' }, 'formValues.gender'],
    ] as const) {
      const res = await act('checker', task, 'approve', { formValues }).expect(400)
      expect(pathsOf(res)).toEqual([path])
    }
    await act('checker', task, 'send-back', { to: 'begin' }).expect(200)
    const begin = await pendingOf(id)
    const bad = await act('filler', begin, 'resubmit', { formValues: { amount: -5 } }).expect(400)
    expect(pathsOf(bad)).toEqual(['formValues.amount'])
    await act('filler', begin, 'resubmit', { formValues: { amount: 10 } }).expect(200)
    await act('checker', await pendingOf(id), 'approve', {
      formValues: { kind: 'b', amount: 7, gender: 'male' },
    }).expect(200)
    expect(await valuesOf(id)).toMatchObject({
      kind: 'b',
      amount: 7,
      title: 'Trip',
      gender: 'male',
    })
  })
})

describe('attachment access: files follow field access; approve and resubmit bind new ones', () => {
  const people = ['sender', 'approver2', 'copied', 'friend', 'stranger'] as const
  const tk: Record<string, string> = {}
  let modelKey: string
  const http = () => request(app.getHttpServer())
  let files = 0
  const upload = async (who: string) => {
    const name = `g${++files}.pdf`
    const pdf = Buffer.from(`%PDF-1.4\n% ${name}\ntrailer\n<<>>\n%%EOF\n`)
    const res = await http()
      .post('/api/storage/objects')
      .set(bearer(tk[who]!))
      .field('bizTag', 'wf.attachment')
      .attach('file', pdf, name)
      .expect(201)
    return `${res.body.data.id}/${name}`
  }
  const download = (who: string, ref: string) =>
    http()
      .get(`/api/storage/objects/${ref.split('/')[0]}/download`)
      .set(bearer(tk[who]!))
  const expectDownloads = async (ref: string, ok: string[], denied: string[]) => {
    for (const who of ok) expect([who, (await download(who, ref)).status]).toEqual([who, 200])
    for (const who of denied) expect([who, (await download(who, ref)).status]).toEqual([who, 403])
  }
  const act = (who: string, task: number, action: string, payload: object = {}) =>
    http().post(`/api/wf/tasks/${task}/${action}`).set(bearer(tk[who]!)).send(payload)
  const pendingOf = async (id: number) =>
    (await ds.query("SELECT id FROM wf_task WHERE instance_id = ? AND state = 'pending'", [id]))[0]
      .id as number
  const detail = async (who: string, id: number) =>
    (await http().get(`/api/wf/instances/${id}`).set(bearer(tk[who]!)).expect(200)).body.data

  beforeAll(async () => {
    for (const who of people) tk[who] = await user(who, [])
    const schemaJson = {
      rule: [
        { type: 'input', field: 'memo', title: 'Memo' },
        { type: 'qw-upload', field: 'files', title: 'Files' },
        { type: 'qw-upload', field: 'secret', title: 'Secret' },
      ],
    }
    const form = await add(body(unique(), { schemaJson }))
    modelKey = unique()
    const admin = (path: string, payload: object) =>
      http().post(`/api/wf/models${path}`).set(bearer(tokens.admin)).send(payload).expect(201)
    const model = (await admin('', { modelKey, name: 'Hid', formKind: 'dynamic', formId: form.id }))
      .body.data
    const tree = {
      id: 'begin',
      type: 'begin',
      name: 'Begin',
      access: { files: 'edit', memo: 'edit', secret: 'edit' },
      next: {
        id: 'copy',
        type: 'notify',
        name: 'Copy',
        assignee: { kind: 'users', ids: [named.copied] },
        next: {
          id: 'check',
          type: 'review',
          name: 'Check',
          assignee: { kind: 'users', ids: [named.approver2] },
          access: { secret: 'hide', files: 'edit' },
          sign: 'any',
          whenNobody: 'autoPass',
          whenInitiatorIsReviewer: 'self',
          onReject: 'finish',
        },
      },
    }
    await admin(`/${model.id}/versions`, { tree })
  })

  const startWith = async (values: object) =>
    (
      await http()
        .post('/api/wf/instances')
        .set(bearer(tk.sender!))
        .send({ modelKey, formValues: values })
        .expect(201)
    ).body.data.id as number

  it("a step's hidden upload field: its approver 403; visible fields, the notify cc and the initiator 200", async () => {
    const [open, hidden] = [await upload('sender'), await upload('sender')]
    await startWith({ memo: 'hide', files: open, secret: hidden })
    await expectDownloads(open, ['sender', 'approver2', 'copied'], ['stranger'])
    await expectDownloads(hidden, ['sender', 'copied'], ['approver2', 'stranger'])
  })

  it('a manual cc sees what the step that sent it sees: no hidden field, none of its files', async () => {
    const [open, hidden] = [await upload('sender'), await upload('sender')]
    const id = await startWith({ memo: 'cc', files: open, secret: hidden })
    await act('approver2', await pendingOf(id), 'cc', { userIds: [named.friend] }).expect(200)
    const seen = await detail('friend', id)
    expect(seen.access).toEqual({ secret: 'hide' })
    expect(Object.keys(seen.formValues).sort()).toEqual(['files', 'memo'])
    expect(seen.schema.rule.map((r: { field: string }) => r.field)).toEqual(['memo', 'files'])
    await expectDownloads(open, ['friend'], [])
    await expectDownloads(hidden, [], ['friend'])
    // a manual cc takes nothing from whom the instance shows by another way: the notify step's cc (reads
    // every field), the initiator, a root admin
    const [admin] = await ds.query("SELECT id FROM iam_user WHERE username = 'admin'")
    const userIds = [named.copied, named.sender, Number(admin.id)]
    await act('approver2', await pendingOf(id), 'cc', { userIds }).expect(200)
    expect((await detail('copied', id)).access).toEqual({})
    await expectDownloads(hidden, ['copied'], [])
    expect((await detail('sender', id)).formValues.secret).toBe(hidden)
    const root = await http().get(`/api/wf/instances/${id}`).set(bearer(tokens.admin)).expect(200)
    expect(root.body.data.access).toEqual({})
  })

  it('a file moves to no other field: not out of one hidden from the approver, nor between edit fields (400 C1009)', async () => {
    const [open, hidden] = [await upload('sender'), await upload('sender')]
    const id = await startWith({ memo: 'move', files: open, secret: hidden })
    const res = await act('approver2', await pendingOf(id), 'approve', {
      formValues: { files: `${open}\n${hidden}` },
    }).expect(400)
    expect(res.body.code).toBe(Err.STORAGE_REF_INVALID.code)
    await expectDownloads(hidden, ['sender'], ['approver2'])
    // begin edits both: a file each field held stays, one from the other field is not taken
    await act('approver2', await pendingOf(id), 'send-back', { to: 'begin' }).expect(200)
    const moved = await act('sender', await pendingOf(id), 'resubmit', {
      formValues: { files: open, secret: `${hidden}\n${open}` },
    }).expect(400)
    expect(moved.body.code).toBe(Err.STORAGE_REF_INVALID.code)
    await act('sender', await pendingOf(id), 'resubmit', {
      formValues: { files: open, secret: hidden },
    }).expect(200)
  })

  it('resubmit and approve bind the files they add (own uploads only, else 400); a dropped file is gone', async () => {
    const first = await upload('sender')
    const id = await startWith({ memo: 'redo', files: first })
    await act('approver2', await pendingOf(id), 'send-back', { to: 'begin' }).expect(200)
    const added = await upload('sender')
    // someone else's upload: 400 C1009, nothing bound
    const foreign = await upload('stranger')
    const refused = await act('sender', await pendingOf(id), 'resubmit', {
      formValues: { files: `${added}\n${foreign}` },
    }).expect(400)
    expect(refused.body.code).toBe(Err.STORAGE_REF_INVALID.code)
    await expectDownloads(added, ['sender'], ['approver2'])
    // the first file dropped, a new one added: the approver downloads the new one only
    await act('sender', await pendingOf(id), 'resubmit', { formValues: { files: added } }).expect(
      200,
    )
    await expectDownloads(added, ['sender', 'approver2', 'copied'], ['stranger'])
    await expectDownloads(first, ['sender'], ['approver2', 'copied'])
    // the approver adds a file of their own on approve: the initiator downloads it
    const review = await upload('approver2')
    await act('approver2', await pendingOf(id), 'approve', {
      formValues: { files: `${added}\n${review}` },
    }).expect(200)
    await expectDownloads(review, ['sender', 'approver2', 'copied'], ['stranger'])
  })

  it('a version whose tree no longer compiles (no form shown): its files for their uploader only', async () => {
    const open = await upload('sender')
    await startWith({ memo: 'broken', files: open })
    await expectDownloads(open, ['sender', 'approver2'], [])
    const sql = 'UPDATE wf_version SET tree_json = ? WHERE model_key = ?'
    const [{ tree }] = await ds.query(
      'SELECT tree_json AS tree FROM wf_version WHERE model_key = ?',
      [modelKey],
    )
    await ds.query(sql, [JSON.stringify({ id: 'begin' }), modelKey])
    try {
      await expectDownloads(open, ['sender'], ['approver2', 'copied'])
    } finally {
      await ds.query(sql, [JSON.stringify(tree), modelKey])
    }
  })
})

describe('errors', () => {
  it('403 per permission: browse-only may list, not view/create/modify/delete; no perm → no list', async () => {
    const { id } = await add(body(unique()))
    await call('reader', 'get').expect(200)
    const forbidden = [
      call('reader', 'get', `/${id}`),
      call('reader', 'post', '', body(unique())),
      call('reader', 'put', `/${id}`, {}),
      call('reader', 'put', `/${id}/enabled`, { enabled: false }),
      call('reader', 'delete', `/${id}`),
      call('reader', 'post', '/batch-delete', { ids: [id] }),
      call('plain', 'get'),
    ]
    for (const res of await Promise.all(forbidden)) {
      expect(res.status).toBe(403)
      expect(res.body.code).toBe(Err.FORBIDDEN.code)
    }
  })

  it('400: invalid body / query / id, with translated field messages', async () => {
    const { id } = await add(body(unique()))
    const required = (lang: string, field: string) =>
      t(lang, 'validation.required', { field: label(lang, field) })
    expect(label('zh-CN', 'name')).not.toMatch(/^field\./)
    expect(label('en-US', 'name')).not.toMatch(/^field\./)
    const zh = await create({ ...body(unique()), name: '', note: 'x'.repeat(501) }).expect(400)
    expect(zh.body).toMatchObject({
      code: Err.VALIDATION_FAILED.code,
      msg: required('zh-CN', 'name'),
    })
    expect(zh.body.errors).toEqual([
      { path: 'name', msg: required('zh-CN', 'name') },
      {
        path: 'note',
        msg: t('zh-CN', 'validation.too_big.string', {
          field: label('zh-CN', 'note'),
          maximum: 500,
        }),
      },
    ])
    const { name: _, ...keyless } = body(unique())
    const en = await create(keyless).set('Accept-Language', 'en-US').expect(400)
    expect(en.body.errors).toEqual([{ path: 'name', msg: required('en-US', 'name') }])
    await call('admin', 'get').query({ sort: 'enabled' }).expect(400)
    await call('admin', 'put', `/${id}/enabled`, { enabled: 'no' }).expect(400)
    await call('admin', 'post', '/batch-delete', { ids: [] }).expect(400)
    await call('admin', 'get', '/abc').expect(400)
  })

  it('409 duplicate: a unique value already taken (create and update; case-insensitive)', async () => {
    const tag = unique()
    const taken = await add(body(tag))
    const other = await add(body(unique()))
    for (const res of [
      await create({ ...body(unique()), name: taken.name.toUpperCase() }),
      await call('admin', 'put', `/${taken.id}`, { name: other.name }),
    ]) {
      expect(res.status).toBe(409)
      expect(res.body).toMatchObject({
        code: Err.DUPLICATE.code,
        msg: t('zh-CN', Err.DUPLICATE.key),
      })
    }
  })

  it('404: unknown ids for get, update, enabled, delete; a batch with one unknown id deletes nothing', async () => {
    const { id } = await add(body(unique()))
    for (const res of [
      await call('admin', 'get', `/${MISSING}`),
      await call('admin', 'put', `/${MISSING}`, {}),
      await call('admin', 'put', `/${MISSING}/enabled`, { enabled: true }),
      await call('admin', 'delete', `/${MISSING}`),
      await call('admin', 'post', '/batch-delete', { ids: [id, MISSING] }),
    ]) {
      expect(res.status).toBe(404)
      expect(res.body.code).toBe(Err.NOT_FOUND.code)
    }
    await call('admin', 'get', `/${id}`).expect(200)
  })

  it('the same create submitted twice within 3 s → 429 (@Idempotent)', async () => {
    const tag = unique()
    await create(body(tag)).expect(201)
    const again = await create(body(tag)).expect(429)
    expect(again.body.code).toBe(Err.TOO_MANY_REQUESTS.code)
  })
})

it('@ActionLog: every write leaves a row with domain wf.form, its verb and the id', async () => {
  const trace = `${PREFIX}${process.pid}-`
  const created = await create(body(unique())).set('X-Request-Id', `${trace}c`).expect(201)
  const { id } = created.body.data
  await call('admin', 'put', `/${id}`, {}).set('X-Request-Id', `${trace}u`)
  await call('admin', 'put', `/${id}/enabled`, { enabled: false }).set('X-Request-Id', `${trace}e`)
  await call('admin', 'delete', `/${id}`).set('X-Request-Id', `${trace}d`)
  await call('admin', 'post', '/batch-delete', { ids: [MISSING] }).set('X-Request-Id', `${trace}b`)
  const expected: [string, object][] = [
    ['c', { verb: 'create', biz_id: String(id), ok: 1 }],
    ['u', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['e', { verb: 'modify', biz_id: String(id), ok: 1 }],
    ['d', { verb: 'remove', biz_id: String(id), ok: 1 }],
    ['b', { verb: 'remove', biz_id: null, ok: 0, error_msg: Err.NOT_FOUND.key }],
  ]
  for (const [suffix, row] of expected)
    expect(await logOf(ds, `${trace}${suffix}`)).toMatchObject({
      domain: 'wf.form',
      username: 'admin',
      ...row,
    })
})

it('Swagger documents every route', async () => {
  const doc = (await request(app.getHttpServer()).get('/api/docs-json').expect(200)).body
  expect(
    Object.keys(doc.paths)
      .filter((p) => p.startsWith(URL))
      .sort(),
  ).toEqual([URL, `${URL}/batch-delete`, `${URL}/{id}`, `${URL}/{id}/enabled`])
  expect(
    doc.paths[URL].get.responses['200'].content['application/json'].schema.properties.data,
  ).toMatchObject({ properties: { items: { type: 'array' }, total: { type: 'integer' } } })
})
