// @generated by qw-codegen (crud)
import { z } from 'zod'
import { pageQuery } from '../../common/pagination.js'
import { fieldDomains } from '../../validation/zod-i18n.js'

/**
 * Runs (`job_run`), `/api/scheduler/runs` (see docs/design-notes.md#api-envelope): one row per attempt of a task's fire,
 * written by the scheduler only. Field labels `field.scheduler.run.<prop>`. Hand-edited (G module, like
 * the log pages): `remove` (one, a batch, or `POST /clean` everything).
 */

export const runPerms = {
  browse: 'scheduler.run.browse',
  view: 'scheduler.run.view',
  export: 'scheduler.run.export',
  /** DELETE /:id, POST /batch-delete, POST /clean */
  remove: 'scheduler.run.remove',
} as const

/** GET query: paging, sort and the list filters (text contains, ranges from / to, the rest equals). */
export const runQuery = pageQuery([
  'taskId',
  'taskName',
  'handler',
  'attempt',
  'startedAt',
  'endedAt',
  'costMs',
  'id',
])
  .extend({
    taskId: z.coerce.number().int().optional(),
    taskName: z.string().trim().max(64).optional(),
    handler: z.string().trim().max(128).optional(),
    outcome: z.string().trim().max(12).optional(),
    startedAtFrom: z.iso.datetime({ offset: true }).optional(),
    startedAtTo: z.iso.datetime({ offset: true }).optional(),
  })
  .register(fieldDomains, { domain: 'scheduler.run' })
export type RunQuery = z.output<typeof runQuery>

export const runVo = z.object({
  id: z.number().int(),
  taskId: z.number().int(),
  taskName: z.string(),
  handler: z.string(),
  params: z.unknown(),
  attempt: z.number().int(),
  outcome: z.string(),
  output: z.string().nullable(),
  error: z.string().nullable(),
  startedAt: z.iso.datetime(),
  endedAt: z.iso.datetime().nullable(),
  costMs: z.number().int(),
})
export type RunVo = z.infer<typeof runVo>
