// @generated by qw-codegen (crud)
// Task menus: the page under the `monitor` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (scheduler.task.json), the actions' in menu.json (menu.action.*).
import { taskPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [taskPerms.browse, 'menu.action.browse'],
  [taskPerms.view, 'menu.action.view'],
  [taskPerms.create, 'menu.action.create'],
  [taskPerms.modify, 'menu.action.modify'],
  [taskPerms.remove, 'menu.action.remove'],
  [taskPerms.export, 'menu.action.export'],
  [taskPerms.run, 'menu.action.run'],
]

export async function seedTask(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'monitor' })
  if (parentId === undefined) throw new Error('seedTask: the monitor menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'scheduler-task' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.scheduler.task',
      route_path: '/scheduler/tasks',
      component: 'platform/scheduler/task/index',
      component_name: 'SchedulerTask',
      keep_alive: 1,
      icon: 'lucide:alarm-clock',
      sort_no: 20,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
