// @generated by qw-codegen (crud)
import { Column, Entity } from 'typeorm'
import { BaseEntity, decimalNumber } from '../../../core/db/base.entity.js'

/** `biz_leave_request`: 请假申请 */
@Entity('biz_leave_request')
export class Leave extends BaseEntity {
  /** 申请人 ID */
  @Column({ name: 'user_id', type: 'bigint', unsigned: true })
  userId: number

  /** 申请人部门 ID */
  @Column({ name: 'dept_id', type: 'bigint', unsigned: true, nullable: true })
  deptId: number | null

  /** 请假类型（字典 biz.leave_kind） */
  @Column({ name: 'leave_kind', length: 16 })
  leaveKind: string

  /** 开始时间（UTC） */
  @Column({ name: 'start_at', type: 'datetime', precision: 3 })
  startAt: Date

  /** 结束时间（UTC） */
  @Column({ name: 'end_at', type: 'datetime', precision: 3 })
  endAt: Date

  /** 请假天数 */
  @Column({ type: 'decimal', precision: 5, scale: 1, transformer: decimalNumber })
  days: number

  /** 请假事由 */
  @Column({ length: 500 })
  reason: string

  /** 状态（draft/in_review/approved/rejected/canceled） */
  @Column({ length: 12, default: 'draft' })
  state: string

  /** 流程实例 ID（为空则未发起） */
  @Column({ name: 'instance_id', type: 'bigint', unsigned: true, nullable: true })
  instanceId: number | null
}
