// @generated by qw-codegen (crud)
import type { RunVo } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/scheduler/runs'

/** /api/scheduler/runs: read, export and delete (one, a batch or everything). */
export const runApi = {
  ...crudApi<RunVo>(BASE),
  clean: () => api.post(`${BASE}/clean`),
}
