// @generated by qw-codegen (crud)
import type { JobHandlerVo, JobRunOnceVo, TaskCreate, TaskVo } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/scheduler/tasks'

/** /api/scheduler/tasks: the standard CRUD calls plus the module's own. */
export const taskApi = {
  ...crudApi<TaskVo, TaskCreate>(BASE),
  setEnabled: (id: number, enabled: boolean) => api.put(`${BASE}/${id}/enabled`, { enabled }),
  /** the `@JobHandler` registry: the only names a task may take (the handler dropdowns) */
  handlers: () => api.get<JobHandlerVo[]>(`${BASE}/handlers`),
  /** fires the task once now with its stored params; the runs land in the run log */
  run: (id: number) => api.post<JobRunOnceVo>(`${BASE}/${id}/run`),
}
