// scripts/gen-check-golden.mjs helpers (quality gate; see docs/design-notes.md#codegen): it resets only named test DB/Redis
// pairs, and it also fails on a committed @generated file of a G0 module the generator no longer renders.
// The whole check (build, reset, render, diff) is `pnpm gen:check-golden` in `pnpm ci:local`.
import childProcess, { execFileSync } from 'node:child_process'
import fs, {
  existsSync,
  linkSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import { syncBuiltinESMExports } from 'node:module'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import * as workspace from '../../src/modules/platform/codegen/workspace.js'
import { MOBILE } from '../../src/modules/platform/codegen/workspace.js'

const SCRIPT = pathToFileURL(join(process.cwd(), '../../scripts/gen-check-golden.mjs')).href
const { ALLOWED_PAIRS, committedGenerated, refusal, syncGolden, testLanes } = (await import(
  SCRIPT
)) as {
  ALLOWED_PAIRS: string[][]
  testLanes: (file?: string) => { testPairs?: string[][] }
  committedGenerated: (rendered: string[], at: string) => string[]
  syncGolden: (
    out: string,
    at: string,
    guards: typeof workspace,
    write?: boolean,
  ) => { files: string[]; differ: string[]; stale: string[] }
  refusal: (env: Record<string, string | undefined>, pairs?: string[][]) => string | null
}

it('accepts only the named test database and Redis db pairs', () => {
  // the default pair always; extra pairs only from the optional private file
  expect(ALLOWED_PAIRS[0]).toEqual(['qiwu_test', '15'])
  expect(ALLOWED_PAIRS.slice(1)).toEqual(testLanes().testPairs ?? [])
  const allowed = [
    ['qiwu_test', '15'],
    ['qiwu_alt_test', '7'],
  ]
  for (const [DB_NAME, REDIS_DB] of allowed)
    expect(refusal({ DB_NAME, REDIS_DB }, allowed)).toBeNull()
  expect(refusal({ DB_NAME: 'qiwu_test', REDIS_DB: '15' })).toBeNull()
  const invalid: Record<string, string | undefined>[] = [
    { DB_NAME: 'qiwu_alt_test', REDIS_DB: '15' },
    { DB_NAME: 'qiwu_test', REDIS_DB: '7' },
    { DB_NAME: 'qiwu_dev', REDIS_DB: '13' },
    { DB_NAME: 'qiwu_other_test', REDIS_DB: '9' },
    { DB_NAME: 'qiwu_test' },
    {},
  ]
  for (const env of invalid) {
    const message = refusal(env, allowed)
    expect(message).toContain(`got ('${env.DB_NAME ?? ''}', '${env.REDIS_DB ?? ''}')`)
    for (const [db, redis] of allowed) expect(message).toContain(`(${db}, ${redis})`)
    expect(refusal(env, [['qiwu_test', '15']])).not.toBeNull()
  }
})

it('reads extra test pairs from the optional private file only when it exists', () => {
  const dir = mkdtempSync(join(tmpdir(), 'qw-golden-pairs-'))
  try {
    expect(testLanes(join(dir, 'missing.json'))).toEqual({})
    const file = join(dir, 'pairs.json')
    writeFileSync(file, JSON.stringify({ testPairs: [['qiwu_alt_test', '7']] }))
    expect(testLanes(file).testPairs).toEqual([['qiwu_alt_test', '7']])
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
})

it('lists the committed @generated files of the rendered modules, rendered or not', () => {
  const root = mkdtempSync(join(tmpdir(), 'qw-golden-files-'))
  const put = (path: string, content: string) => {
    mkdirSync(dirname(join(root, path)), { recursive: true })
    writeFileSync(join(root, path), content)
  }
  try {
    const mod = 'apps/server/src/modules/demo/book'
    const ts = '// @generated by qw-codegen (crud)\n'
    const vue = '<!-- @generated by qw-codegen (crud) -->\n'
    for (const f of ['book.entity.ts', 'book.service.ts', 'book.old.ts']) put(`${mod}/${f}`, ts)
    put(`${mod}/book.helper.ts`, '// hand-written\n')
    put('apps/web/src/views/demo/book/index.vue', vue)
    put('apps/web/src/views/demo/book/detail.vue', vue)
    put('apps/server/test/e2e/demo-book.e2e-spec.ts', ts)
    put('apps/server/test/e2e/demo-book-extra.e2e-spec.ts', '// hand-written\n')
    put('apps/server/test/e2e/iam-other.e2e-spec.ts', ts) // not a G0 module
    put('packages/shared/src/demo/book.schema.ts', ts)
    // the uni-app pages of a withMobile module: its page directory and its api file
    put(`${MOBILE}pages-biz/demo/book/index.vue`, vue)
    put(`${MOBILE}pages-biz/demo/book/old.vue`, vue)
    put(`${MOBILE}pages-biz/demo/book/hand.vue`, '<template />\n')
    put(`${MOBILE}api/demo/book.ts`, ts)
    put(`${MOBILE}api/demo/other.ts`, ts)
    const rendered = [
      `${mod}/book.entity.ts`,
      `${mod}/book.service.ts`,
      'apps/web/src/views/demo/book/index.vue',
      'packages/shared/src/demo/book.schema.ts',
    ]
    expect(committedGenerated(rendered, root).sort()).toEqual([
      `${mod}/book.entity.ts`,
      `${mod}/book.old.ts`,
      `${mod}/book.service.ts`,
      'apps/server/test/e2e/demo-book.e2e-spec.ts',
      'apps/web/src/views/demo/book/detail.vue',
      'apps/web/src/views/demo/book/index.vue',
      `${MOBILE}api/demo/book.ts`,
      `${MOBILE}pages-biz/demo/book/index.vue`,
      `${MOBILE}pages-biz/demo/book/old.vue`,
      'packages/shared/src/demo/book.schema.ts',
    ])
    // a project domain's module at <domain>/<business>
    const course = 'apps/server/src/modules/erp/course'
    put(`${course}/course.entity.ts`, ts)
    put('apps/web/src/views/erp/course/index.vue', vue)
    put('apps/web/src/api/erp/course.ts', ts)
    put('packages/shared/src/erp/course.schema.ts', ts)
    put('apps/server/test/e2e/erp-course.e2e-spec.ts', ts)
    expect(committedGenerated([`${course}/course.entity.ts`], root).sort()).toEqual([
      `${course}/course.entity.ts`,
      'apps/server/test/e2e/erp-course.e2e-spec.ts',
      'apps/web/src/api/erp/course.ts',
      'apps/web/src/views/erp/course/index.vue',
      'packages/shared/src/erp/course.schema.ts',
    ])
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
})

describe('cross-platform G0 comparison and explicit write', () => {
  const mod = 'apps/server/src/modules/demo/book'
  const entity = `${mod}/book.entity.ts`
  const service = `${mod}/book.service.ts`
  const fresh = 'apps/web/src/views/demo/book/detail.vue'
  const stale = `${mod}/book.old.ts`
  const generated = '// @generated by qw-codegen (crud)\n'
  let tmp: string
  let repo: string
  let out: string
  const put = (base: string, path: string, content = generated) => {
    mkdirSync(dirname(join(base, path)), { recursive: true })
    writeFileSync(join(base, path), content, 'utf8')
  }
  const git = (...args: string[]) =>
    execFileSync('git', args, { cwd: repo, encoding: 'utf8', timeout: 10_000 })
  const commit = () => {
    git('add', '.')
    git(
      '-c',
      'user.name=Golden Test',
      '-c',
      'user.email=golden@example.invalid',
      '-c',
      'commit.gpgsign=false',
      'commit',
      '-qm',
      'fixture',
    )
  }
  beforeEach(() => {
    tmp = realpathSync(mkdtempSync(join(tmpdir(), 'qw-golden 中文 space-')))
    repo = join(tmp, 'repo')
    out = join(tmp, 'out')
    mkdirSync(repo)
    mkdirSync(out)
    git('init', '-q')
    put(repo, entity)
    put(repo, service, `${generated}const value = 1\n`)
    put(out, entity)
    put(out, service, `${generated}const value = 1\n`)
    commit()
  })
  afterEach(() => {
    vi.restoreAllMocks()
    syncBuiltinESMExports()
    rmSync(tmp, { recursive: true, force: true })
  })

  it('compares identical, missing, changed and stale files without changing the repository; write then check matches', () => {
    const stdout = vi.spyOn(process.stdout, 'write').mockReturnValue(true)
    const log = vi.spyOn(console, 'log').mockImplementation(() => undefined)
    expect(syncGolden(out, repo, workspace)).toMatchObject({ differ: [], stale: [] })
    put(out, service, `${generated}const value = 2\n`)
    put(out, fresh, '<!-- @generated by qw-codegen (crud) -->\n<template>中文</template>\n')
    put(repo, stale)
    put(repo, `${mod}/hand.ts`, '// hand-written\n')
    put(repo, 'apps/server/src/modules/demo/other/old.ts')
    put(repo, 'apps/web/src/locales/zh-CN/demo.book.json', '{"obsolete":true}\n')
    commit()
    const result = syncGolden(out, repo, workspace)
    expect(result.differ.sort()).toEqual([service, fresh].sort())
    expect(result.stale).toEqual([stale])
    expect(stdout).toHaveBeenCalledWith(
      expect.stringContaining(`--- a/${service}\n+++ b/${service}\n@@`),
    )
    expect(log).toHaveBeenCalledWith(`missing: ${fresh}`)
    expect(log).toHaveBeenCalledWith(`stale: ${stale}`)
    expect(readFileSync(join(repo, service), 'utf8')).toContain('value = 1')
    expect(existsSync(join(repo, fresh))).toBe(false)
    expect(existsSync(join(repo, stale))).toBe(true)
    syncGolden(out, repo, workspace, true)
    expect(readFileSync(join(repo, service))).toEqual(readFileSync(join(out, service)))
    expect(readFileSync(join(repo, fresh), 'utf8')).toContain('中文')
    expect(existsSync(join(repo, stale))).toBe(false)
    for (const path of [
      `${mod}/hand.ts`,
      'apps/server/src/modules/demo/other/old.ts',
      'apps/web/src/locales/zh-CN/demo.book.json',
    ])
      expect(existsSync(join(repo, path))).toBe(true)
    expect(syncGolden(out, repo, workspace)).toMatchObject({ differ: [], stale: [] })
  })

  it('detects committed CRLF bytes against rendered LF, prints a path hint, and matches after write', () => {
    const lf = `${generated}const value = 1\n`
    const crlf = lf.replace(/\n/g, '\r\n')
    put(repo, '.gitattributes', '* -text\n')
    put(repo, service, crlf)
    commit()
    expect(git('status', '--porcelain')).toBe('')
    const stdout = vi.spyOn(process.stdout, 'write').mockReturnValue(true)

    expect(syncGolden(out, repo, workspace)).toMatchObject({ differ: [service], stale: [] })
    expect(stdout).toHaveBeenCalledWith(expect.stringContaining(service))
    expect(readFileSync(join(repo, service))).toEqual(Buffer.from(crlf))
    expect(git('status', '--porcelain')).toBe('')

    expect(syncGolden(out, repo, workspace, true).differ).toEqual([service])
    expect(readFileSync(join(repo, service))).toEqual(Buffer.from(lf))
    expect(syncGolden(out, repo, workspace)).toMatchObject({ differ: [], stale: [] })
  })

  it.each(['working', 'staged', 'stale', 'deleted'])(
    'refuses %s dirty targets before writing any file',
    (kind) => {
      put(out, fresh, '<template />\n')
      if (kind === 'stale') {
        put(repo, stale)
        commit()
        put(repo, stale, `${generated}// edited\n`)
      } else if (kind === 'deleted') rmSync(join(repo, service))
      else {
        put(repo, service, `${generated}// edited\n`)
        if (kind === 'staged') git('add', service)
      }
      const observed = join(repo, kind === 'stale' ? stale : service)
      const before = existsSync(observed) ? readFileSync(observed) : null
      expect(() => syncGolden(out, repo, workspace, true)).toThrow(/refused dirty targets/)
      expect(existsSync(join(repo, fresh))).toBe(false)
      expect(existsSync(observed) ? readFileSync(observed) : null).toEqual(before)
    },
  )

  it.each([false, true])(
    'refuses an existing untracked target even if ignored=%s or identical',
    (ignored) => {
      put(out, fresh, '<template />\n')
      put(repo, fresh, '<template />\n')
      if (ignored) put(repo, '.gitignore', fresh)
      put(out, service, `${generated}// changed\n`)
      expect(() => syncGolden(out, repo, workspace, true)).toThrow(/untracked existing target/)
      expect(readFileSync(join(repo, service), 'utf8')).toContain('value = 1')
    },
  )

  it.each(['assume-unchanged', 'skip-worktree'])(
    'refuses a tracked %s target before writing any file',
    (flag) => {
      git('update-index', `--${flag}`, service)
      put(repo, service, `${generated}// hidden edit\n`)
      put(out, service, `${generated}// changed\n`)
      put(out, fresh, '<template />\n')
      expect(() => syncGolden(out, repo, workspace, true)).toThrow(
        `refused assume-unchanged or skip-worktree target: ${service}`,
      )
      expect(readFileSync(join(repo, service), 'utf8')).toContain('hidden edit')
      expect(existsSync(join(repo, fresh))).toBe(false)
    },
  )

  it('replaces a tracked target without overwriting another hardlink to its bytes', () => {
    const linked = join(tmp, 'linked.ts')
    linkSync(join(repo, service), linked)
    put(out, service, `${generated}// changed\n`)
    syncGolden(out, repo, workspace, true)
    expect(readFileSync(join(repo, service), 'utf8')).toContain('changed')
    expect(readFileSync(linked, 'utf8')).toContain('value = 1')
  })

  it.each([
    'README.md',
    'apps/web/src/core/danger.ts',
    'apps/server/src/modules/demo/other/x.ts',
    'apps/web/src/locales/zh-CN/demo.other.json',
  ])('rejects rendered output outside G0: %s', (path) => {
    put(out, fresh, '<template />\n')
    put(out, path, '// bad\n')
    expect(() => syncGolden(out, repo, workspace, true)).toThrow(/not a writable|not a G0 target/)
    expect(existsSync(join(repo, fresh))).toBe(false)
    expect(existsSync(join(repo, path))).toBe(false)
  })

  it('rejects a traversal disguised with backslashes', (context) => {
    if (process.platform === 'win32') {
      context.skip()
      return
    }
    // A backslash is a literal filename on POSIX, normalized by filesOf; it cannot become a traversal.
    put(out, 'apps/web/src/..\\..\\escape.ts')
    expect(() => syncGolden(out, repo, workspace, true)).toThrow(/refused path/)
    expect(readFileSync(join(repo, service), 'utf8')).toContain('value = 1')
  })

  it('rejects an entity anchor outside existing G0 and an empty rendered batch', () => {
    put(out, 'apps/server/src/modules/demo/other/other.entity.ts')
    expect(() => syncGolden(out, repo, workspace, true)).toThrow(/not an existing G0 module/)
    expect(existsSync(join(repo, 'apps/server/src/modules/demo/other'))).toBe(false)
    rmSync(out, { recursive: true })
    mkdirSync(out)
    expect(() => syncGolden(out, repo, workspace, true)).toThrow(/no G0 entity/)
  })

  it('rejects a committed clean entity anchor without a generated header before any write', () => {
    const handWritten = '// hand-written entity\n'
    const originalService = readFileSync(join(repo, service))
    put(repo, entity, handWritten)
    put(repo, stale)
    commit()
    expect(git('status', '--porcelain')).toBe('')
    put(out, service, `${generated}// changed\n`)
    put(out, fresh, '<template />\n')

    expect(() => syncGolden(out, repo, workspace, true)).toThrow(/not an existing G0 module/)
    expect(readFileSync(join(repo, entity))).toEqual(Buffer.from(handWritten))
    expect(readFileSync(join(repo, service))).toEqual(originalService)
    expect(readFileSync(join(repo, stale))).toEqual(Buffer.from(generated))
    expect(existsSync(join(repo, fresh))).toBe(false)
    expect(git('status', '--porcelain')).toBe('')
  })

  it('reports a missing entity in default check mode', () => {
    rmSync(join(repo, entity))
    const log = vi.spyOn(console, 'log').mockImplementation(() => undefined)
    expect(syncGolden(out, repo, workspace).differ).toEqual([entity])
    expect(log).toHaveBeenCalledWith(`missing: ${entity}`)
    expect(existsSync(join(repo, entity))).toBe(false)
  })

  it.each(['rendered', 'stale'])(
    'refuses a directory junction in the %s scope before writing',
    (kind) => {
      const outside = join(tmp, 'outside')
      mkdirSync(outside)
      put(outside, 'old.ts')
      if (kind === 'rendered') {
        mkdirSync(join(repo, 'apps/web/src/views/demo'), { recursive: true })
        symlinkSync(outside, join(repo, 'apps/web/src/views/demo/book'), 'junction')
        put(out, fresh, '<template />\n')
      } else symlinkSync(outside, join(repo, mod, 'linked'), 'junction')
      put(out, service, `${generated}// changed\n`)
      expect(() => syncGolden(out, repo, workspace, true)).toThrow(/symlink/)
      expect(readFileSync(join(repo, service), 'utf8')).toContain('value = 1')
      expect(existsSync(join(outside, 'old.ts'))).toBe(true)
      expect(existsSync(join(outside, 'detail.vue'))).toBe(false)
    },
  )

  for (const dangling of [false, true])
    it(`refuses a file symlink, including dangling=${dangling}`, (context) => {
      rmSync(join(repo, service))
      const dest = join(tmp, 'outside.ts')
      if (!dangling) writeFileSync(dest, generated)
      try {
        symlinkSync(dest, join(repo, service), 'file')
      } catch (err) {
        if (process.platform === 'win32' && (err as NodeJS.ErrnoException).code === 'EPERM') {
          context.skip()
          return
        }
        throw err
      }
      expect(() => syncGolden(out, repo, workspace, true)).toThrow(/symlink/)
      expect(existsSync(dest)).toBe(!dangling)
    })

  it('fails closed when git target validation fails', () => {
    put(out, fresh, '<template />\n')
    vi.spyOn(childProcess, 'spawnSync').mockReturnValue({
      status: 2,
      stderr: 'git failed',
      stdout: '',
    } as ReturnType<typeof childProcess.spawnSync>)
    syncBuiltinESMExports()
    expect(() => syncGolden(out, repo, workspace, true)).toThrow(/git target check failed/)
    expect(existsSync(join(repo, fresh))).toBe(false)
  })

  it('reports tracked and newly created touched paths on a partial write failure without restoring them', () => {
    const first = `${mod}/aaa-new.ts`
    const failed = `${mod}/zzz-new.ts`
    put(out, first)
    put(out, failed)
    put(out, service, `${generated}// changed\n`)
    const original = fs.writeFileSync
    vi.spyOn(fs, 'writeFileSync').mockImplementation(
      (...args: Parameters<typeof fs.writeFileSync>) => {
        if (args[0] === join(repo, failed)) throw new Error('injected disk failure')
        return original(...args)
      },
    )
    syncBuiltinESMExports()
    let message = ''
    try {
      syncGolden(out, repo, workspace, true)
    } catch (err) {
      message = (err as Error).message
    }
    expect(message).toContain('write failed: injected disk failure')
    expect(message).toContain(`touched paths: ${first}, ${service}, ${failed}`)
    expect(message).toContain(`git checkout -- ${service}`)
    expect(message).toContain(`remove new files if present: ${first}, ${failed}`)
    expect(existsSync(join(repo, first))).toBe(true)
    expect(readFileSync(join(repo, service), 'utf8')).toContain('changed')
  })
})
