// @generated by qw-codegen (crud)
// Http fault menus: the page under the `audit` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (audit.http-fault.json), the actions' in menu.json (menu.action.*).
import { httpFaultPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [httpFaultPerms.browse, 'menu.action.browse'],
  [httpFaultPerms.view, 'menu.action.view'],
  [httpFaultPerms.export, 'menu.action.export'],
  [httpFaultPerms.handle, 'menu.action.handle'],
]

export async function seedHttpFault(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'audit' })
  if (parentId === undefined) throw new Error('seedHttpFault: the audit menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'audit-http-fault' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.audit.httpFault',
      route_path: '/audit/http-faults',
      component: 'platform/audit/http-fault/index',
      component_name: 'AuditHttpFault',
      keep_alive: 1,
      icon: 'lucide:bug',
      sort_no: 40,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
