<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { type I18nText, paramCreate } from '@qiwu/shared'
import { paramApi } from '@/api/platform/settings/param'
import I18nInput from '@/core/components/I18nInput.vue'
import { useCrudForm } from '@/core/composables/use-crud'

/**
 * Add / edit form of the param list, opened with `openDialog(ParameterForm, { id })`. The key and the
 * secret flag are set when adding; a builtin param keeps whether it is public, a secret one is never
 * public. A secret value loads as the mask: saved unchanged, the stored value stays.
 */
defineOptions({ name: 'SettingsParameterForm' })
const { id } = defineProps<{ id?: number }>()
const emit = defineEmits<{ done: [saved: { id: number }]; cancel: [] }>()
const { t } = useI18n()
const { model, row, formRef, rules, loading, submitting, submit } = useCrudForm({
  api: paramApi,
  schema: paramCreate,
  emptyModel: () => ({
    paramKey: '',
    paramValue: '',
    name: '',
    nameI18n: null as I18nText | null,
    groupCode: '',
    isSecret: false,
    isPublic: false,
    note: '',
  }),
  id,
  emit,
})
// a secret param is never public (the server refuses the pair)
watch(
  () => model.isSecret,
  (secret) => {
    if (secret) model.isPublic = false
  },
)
</script>

<template>
  <el-form ref="formRef" v-loading="loading" :model="model" :rules="rules" label-position="left">
    <el-form-item :label="t('field.settings.param.paramKey')" prop="paramKey">
      <el-input
        v-model="model.paramKey"
        maxlength="128"
        :disabled="id != null"
        placeholder="storage.max_size_mb"
      />
    </el-form-item>
    <el-form-item :label="t('field.settings.param.paramValue')" prop="paramValue">
      <el-input
        v-model="model.paramValue"
        type="textarea"
        :rows="3"
        maxlength="16383"
        show-word-limit
      />
      <div v-if="row?.isSecret" class="param-form__hint">{{ t('settings.param.secretHint') }}</div>
    </el-form-item>
    <el-form-item :label="t('field.settings.param.name')" prop="name">
      <el-input v-model="model.name" maxlength="128" />
    </el-form-item>
    <el-form-item :label="t('field.settings.param.nameI18n')" prop="nameI18n">
      <I18nInput
        v-model="model.nameI18n"
        :label="t('field.settings.param.nameI18n')"
        :maxlength="128"
      />
    </el-form-item>
    <el-form-item :label="t('field.settings.param.groupCode')" prop="groupCode">
      <el-input v-model="model.groupCode" maxlength="64" />
    </el-form-item>
    <el-form-item :label="t('field.settings.param.isSecret')" prop="isSecret">
      <el-switch v-model="model.isSecret" :disabled="id != null" />
    </el-form-item>
    <el-form-item :label="t('field.settings.param.isPublic')" prop="isPublic">
      <el-switch v-model="model.isPublic" :disabled="model.isSecret || row?.isBuiltin" />
    </el-form-item>
    <el-form-item :label="t('field.settings.param.note')" prop="note">
      <el-input v-model="model.note" type="textarea" :rows="3" maxlength="500" show-word-limit />
    </el-form-item>
  </el-form>
  <div class="qw-dialog-footer">
    <el-button @click="emit('cancel')">{{ t('common.action.cancel') }}</el-button>
    <el-button type="primary" :loading="submitting" @click="submit">
      {{ t('crud.action.save') }}
    </el-button>
  </div>
</template>

<style scoped>
.param-form__hint {
  margin-top: 4px;
  font-size: 12px;
  line-height: 18px;
  color: var(--qw-text-3);
}
</style>
