// @generated by qw-codegen (crud)
// Run menus: the page under the `monitor` group (found by route_name, never by id) and
// one action row per permission, upserted by route_name / perms. Names are i18n keys: the page's in
// the module's web locale fragment (scheduler.run.json), the actions' in menu.json (menu.action.*).
import { runPerms } from '@qiwu/shared'
import type { EntityManager } from 'typeorm'
import { findId, upsert } from '../../../../db/seeds/upsert.js'

const ACTIONS: [perms: string, name: string][] = [
  [runPerms.browse, 'menu.action.browse'],
  [runPerms.view, 'menu.action.view'],
  [runPerms.export, 'menu.action.export'],
  [runPerms.remove, 'menu.action.remove'],
]

export async function seedRun(q: EntityManager): Promise<string[]> {
  const parentId = await findId(q, 'iam_menu', { route_name: 'monitor' })
  if (parentId === undefined) throw new Error('seedRun: the monitor menu group is missing')
  const pageId = await upsert(
    q,
    'iam_menu',
    { route_name: 'scheduler-run' },
    {
      parent_id: parentId,
      kind: 'page',
      name: 'menu.scheduler.run',
      route_path: '/scheduler/runs',
      component: 'platform/scheduler/run/index',
      component_name: 'SchedulerRun',
      keep_alive: 1,
      icon: 'lucide:list-checks',
      sort_no: 30,
    },
  )
  for (const [i, [perms, name]] of ACTIONS.entries())
    await upsert(
      q,
      'iam_menu',
      { kind: 'action', perms },
      { parent_id: pageId, name, sort_no: (i + 1) * 10 },
    )
  return []
}
