// @generated by qw-codegen (crud)
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { RunController } from './run.controller.js'
import { Run } from './run.entity.js'
import { RunService } from './run.service.js'

@Module({
  imports: [TypeOrmModule.forFeature([Run])],
  controllers: [RunController],
  providers: [RunService],
})
export class RunModule {}
