// @generated by qw-codegen (crud)
import type { OAuthGrantType } from '@qiwu/shared'
import { Column, Entity } from 'typeorm'
import { BaseEntity } from '../../../../core/db/base.entity.js'

/** `oauth_client`: OAuth2 客户端 */
@Entity('oauth_client')
export class Client extends BaseEntity {
  /** 客户端标识（client_id，区分大小写） */
  @Column({ name: 'client_id', length: 64 })
  clientId: string

  /**
   * The secret's hex sha256 (`secretDigest`; the column comment's bcrypt is outdated), null for
   * built-in clients; not loaded by reads (`select: false`), so optional
   */
  @Column({ name: 'secret_hash', type: 'varchar', length: 100, nullable: true, select: false })
  secretHash?: string | null

  /** 名称（种子为 seed.* 键） */
  @Column({ length: 64 })
  name: string

  /** 图标地址 */
  @Column({ name: 'logo_url', type: 'varchar', length: 512, nullable: true })
  logoUrl: string | null

  /** 授权类型（authorization_code/refresh_token/client_credentials） */
  @Column({ name: 'grant_types', type: 'json' })
  grantTypes: OAuthGrantType[]

  /** 回调地址（逐字精确匹配） */
  @Column({ name: 'redirect_uris', type: 'json' })
  redirectUris: string[]

  /** 可申请的权限范围 */
  @Column({ type: 'json' })
  scopes: string[]

  /** 免确认的权限范围 */
  @Column({ name: 'auto_approve_scopes', type: 'json' })
  autoApproveScopes: string[]

  /** 访问令牌有效期（秒） */
  @Column({ name: 'access_ttl_sec', type: 'int', default: 1800 })
  accessTtlSec: number

  /** 刷新令牌有效期（秒，也是授权会话的绝对上限） */
  @Column({ name: 'refresh_ttl_sec', type: 'int', default: 604_800 })
  refreshTtlSec: number

  /** 是否内置（不可删） */
  @Column({ name: 'is_builtin', type: 'boolean', default: false })
  isBuiltin: boolean

  /** 是否启用 */
  @Column({ type: 'boolean', default: true })
  enabled: boolean
}
