// @generated by qw-codegen (crud)
import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  ParseIntPipe,
  Post,
  Put,
  Query,
} from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import {
  type ClientCreate,
  clientCreate,
  clientCreatedVo,
  clientPerms,
  type ClientQuery,
  clientQuery,
  clientSecretVo,
  type ClientUpdate,
  clientUpdate,
  clientVo,
  type EnabledBody,
  enabledBody,
  type IdsBody,
  idsBody,
  pageVo,
} from '@qiwu/shared'
import { ActionLog } from '../../../../core/audit/action-log.js'
import { RequirePerm } from '../../../../core/auth/decorators.js'
import { Idempotent } from '../../../../core/guard/idempotent.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import type { Client } from './client.entity.js'
import { ClientService } from './client.service.js'

@ApiTags('oauth')
@Controller('oauth/clients')
export class ClientController {
  constructor(private readonly clients: ClientService) {}

  @Get()
  @RequirePerm(clientPerms.browse)
  @ApiOperation({ summary: 'Page of clients' })
  @ApiEnvelope(pageVo(clientVo))
  page(@Query({ schema: clientQuery }) query: ClientQuery) {
    return this.clients.page(query)
  }

  @Get(':id')
  @RequirePerm(clientPerms.view)
  @ApiOperation({ summary: 'One client' })
  @ApiEnvelope(clientVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.clients.get(id)
  }

  @Post()
  @RequirePerm(clientPerms.create)
  @Idempotent()
  @ActionLog({
    domain: 'oauth.client',
    verb: 'create',
    bizId: (_req, row) => (row as Client | undefined)?.id,
  })
  @ApiOperation({ summary: 'Add a client; its generated secret is answered this once only' })
  @ApiEnvelope(clientCreatedVo, 201)
  create(@Body({ schema: clientCreate }) dto: ClientCreate) {
    return this.clients.create(dto)
  }

  @Put(':id')
  @RequirePerm(clientPerms.modify)
  @ActionLog({ domain: 'oauth.client', verb: 'modify' })
  @ApiOperation({ summary: 'Change a client (disabling it ends its sessions)' })
  @ApiEnvelope()
  update(@Param('id', ParseIntPipe) id: number, @Body({ schema: clientUpdate }) dto: ClientUpdate) {
    return this.clients.update(id, dto)
  }

  @Put(':id/enabled')
  @RequirePerm(clientPerms.modify)
  @ActionLog({ domain: 'oauth.client', verb: 'modify' })
  @ApiOperation({ summary: 'Enable or disable a client (disabling ends its sessions)' })
  @ApiEnvelope()
  setEnabled(
    @Param('id', ParseIntPipe) id: number,
    @Body({ schema: enabledBody }) dto: EnabledBody,
  ) {
    return this.clients.update(id, dto)
  }

  /** Double clicks would reset twice and void the secret shown first: 429 within 3 s. */
  @Post(':id/secret')
  @HttpCode(200)
  @RequirePerm(clientPerms['reset-secret'])
  @Idempotent()
  @ActionLog({ domain: 'oauth.client', verb: 'reset-secret' })
  @ApiOperation({
    summary: 'Reset the client secret; the new one is answered this once only (tokens stay)',
  })
  @ApiEnvelope(clientSecretVo)
  resetSecret(@Param('id', ParseIntPipe) id: number) {
    return this.clients.resetSecret(id)
  }

  @Delete(':id')
  @RequirePerm(clientPerms.remove)
  @ActionLog({ domain: 'oauth.client', verb: 'remove' })
  @ApiOperation({ summary: 'Delete a client (ends its sessions)' })
  @ApiEnvelope()
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.clients.remove([id])
  }

  @Post('batch-delete')
  @HttpCode(200)
  @RequirePerm(clientPerms.remove)
  @ActionLog({ domain: 'oauth.client', verb: 'remove' })
  @ApiOperation({ summary: 'Delete clients: all or none (ends their sessions)' })
  @ApiEnvelope()
  batchRemove(@Body({ schema: idsBody }) { ids }: IdsBody) {
    return this.clients.remove(ids)
  }
}
