// @generated by qw-codegen (crud)
import { Module } from '@nestjs/common'
import { TypeOrmModule } from '@nestjs/typeorm'
import { ClientController } from './client.controller.js'
import { Client } from './client.entity.js'
import { ClientService } from './client.service.js'

@Module({
  imports: [TypeOrmModule.forFeature([Client])],
  controllers: [ClientController],
  providers: [ClientService],
})
export class ClientModule {}
