// @generated by qw-codegen (crud)
import { z } from 'zod'
import { pageQuery } from '../../common/pagination.js'
import { fieldDomains } from '../../validation/zod-i18n.js'
import { STORAGE_DRIVERS } from './storage-driver.schema.js'

/**
 * Configs (`fs_storage`), `/api/storage/configs` (see docs/design-notes.md#api-envelope). Field labels
 * `field.storage.config.<prop>`. The add / edit bodies and the form's detail are driver-specific:
 * `storageConfigCreate` / `storageConfigUpdate` / `storageConfigVo` (storage-driver.schema.ts).
 */

export const configPerms = {
  browse: 'storage.config.browse',
  view: 'storage.config.view',
  create: 'storage.config.create',
  /** also test connection (`POST /:id/test`) and set primary (`PUT /:id/primary`) */
  modify: 'storage.config.modify',
  remove: 'storage.config.remove',
} as const

/** GET query: paging, sort and the list filters (text contains, ranges from / to, the rest equals). */
export const configQuery = pageQuery(['name', 'driver', 'createdAt', 'id'])
  .extend({
    name: z.string().trim().max(64).optional(),
    driver: z.enum(STORAGE_DRIVERS).optional(),
    enabled: z.stringbool().optional(),
  })
  .register(fieldDomains, { domain: 'storage.config' })
export type StorageConfigQuery = z.output<typeof configQuery>

/** A list row: never the driver config (endpoint, keys): the form reads `GET /:id`. */
export const configVo = z.object({
  id: z.number().int(),
  /** i18n key (seeded, `seed.storage.*`) or text */
  name: z.string(),
  driver: z.enum(STORAGE_DRIVERS),
  isPrimary: z.boolean(),
  enabled: z.boolean(),
  note: z.string().nullable(),
  createdBy: z.number().int().nullable(),
  createdAt: z.iso.datetime(),
  updatedBy: z.number().int().nullable(),
  updatedAt: z.iso.datetime(),
})
export type StorageConfigRowVo = z.infer<typeof configVo>
