// @generated by qw-codegen (crud)
import type { ActionLogVo } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/audit/action-logs'

/** /api/audit/action-logs: read, export and delete (one, a batch or everything). */
export const actionLogApi = {
  ...crudApi<ActionLogVo>(BASE),
  clean: () => api.post(`${BASE}/clean`),
}
