// @generated by qw-codegen (crud)
import type { HttpFaultState, HttpFaultVo } from '@qiwu/shared'
import { api, crudApi } from '@/core/request/http'

const BASE = '/audit/http-faults'

/** /api/audit/http-faults: the list, one row, the export and the handling state. */
export const httpFaultApi = {
  // read-only: the list, one row and the export
  ...crudApi<HttpFaultVo>(BASE),
  setState: (id: number, state: HttpFaultState) =>
    api.put<HttpFaultVo>(`${BASE}/${id}/state`, { state }),
}
