// @generated by qw-codegen (crud)
import type { HttpTraceVo } from '@qiwu/shared'
import { crudApi } from '@/core/request/http'

const BASE = '/audit/http-traces'

/** /api/audit/http-traces: the standard CRUD calls. */
export const httpTraceApi = {
  // read-only: the list, one row and the export
  ...crudApi<HttpTraceVo>(BASE),
}
