// @generated by qw-codegen (crud)
import { Injectable, NotFoundException } from '@nestjs/common'
import { TransactionHost } from '@nestjs-cls/transactional'
import type { TransactionalAdapterTypeOrm } from '@nestjs-cls/transactional-adapter-typeorm'
import type { InboxQuery } from '@qiwu/shared'
import type { SelectQueryBuilder } from 'typeorm'
import { BaseCrudService } from '../../../../core/db/base-crud.service.js'
import { contains, paginate } from '../../../../core/db/page.js'
import { User } from '../../iam/user/user.entity.js'
import { Inbox } from './inbox.entity.js'

/**
 * Inboxes over BaseCrudService. Read only here: rows are soft-deleted like every
 * table and dropped for good by `audit.purge` past `audit.retention_days`.
 */
@Injectable()
export class InboxService extends BaseCrudService<Inbox> {
  constructor(txHost: TransactionHost<TransactionalAdapterTypeOrm>) {
    super(txHost, Inbox)
  }

  private withRecipient() {
    return this.scopedQb('t').leftJoinAndMapOne(
      't.recipient',
      User,
      'recipient',
      'recipient.id = t.userId AND recipient.deletedAt IS NULL',
    )
  }

  private display(row: Inbox) {
    const { recipient, ...rest } = row as Inbox & { recipient?: User }
    return {
      ...rest,
      recipientName: recipient ? `${recipient.displayName} (${recipient.username})` : null,
    }
  }

  async adminPage(query: InboxQuery) {
    const page = await paginate(this.filter(this.withRecipient(), query), query)
    return { ...page, items: page.items.map((row) => this.display(row)) }
  }

  async adminGet(id: number) {
    const row = await this.withRecipient().andWhere('t.id = :id', { id }).getOne()
    if (!row) throw new NotFoundException()
    return this.display(row)
  }

  protected override filter(
    qb: SelectQueryBuilder<Inbox>,
    { userId, templateCode, category, title, status, createdAtFrom, createdAtTo }: InboxQuery,
  ): SelectQueryBuilder<Inbox> {
    if (userId !== undefined) qb.andWhere('t.user_id = :userId', { userId })
    if (templateCode)
      qb.andWhere('t.template_code LIKE :templateCode', { templateCode: contains(templateCode) })
    if (category) qb.andWhere('t.category = :category', { category })
    if (title) qb.andWhere('t.title LIKE :title', { title: contains(title) })
    if (status) qb.andWhere('t.status = :status', { status })
    if (createdAtFrom)
      qb.andWhere('t.created_at >= :createdAtFrom', { createdAtFrom: new Date(createdAtFrom) })
    if (createdAtTo)
      qb.andWhere('t.created_at <= :createdAtTo', { createdAtTo: new Date(createdAtTo) })
    return qb
  }
}
