// @generated by qw-codegen (crud)
import { Controller, Get, Param, ParseIntPipe, Query } from '@nestjs/common'
import { ApiOperation, ApiTags } from '@nestjs/swagger'
import { inboxPerms, type InboxQuery, inboxQuery, inboxVo, pageVo } from '@qiwu/shared'
import { RequirePerm } from '../../../../core/auth/decorators.js'
import { ApiEnvelope } from '../../../../core/http/api-envelope.decorator.js'
import { InboxService } from './inbox.service.js'

@ApiTags('messaging')
@Controller('messaging/inboxes')
export class InboxController {
  constructor(private readonly inboxes: InboxService) {}

  @Get()
  @RequirePerm(inboxPerms.browse)
  @ApiOperation({ summary: 'Page of inboxes' })
  @ApiEnvelope(pageVo(inboxVo))
  page(@Query({ schema: inboxQuery }) query: InboxQuery) {
    return this.inboxes.adminPage(query)
  }

  @Get(':id')
  @RequirePerm(inboxPerms.view)
  @ApiOperation({ summary: 'One inbox' })
  @ApiEnvelope(inboxVo)
  get(@Param('id', ParseIntPipe) id: number) {
    return this.inboxes.adminGet(id)
  }
}
