// @generated by qw-codegen (crud)
import { Column, Entity } from 'typeorm'
import { CreatedEntity } from '../../../../core/db/base.entity.js'

/** `msg_inbox`: 站内信 (append-only: no audit columns, read-only page) */
@Entity('msg_inbox')
export class Inbox extends CreatedEntity {
  /** 收件人 ID */
  @Column({ name: 'user_id', type: 'bigint', unsigned: true })
  userId: number

  /** 模板编码 */
  @Column({ name: 'template_code', length: 100 })
  templateCode: string

  /** 语言 */
  @Column({ length: 10 })
  locale: string

  /** 分类（system/business） */
  @Column({ length: 16 })
  category: string

  /** 发送方名称（模板快照） */
  @Column({ name: 'sender_label', type: 'varchar', length: 64, nullable: true })
  senderLabel: string | null

  /** 标题 */
  @Column({ length: 200 })
  title: string

  /** 正文（纯文本） */
  @Column({ type: 'text' })
  body: string

  /** 参数 */
  @Column({ type: 'json', nullable: true })
  params: unknown

  /** 状态（pending/sending/delivered/failed） */
  @Column({ length: 12, default: 'pending' })
  status: string

  /** 发送尝试次数 */
  @Column({ type: 'tinyint', unsigned: true, default: 0 })
  attempts: number

  @Column({ name: 'claimed_at', type: 'datetime', precision: 3, nullable: true, select: false })
  claimedAt: Date | null

  /** 阅读时间（UTC） */
  @Column({ name: 'read_at', type: 'datetime', precision: 3, nullable: true })
  readAt: Date | null
}
