<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { leaveCreate } from '@qiwu/shared'
import { leaveApi } from '@/api/biz/leave'
import DictSelect from '@/core/components/DictSelect.vue'
import { useCrudForm } from '@/core/composables/use-crud'

/**
 * The leave request form: the new-request page's content (submit = start the approval) and the edit dialog
 * of a request sent back to its owner (`openDialog(LeaveForm, { id })`, view.vue).
 */
defineOptions({ name: 'BizLeaveForm' })
const { id } = defineProps<{ id?: number }>()
const emit = defineEmits<{ done: [saved: { id: number }]; cancel: [] }>()
const { t } = useI18n()
const { model, formRef, rules, loading, submitting, submit } = useCrudForm({
  api: leaveApi,
  schema: leaveCreate,
  emptyModel: () => ({ leaveKind: '', startAt: null, endAt: null, days: null, reason: '' }),
  id,
  emit,
})
</script>

<template>
  <el-form ref="formRef" v-loading="loading" :model="model" :rules="rules" label-position="left">
    <el-form-item :label="t('field.biz.leave.leaveKind')" prop="leaveKind">
      <DictSelect v-model="model.leaveKind" code="biz.leave_kind" />
    </el-form-item>
    <el-form-item :label="t('field.biz.leave.startAt')" prop="startAt">
      <!-- sent as an instant with the browser's offset (the API takes ISO-8601 with an offset) -->
      <el-date-picker
        v-model="model.startAt"
        type="datetime"
        value-format="YYYY-MM-DD[T]HH:mm:ss.SSSZ"
      />
    </el-form-item>
    <el-form-item :label="t('field.biz.leave.endAt')" prop="endAt">
      <!-- sent as an instant with the browser's offset (the API takes ISO-8601 with an offset) -->
      <el-date-picker
        v-model="model.endAt"
        type="datetime"
        value-format="YYYY-MM-DD[T]HH:mm:ss.SSSZ"
      />
    </el-form-item>
    <el-form-item :label="t('field.biz.leave.days')" prop="days">
      <el-input-number
        v-model="model.days"
        :min="0.1"
        :max="9999.9"
        :precision="1"
        :step="0.1"
        controls-position="right"
      />
    </el-form-item>
    <el-form-item :label="t('field.biz.leave.reason')" prop="reason">
      <el-input v-model="model.reason" type="textarea" :rows="3" maxlength="500" show-word-limit />
    </el-form-item>
  </el-form>
  <div class="qw-dialog-footer">
    <el-button @click="emit('cancel')">{{ t('common.action.cancel') }}</el-button>
    <!-- a new request is submitted for approval at once -->
    <el-button type="primary" :loading="submitting" @click="submit">
      {{ t(id ? 'crud.action.save' : 'biz.leave.submit') }}
    </el-button>
  </div>
</template>
