<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { onActivated, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import dayjs from 'dayjs'
import { leavePerms } from '@qiwu/shared'
import { leaveApi } from '@/api/biz/leave'
import DictSelect from '@/core/components/DictSelect.vue'
import DictTag from '@/core/components/DictTag.vue'
import QwTable from '@/core/components/QwTable.vue'
import Pagination from '@/core/components/Pagination.vue'
import TableToolbar from '@/core/components/TableToolbar.vue'
import { useCrudList } from '@/core/composables/use-crud'
import type { QwColumn } from '@/core/composables/use-table-prefs'
import { Icon } from '@/core/icons'

// keep-alive name = the seeded menu's component_name
defineOptions({ name: 'BizLeave' })

const { t } = useI18n()
const { query, rows, total, loading, filtered, search, reset, refresh, onSortChange } = useCrudList(
  {
    api: leaveApi,
    filters: {
      leaveKind: null as string | null,
      startAtRange: null as [string, string] | null,
      createdAtRange: null as [string, string] | null,
    },
    sort: '-createdAt',
  },
)
const showSearch = ref(true)
// order and visibility are the user's column settings (table id `biz.leave`); short columns get a
// fixed width (longest locale's header + sort caret); the free text, else the name, takes the rest
const columns: QwColumn[] = [
  { prop: 'leaveKind', label: 'field.biz.leave.leaveKind', width: 120, showOverflowTooltip: true },
  { prop: 'startAt', label: 'field.biz.leave.startAt', sortable: true, width: 160 },
  { prop: 'endAt', label: 'field.biz.leave.endAt', sortable: true, width: 160 },
  { prop: 'days', label: 'field.biz.leave.days', sortable: true, width: 120, align: 'right' },
  {
    prop: 'state',
    label: 'field.biz.leave.state',
    sortable: true,
    width: 140,
    showOverflowTooltip: true,
  },
  { prop: 'createdAt', label: 'field.common.createdAt', sortable: true, width: 160 },
  { prop: 'reason', label: 'field.biz.leave.reason', minWidth: 120, showOverflowTooltip: true },
]
// a new request and a request's own page (where one sent back is edited and resubmitted) are pages of their
// own: the model's create_route and view_component (see docs/design-notes.md#workflow)
const router = useRouter()
// kept alive: reload when shown again (a request submitted or decided on meanwhile)
let shown = false
onActivated(() => {
  if (shown) void refresh()
  shown = true
})
</script>

<template>
  <div class="qw-page">
    <el-card v-show="showSearch" class="qw-search-panel">
      <el-form :model="query" inline @submit.prevent="search">
        <el-form-item :label="t('field.biz.leave.leaveKind')">
          <DictSelect v-model="query.leaveKind" code="biz.leave_kind" />
        </el-form-item>
        <el-form-item :label="t('field.biz.leave.startAt')" class="qw-search-wide">
          <el-date-picker
            v-model="query.startAtRange"
            type="daterange"
            value-format="YYYY-MM-DD"
            :start-placeholder="t('field.biz.leave.startAtFrom')"
            :end-placeholder="t('field.biz.leave.startAtTo')"
          />
        </el-form-item>
        <el-form-item :label="t('field.common.createdAt')" class="qw-search-wide">
          <el-date-picker
            v-model="query.createdAtRange"
            type="daterange"
            value-format="YYYY-MM-DD"
            :start-placeholder="t('field.common.createdAtFrom')"
            :end-placeholder="t('field.common.createdAtTo')"
          />
        </el-form-item>
        <el-form-item class="qw-search-actions">
          <!-- plain: the toolbar's create stays the page's one solid primary button (§1) -->
          <el-button type="primary" plain native-type="submit">
            <el-icon class="el-icon--left"><Icon icon="lucide:search" /></el-icon>
            {{ t('crud.action.search') }}
          </el-button>
          <el-button @click="reset">{{ t('crud.action.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="qw-table-panel">
      <TableToolbar
        v-model:search="showSearch"
        table-id="biz.leave"
        :columns="columns"
        @refresh="refresh"
      >
        <el-button v-perm="leavePerms.create" type="primary" @click="router.push('/biz/leave/new')">
          <el-icon class="el-icon--left"><Icon icon="lucide:plus" /></el-icon>
          {{ t('crud.action.create') }}
        </el-button>
      </TableToolbar>

      <QwTable
        table-id="biz.leave"
        :columns="columns"
        :data="rows"
        :loading="loading"
        :filtered
        @sort-change="onSortChange"
        @reset-filters="reset"
      >
        <template #cell-leaveKind="{ row }">
          <DictTag code="biz.leave_kind" :value="row.leaveKind" />
        </template>
        <template #cell-startAt="{ row }">{{
          dayjs(row.startAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #cell-endAt="{ row }">{{ dayjs(row.endAt).format('YYYY-MM-DD HH:mm') }}</template>
        <template #cell-days="{ row }">{{ row.days.toFixed(1) }}</template>
        <template #cell-createdAt="{ row }">{{
          dayjs(row.createdAt).format('YYYY-MM-DD HH:mm')
        }}</template>
        <template #cell-state="{ row }">
          <DictTag code="biz.leave_state" :value="row.state" />
        </template>
        <template #actions="{ row }">
          <el-button link type="primary" @click="router.push(`/biz/leave/${row.id}`)">
            {{ t('biz.leave.view') }}
          </el-button>
        </template>
      </QwTable>

      <Pagination
        v-model:page="query.page"
        v-model:page-size="query.pageSize"
        :total="total"
        @change="refresh"
      />
    </el-card>
  </div>
</template>
