<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { dictEntryCreate, type I18nText } from '@qiwu/shared'
import { dictEntryApi } from '@/api/platform/settings/dict-entry'
import DictSelect from '@/core/components/DictSelect.vue'
import I18nInput from '@/core/components/I18nInput.vue'
import { useCrudForm } from '@/core/composables/use-crud'

/**
 * Add / edit form of one dict's entry list, opened with `openDialog(DictEntryForm, { id, dictCode })`:
 * a new entry goes into `dictCode` (an entry stays in its dict); the label per language wins over the
 * label.
 */
defineOptions({ name: 'SettingsDictEntryForm' })
const { id, dictCode } = defineProps<{ id?: number; dictCode: string }>()
const emit = defineEmits<{ done: [saved: { id: number }]; cancel: [] }>()
const { t } = useI18n()
const { model, formRef, rules, loading, submitting, submit } = useCrudForm({
  api: dictEntryApi,
  schema: dictEntryCreate,
  emptyModel: () => ({
    dictCode,
    value: '',
    label: '',
    labelI18n: null as I18nText | null,
    sortNo: 0,
    tagType: null,
    cssClass: '',
    isDefault: false,
    enabled: true,
    note: '',
  }),
  id,
  emit,
})
</script>

<template>
  <el-form ref="formRef" v-loading="loading" :model="model" :rules="rules" label-position="left">
    <el-form-item :label="t('field.settings.dictEntry.dictCode')" prop="dictCode">
      <el-input v-model="model.dictCode" disabled />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.value')" prop="value">
      <el-input v-model="model.value" maxlength="100" />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.label')" prop="label">
      <el-input v-model="model.label" maxlength="100" />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.labelI18n')" prop="labelI18n">
      <I18nInput
        v-model="model.labelI18n"
        :label="t('field.settings.dictEntry.labelI18n')"
        :maxlength="100"
      />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.sortNo')" prop="sortNo">
      <el-input-number v-model="model.sortNo" :min="0" :max="999999" controls-position="right" />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.tagType')" prop="tagType">
      <DictSelect v-model="model.tagType" code="settings.tag_type" />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.cssClass')" prop="cssClass">
      <el-input v-model="model.cssClass" maxlength="100" />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.isDefault')" prop="isDefault">
      <el-switch v-model="model.isDefault" />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.enabled')" prop="enabled">
      <el-switch v-model="model.enabled" />
    </el-form-item>
    <el-form-item :label="t('field.settings.dictEntry.note')" prop="note">
      <el-input v-model="model.note" type="textarea" :rows="3" maxlength="500" show-word-limit />
    </el-form-item>
  </el-form>
  <div class="qw-dialog-footer">
    <el-button @click="emit('cancel')">{{ t('common.action.cancel') }}</el-button>
    <el-button type="primary" :loading="submitting" @click="submit">
      {{ t('crud.action.save') }}
    </el-button>
  </div>
</template>
