<!-- @generated by qw-codegen (crud) -->
<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import { useI18n } from 'vue-i18n'
import dayjs from 'dayjs'
import type { ActionLogVo } from '@qiwu/shared'
import { actionLogApi } from '@/api/platform/audit/action-log'
import DictTag from '@/core/components/DictTag.vue'
import { tx } from '@/core/i18n'

/** One action log in the list's detail drawer (GET /:id). */
defineOptions({ name: 'AuditActionLogDetail' })
const { id } = defineProps<{ id: number }>()
const { t } = useI18n()

const row = shallowRef<ActionLogVo>()
const loading = ref(true)
// failures are toasted by the request layer (404 out of scope included)
actionLogApi
  .get(id)
  .then((r) => (row.value = r))
  .catch(() => undefined)
  .finally(() => (loading.value = false))
const time = (iso: string | null) => (iso ? dayjs(iso).format('YYYY-MM-DD HH:mm') : '')
</script>

<template>
  <div v-loading="loading" class="qw-detail">
    <el-descriptions v-if="row" :column="1" border>
      <el-descriptions-item :label="t('field.audit.actionLog.traceId')">
        {{ row.traceId }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.domain')">
        {{ row.domain }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.verb')">
        <DictTag code="audit.verb" :value="row.verb" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.bizId')">
        {{ row.bizId }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.userId')">
        {{ row.userId }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.userType')">
        <DictTag code="audit.user_type" :value="row.userType" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.username')">
        {{ row.username }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.deptName')">
        {{ row.deptName ? tx(row.deptName) : '' }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.httpMethod')">
        {{ row.httpMethod }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.url')">
        <span class="qw-detail__text">{{ row.url }}</span>
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.ip')">
        {{ row.ip }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.location')">
        {{ row.location }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.userAgent')">
        <span class="qw-detail__text">{{ row.userAgent }}</span>
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.params')">
        <span class="qw-detail__text">{{ row.params }}</span>
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.result')">
        <span class="qw-detail__text">{{ row.result }}</span>
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.ok')">
        <DictTag code="core.yes_no" :value="row.ok" />
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.errorMsg')">
        <span class="qw-detail__text">{{ row.errorMsg }}</span>
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.audit.actionLog.costMs')">
        {{ row.costMs }}
      </el-descriptions-item>
      <el-descriptions-item :label="t('field.common.createdAt')">
        {{ time(row.createdAt) }}
      </el-descriptions-item>
    </el-descriptions>
  </div>
</template>
